### ISSUE TITLE
HowTo with Logstash

### ISSUE THREAD

**Issue by genofire** [uken/fluent-plugin-elasticsearch#1006]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

**Is your feature request related to a problem? Please describe.**

Please write a documentation, how to use with logstash in between.

Get logstash become an input of `http` or `tcp` ?
What is the correct codec `elk_bulk`, `fluent` or `json` ?
With `elk_bulk` is a `target` notwendet?

Maybe write an example logstash file in the README (together with an example setup)

**Comment by cosmo0920** [comment]
This plugin does not compatible with logstash.
If you want to use it with logstash, you might be able to use logstash-code-fluent and tcp input as described here:
https://www.elastic.co/guide/en/logstash/current/plugins-codecs-fluent.html
