### ISSUE TITLE
fluentd types to elasticsearch types

### ISSUE THREAD

**Issue by smcavoy-b** [uken/fluent-plugin-elasticsearch#101]
I am wondering how/if the plugin handles types set in elastic search.

Example:
types time:time, code:int, size:int, request_time:float

I would expect that these fields would be written in elasticsearch as these types. Currently that is not the case. A new day/index results in all of these fields being strings.

**Comment by dterror** [comment]
You can specify those in your elasticsearch configuration:

http://www.elastic.co/guide/en/elasticsearch/reference/1.3/indices-templates.html

Template name can include wildcards, so you name it `logstash-*`
