### ISSUE TITLE
Existing Mapping is not Respected

### ISSUE THREAD

**Issue by dmfenton** [uken/fluent-plugin-elasticsearch#102]
It seems I'm having the same problem as others, but type-name is not helping. A second set of mappings is being created every time I start indexing my csvs. Here's a GIST of all the relevant information.

https://gist.github.com/dmfenton/23197b0729b6735f47ab#file-configuration

**Comment by dmfenton** [comment]
Actually I think I found the problem, spaces between keys in my config. I think this is a bug for fluentd core.

**Comment by dmfenton** [comment]
https://github.com/fluent/fluentd/issues/590

**Comment by dterror** [comment]
cool @dmfenton good catch
