### ISSUE TITLE
Installed un-desired version of elasticsearch client

### ISSUE THREAD

**Issue by shdluan** [uken/fluent-plugin-elasticsearch#1023]
(check apply)
- [ ] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Problem

my elasticsearch's version is 7.11.1,
when I install fluent-plugin-elasticsearch, it default install elasticsearch:8.8.0, even if I already install elasticsearch:7.11.1
I tried use --with-elasticsearch-version=7.11.1, but it useless.
As result it meets error: using elasticsearch client 8.8.0 is not compatible for you elasticsearch server

how could I install fluent-plugin-elasticsearch and specify the version of elasticsearch client

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

**OR**

Provide example config and message

#### Expected Behavior or What you need to ask

...

#### Using Fluentd and ES plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others?
* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
* ES plugin 3.x.y/2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
* ES version (optional)
* ES template(s) (optional)

**Comment by shdluan** [comment]
I used gem package manager tool bundle and resolved the problem
tks

**Comment by cosmo0920** [comment]
gem command always pulls the latest version of gems.
Instead, you have to use bundler and create Gemfile which defines the dependencies like as:
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.16/debian-elasticsearch7/Gemfile

fluentd accepts --gemfile option and handles bundler installed gems.
https://docs.fluentd.org/deployment/plugin-management#gemfile-option

**Comment by shdluan** [comment]
Dear friend:
the bundle just resolved my questions.

thanks again for your reply.


thanks again !


| |
Luan Shd
|
|
***@***.***
|
---- Replied Message ----
| From | Hiroshi ***@***.***> |
| Date | 6/27/2023 11:57 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [uken/fluent-plugin-elasticsearch] Installed un-desired version of elasticsearch client (Issue #1023) |

gem command always pulls the latest version of gems.
Instead, you have to use bundler and create Gemfile which defines the dependencies like as:
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.16/debian-elasticsearch7/Gemfile

fluentd accepts --gemfile option and handles bundler installed gems.
https://docs.fluentd.org/deployment/plugin-management#gemfile-option
