### ISSUE TITLE
What happens if elasticsearch returns other then 200?

### ISSUE THREAD

**Issue by sazo** [uken/fluent-plugin-elasticsearch#105]
Hallo,

What happens if elasticsearch reject the request with and error(HTTP header != 200)? is it saved in fluentd buffer to the problem is fixed? does it just discard the data?

**Comment by pitr** [comment]
Good question! Not sure.. probably discarded

**Comment by sazo** [comment]
@pitr Okay, not what i hoped for. but got an answer. :+1: will make a feature request not to discard the data.

**Comment by ajevans85** [comment]
Looking everything is discarded, 200 non 200. It would be useful if non 200 responses was logged and also if the request is a 200 but the response has `{"errors":true, items:[...] }` so it's easy to spot indexing failures and dropped lines on the trace log level.

**Comment by pitr** [comment]
Very good catch @sazo, thanks @ajevans85. We would very much welcome a PR.

I know that [ES change response format changed in 1.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/_return_values.html), the solution should work with all ES responses.

**Comment by cosmo0920** [comment]
Does anyone want to evaluate v1.11.0 with Fluentd v0.12 or v2.1.0 with Fluentd v0.14?

**Comment by cosmo0920** [comment]
Now, this plugin can handle non 200 response:

>   1. ElasticsearchVersionMismatch - We did not receive an error
     payload that matches our expectations, so this is considered
     a possible Elasticsearch version mismatch
>  2. UnrecognizedElasticsearchError - We encountered some error
     from Elasticsearch which we don't recognize
>  3. ElasticsearchOutOfMemory - If Elasticsearch is responding, but
     telling us it is out of memory, status code 500, with an error
     type of "out_of_memory_error", we'll keep retrying until it
     returns to us successfully
>  4. BulkIndexQueueFull - If Elasticsearch responds with a bulk
     index request rejected error, 429, with an error type of
     "es_rejected_execution_exception", we'll keep retrying until
     it returns to us successfully
>  5. ElasticsearchError - Some other status code 500 with an
     unknown error type.

ref: #282, #324, and #322.

If anyone want to handle more non 200 response, please open an another issue.
