### ISSUE TITLE
Best way to see what's being emitted to ES?

### ISSUE THREAD

**Issue by franfabrizio** [uken/fluent-plugin-elasticsearch#111]
Sorry, this is sort of a newbie question rather than an issue.  I started using this plugin today in the hopes of parsing a few years' of historical log data for my application from CSV into elasticsearch.  The CSV data has about 566k lines that look like this:

```
1,"2011-10-11 12:21:01",ds1,1790_cPop,"Census of the United States, 1790: Population Data for US",ds1.dt1,"Total Population","1790_cPop: Total Population"
```

Here's the td-agent.conf I am using:

```
<source>
  type tail
  read_from_head true
  path /to/my/csv/file.csv
  pos_file /var/log/td-agent/my-csv-file.log.pos 
  tag mycsvdata 
  format csv
  keys id,created_at,ds_istads_id,ds_code,ds_label,dt_istads_id,dt_label_nhgis,dt_string 
  time_key created_at 
</source>

<match **>
  type elasticsearch
  logstash_format true
  logstash_prefix fluent-nhgis
  disable_retry_limit true
  request_timeout 15s
  #  host <hostname> #(optional; default="localhost")
  #  port <port> #(optional; default=9200)
  #  index_name <index name> #(optional; default=fluentd)
  #  type_name <type name> #(optional; default=fluentd)
</match>
```
When I run this, I get lots of indexes created, with names like fluent-nhgis-2011.04.26.  I get about 1,300 or so indexes total, which is what I expect, because I have data for nearly every day since late 2011.

The issue: about 1/4 of the indexes end up with 0 documents in them.  These are days for which there are definitely records in the data, so there should be documents.  I started wondering if there is an issue parsing the CSV, but I modified the config using a "type copy" setup to copy all of the messages out to a file as well as to elasticsearch.  In doing so, I see the right number of messages emitted to the files (about 566k).  So I'd like to now see exactly what is being sent to / received by elasticsearch, to verify if any documents are being sent for the days that are showing 0 documents.  Basically, I need to figure out if the problem is on the plugin side, or an indexing issue on the ES side. 

What's the best way to see exactly what this plugin is emitting to elasticsearch?

**Comment by dterror** [comment]
You can check Elasticsearch logs for any error logs on parsing documents. In my experience, one big reason for ES to refuse logs is wrong mapping on types. For example, if the first `ds_code` ES sees is an integer, it will try to be smart the define `ds_code` as an int, in which case it might ignore all the ones that are strings.

With that said, this plugin doesn't have a super verbose debug mode, so you'll have to use other tools, ES logs are a good bet, or `ngrep`-ing.
