### ISSUE TITLE
Add support for outbound proxies

### ISSUE THREAD

**Issue by kkwoker** [uken/fluent-plugin-elasticsearch#115]
I've got an outbound proxy on my application. Fluentd needs to connect to the proxy before connecting to Elasticsearch. Is there any support for this?

**Comment by dterror** [comment]
No support atm @kkwoker, we welcome pull-requests

**Comment by ashb** [comment]
This might be as simple as setting `http_proxy` environment variable -- we're using the Farady gem for the HTTP requests and it supports that https://github.com/lostisland/faraday/blob/e10ef5ea8952b7b848e797e2f80136426063d6b8/lib/faraday/connection.rb#L52-L53

**Comment by pitr** [comment]
Indeed! Starting form version 0.8 of this gem we use `excon`, and it similarly uses `http_proxy` and https_proxy` environment variables - https://github.com/excon/excon#proxy-support Good catch @ashb

**Comment by pitr** [comment]
Added a note to readme - https://github.com/uken/fluent-plugin-elasticsearch/blob/master/README.md#proxy-support
