### ISSUE TITLE
FluentD regex parsed values not appearing in Elasticsearch

### ISSUE THREAD

**Issue by RobertLippens** [uken/fluent-plugin-elasticsearch#118]
I am attempting to take Springboot logs from files, parse out useful information, and send the result to Elasticsearch, and ultimately read from Kibana.  My fluentd.conf looks like the following:

    <source>
      type tail
      read_from_head true
      path /path/to/log/
      pos_file /path/to/pos_file
      format /^(?<date>[0-9]+-[0-9]+-[0-9]+\s+[0-9]+:[0-9]+:[0-9]+.[0-9]+)\s+(?<log_level>[Aa]lert|ALERT|[Tt]race|TRACE|[Dd]ebug|DEBUG|[Nn]otice|NOTICE|[Ii]nfo|INFO|[Ww]arn?(?:ing)?|WARN?(?:ING)?|[Ee]rr?(?:or)?|ERR?(?:OR)?|[Cc]rit?(?:ical)?|CRIT?(?:ICAL)?|[Ff]atal|FATAL|[Ss]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)\s+(?<pid>[0-9]+)\s+---\s+(?<message>.*)$/
      tag my.app
    </source>
    <match my.app>
     type stdout
    </match>
    <match my.app>
     type elasticsearch
     logstash_format true
     host myhosthere
     port 9200
     index_name fluentd-app
     type_name fluentd
    </match>

Given a typical Springboot log line:

    2015-07-16 19:20:04.074 INFO 16649 --- [ main] {springboot message}

By also writing to stdout as a test, I see my parser is resulting in:
    
    {
     "date":"2015-07-16 19:20:04.074",
     "log_level":"INFO",
     "pid":"16649",
     "message":"[ main] {springboot message}"
    }

However, when this gets written to Elasticsearch, all that results is:

    {
     _index: "fluentd-app-2015.07.16",
     _type: "fluentd",
     _id: "AU6YT5sjvkxiJXWCxeM8",
     _score: 1,
     _source: {
      message: "2015-07-16 19:20:04.074 INFO 16649 --- [ main] {springboot message}",
      @timestamp: "2015-07-16T19:20:04+00:00"
     }
    },

From what I had read about [fluentd-plugin-elasticsearch][1] I expected _source to contain all of the parsed fields that I see in stdout.  I have also tried the grok parser - though it seems apparent the issue lies with understanding of the fluentd elasticsearch plugin.  How do I get the fields I parsed to persist to elasticsearch?

  [1]: https://github.com/uken/fluent-plugin-elasticsearch

**Comment by dterror** [comment]
Hi @RobertLippens, I replicated your environment with the configs you posted and I'm getting this stored in elasticserch:
```json
{
      "_index" : "logstash-2015.07.18",
      "_type" : "fluentd",
      "_id" : "AU6e_dcKnQw_5pPdSJt1",
      "_score" : 1.0,
      "_source": {"date":"2015-07-16 19:20:04.074","log_level":"INFO","pid":"16649","message":"[ main] {springboot message}","@timestamp":"2015-07-17T22:28:30-04:00"}
}
```

Everything looks alright. What does the mapping of your type look like? Also what version of fluentd and fluentd-plugin-elasticsearch are you using?

**Comment by RobertLippens** [comment]
@dterror I must have installed something incorrectly.  When you said the configuration had worked for you, I just reinstalled everything and lo and behold, it worked great.  I will close this issue, thanks.
