### ISSUE TITLE
Dynamic variables in config

### ISSUE THREAD

**Issue by dterror** [uken/fluent-plugin-elasticsearch#122]
It seems like a lot of people want to use dynamic variables in configuration, mostly to retrieve index and type based on record and tag variables. The common resolution to this is using the forrest plugin, but it turns out there are a lot of problems with that plugin.

Ideally this plugin wouldn't have to deal with this concern, but as a lot of users seem to really need it, I think we should think of the best away to tackle it.

Related PRs/issues:
- https://github.com/uken/fluent-plugin-elasticsearch/pull/91
- https://github.com/uken/fluent-plugin-elasticsearch/pull/116
- https://github.com/fluent/fluentd/issues/596

@pitr

**Comment by dterror** [comment]
Q: do we need to support record fields exposed as configuration objects?
For example:
```
<match **>
     type elasticsearch
     type_name ${a_key_in_my_object}
 </match>
```

And then at what depth would we allow it? Should we expose a jsonpath interface so that people refer to `${keys.in.arbitrary.levels}`?

**Comment by pitr** [comment]
To me it seems that we essentially need to add a way for users to write code in their config. Otherwise, no amount of customisation will satisfy all the requirements.

PS. One thing I'd like to suggest is creating a separate plugin (e.g. `out_elasticsearch_dynamic.rb`) so we can experiment before impacting existing users of this plugin.

**Comment by dterror** [comment]
+1 and +1

**Comment by pitr** [comment]
How about allowing Ruby expanding using `${..}` syntax like [filter_record_transformer](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/filter_record_transformer.rb) but for most fields?

**Comment by dterror** [comment]
I think we might have to do it in order to achieve full-flexibility. I think this is probably super unsafe and inefficient, but Fluentd is using it, so... idk.

**Comment by pitr** [comment]
So would something like this work for everyone?

```
<match my.logs.*>
  type elasticsearch_unsafe
  host ${tag_parts[3]}.example.com
  port ${9200+rand(4)}
  logstash_prefix ${record['prefix'] || 'generic_prefix'}
  include_tag_key ${record['username'] != 'admin'}
  id_key ${record['my_id'] ? 'my_id' : 'id'}
</match>
```

**Comment by ewolinetz** [comment]
@pitr +1

**Comment by jimmidyson** [comment]
@pitr :+1:

**Comment by jeesim2** [comment]
I have really wanted this feature dynamic variables in configuration to solve my difficulties that every new elasticsearch type need to be configured in fluentd.conf. if not it may produce mapping conflicts in elasticsearch.

btw.
from elasticsearch 2.0 it totally refactored.
and different mapping with same filed wll not allowed at all in same index(not type)

https://www.elastic.co/blog/great-mapping-refactoring

now I'm recosider this feature could solve my problem.
if different mapping with same name allowed in same index, elasticsearch _type got a little meaningless.

how do you guys think about this?

'''
In the end, we opted to enforce the rule that all fields with the same name in the same index must have the same mapping, although certain parameters such as copy_to and enabled are still allowed to be specified per-type. This resolves the issues with data corruption, query time exceptions, and incorrect results. Queries and aggregations remain as fast as they are today, and we can maximise compression and minimise heap and disk usage.
'''

**Comment by salekseev** [comment]
@pitr +1

**Comment by pitr** [comment]
Looks like this solution is acceptable to everyone. If anyone wants to tackle this, a PR would be very welcomed.

**Comment by ewolinetz** [comment]
I have a proposed change, after a bit more edge case testing I'll open an initial PR

**Comment by pitr** [comment]
great news @ewolinetz, feel free to open a PR before it's ready

**Comment by ymattw** [comment]
@pitr Solution looks good, definitely meets my needs.

**Comment by cherrot** [comment]
@pitr @ewolinetz :+1: :+1:

**Comment by pitr** [comment]
v1.1.0 has been released with support for `elasticsearch_dynamic` plugin, thanks @ewolinetz

**Comment by bulemoon** [comment]
The record has a field named type. I want to assign independent logstash prefix with the field value. Does the plugin support the ruby code? For example:
if record[type] = 'A'
    logstash_prefix = 'x'
elsif record[type] = 'B'
    logstash_prefix = 'z'
end
