### ISSUE TITLE
Question on timestamps

### ISSUE THREAD

**Issue by fideloper** [uken/fluent-plugin-elasticsearch#124]
Hello!

It looks like a parsed timestamp is only included if using `logstash_format`. 

I'm setting `logstash_format` to false in order to specify an index with a custom mapping in an attempt to divide records up into separate indexes for things like http logs vs syslogs.

I was wondering if there was a specific reason not to include a timestamp in that case? I believe we'd then have to fall back to  having Elasticsearch create a timestamp, which may then not match the time of a log event.

(I'm totally fine if my understanding is completely wrong! Let me know if you think so :D )

In the end, I might just use the same logstash format for each index created via templates, rather than specify mappings per index, but I'm interested to know if I just have an incorrect understanding of the best way to go about this.

**Comment by dterror** [comment]
Haya,

So, we add `@timestamp` on `logstash_format` as part of mimicking Logstash's output (the original use-case was that we wanted to use [Kibana](https://www.elastic.co/videos/kibana-logstash).

If you want to add a timestamp field to your record without all the logstash stuff, maybe using a filter like [record_transformer](http://docs.fluentd.org/articles/filter_record_transformer) would do the trick.

**Comment by fideloper** [comment]
Thanks! 

For any future people:

For now, I'm creating templates with the Logstash format and using the `logstash_prefix` option to create separate indexes per use case (http logs vs syslogs vs application logs), each with the same "Logstash format".

I make a format per "template":

```json
{
  "template" : "logstash-*",
  "settings" : {
    "index.refresh_interval" : "5s"
  },
  "mappings" : {
    "_default_" : {
       "_all" : {"enabled" : true, "omit_norms" : true},
       "dynamic_templates" : [ {
         "message_field" : {
           "match" : "message",
           "match_mapping_type" : "string",
           "mapping" : {
             "type" : "string", "index" : "analyzed", "omit_norms" : true
           }
         }
       }, {
         "string_fields" : {
           "match" : "*",
           "match_mapping_type" : "string",
           "mapping" : {
             "type" : "string", "index" : "analyzed", "omit_norms" : true,
               "fields" : {
                 "raw" : {"type": "string", "index" : "not_analyzed", "ignore_above" : 256}
               }
           }
         }
       } ],
       "properties" : {
         "@version": { "type": "string", "index": "not_analyzed" },
         "geoip"  : {
           "type" : "object",
             "dynamic": true,
             "properties" : {
               "location" : { "type" : "geo_point" }
             }
         }
       }
    }
  }
}
```

Where `"template" : "logstash-*",` becomes :+1: 

* `"template" : "syslog",`
* `"template" : "http-*",`
* `"template" : "app-*",`

...in my use cases
