### ISSUE TITLE
Document relationship between `index_name` and `logstash_format` attributes

### ISSUE THREAD

**Issue by aj-jester** [uken/fluent-plugin-elasticsearch#125]
May be this is obvious to most but it was confusing why `index_name something` wasn't being reflected in elasticsearch when using `logstash_format true`. I went spelunking through the codebase and turns out if `logstash_format true` then `index_name` has no effect. Perhaps the documentation should make this clear?

https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L133-149

Thanks.

**Comment by pitr** [comment]
Good point @aj-jester. Would you be able to make a PR with doc improvement?

**Comment by nweiler** [comment]
Thanks for the comment, @aj-jester. I found this confusing as well.

**Comment by jamesone** [comment]
Any update on this?

**Comment by lukmanulhakimd** [comment]
Just run into this myself. Any update on this?
