### ISSUE TITLE
Protect against near-zero timestamps

### ISSUE THREAD

**Issue by portante** [uken/fluent-plugin-elasticsearch#129]
We ran into a case where we were tailing a file, parsing the log line to get the timestamp, forwarding the record, and failing to see it indexed as expected.

We have about 2,000 indexes in our ES instance, and we failed to see that the log data was landing in "`logstash-1970-01-01`".  There were no errors in any logs, or otherwise some indication that we had a bad timestamp.

Here was our config (notice "`%s`" and not "`%S`"):
```
<source>
  @type tail
  path /tmp/python-fluentd.log
  tag python.test
  format /(?<time>[^ ]* [^ ]*) (?<message>.*)/
  time_format %Y-%m-%d %H:%M:%s
</source>
```

It would be helpful to have this plugin protect against such events by logging a warning if the "`time`" value is close to zero when being used to construct the timestamp.

See line https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L140 for where we might make such a check.

**Comment by repeatedly** [comment]
This problem will be solved with strptime gem.
Can we close this issue?

https://github.com/fluent/fluentd/issues/677
