### ISSUE TITLE
Support Amazon Elasticsearch service's Signature Version 4 writes

### ISSUE THREAD

**Issue by robbwagoner** [uken/fluent-plugin-elasticsearch#131]
Today on the [AWS Blog] Amazon Elasticsearch service (*Amazon ES*) was announced.
This means that for Fluentd to be able to write log events to Amazon ES with a non-[IP-based] access policy, they must be signed with Signature Version 4. For example, sending log events from an ephemeral EC2 instance with an IAM Role. 

AWSLabs did open source the [Logstash output plugin for Amazon ES]. I hope that will make the changes necessary straightforward.

[AWS Blog]: https://aws.amazon.com/blogs/aws/new-amazon-elasticsearch-service/
[Logstash output plugin for Amazon ES]: https://github.com/awslabs/logstash-output-amazon_es
[Signing service requests]: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-signing-service-requests
[IP-based]: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-gsg-upload-data.html

**Comment by repeatedly** [comment]
AWS team implements own transport layer and they think releasing it helps other people.

https://github.com/awslabs/logstash-output-amazon_es/issues/1

If AWS team releases transport gem or Elasticsearch-ruby supports AES, we can easy to support AES.

**Comment by llibra** [comment]
FYI:

* https://github.com/winebarrel/faraday_middleware-aws-signers-v4
* https://github.com/atomita/fluent-plugin-aws-elasticsearch-service

**Comment by hsingh6764** [comment]
This is great!

**Comment by hSATAC** [comment]
:+1: to this

**Comment by robbwagoner** [comment]
Great! I am installing the AWS ES fluent plugin this morning to test it out.

**Comment by pitr** [comment]
Whoever tries it successfully, please let us know here so we can link to it from README

**Comment by mzahidriaz** [comment]
I've successfully used
 [https://github.com/atomita/fluent-plugin-aws-elasticsearch-service](https://github.com/atomita/fluent-plugin-aws-elasticsearch-service)

and post my apache access log to the amazon elastic search
