### ISSUE TITLE
Documents not getting into ES with a custom index.

### ISSUE THREAD

**Issue by paritosh16** [uken/fluent-plugin-elasticsearch#132]
I have the following configuration for dumping logs into ElasticSearch.
```
<match *.**>
  type copy
  <store>
    type elasticsearch
    host localhost
    port 9200
    include_tag_key true
    tag_key @log_name
    index_name fluentd
    type_name fluentd
  </store>
</match>
```
I have a plugin that grabs logs from S3. I have defined the mapping for the logs in elasticSearch. The plugin logs are getting into ElasticSearch but the log files from the S3 are not getting into ES.
If I remove the `index_name` and `type_name` along with adding `logstash_format true` to the above configuration, everything works like a charm. I need my custom index to be the one receiving the documents.
To be honest, I really don't know if this issue is with the log grabbing plugin or the `fluent-plugin-elasticsearch`. Thank you for the help.

**Comment by pitr** [comment]
Can you post an example log from S3?

**Comment by paritosh16** [comment]
The example log from S3
```
2015-05-13T23:39:43.945958Z my-loadbalancer 192.168.131.39:2817 10.0.0.1:80 0.001065 0.000015 0.000023 - - 57 502 "- - - " "-" ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2
```

**Comment by pitr** [comment]
How does that message look in JSON format?

**Comment by pitr** [comment]
closing old task
