### ISSUE TITLE
What's ssl_verify for and how to use it if true

### ISSUE THREAD

**Issue by iamzhout** [uken/fluent-plugin-elasticsearch#137]
In the README file, it suggests to set `ssl_verify` as `false`, is it because ssl verify is not fully supported?

In my case, when I set it true, I will get below error in td-agent.log file, and fail to send log via https to elasticsearch successfully.
```
2015-12-07 10:33:05 +0000 [warn]: fluent/output.rb:354:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2015-12-07 10:33:05 +0000 error_class="Faraday::SSLError" error="Unable to veri
fy certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `ENV['SSL_CERT_DIR'] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, `ENV['SSL_CERT_FILE'] = path_to_file`, `Excon
.defaults[:ssl_verify_callback] = callback` (see OpenSSL::SSL::SSLContext#verify_callback), or `Excon.defaults[:ssl_verify_peer] = false` (less secure)." plugin_id="object:3f8078cb5830"

```

Does anyone know how to make ssl_verify to work? or is it a bug of fluentd-plugin-elasticsearch plugin?

Regards,
Tao

**Comment by pitr** [comment]
`ssl_verify` was added to support self-signed certificates, see #99
