### ISSUE TITLE
Node discovery?

### ISSUE THREAD

**Issue by lam-juice** [uken/fluent-plugin-elasticsearch#141]
Having a round robin list of nodes is not scalable as the number of ElasticSearchnodes go up.  The list of nodes can be obtained through the /_nodes URI, so I wonder whether the Ruby ElasticSearch library is providing a node discovery API that can be used?

This way, an ElasticSearch cluster can be grown without having to modify the plugin configuration.

**Comment by pitr** [comment]
this feature was added last year, #78 and I clarified the README just now 82d1c86

**Comment by lam-juice** [comment]
Thanks, my bad - does it mean reload_connections and reload_on_failure will try to obtain a node list from the server, regardless of what my initial "hosts" list is?  So the initial "hosts" list will just serve as a starting point - and the config file does not need to be modified as new ElasticSearch nodes are added.

Thanks Pitr.

**Comment by pitr** [comment]
that's right!
