### ISSUE TITLE
Providing a way to index strings which are not_analyzed

### ISSUE THREAD

**Issue by erez-rabih** [uken/fluent-plugin-elasticsearch#144]
Hi,

I'm using the plugin to ship logs to Logstash. My problem is that I'd like some of the fields to be indexed in ES without being analyzed.
I know that Logstash shipper takes each string field and indexes it in ES in two different fields:
1. The original field as analyzed
2. original_field.raw as not_analyzed

Is there a way to tell the plugin to ship a certain field as not analyzed? Or even have all string fields indexed as both analyzed and not_analyzed?

Thanks.

**Comment by pitr** [comment]
This was just asked in #142, I'm copying the answer from there:

You need to predefine an index template ahead of time - see https://github.com/uken/fluent-plugin-elasticsearch#index-templates

**Comment by erez-rabih** [comment]
@pitr Would you accept a PR to make it an option built into the plugin?

**Comment by pitr** [comment]
no, that is outside the scope of this plugin (but thanks for asking). You can do this during service provisioning with chef/ansible/etc, or in cron if you rotate your indices often, or manually if you just need to do this once. There are better places for this functionality than in a plugin that only deals with sending data to ES.

**Comment by erez-rabih** [comment]
OK, thanks for the quick response.
