### ISSUE TITLE
_Routing support missing 

### ISSUE THREAD

**Issue by vishnuvg1984** [uken/fluent-plugin-elasticsearch#147]
Currently there is no way to pass "_routing" information to elastic search bulk api through this plugin, "_routing" is a required feature for performance and the elastic search bulk api supports too. Anyone knows, Is there any other way to pass "_routing" information by using this plugin... 

When gone through "code" , looks like the feature is missing...

**Comment by pitr** [comment]
looks like should be relatively easy to implement, PR is definitely welcomed
