### ISSUE TITLE
bypass type_name

### ISSUE THREAD

**Issue by nnovikov** [uken/fluent-plugin-elasticsearch#149]
If log file in JSON format have _type key, I want to bypass _type without change it to "fluentd" (by default).

**Comment by pitr** [comment]
3 things I think you can do:

1. Use forest plugin and specify different values for _type key that you have. See https://github.com/uken/fluent-plugin-elasticsearch#not-seeing-a-config-you-need
2. Use `@type elasticsearch_dynamic`, see https://github.com/uken/fluent-plugin-elasticsearch#dynamic-configuration
3. Create a PR that implements the behaviour that you want. If you decided to do this, first let us know here how you are planning to implement it

**Comment by pitr** [comment]
implemented in #169
