### ISSUE TITLE
Time.parse is slow - allow other methods of finding index name

### ISSUE THREAD

**Issue by ashb** [uken/fluent-plugin-elasticsearch#152]
We're trying to use fluentd to push a lot of logs into ElasticSearch for Kibana (so we've got `logstash_format` set to true to use date-suffixed-indexs) and we noticed that fluentd was consuming a lot of CPU.

So I fired up ruby-prof and pushed 50k messages through fluentd as quick as I could send them. What I found was that in this case we were spending 11.79s inside `Fluent::MemoryBufferChunk#msgpack_each` on [line 59](https://github.com/uken/fluent-plugin-elasticsearch/blob/v1.1.0/lib/fluent/plugin/out_elasticsearch.rb#L131) and of that it spend 8.88s in Time.parse (75%)!  All this just to find out which index name to use.

(I was profiling v1.1.0, but this hasn't changed other than to be on [line 152](https://github.com/uken/fluent-plugin-elasticsearch/blob/v1.3.0/lib/fluent/plugin/out_elasticsearch.rb#L152) in the most recent version.)

I started trying other time parsing methods (all times are per iteration of the `msgpack_each` which is called 50k, ones per message). Each test was only run once so they aren't hugely precise but rough improvements are still useful in the broad sense.

- `Time.iso8601` went down to 9.13 s (1.29x faster than `Time.parse`. `Time.iso8601 is an alias for `Time.xmlschema`)
- `Time.strptime(record['@timestamp'], "%FT%T.%N%z")` 9.08  (1.30x faster. This is basically a poorer version of `Time.xmlschema` which uses a regex internal allowing for optional fractional seconds.)
- My own regex based version took 7.82s (1.5x faster) but again just as limiting in format to the strptime version. I'm not sure which regex I did here, sorry - It might just have been to capture Y-m-d, then pass this into `Time.new`) But either way - this wasn't very generic and didn't work if something used a timezone other than UTC/"00:00".
- I then tried not creating a Time object at all and just using `"#{y}.#{m}.#{d}"`: 2.05s (5.75x faster!)

A lot of the time using any of the `Time` methods is in constructing an object, and converting between UTC and not. 

So I found that there were some gains to be had, and one outstanding way if I'd be willing to massively simplify it. But I doubt _I'd_ accept a PR for that ;)

For our use case since we can control the format that things log in and know that we set all our server time zones to UTC that a simple detection for `yyyy-mm-dd` would work for us, but that's probably too specific for us, so I thought about another way of doing this.

The best option that I could think of was to have a previous filter set `record["@target_index"]` to the value we want (using a very quick regex based version just to pull out the date) and then add a simple flag to the plugin of this config.

So that is a really long winded way of saying I'm thinking of adding two config params:

- `config_param :autodetect_target_index, :bool, :default => true`
- `config_param :index_key, :string, :default => "@target_index"`

With the following change in behaviour:

```diff
+      if @autodetect_target_index
+        target_index = record[@index_key] || @index_name
+      elsif @logstash_format
         if record.has_key?("@timestamp")
```

(along with appropriate tests and docs)

Does this sound like an acceptable solution?

The command I was using to perform these profiles was `bundle exec ruby-prof --mode=cpu -x 'Kernel#gem_original_require'  -x 'Kernel#require' -x 'Kernel#load' -f profile-report.html -p graph_html --exclude-common-callbacks --exclude-common-cycles -- /Users/ash/.rbenv/versions/2.2.3//bin/fluentd -c fluent.conf -p $PWD/plugins --no-supervisor` with a small custom filter plugin that send a kill signal to itself once it had processed 50k messages

**Comment by ashb** [comment]
Oh and other profile results: of the time spent in our `write` method, 30% was in the `msgpack_each` loop and the other 47% (about 10s) was in `Elasticsearch::API::Actions#bulk` but only a fraction of a second seemed to be in IO wait time - most seemed to be in parsing and building up the response objects.

I'm not sure what to make of this. I might be reading the profiler results wrong here.

**Comment by pitr** [comment]
That's very interesting! Thanks for looking into this.

FYI I replicated it with this setup - https://gist.github.com/pitr/9a518e840db58f435911 where I use in_dummy plugin to generate data

**Comment by pitr** [comment]
I benchmarked a few time parsing methods and here's what I found:

```ruby
require 'time'
require 'benchmark'
n = 200_000

Benchmark.bm(20) do |x|
  x.report('Time.parse') { n.times { Time.parse('Thu Nov 29 14:33:20 GMT 2001') } }
  x.report('Time.strptime') { n.times { Time.strptime("Thu Nov 29 14:33:20 GMT 2001", "%a %b %d %H:%M:%S %Z %Y") } }
  x.report('Time.xmlschema') { n.times { Time.xmlschema("2001-11-29T09:33:20-05:00") } }
  x.report('DateTime.strptime') { n.times { DateTime.strptime("Thu Nov 29 14:33:20 GMT 2001", "%a %b %d %H:%M:%S %Z %Y") } }
end
```

With the following results:

```
                           user     system      total        real
Time.parse             5.660000   0.150000   5.810000 (  5.817896)
Time.strptime          2.090000   0.070000   2.160000 (  2.172890)
Time.xmlschema         1.460000   0.030000   1.490000 (  1.485995)
DateTime.strptime      1.100000   0.050000   1.150000 (  1.150585)
```

`DateTime.strptime` is fastest because 1) it does not use regexes, but [a simple C-based parse](https://github.com/ruby/ruby/blob/ruby_2_2/ext/date/date_strftime.c) and 2) it doesn't return a Time instance.

**Comment by pitr** [comment]
I think the best thing would be to use `strptime` if the format is specified, falling back to `Time.parse`.

Also, we might be doing too much with the time object. Eg in case of `@timestamp` being specified we do:

```ruby
time = Time.parse record["@timestamp"]
target_index = "#{@logstash_prefix}-#{Time.at(time).getutc.strftime("#{@logstash_dateformat}")}"
```

`Time.at` is completely unnecessary.

Throughts?

Regarding using a filter plugin that would set `record["@target_index"]`, wouldn't that just move cpu time to that plugin?

**Comment by ashb** [comment]
It's interesting that the `DateTime` version of `strptime` is twice as fast as the `Time` version of it! I guess the advantage of `Time.parse` is that it handles many more formats (which is probably a large part of what makes it slow.)

> Regarding using a filter plugin that would set record["@target_index"], wouldn't that just move cpu time to that plugin?

It would for a general case - but because I can control more closely the log producers I can use a very simple (read quick) regex to set this. But that wouldn't work for a general case.

`Time.at` is unnecessary but wasn't showing up as a significant time sink in any of my benchmarks -- possibly just because I wasn't hitting that code path. No reason not to tidy it up though!

Options now:

- Provide a strptime format and use `DateTime.strptime` (this could work for us) -- if it's not provided possibly fallback to `Time.parse`?
- Thinking about it I could possibly use the dynamic plugin for my needs (I'm trying and benchmarking this now)
- Something horrible and hacky around ffi to call the C strptime/strftime and avoid ruby object creation which was a big chunk of the time. Fast but possibly not that maintainable.

(This will be a slow conversation due to time zones – there's 8 hours between us)

**Comment by ashb** [comment]
Oh Just saw this:

> **this uses Ruby's eval for every message, so there are performance and security implications.**

so I won't be going down that approach - eval'ing something from log output seems like a bad idea, even if it should be something controlled by a previous filter that I wrote :)

**Comment by pitr** [comment]
Option 3: there's https://github.com/rtomayko/date-performance but it only supports Ruby 1.8 and Date. I wish there was something that just wraps [strftime from time.h](http://en.cppreference.com/w/c/chrono/strftime)

Option 2 is not really an option for you, due to performance penalty as you noticed :) It's there if you need a lot of control or have an extremely non-standard setup.

Option 1 is probably the best and most useful to most people. Would you be able to tackle it?

**Comment by ashb** [comment]
Sure, I'll create a PR adding a `DateTime.strptime` based version looking at a `timestamp_format` config param (I'll try to reuse the name that the default plugins have. Cant remember exactly what it is right now)

Would you also accept a different PR that adds my original idea of pull target index from a record attribute?

**Comment by ashb** [comment]
>  I wish there was something that just wraps strftime from time.h

ruby-ffi based version? I'm not sure how easy that would be to install, nor how much speed we'd get out of it.

**Comment by pitr** [comment]
Awesome, thanks!

Regarding original idea, yes as long as the configs are closer to this

```ruby
config_param :target_index_key, :string, :default => nil
```

There's no need for two configs if one will do just fine, and defaults should never break current behaviour.

**Comment by ashb** [comment]
#154 for the second PR.

**Comment by pitr** [comment]
thanks @ashb, 1.4.0 is out with both #153 and #154

**Comment by ashb** [comment]
\o/ Thanks for the speedy response and helping me get these merged.
