### ISSUE TITLE
Support elasticsearch-2.2?

### ISSUE THREAD

**Issue by zhangbin666888** [uken/fluent-plugin-elasticsearch#156]
hi, Does this plugin support elasticsearch-2.2 ? 
when i use elasticsearch-2.2 ,i  don`t found having logs to pass back

**Comment by pitr** [comment]
Hmm, not seeing anything that could cause this in either [Breaking changes in 2.1](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-2.1.html) or [Breaking changes in 2.2](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-2.2.html)

Is there anything in elasticsearch logs?

**Comment by static-max** [comment]
Works with all version of 2.2.X and 2.3 (currently) for me

**Comment by pitr** [comment]
thanks @static-max !
