### ISSUE TITLE
Make adding of "@timestamp" optional if time_key is specified

### ISSUE THREAD

**Issue by static-max** [uken/fluent-plugin-elasticsearch#160]
I want to use Logstash-style index names, but my data to ingest already contains a timestamp field that I use for queries, and I don't want an additional field named "@timestamp" that occupies disk space and is never used.

Great plugin by the way!

**Comment by pitr** [comment]
Sounds like a good idea, if you are not using Kibana. Feel free to contribute a PR.

**Comment by static-max** [comment]
Ok, how should we name the config? `time_key_exclude_timestamp`?

**Comment by pitr** [comment]
that sounds good
