### ISSUE TITLE
Index names should be converted to lowercase

### ISSUE THREAD

**Issue by meetyg** [uken/fluent-plugin-elasticsearch#162]
Currently, Elasticsearch doesn't support uppercase letters in index names.
Therefore, in my opinion the fluent-elasticsearch plugin should handle this, be lower-casing
the index name before inserting to Elasticsearch.
This should be done to the final index name, no matter what the index name source is from (logstash-prefix, index_name, etc...)

**Comment by pitr** [comment]
Sounds like a good idea! @meetyg would you be able to implement this?

**Comment by meetyg** [comment]
I wanted to make sure that others are also interested in this feature.
I'm not a ruby programmer, but it does sound easy, so I guess I could give it a try.
I'll open a pull-request soon.

**Comment by meetyg** [comment]
Accidentally closed this.
I'll close after the pull-request (that I will open) will be merged.

**Comment by meetyg** [comment]
Opened pull-request: #163 
https://github.com/uken/fluent-plugin-elasticsearch/pull/163

**Comment by meetyg** [comment]
@pitr what do you think? Is the PR acceptable ?
