### ISSUE TITLE
 Service 'fluentd' failed to build: lstat plugins: no such file or directory

### ISSUE THREAD

**Issue by panikumarm** [uken/fluent-plugin-elasticsearch#165]
docker build fails  with the following exception: I'm using local dockertoolbox on windows machine

Dockerfile:

```
FROM fluent/fluentd:latest
MAINTAINER <your name>
USER fluent
WORKDIR /home/fluent
ENV PATH /home/fluent/.gem/ruby/2.2.0/bin:$PATH
RUN gem install fluent-plugin-secure-forward fluent-plugin-elasticsearch fluent-plugin-burrow fluent-plugin-grep
EXPOSE 24284
CMD fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
```

**Comment by pitr** [comment]
I have no windows machine I can test this on. Can you post a full stacktrace?

**Comment by andesyudanto** [comment]
@panikumarm you need to create `fluent.conf` file and `plugins` directory first before build the fluentd docker image. 
Because there are `ONBUILD` command on `fluent/fluentd:latest` image that need to copy your `fluent.conf` and `plugins` inside the docker image you want to build.

**Comment by cosmo0920** [comment]
This issue seems to be Dockerfile building issue on Windows not for fluent-plugin-elasticsearch.
Closing.
