### ISSUE TITLE
Support for script write operation

### ISSUE THREAD

**Issue by jonsgreen** [uken/fluent-plugin-elasticsearch#166]
I am wondering if it would be possible to add a script options for write_operation. Code might look something like this:
```ruby
  def append_record_to_messages(op, meta, record, msgs)                            
    case op                                                                        
    when "script"                                                                  
      if meta.has_key?("_id")                                                      
        msgs << { "update" => meta }                                               
        msgs << { "script" => record.delete('script'), "upsert" => record }               
      end        
```
I am using this successfully in a plugin that inherits and overwrites the above method. If you think this would be an acceptable feature I am willing to write some tests and submit a pull request. It would also need some documentation since obviously it requires a filter plugin that adds the script to the record.

**Comment by pitr** [comment]
The idea sounds interesting. What about the script itself being configured by this plugin instead of using filter plugin?

Could you give an example of where you would use this feature?

Is the plugin you are using opensourced?

**Comment by jonsgreen** [comment]
It might be possible for the script to be configured though I don't know how limiting the fluent parser is. The filter plugin that we use is in a private repo but I can describe the use case where I needed this feature.

We are storing some twitter/gnip activities in elastic search and keep track of tags from matching rules. We needed to run a historical job and had to break up our rules into two batches since there is a limit per job. Anyhow, we ended up with two sets of overlapping activities however each with its own set of tags. If I did a regular update/upsert then the matching rule tags from the second job would override the tag from the first. I used a script to merge the tags. I have to filter each record anyhow so ended up adding the script to each record with the following code:
```ruby
 record['script'] = {
    'file' => 'merge_tags',
    'params' => { 'new_tags' => record['gnip']['matching_rules'] }
 }
```
On my elasticsearch cluster I have the actual groovy script file:
```groovy
ctx._source.gnip.matching_rules += new_tags
ctx._source.gnip.matching_rules.unique()
```
Not sure if this was the only or best way to approach the problem but combined with the above append_record_to_messages change did the trick.

I am not sure how easy even that simple script would be to add to the configuration. Some folks might want to do inline scripts which would be even more complex. There could even be a use case in which a different script would be used for different records. 

There may be other ways of configuring this that I have not thought of or not aware of so I welcome any feedback or suggestions.

**Comment by pitr** [comment]
Interesting use case, just not sure how useful this would be to others. Adding any functionality to the plugin needs to be useful to as many people as possible. Seems like you solved this for your task, I don't think there's any need for this functionality in this plugin. At least for now. If others start requesting it we can revisit. Thanks again.
