### ISSUE TITLE
Question: break up tag into multiple fields

### ISSUE THREAD

**Issue by MrMMorris** [uken/fluent-plugin-elasticsearch#167]
Awesome plugin. Really easy to get going. Have a question:

I have something like `--log-opt tag=docker.<hostname>.{{.ImageName}}.{{.Name}}`. I have changed the `tag` field to be `not_analyzed` so I can properly search it like a string, but it would be more flexible if I could take the `tag` field and break it into multiple fields such as:

```json
{  
  "hostname": "<hostname>",
  "image": "{{.ImageName}}",
  "container_name": "{{.Name}}"
}
```

Is there any way to accomplish this? I was looking at `split` but it doesn't seem to be able to split a value into multiple fields. I guess this is more of an elasticsearch question, but I thought I'd see if you have any insights. Not sure if docker labels or something would help here.

Thanks

**Comment by pitr** [comment]
Some plugins you can try are [fluent-plugin-record-modifier](https://github.com/repeatedly/fluent-plugin-record-modifier), [fluent-plugin-record-modifier](https://github.com/repeatedly/fluent-plugin-record-modifier), [fluent-plugin-record-reformer](https://github.com/sonots/fluent-plugin-record-reformer), [fluent-plugin-rewrite-tag-filter](https://github.com/fluent/fluent-plugin-rewrite-tag-filter). There's more [here](http://www.fluentd.org/plugins)
