### ISSUE TITLE
Timestamp not showing in elastic search

### ISSUE THREAD

**Issue by mpas** [uken/fluent-plugin-elasticsearch#173]
In my current setup i am trying to send my log information to elastic search. Fluentd is not complaining and it seems that the logdata is send to Elastic Search. But the `@timestamp` is not working.

I have the following config.

```
  <match **>
    @type elasticsearch
    host localhost
    port 9200
    time_key_format %Y-%m-%d %H:%M:%S.%N
    time_key time_stamp
    logstash_format true
  </match>
```

The payload of my record actually contain a `time_stamp` field with the following content:
`"time_stamp":"2016-06-07 17:38:51.317"`

When i open the index in Kibana the dropdown field for the `@timestamp` just stays empty. I can select the `timefield name` dropdown in Kibana but nothing shows up.

Any hints on what the issue could be? Or is there a better way to get the `timestamp` field in?

Maybe it is related to issue #157 , i also see no errors.

**Comment by pitr** [comment]
1. Can you verify that the raw record in elasticsearch does not contain the timestamp?
2. Does payload contain `@timestamp`?

**Comment by cosmo0920** [comment]
No response. Closing.
