### ISSUE TITLE
Turning off @timestamp does not seem to be working when logstash_format is used

### ISSUE THREAD

**Issue by mohigupt** [uken/fluent-plugin-elasticsearch#180]
Hey,

I do not require @timestamp field to be emitted in fluentd output to elasticsearch and so am trying to disable it as :

```
<match app.json>
   @type elasticsearch
    logstash_format true
    logstash_prefix app
    time_key_exclude_timestamp  true
    hosts  127.0.0.1:9200 
    type_name logs
    flush_interval 1s
</match>
```
However, I still see @timestamp getting popped-up in my fluentd output to elastic.
I noticed that when I do not use logstash_format, i.e. "logstash_format  false" and specify my own index/type names, it works fine (i.e. @timestamp is not sent in fluentd output with  "time_key_exclude_timestamp  true").

Can somebody help if am missing some config or there is something more to be done to omit @timestamp in output with "logstash_format true"?

Thanks.

**Comment by pitr** [comment]
`time_key_exclude_timestamp` option only works with `time_key` setting - https://github.com/uken/fluent-plugin-elasticsearch/blob/ff69bb1/lib/fluent/plugin/out_elasticsearch.rb#L240

**Comment by mohigupt** [comment]
Thanks, it worked fine when I specified the root field “logtime” of my Json message as time_key. With a nested field like “metadata.timestamp”, it doesn’t work. I think its because fluentd doesn’t support peeking into the nested Json fields. 
I found this plugin -  https://github.com/vanilla/fluent-plugin-burrow - which might help here(will tryout) but please let me know if you know of some other way to access nested elements.

Best,
Mohit

**Comment by pitr** [comment]
Cool. Feel free to add support for dot notation in `time_key`, I'll happily merge it.
