### ISSUE TITLE
Behaviour when elastic cluster size full

### ISSUE THREAD

**Issue by geek876** [uken/fluent-plugin-elasticsearch#195]
Wanted to understand the behaviour of plugin when the destination elastic-search cluster size is full.

We noticed that the plugin doesn't throw any errors so the events seem to go in a black-hole. Once storage becomes available the plugin starts to push as normal.

I believe the plugin should fail with errors and events start to go to `secondary` after the usual retry loop when the destination ES cluster is full.

My configs
```

<match **.elasticsearch>
    type "aws-elasticsearch-service"
    buffer_type file
    buffer_path /var/log/td-agent/buffer/elasticsearch
    buffer_queue_limit 512m
    buffer_chunk_limit 8m
    disable_retry_limit false
    retry_limit 20
    retry_wait 10s

    max_retry_wait 120s
    num_threads 10
    include_tag_key true
    tag_key tag
    logstash_format true
    logstash_prefix fluentd
    flush_interval 10s
    reload_on_failure  false
    reload_connections false
    <endpoint>
      url    https://xxxx.eu-west-1.es.amazonaws.com
      region eu-west-1
    </endpoint>
    <secondary>
      type file
      path '/var/log/td-agent/fluent-plugin-aws-elasticsearch-service.failed'
    </secondary>
</match>

```

**Comment by pitr** [comment]
Events do not go to a black hole. They get buffered. Fluentd has buffering and retry mechanism, see https://github.com/uken/fluent-plugin-elasticsearch#buffered-output-options I recommend `file` buffer type.

It is not this plugin's responsibility to monitor elasticsearch cluster. You can use nagios to check various ES stats. Fluentd log should contain messages from this plugin that warn about not being able to connect to ES cluster, retries and, in an event of continuous failure, eventual discarding of events.

**Comment by geek876** [comment]
@pitr thanks for your response. Indeed I was expecting that the events would be buffered (I do have a file buffer set) and then after the `retry` count has been reached, I expected events to start going to `secondary` which is also a `file` but nothing like this happened.

I suspect this is related to issue #105. 

I am not aware what status response ES returns if storage is full ( I have asked this within their forums and awaiting reply).
