### ISSUE TITLE
ruby code not handled

### ISSUE THREAD

**Issue by nico2610** [uken/fluent-plugin-elasticsearch#212]
#### Problem

I'm trying to add some ruby code in the config : 

```
    hosts "#{case ENV['HOSTNAME'].split('.')[1]; when 'hostA' then 'EShost1:9200,EShost2:9200'; when 'hostB' then 'EShost3:9200,EShost4:9200'; when 'hostC' then 'EShost5:9200,EShost6:9200'; end}"
    logstash_format true
    time_key_format %Y-%m-%dT%H:%M:%S.%N%z
```

I can't restart the process without error and I don't have a lot a of detail in the logs (neither in the systemctl logs or within the journal logs.)

```
2016-11-04 09:31:54 +0100 [info]: shutting down fluentd
2016-11-04 09:31:54 +0100 [info]: shutting down input type="forward" plugin_id="object:3fd8472742a0"
2016-11-04 09:31:54 +0100 [info]: shutting down output type="copy" plugin_id="object:3fd84726a4f8"
2016-11-04 09:31:55 +0100 [info]: process finished code=0
```
If I specify fixed hosts without ruby code, it works fine.
I know that the "#{ruby code}" feature is handled in fluentd core, but it seems not to be the case in the plugin.

**Comment by pitr** [comment]
fluentd doesn't handle `#{ruby}` AFAIK. This plugin provides [elasticsearch_dynamic](https://github.com/uken/fluent-plugin-elasticsearch#dynamic-configuration) which lets you specify ruby code in your configs
