### ISSUE TITLE
Support for ingest pipelines in elasticsearch 5.x

### ISSUE THREAD

**Issue by mohit-soral** [uken/fluent-plugin-elasticsearch#217]
#### Problem
With elastic 5.0 their new feature of ingest node is quiet helpful. 

When using Filebeat (as log pusher) there is a new config option, which allows to specify an ingest pipeline to which the logs are to be pushed (for parsing before indexing).

How may we do the same from fluentd ?
Is there a way we can tweak the URL for the bulk API of elasticsearch ?
...

#### Steps to replicate
[This](https://www.elastic.co/guide/en/beats/filebeat/master/configuring-ingest-node.html) will give an idea of the Filebeat configuration for pipeline

**Comment by pitr** [comment]
I'm not familiar with Filebeat, feel free to open a PR

**Comment by cosmo0920** [comment]
#266 is merged and released as 1.9.6. Closing.
