### ISSUE TITLE
Safely recover from ES failure

### ISSUE THREAD

**Issue by MiLk** [uken/fluent-plugin-elasticsearch#219]
Over the last few months, I had several issues with my ES cluster (out of disk space, out of memory, network failure, ...).
When the ES cluster is not reachable, fluentd starts to buffer the messages.

But when I restore the ES cluster, and send a `SIGUSR1` to forces the buffered messages to be flushed and reopens Fluentd’s log, ES can't process everything, starts to timeout and I'm back in a non-working state.

I have to delete the buffers, and reload fluentd to process the logs.

My config is:
```
<source>
  @type syslog
  port 5140
  bind 0.0.0.0
  tag system
  include_source_host true
</source>

<filter system.local0.**>
  @type parser
  key_name message
  format json
  suppress_parse_error_log true
  reserve_data true
</filter>

<match system.**>
  @type copy
  <store>
    @type s3

    s3_bucket REDACTED
    s3_region ap-northeast-1
    path logs/

    time_slice_format %Y%m%d%H
    time_slice_wait 10m
    utc

    use_server_side_encryption AES256

    buffer_type file
    buffer_path /mnt/fluentd/logstash/s3
    buffer_chunk_limit 256m
  </store>
  <store>
    @type elasticsearch
    logstash_format true
    hosts elasticsearch.service.consul:9200
    type_name syslog
    include_tag_key true

    buffer_type file
    buffer_path /mnt/fluentd/logstash/es
    buffer_chunk_limit 256m
  </store>
</match>
```

Is there something I can do to reduce the speed of the buffered messages sent to ES?
Or any other option to handle that?

**Comment by pitr** [comment]
Apart from experimenting with [Buffered Output Options](https://github.com/uken/fluent-plugin-elasticsearch#buffered-output-options), I suggest increasing the size of ElasticSearch or tweaking its settings like `refresh_interval`

**Comment by MiLk** [comment]
Ok. I've reduced the `buffer_chunk_limit` which was probably too high and tweaked the `retry_wait`. I will see how it goes.

Thank you.

**Comment by brandonmp** [comment]
dealing w/ this too, though i'm using hosted `elasticsearch` so don't have the ES tweak option. I hit a `BufferQueueLimitError` error that returned `exceptions` to all my apps forwarding to `fluentd` & brought them to a stand-still.

@pitr, @MiLk -- do you view these options (the **bolded**) as sufficient for avoiding the kind of chain-reaction `exceptions` an `ES` write failure can produce? I'm new to `fluentd` so hoping for opinions more expert than my own. 

```
<match **>
  @type copy
  <store>
    @type s3
   # etc etc, not relevant
  </store>
  <store>
    @type elasticsearch
    host logsene
    port 443
    scheme https
    index_name logsene-api-key
    buffer_type file
    buffer_path /tmp/fluent/es-buffer/es.all.*.buffer
    **buffer_chunk_limit 250k
    buffer_queue_full_action drop_oldest_chunk
    flush_interval 50s
    retry_limit 5
    retry_wait 60**
    num_threads 1
  </store>
  **<secondary>
    @type file # or forward
    path /var/log/fluent/forward-failed
  </secondary>**
</match>
```

If I understand the docs correctly, setting the `buffer_queue_full_action` should outright avoid the `exception` scenario by dropping logs to make the `buffer` effectively bottomless.

Then, to prevent lost logs, the `secondary` config should provide a place for logs to go in the event that a misfit log is being repeatedly rejected by `ES`

**Comment by MiLk** [comment]
With that configuration, you will loose the messages which would fail to be sent after 5 attempts within 5 minutes.
I'm now using the following:
```
    buffer_chunk_limit 32m

    disable_retry_limit true
    retry_wait 2s
    request_timeout 30s
```
It's slightly better, but I still have issues.

**Comment by macdjord** [comment]
Setting a large request_timeout value should help.

**Comment by MiLk** [comment]
Yes, the situation is now better for different reasons.
Increasing `request_timeout` and reducing `buffer_chunk_limit` seems to be the way to go.
