### ISSUE TITLE
Support nanosecond timestamps

### ISSUE THREAD

**Issue by yissachar** [uken/fluent-plugin-elasticsearch#222]
Fluentd 0.14 has support for nanosecond timestamps but it seems that this plugin does not support that.

Example config:

```
<source>
  @type tail
  read_from_head true
  path catalina.out
  pos_file catalina.pos
  time_format %Y-%m-%d %H:%M:%S,%L
  tag foo.*
  format multiline
  format_firstline /\d{4}-\d{2}-\d{2}/
  format1 /^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) \[(?<thread>.*)\] (?<level>[^\s]*)(?<message>.*)/
</source>

<match foo.**>
  @type elasticsearch
  logstash_format true
  flush_interval 5s
  host localhost
  port 9200
</match>
```

When using this config I end up with timestamps that are only resolved to the second. If I use stdout output instead of Elasticsearch then I see that the timestamps have millisecond granularity.

**Comment by yissachar** [comment]
@pitr I started coding up the required changes and currently have something that works for me. However, supporting this feature requires moving to the v0.14 API, which means that users on Fluentd v0.12 would not be able to use new versions of this plugin until they upgrade their Fluentd version to >=0.14. Before I put any further work into cleaning up my code and submitting a PR, I'd like to know if this is something that you are OK with or not.

**Comment by pitr** [comment]
@yissachar I am perfectly fine with that, 0.14 was released 6 months ago, about time we jump on that bandwagon. Also, I found [instructions on upgrading plugin from 0.12 to 0.14](http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12) I am planning to follow section "Updating Plugins Overview" when releasing 0.14-only version of this plugin.

**Comment by miketheman** [comment]
Bump. I filed myself a reminder to check back in on this issue since we notices our problem in January.

Is there anything we can do to help move this along? We'd really like the precision added via these timestamps.

**Comment by ChipmunkV** [comment]
@yissachar, is there a WIP PR?

**Comment by davidgacc** [comment]
I am trying to see the timestamp with miliseconds on Kibana. But it seems only to show only seconds

fluentd 0.14.19
td-agent 0.14.16

Example of my log:

2017-04-02 00:00:02,027 INFO  [com.***] (http--0.0.0.0) text

Ouput on Kibana:

April 2nd 2017, 00:00:02.000

`<source>
        @type tail
        path /home/arias/Documents/log/teste_21.log
        pos_file /var/log/td-agent/td-agent-test-62.log
        read_from_head true
        format multiline
        format_firstline /[0-9]+-[0-9]+-[0-9]+/
        format1 /^(?<timestamp>[0-9]+-[0-9]+-[0-9]+\s+[0-9]+:[0-9]+:[0-9]+,[0-9]+)\s+(?<log_level>[a-zA-Z]+)\s+\[(?<class>.*)\]\s+\((?<thread_pool>.*)\)\s+(?<log_message>.*)/
        keep_time_key true
        time_key timestamp
        time_format %Y-%m-%d %H:%M:%S,%L
        tag teste-3.log
</source>

## Store Data in Elasticsearch
<match *.**>
        @type copy
        <store>
                @type elasticsearch
                host ***.es.amazonaws.com
                port 80
                logstash_format true
                logstash_prefix activation 
                utc_index true
                time_key_format %Y.%m.%d
                buffer_type memory
                buffer_chunk_limit 8M
                buffer_queue_limit 512
                reload_connections false
                reload_on_failure true
                flush_at_shutdown true
        </store>
</match>
`
Any ideas? I would appreaciate your help.
Thank you.

**Comment by davidgacc** [comment]
@yissachar what version of EL are you using?

**Comment by yissachar** [comment]
@ChipmunkV See the linked PR https://github.com/uken/fluent-plugin-elasticsearch/pull/223

@davidgacc I am using Elasticsearch 5.x
