### ISSUE TITLE
How can I get fluent-plugin-elasticsearch plugin preinstalled in the td-agent rpm package?

### ISSUE THREAD

**Issue by liujiawinds** [uken/fluent-plugin-elasticsearch#226]
#### Problem
I have a `td-agent-2.3.3-0.el6.x86_64.rpm` and I installed it on my produce environment.
But, It's very very slow to install the elasticsearch plugin by command below. 

```
td-agent-gem install fluent-plugin-elasticsearch --no-document
```

So, I'm trying to get fluent-plugin-elasticsearch plugin preinstalled in the td-agent rpm package?

Is there some advice?
...

**Comment by pitr** [comment]
Maybe @repeatedly has some tips. I've always done it the way you do it. Also try adding `--no-ri --no-rdoc`

Alternatively consider using [Packer](https://www.packer.io/) to pre-bake image

**Comment by liujiawinds** [comment]
@pitr Thanks, I'v solved it.  [td-agent2 Packaging Scripts](https://github.com/treasure-data/omnibus-td-agent)
