### ISSUE TITLE
mapper_parsing_exception not communicated through logs

### ISSUE THREAD

**Issue by zgolus** [uken/fluent-plugin-elasticsearch#227]
When trying to index a document which would cause mapping type conflict (e.g. when trying to store a string to a field declared as an object) I get no indication of failure from the plugin, it just silently skips the document, however when trying to index the same document directly in ES I'm getting mapper_parsing_exception (400). I would expect in such situation that a log entry is created so the issue can be spotted and fixed.

I'm using dockerized fluentd v0.12.29 with fluent-plugin-elasticsearch v1.9.0 and fluent-plugin-aws-elasticsearch-service v0.1.6 on AWS Elasticsearch Service (2.3).

Best,
Jakub

**Comment by pitr** [comment]
Please provide steps to replicate. You can use this gist as a starting point

**Comment by zgolus** [comment]
I have created a gist with all files needed to recreate the issue: https://gist.github.com/zgolus/813ea2c30c142b9c740f50529a709878

To reproduce the issue please do the following:

Clone the gist:
`git clone https://gist.github.com/813ea2c30c142b9c740f50529a709878.git`
`cd 813ea2c30c142b9c740f50529a709878`

Build the image:
`docker build -t ps-fluentd .`

Start docker compose which will spawn Fluentd, Elasticsearch, Kibana and Nginx which will produce some logs:
`docker-compose up`

Deliberately preconfigure Elasticsearch with a mapping that is wrong:
`http PUT http://localhost:9200/fluentd < mapping.json`

Hit NGINX container to produce a log that doesnt match the mapping that we just provided:
`http GET http://localhost:80`

Make sure that no log was added to "fluentd" index:
`http GET http://localhost:9200/_cat/count/fluentd`

Check docker compose output and see that Elasticsearch reported an error regarding wrong mapping:
`elasticsearch_1  | [2017-01-03 15:15:50,489][DEBUG][action.bulk              ] [Luna] [fluentd][4] failed to execute bulk item (index) index {[fluentd][fluentd][AVlk5pZR2rU6autXE0ta], source[{"container_id":"1ae165321463b45a8baca9d4ae9a4f17f74db69c583bdb3d2d2badbad6e6f56f","container_name":"/813ea2c30c142b9c740f50529a709878_nginx_1","source":"stdout","log":"172.23.0.1 - - [03/Jan/2017:15:15:47 +0000] \"GET / HTTP/1.1\" 200 612 \"-\" \"HTTPie/0.9.2\" \"-\"","@timestamp":"2017-01-03T15:15:48.202+0000"}]}`

Expected behavior: fluent-plugin-elasticsearch reports problems with writing to ES index 

Unfortunately there is no error reported by fluentd which makes things particularly hard for those of us who are using AWS Elasticsearch service where we don't have access to ES logs.

Best,
Jakub

**Comment by pitr** [comment]
Thanks!

So I see that `client.bulk body: data` returns the following response:

```
{"took"=>20, "errors"=>true, "items"=>[{"create"=>{"_index"=>"fluentd", "_type"=>"fluentd", "_id"=>"AVllNq8DL0UhQTTYDNm9", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"object mapping for [log] tried to parse field [log] as object, but found a concrete value"}}}, {"create"=>{"_index"=>"fluentd", "_type"=>"fluentd", "_id"=>"AVllNq8EL0UhQTTYDNm-", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"object mapping for [log] tried to parse field [log] as object, but found a concrete value"}}}, {"create"=>{"_index"=>"fluentd", "_type"=>"fluentd", "_id"=>"AVllNq8EL0UhQTTYDNm_", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"object mapping for [log] tried to parse field [log] as object, but found a concrete value"}}}]}
```

So we could check if `errors` is true and log response to error. @zgolus would you be able to open a PR with this change? I don't think we need tests for this (as long as existing pass)
