### ISSUE TITLE
wrong type mapping between date and long

### ISSUE THREAD

**Issue by tonny1983** [uken/fluent-plugin-elasticsearch#228]
#### Problem
I want to input some date type data to elasticsearch, but it seems long as result after imported.

#### Steps to replicate
Here's my input data (cvs format)
`222538,222501,2016-12-20 01:13:22.000000 +0000,2016-12-20 01:14:15.000000 +0000`

And the conf file as follows:
```
<source>
  @type tail
  read_from_head true

  tag sample.csv 
  format csv
  keys ID,PROC_INST_ID,CREATE_TIME,LAST_UPDATED_TIME
  types ID:string,PROC_INST_ID:string,CREATE_TIME:time:%F %T.%L %z,LAST_UPDATED_TIME:time:%F %T.%L %z
  time_key LAST_UPDATED_TIME 
  time_format %F %T.%L %z
</source>

<match sample.csv**>
  @type elasticsearch
  logstash_format true
  host localhost 
  port 9200 
  index_name sample
  type_name sample 
</match>
```

The type of "CREATE_TIME" should be "date", but I got the type of "long" as follws:

```
"mappings": {

    "purchase": {
        "properties": {
            "CREATE_TIME": {
                "type": "long"
            }
...
```

I used elasticsearch v5.1.1, elasticsearch v.1.1.pre, elasticsearch-api v.1.1.pre, elasticsearch-transport v.1.1.pre and td-agent v.0.12.19

**Comment by pitr** [comment]
Can you replicate by cloning https://gist.github.com/pitr/9a518e840db58f435911

**Comment by tonny1983** [comment]
I've done the process and got some files in report folder, but can I verify them?

**Comment by pitr** [comment]
@tonny1983 could you post the process you used to replicate

**Comment by cosmo0920** [comment]
No response. Closing.
