### ISSUE TITLE
replicate data when data mount is big?

### ISSUE THREAD

**Issue by Mvpanswer7** [uken/fluent-plugin-elasticsearch#229]
I upsert 1000 rows of data into es, plugin works fine, but when I upsert 10,000,000 rows ,plugin gives back 
`2017-01-03 15:48:17 +0800 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached`  and `2017-01-03 15:48:18 +0800 [info]: Connection opened to Elasticsearch cluster => {:host=>"192.168.1.10", :port=>9200, :scheme=>"http"}` but after fluentd finished , I find 11,000,000 rows of data in my es, is there some things to do with my network connection, and cause plugin retry mechanism???

**Comment by Mvpanswer7** [comment]
Is there any chance that I can turn off the retry mechanism of buffer output plugin?

**Comment by pitr** [comment]
This plugin does inserts in batches, which is configurable, see [Buffered Output Options](https://github.com/uken/fluent-plugin-elasticsearch#buffered-output-options)
