### ISSUE TITLE
Add option logstash_prefix_key?

### ISSUE THREAD

**Issue by javefang** [uken/fluent-plugin-elasticsearch#233]
#### Problem
I'm using fluentd and the elasticsearch plugin to collect logs from our k8s cluster. My log message have roughly the following format

```
{ "kubernetes": { "namespace_name": "dev" }, "log": "this is a sample log" }
```

For now I'm using `logstash_format true`, which will index the logs into indices `logstash-yyyy.mm.dd`. This is not ideal since the k8s cluster is shared and apps in each namespace write logs with different fields which can potentially cause a mapping conflict.

Ideally I would like to pick the index prefix with field value `kubernetes.namespace_name`. Looking through the documentation I find it's not currently possible. Does it make sense to add an option called `logstash_prefix_key`?

#### Steps to replicate
(None)

**Comment by bz-keitaro-kobayashi** [comment]
We use `fluent-plugin-forest` to work around this limitation, as detailed in the [docs here](https://github.com/uken/fluent-plugin-elasticsearch#not-seeing-a-config-you-need). It would be nice to not use forest for large amounts of tag patterns, though. There's also `elasticsearch_dynamic` in the example below that, with its own concerns.

**Comment by richm** [comment]
https://github.com/uken/fluent-plugin-elasticsearch/pull/281

**Comment by cosmo0920** [comment]
#288 had been shipped.
This feature is available in 2.x versions.
For 1.x versions, I think that this should be a limitation.
