### ISSUE TITLE
Integration with search guard

### ISSUE THREAD

**Issue by Passpes** [uken/fluent-plugin-elasticsearch#236]
How can I integrate fluentd with elasticsearch using search guard 5 ?

**Comment by jklap** [comment]
Set "user" and "password" in your fluentd elastic plugin config.

Set up the user in SG5 using the samples they provide for logstash.

**Comment by cosmo0920** [comment]
Inactive and seems to be answered. Closing.

**Comment by cosmo0920** [comment]
ES plugin can communicate with basic authentication to ES.
Its community edition is included Basic Authentication ("user" and "passoword") feature which can be handled by ES plugin.
