### ISSUE TITLE
Need some guidance on how to troubleshoot write issue

### ISSUE THREAD

**Issue by tonyjchong** [uken/fluent-plugin-elasticsearch#238]
#### Problem

My problem seems simple to fix but it's been tough road getting to this point. I can't get FluentD to write to Elasticsearch. I have 2 outputs in my Fluentd config, one for ES and one for S3. The S3 output is working and logs don't give any error, even in debug mode. I am expecting a logstash-XXXXXX index but no logstash index, no new index at all.

Here's my environment:
* Kubernetes
* Fluent v0.12.31 running in a container I made. Starts up with no errors
* ES 5.2.0 & Kibana 5.2.0 running in containers that I made. Everything is green.
  * 3 masters
  * 2 data
  * 2 ingest
  * 2 coordinators (for kibana)
  * X-PACK is setup with basic auth
  * listening port 80

Fluent is configured to point to my ingest nodes. No ingest pipelines setup. My data nodes have `emptyDir: {}` setup in my Kubernetes Deployment. That means that there is no real disk setup. I know data can be stored because I see .monitoring and .kibana indices, and they have rolled over for the new day.

...

#### Steps to replicate
Here's a snippet from the log:

```
2017-02-03 03:36:38 +0000 [info]: plugin/in_tail.rb:557:initialize: following tail of /var/log/containers/fluentd-es-ejrrm_kube-system_POD-62690f33a971cd77091ffe461593e503088a11727cf9411bb51cd44fe9ef574d.log
2017-02-03 03:36:38 +0000 [info]: plugin/in_tail.rb:557:initialize: following tail of /var/log/kube-proxy.log
2017-02-03 03:36:43 +0000 [info]: plugin/out_elasticsearch.rb:165:client: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch", :port=>80, :scheme=>"http", :user=>"elastic", :password=>"obfuscated"}
2017-02-03 03:37:01 +0000 [info]: plugin/in_tail.rb:469:on_rotate: detected rotation of /var/log/containers/fluentd-es-7zj9r_kube-system_POD-53e3b75047cc746799ea2b3a466b036b8e5854dcd44feb39297a6aa54cb90732.log; waiting 5 seconds
2017-02-03 03:37:01 +0000 [info]: plugin/in_tail.rb:469:on_rotate: detected rotation of /var/log/containers/fluentd-es-7zj9r_kube-system_fluentd-es-3c4ade9acc8d1d12d7597c24c2ec655b9025d2a65d9c9a2f0a1e69a9aca4af56.log; waiting 5 seconds
```

Here's a snippet of my config:

```
<source>
  type tail
  format multiline
  multiline_flush_interval 5s
  format_firstline /^\w\d{4}/
  format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
  time_format %m%d %H:%M:%S.%N
  path /var/log/cluster-autoscaler.log
  pos_file /var/log/es-cluster-autoscaler.log.pos
  tag cluster-autoscaler
</source>

<filter kubernetes.**>
  type kubernetes_metadata
</filter>


<match **>
  type copy
  <store>
    type elasticsearch
    include_tag_key true
    host elasticsearch
    user elastic
    password "#{ENV['ES_PASSWORD']}"
    port 80
    logstash_format true
    # Set the chunk limit the same as for fluentd-gcp.
    buffer_chunk_limit 2M
    # Cap buffer memory usage to 2MiB/chunk * 32 chunks = 64 MiB
    buffer_queue_limit 32
    flush_interval 5s
    # Never wait longer than 5 minutes between retries.
    max_retry_wait 30
    # Disable the limit on the number of retries (retry forever).
    disable_retry_limit
    # Use multiple threads for processing.
    num_threads 8
  </store>
  <store>
    type s3
    aws_key_id "#{ENV['S3_KEY_ID']}"
    aws_sec_key "#{ENV['S3_SEC_KEY']}"
    s3_bucket in-crowd-logs
    s3_region us-east-1
    path logs
    s3_object_key_format "%{path}/#{Socket.gethostname}/%{time_slice}_%{index}.%{file_extension}"
    buffer_path /var/log/td-agent/buffer/s3
    time_slice_format %Y-%m-%d/%H
    time_slice_wait 10m
    utc
  </store>
</match>
```

I'm at a loss here. I've used FluentD and ES on ubuntu before, but not with this latest version of ES 5.2.0. Any guidance on why I can't write to the ES would be helpful. 

Thanks,

Tony

**Comment by fanlifei** [comment]
Has the problem been solved?

**Comment by tonyjchong** [comment]
Hi, @fanlifei  thanks for reminding me to update. The issue, I'm almost certain, is not the config or fluentD, but applying X-PACK with version 5.2.0 and the security settings. I don't think I had the right security (too strict) for FluentD to write to it. I ended up switching to Logstash thinking it was a problem with Fluent, but was able to reproduce the issue with Logstash.
