### ISSUE TITLE
Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached

### ISSUE THREAD

**Issue by jaywayjayway** [uken/fluent-plugin-elasticsearch#244]
#### Problem

What's wrong with my  td and ES ?  becuse of the network or other things ? 
...

#### Message 
```
2017-02-24 14:59:13 +0800 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2017-02-24 14:59:17 +0800 [info]: Connection opened to Elasticsearch cluster => {:host=>"es1", :port=>9200, :scheme=>"http"}, {:host=>"es2", :port=>9200, :scheme=>"http"}
```

**Comment by f0** [comment]
i see the same problem with elasticsearch 5.2.0 fluentd v0.12

**Comment by broxio** [comment]
I'm not sure that cause the problem too , in my staging environment I try to run es-cluster on swarm mode and cluster itself working pretty fine with logstash as a shipper  , when switch to fluentd cause the same error. 

elastic search 5.3.0  from docker hub.
td-agent 0.12.3

**Comment by epelc** [comment]
Any workaround for this? Also seeing this with fluentd 0.12.36 and elasticsearch 5.4

**Comment by Anubh** [comment]
Hi,

Just want to know is there any workaround this bug? I am not sure if data is getting the drop.

**Comment by cosmo0920** [comment]
Could you paste your fluentd configuration without sensitive information?

**Comment by thebitguru** [comment]
If anyone else is having this issue and inserting a lot of data, I would suggest reviewing issue https://github.com/uken/fluent-plugin-elasticsearch/issues/50.  That could be the cause.

**Comment by cosmo0920** [comment]
This is also related to https://github.com/elastic/elasticsearch-ruby/issues/464#issuecomment-356500993?

**Comment by alter** [comment]
same shit happened

**Comment by alter** [comment]
This issue appears with using buffer files, if I remove <buffer> section, td-agent works perfectly(but will lost data)

**Comment by cosmo0920** [comment]
I reckon that this issue is also happened by wrong elasticsearch-ruby usage.
If anyone still occur this issue, please open an another issue.
