### ISSUE TITLE
Mapping Templates

### ISSUE THREAD

**Issue by marti6tic** [uken/fluent-plugin-elasticsearch#245]
#### Problem

Hi, we are implementing fluentd with elasticsearch but have an issue based on logstash format true amb elastic templates.

Why we should set a concrete mapping template on fluentd? Our td-agent.conf looks like this. Thanks!!

```aconf
<match *.**.pre>
#type copy
#  <store>
    @type elasticsearch_dynamic
    hosts 172.16.236.139
    #index_name privalia_pre
    type_name sys
    logstash_format true
    logstash_prefix privaliapre
    #time_key_exclude_timestamp true
    #target_index_key 
    #template_name privalia
    #template_file /etc/td-agent/template-index.json
    request_timeout 30s
    reload_connections true
    reload_on_failure true
    include_tag_key false
    reconnect_on_error true
    buffer_type memory
    buffer_chunk_limit 30m
    buffer_queue_limit 30
    flush_interval 1s
    disable_retry_limit false
    retry_limit 0
    retry_wait 1s
    num_threads 2
#  </store>
</match>
```

**Comment by cosmo0920** [comment]
Currently, template functionality does not work on `elasticsearch_dynamic`. :stuck_out_tongue:

**Comment by cosmo0920** [comment]
> Why we should set a concrete mapping template on fluentd?

We should tell actual value types to Elasticsearch.
If you don't have to handle values precisely, it needn't specify Elasticsearch templates.

**Comment by cosmo0920** [comment]
v2.6.2 and v1.13.2 should handle template files.
If you encountered a related bug for this, please reopen this issue.

**Comment by marti6tic** [comment]
Top, will test the functionality and comment. Many thanks.
