### ISSUE TITLE
Add option for a hard cap on push retry time

### ISSUE THREAD

**Issue by n-rook** [uken/fluent-plugin-elasticsearch#248]
I had a several-hour outage in our ElasticSearch cluster recently. Unfortunately, by the time it got fixed, the time until the next retry was already 4 hours.

It would be nice to add a hard cap option, which would make it so no matter how many failures there were, the plugin would still retry every hour (or two hours, or thirty minutes, or whatever is specified).

I'd be willing to contribute to the plugin in order to enable this feature.

**Comment by jklap** [comment]
max_retry_wait: 30m
