### ISSUE TITLE
Make target index more flexible

### ISSUE THREAD

**Issue by devent** [uken/fluent-plugin-elasticsearch#253]
#### Problem
Our company needs an index with the pattern of <name>_<date>, for example `systemd_2017-04-26`. But in your plugin the index pattern is hard-coded to the hyphen `systemd-2017-04-26`.

We now using the workaround with the following configuration that will create an index like `systemd-_2017-04-26`

```
   logstash_dateformat "_%Y.%m.%d"
   logstash_format true
```

Would it be possible to have both the date and to use an underscore instead of a hyphen?

**Comment by cosmo0920** [comment]
This line https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L307 causes issue for you.
Making hyphen separator `-` configurable should solve this issue.
Patch is welcome, thanks.
