### ISSUE TITLE
fluentd sending data to non configured elasticsearch

### ISSUE THREAD

**Issue by meyeet** [uken/fluent-plugin-elasticsearch#256]
#### Problem
fluentd is copying data to the elasticsearch running on localhost even though that cluster is not configured within td-agent.conf

I have three different elasticsearch clusters running.  Two elasticsearch v2.4.4 and One elasticsearch v5.2.1.  I am sending a copy of my incoming data out to one of the v2.4.4 clusters and the v5.2.1 cluster.  For some reason after a couple of hours the data starts showing up in the unconfigured v2.4.4 cluster and no longer appears in the v5.2.1 cluster.  Restarting td-agent fixes the issue for another few hours.  The unconfigured cluster is running on the localhost where my td-agent aggregator is running.

```
@type copy
<store>
   @type elasticsearch
   logstash format true
   hosts xxxx:9200, xxxx:9200, xxxx:9200, xxxx:9200
   reload_on_failure true
   resurrect_after 5s
   disable_retry_limit true
   retry_wait 10s
   max_retry_wait 120s
   flush_interval 10s
   flush_at_shutdown true
</store>
<store>
@type elasticsearch
   logstash format true
   hosts yyyy:9200, yyyy:9200, yyyy:9200, yyyy:9200
   reload_on_failure true
   resurrect_after 5s
   disable_retry_limit true
   retry_wait 10s
   max_retry_wait 120s
   flush_interval 10s
   flush_at_shutdown true
</store>
```
td-agent v0.12.35
elasticsearch 5.0.3
elasticsearch-api 5.0.3
elasticsearch-transport 5.0.3

**Comment by meyeet** [comment]
To further expand on this, I swapped out the 5.2.1 cluster with another 2.4.4 cluster.  The issue goes away.

**Comment by cosmo0920** [comment]
I think that we cannot mix different versions of ES cluster because elasticsearch-ruby does not have backward compatibility.

See: https://github.com/elastic/elasticsearch-ruby#compatibility
