### ISSUE TITLE
Stop recommending fluent-plugin-aws-elasticsearch-service

### ISSUE THREAD

**Issue by dwoo4dwoo** [uken/fluent-plugin-elasticsearch#261]
#### Problem
The atomita/fluent-plugin-aws-elasticsearch plugin seems dead:

https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/issues/29

uken/fluent-plugin-elasticsearch is more widely used; therefore, perhaps the README.md should stop recommending atomita/fluent-plugin-aws-elasticsearch-service for Amazon?  uken/fluent-plugin-elasticsearch works fine with Amazon with the following settings: https://groups.google.com/d/msg/fluentd/uW87VAOqxeE/cfhenicEBAAJ.

The only thing which seems to be missing is Amazon signing: https://github.com/uken/fluent-plugin-elasticsearch/issues/131.  I've added signing in other languages ... but never in Ruby.  If there is a useful library available ... I could give it a shot.  Would you be amenable to receiving such a PR?

David

**Comment by micw** [comment]
Unfortunately #131 is closed. If atomita/fluent-plugin-aws-elasticsearch-service is dead, #131 should probably re-opened and the feature ported from atomita/fluent-plugin-aws-elasticsearch-service.

**Comment by joshk0** [comment]
I ported the signing support in PR #270 , could someone have a look?

**Comment by cosmo0920** [comment]
I've sent a PR into https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/pull/32.
If possible, I'd like to continue to support AWS elasticsearch operations in https://github.com/atomita/fluent-plugin-aws-elasticsearch-service.

**Comment by cosmo0920** [comment]
I contacted @atomita on [Twitter](https://twitter.com/sleepycat_zzz/status/907825409600966657).
He says that "I'll work on this near future".

**Comment by cosmo0920** [comment]
Hi all, @winebarrel created alternative AWS Elasticsearch Service plugin: https://github.com/winebarrel/fluent-plugin-aws-es-service
This plugin depends on aws-sdk v3.
Does anyone want to evaluate it?

**Comment by nsaud01** [comment]
I would @cosmo0920. I don't see any usage instructions though.

**Comment by cosmo0920** [comment]
fluent-plugin-aws-es-service's usage is almost same as this ES plugin, but it needs to specify AWS specific parameters which are `region`, `access_key_id`, `secret_access_key`, and `credentials_provider`:

https://github.com/winebarrel/fluent-plugin-aws-es-service/blob/master/lib/fluent/plugin/elasticsearch_output_client_ext.rb#L6-L9

**Comment by joshk0** [comment]
@cosmo0920 I don't particularly care. I am currently using patched fluent-plugin-aws-elasticsearch-service from your pull request and it works fine. If possible, we should try and maintain only one canonical plugin which provides this functionality. If @winebarrel intends to maintain his version, and it is compatible with 0.14 API, I would recommend that @atomita just shut down his project and redirect it to @winebarrel project. Anything but having two projects that do the same thing.

**Comment by cosmo0920** [comment]
I noticed that @atomita decided to come back to maintainance [https://github.com/atomita/fluent-plugin-aws-elasticsearch-service) project and merged [my PR](https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/pull/32).
Cheers! :tada:

**Comment by cosmo0920** [comment]
@dwoo4dwoo Is both of fluent-plugin-aws-elasticsearch-service v1.0.0.pre.alpha and Fluentd 0.14 or fluent-plugin-aws-elasticsearch-service v0.1.7.pre.alpha and Fluentd 0.12 combinations enough for you?

**Comment by cosmo0920** [comment]
atomita/fluent-plugin-aws-elasticsearch is re-started within this month.
I decide to continue recommending fluent-plugin-aws-elasticsearch in README.
Anyway, thanks for paying attention about this issue.

**Comment by dwoo4dwoo** [comment]
> Is both of fluent-plugin-aws-elasticsearch-service v1.0.0.pre.alpha and Fluentd 0.14 or fluent-plugin-aws-elasticsearch-service v0.1.7.pre.alpha and Fluentd 0.12 combinations enough for you?

Yes @cosmo0920 ... thanks for helping breathe life back into fluent-plugin-aws-elasticsearch :-).

**Comment by zonepalms91** [comment]
@cosmo0920 Issue is still relevant, the current implementation does not work with newer versions of elasticsearch, and even the previously working plugin has stopped working in most cases.

**Comment by cosmo0920** [comment]
@zonepalms91 I’m not AWS ES Service plugin maintainer.
Please request to @atomita.
Thanks.
