### ISSUE TITLE
Empty user & password settings result in HTTP Authentication header sent to ES

### ISSUE THREAD

**Issue by ahawkins** [uken/fluent-plugin-elasticsearch#267]
#### Problem

Empty `user` and `password` settings send HTTP authentication headers. I came across this when working with https://github.com/ahawkins/fluentd-kubernetes-daemonset/blob/f6cb1efe05137f90af7eb0c609ba0268a7546aa2/templates/conf/fluent.conf.erb#L20-L21. The Kubernetes DaemonSet assumes that certain environment variables are set, which translate to empty strings in `fluent.conf`. I suggest the code be updated to use `String#empty`? instead of just `@user` or `@password`. This should solve the issue of sending HTTP authentication headers when none are expected.

#### Steps to replicate

Snippet:

```
user ""
password ""
```

**Comment by polothy** [comment]
Running into this problem myself.  Empty Authorization header being set.  This is on AWS using their ElasticSearch cluster and attempting to send logs with fluentd from a kops cluster.  Here is the error message: `Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Basic Og==` where `Og==` decodes to `:`.

We are using the image `gcr.io/google-containers/fluentd-elasticsearch` and inside its `/etc/fluent/config.d/output.conf` file it has:

```
  user "#{ENV['OUTPUT_USER']}"
  password "#{ENV['OUTPUT_PASSWORD']}"
```

Would a potential fix be to just not pass the following if `@user` or `@password` are empty?
https://github.com/uken/fluent-plugin-elasticsearch/blob/b0d24444888805a3300e59489d818aeb60a8b445/lib/fluent/plugin/out_elasticsearch.rb#L378-L381

**Comment by polothy** [comment]
Just adding a workaround here incase anyone finds this later on.  We are using this [helm chart](https://github.com/kiwigrid/helm-charts/tree/master/charts/fluentd-elasticsearch) to install fluentd and we discovered that the conf files are in the config map and can be overridden via Helm values, EG: https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/values.yaml#L592-L593

So, going forward, that'll be our solution and it appears to be working.

Before we found that _completely acceptable_ workaround, I was trying to fix it in the code.  I came up with [this solution](https://github.com/uken/fluent-plugin-elasticsearch/compare/master...polothy:auth).  By setting user/password to nil, I believe that the Authorization header will not be set, but my Ruby isn't great, so could easily be wrong.

I ran the tests with this change and they all passed:
```
❯ bundle exec rake test
Started
...........................................................................................................................................................................................................................................

Finished in 285.395537 seconds.
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
235 tests, 428 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
0.82 tests/s, 1.50 assertions/s
[Coveralls] Outside the CI environment, not sending data.
```

But I feel like there should be some specific tests added to ensure correct behavior.  Since I'm not great at Ruby and we have a good way forward, I'm not going to add the tests myself.

**Comment by Matiasmct** [comment]
> Just adding a workaround here incase anyone finds this later on. We are using this [helm chart](https://github.com/kiwigrid/helm-charts/tree/master/charts/fluentd-elasticsearch) to install fluentd and we discovered that the conf files are in the config map and can be overridden via Helm values, EG: https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/values.yaml#L592-L593
> 
> So, going forward, that'll be our solution and it appears to be working.
> 
> Before we found that _completely acceptable_ workaround, I was trying to fix it in the code. I came up with [this solution](https://github.com/uken/fluent-plugin-elasticsearch/compare/master...polothy:auth). By setting user/password to nil, I believe that the Authorization header will not be set, but my Ruby isn't great, so could easily be wrong.
> 
> I ran the tests with this change and they all passed:
> 
> ```
> ❯ bundle exec rake test
> Started
> ...........................................................................................................................................................................................................................................
> 
> Finished in 285.395537 seconds.
> ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> 235 tests, 428 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
> 100% passed
> ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> 0.82 tests/s, 1.50 assertions/s
> [Coveralls] Outside the CI environment, not sending data.
> ```
> But I feel like there should be some specific tests added to ensure correct behavior. Since I'm not great at Ruby and we have a good way forward, I'm not going to add the tests myself.

I'm facing the same issue. Not sure I understand what's the workaround, as I haven't been able to get it working. I left both username and password values empty in values.yaml. Even if I manually modify the configmap after deploying the chart to set both values to empty string, I'm getting the same error. Could you help me out?

**Comment by polothy** [comment]
So, you need override the `configMaps.output.conf` Helm value to exclude user and password:

```yaml
configMaps:
  output.conf: |-
    <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level info
      include_tag_key true
      type_name _doc
      host "#{ENV['OUTPUT_HOST']}"
      port "#{ENV['OUTPUT_PORT']}"
      scheme "#{ENV['OUTPUT_SCHEME']}"
      ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
      ssl_verify true
      logstash_format true
      logstash_prefix "#{ENV['LOGSTASH_PREFIX']}"
      reconnect_on_error true
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
        queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
        overflow_action block
      </buffer>
    </match>
```

If user/password appear at all in the config, then the plugin attempts to use them.

**Comment by cosmo0920** [comment]
`use_default` or `use_nil` can handle empty user or password condition.

This could be closed with https://github.com/fluent/fluentd-kubernetes-daemonset/pull/410's change.

**Comment by cosmo0920** [comment]
Our daemonset image uses the following representation:

```
   user "#{ENV['FLUENT_ELASTICSEARCH_USER'] || use_default}"
   password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD'] || use_default}"
```

Could you ask using the above representation in gcr.io/google-containers/fluentd-elasticsearch's authors, @polothy ?
Thanks for using fluent-plugin-elasticsearch plugin!

**Comment by cosmo0920** [comment]
And fluentd-elasticsearch addon on kubernetes is already migrated to use ConfigMap to specify fluentd configuration:
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml#L456

This issue should be occurred.
