### ISSUE TITLE
Specify Content-Type Header?

### ISSUE THREAD

**Issue by alexcurtin** [uken/fluent-plugin-elasticsearch#268]
I am running the latest fluentd image from google to send logs to elastic search and elastic search is replying with a ton of these logs:

[o.e.d.r.RestController ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

Steps to reproduce:

Spin up an EFK stack with latest googles fluentd and elastic search 5.4.2, let the ES cluster boot and you will see the log [o.e.d.r.RestController ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

Is this because of how the latest FluentD is shipping logs off to elastic search?

Provide logs (if relevant):

[o.e.d.r.RestController ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

How can I specify the content-type header in the output of fluentd?

**Comment by Kuckkuck** [comment]
+1
same issue for me. 2000 log lines per 30 minutes with this message.

**Comment by brommer** [comment]
+1 Same for me

**Comment by alexcurtin** [comment]
@Kuckkuck @brommer I think we were using an older version of this plugin if you guys are using the FluentD image from google's GCR. I pulled down the google's dockerfile and made sure it uses the latest version of fluent-plugin-elasticsearch that fixes the content-header issue and rebuilt the image and hosted it on my public dockerhub here https://hub.docker.com/r/alexcurtin/fluentd-logging/

Keep in mind this image utilizes a td-agent.conf thats setup in a specific way, so you guys can look at the source here: https://github.com/wrsinc/kubernetes-efk-gcp/tree/master/fluentd-logging

So, you may have to change your td-agent.conf to suit your needs and build your own image.

That should fix this issue let me know if it does for you guys.

**Comment by shane-axiom** [comment]
Verifying that upgrading to version 1.9.5 got rid of these warnings for me.

**Comment by cosmo0920** [comment]
ES plugin 1.9.5 solves this.
