### ISSUE TITLE
Miliseconds is not showing in Elasticsearch 5.3 (AWS)

### ISSUE THREAD

**Issue by davidgacc** [uken/fluent-plugin-elasticsearch#273]
I am trying to see the timestamp with miliseconds on Kibana. But it seems only to show seconds

fluentd 0.14.19
td-agent 0.14.16

Example of my log:

2017-04-02 00:00:02,027 INFO [com.***] (http--0.0.0.0) text

Output on Kibana:

@timestamp : April 2nd 2017, 00:00:02.000

```
<source>
        @type tail
        path /home/arias/Documents/log/teste_21.log
        pos_file /var/log/td-agent/td-agent-test-62.log
        read_from_head true
        format multiline
        format_firstline /[0-9]+-[0-9]+-[0-9]+/
        format1 /^(?<timestamp>[0-9]+-[0-9]+-[0-9]+\s+[0-9]+:[0-9]+:[0-9]+,[0-9]+)\s+(?<log_level>[a-zA-Z]+)\s+\[(?<class>.*)\]\s+\((?<thread_pool>.*)\)\s+(?<log_message>.*)/
        keep_time_key true
        time_key timestamp
        #read_lines_limit 8000
        time_format %Y-%m-%d %H:%M:%S,%L
        tag teste-3.log
</source>

<match *.**>
        @type copy
        <store>
                @type elasticsearch
                host ***.com
                port 80
                logstash_format true
                logstash_prefix activation # set prefix name
                utc_index true
                time_key_format %Y.%m.%d
                buffer_type memory
                buffer_chunk_limit 8M
                buffer_queue_limit 512
                reload_connections false
                reload_on_failure true
                flush_at_shutdown true
        </store>
</match>

```
Any ideas ?. I would appreaciate your help.
Thank you.

**Comment by yissachar** [comment]
This won't work until https://github.com/uken/fluent-plugin-elasticsearch/issues/222 is resolved.

In the meantime you could use my [branch](https://github.com/uken/fluent-plugin-elasticsearch/pull/223) which adds this support.

**Comment by davidgacc** [comment]
@yissachar thank you! It worked! :)

**Comment by georgehdd** [comment]
@yissachar will your branch be merged soon?

**Comment by yissachar** [comment]
@georgehdd I doubt it. Unfortunately this project doesn't seem to have an active maintainer.

**Comment by gihad** [comment]
It looks like we found a maintainer.

**Comment by cosmo0920** [comment]
Should we merge https://github.com/uken/fluent-plugin-elasticsearch/pull/223 and release as 2.0.0.rc1?

**Comment by gihad** [comment]
Sounds good. I will sort out rubygems pushing issue.

**Comment by cosmo0920** [comment]
fluent-plugin-elasticsearch 2.0.0.rc.1 can handle it.
