### ISSUE TITLE
add an exit on failure config option

### ISSUE THREAD

**Issue by vixns** [uken/fluent-plugin-elasticsearch#276]
#### Problem

My use case : kafka input plugin > filters > ES output
When the ES cluster has some big/long trouble, kafka messages are still consumed, and kafka offset commited, until fluentd is restarted.
After fixing ES and restarting fluentd, I cannot replay messages before the commited offset.

Unless we can create some sort of link/callback/pubsub between plugins, having an option to exit fluentd early on elasticsearch output failure would help to mitigate.

**Comment by cosmo0920** [comment]
Could you paste your fluentd log without sensitive information?
Concrete stacktrace might be helpful.

**Comment by cosmo0920** [comment]
How about evaluate Fluentd v0.14 in your use case?
v0.14 might solve this issue.

**Comment by vixns** [comment]
I will post a stack trace the next time I face this issue, we are using v0.14.

**Comment by cosmo0920** [comment]
How about using file buffer to ensure resending messages?

**Comment by cosmo0920** [comment]
No comments on v0.14 evaluation.
I reckon that Fluentd v0.14/v1 with Kafka and ES plugins works fine.
