### ISSUE TITLE
Simple Auth not working with ES5

### ISSUE THREAD

**Issue by krlng** [uken/fluent-plugin-elasticsearch#277]
#### Problem
I want to send logs to an AWS ES5.3 through a simple-auth service running in Kubernetes. 

Inserting values using the http type works, but the elasticsearch fluent plugin does neither insert values nor prints any errors. The problem seems to be the basic auth, since it works if I open ES.

#### Steps to replicate

I am using the versions I found [here](https://github.com/uken/fluent-plugin-elasticsearch/issues/231#issuecomment-306039688):

fluentd-plugin-elasticsearch v1.9.5
elasticsearch v5.0.4
elasticsearch-api v5.0.4
elasticsearch-transport v5.0.4

My fluentd configuration looks like    

```
  <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /tmp/es-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
      time_key date
    </source>

    <match kubernetes.**>
      @type copy
      <store>
        @type file
        path /tmp/log/fluent/myapp1
      </store>
      <store>
        @type elasticsearch
        host  "user:pw@my-url"
        scheme https
        index_name kubernetes
        type_name fluentd
      </store>
      <store>
          @type http
          endpoint_url    "#{ENV['ES_HOST']}"
          http_method     post
          serializer      json
          authentication  basic
          username        "#{ENV['ES_USERNAME']}"
          password        "#{ENV['ES_PASSWORD']}"
      </store>
    </match>
```

**Comment by bechtoldt** [comment]
can you show the HTTP request from your client (fluentd) and the HTTP response from your reverse proxy?

**Comment by bechtoldt** [comment]
is this related to #257

**Comment by cosmo0920** [comment]
Is this related to https://github.com/elastic/elasticsearch-ruby/issues/464#issuecomment-356500993?
