### ISSUE TITLE
How do I send severity?

### ISSUE THREAD

**Issue by marksawersw** [uken/fluent-plugin-elasticsearch#278]
#### Problem
I'd like to get log severity indexed and searchable in elasticsearch. I set up syslog inputs to output to a file, and I see the full priority (facility and severity):

    2017-08-11T20:13:01+00:00	syslog.authpriv.info	{"host":"ip-xx-xx-xx-xx","ident":"CRON","pid":"32544","message":"pam_unix(cron:session): session closed for user root"}

So fluentd knows about it.

However, when I tcpdump the fluentd output to port 9200 elasticsearch, I don't see any severity, for example (on a different message):

    .+<+.+<+POST /_bulk HTTP/1.1
    User-Agent: Faraday v0.12.2
    Authorization: Basic ***
    Content-Type: application/json
    Host: elasticsearch:9200
    Content-Length: 183

    {"index":{"_index":"fluentd-2017.08.11","_type":"fluentd"}}
    {"host":"ip-xx-xx-xx-xx","ident":"logger","pid":"1013","message":"hello, world","@timestamp":"2017-08-11T20:37:56+00:00"}

My fluentd conf is pretty vanilla:

    <match **>
     @type elasticsearch
     host elasticsearch
     port 9200
     user elastic
     password ***
     logstash_format true
     logstash_prefix fluentd
     flush_interval 1s # for testing
    </match>

I did a string search for 'severity' on the plugin source but don't see anything.

Don't see that as an available field in kibana on my fluentd-* index. Is this a constraint in the logstash 'protocol' or elasticsearch itself? Or is there there an opportunity to customize the format in my fluentd match block?

Thanks!

**Comment by Tom-Fawcett** [comment]
You could extract it from the tag:

```
<filter syslog.*.*>
  @type record_transformer
  <record>
    facility ${tag_parts[1]}
    severity ${tag_parts[2]}
  </record>
</filter>
```

**Comment by marksawersw** [comment]
This worked beautifully. Thank you!
