### ISSUE TITLE
What happens if time_key is not present

### ISSUE THREAD

**Issue by jchannon** [uken/fluent-plugin-elasticsearch#284]
#### Problem
I have multiple sources. If I say `time_key ts` in my config and one source doesn't have that field what happens? As far as I can see it still gets imported into ES with a timestamp field.  If it can't find the field does it therefore ignore the `time_key_format`?

```
time_key ts
time_key_format %Y-%m-%dT%H:%M:%S.%NZ
```

**Comment by cosmo0920** [comment]
`elasticsearch` adds a timestamp field which uses time in each event:
https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L302-L304

**Comment by jchannon** [comment]
Thanks so I see it takes the time element from the input plugin and calls `Time.at(time).to_datetime.iso8601(@time_precision)}`

So i took this code and put it in the filter plugin to store a new field

```

# Tell fluentd to listen on 24224 for TCP messages
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

# Tell fluentd to listen on 24220 for HTTP requests to get health check info
<source>
  @type monitor_agent
  bind 0.0.0.0
  port 24220
</source>

<filter **>
  @type record_modifier
  <record>
    willstore "${Time.at(time).to_datetime.iso8601(6)}"
    longtime "${Time.at(time).to_f}"
  </record>
</filter>

<match **>
  @type copy
  <store>
    @type elasticsearch
    host "#{ENV['ELASTIC_HOST']}"
    port 9200
    logstash_format true
    logstash_prefix fluentd
    logstash_dateformat %Y%m%d
    time_key_exclude_timestamp false
    time_key ts
    time_key_format %Y-%m-%dT%H:%M:%S.%NZ
    time_precision 6
    include_tag_key true
    type_name access_log
    tag_key @log_name
    flush_interval 1s
  </store>
  <store>
    @type stdout
  </store>
</match>
```

When I look in ES I see:

```
    "willstore": "2017-09-06T16:40:58.267347+00:00",
    "longtime": 1504716058.26735,
    "@timestamp": "2017-09-06T16:40:58.000000+00:00",
```

Basically the same code is getting executed in the filter plugin as the ES plugin but the ES plugin seems to be stripping the milliseconds.  Why is that?

**Comment by cosmo0920** [comment]
> Basically the same code is getting executed in the filter plugin as the ES plugin but the ES plugin seems to be stripping the milliseconds. Why is that?

Because ES plugin uses traditional Fluentd Plugin API, Fluentd v0.14 drops nenoseconds precision from time when plugin uses old style API. 
https://github.com/fluent/fluentd/blob/master/lib/fluent/compat/output.rb#L460

**Comment by jchannon** [comment]
Is there an ETA when the plugin will use new fluentd 14 API?

**Comment by cosmo0920** [comment]
> Is there an ETA when the plugin will use new fluentd 14 API?

Using new API is done here: #223.
But @gihad and I don't have publish gem rights in rubygems yet.

**Comment by jchannon** [comment]
So if fluentd posts a date with nanosecond precision (once the gem is released) will this effect ES and it's current usage of date time in that it only stores timestamp fields up to millisenconds? I assume not but thought I'd check. https://github.com/elastic/elasticsearch/issues/10005

**Comment by gihad** [comment]
@cosmo0920 I got in touch with @pitr and he added both of us as gem owners in rubygems.

**Comment by cosmo0920** [comment]
@jchannon I'd published nanosecond precision patches as 2.0.0.rc.1.
Could you try this with `gem install fluent-plugin-elasticsearch --pre` or adding `gem "fluent-plugin-elasticsearch", "2.0.0.rc.1" in Gemfile?

**Comment by cosmo0920** [comment]
> So if fluentd posts a date with nanosecond precision (once the gem is released) will this effect ES and it's current usage of date time in that it only stores timestamp fields up to millisenconds?

ES plugin fills `@timestamp` fields up to nanoseconds.

configuration file:

```aconf
<source>
  @type forward
</source>
<match my.logs>
  @type elasticsearch
  include_tag_key true
  tag_key _key
  flush_interval 1s
  buffer_type file
  buffer_path tmp
  logstash_format true
  time_key ts
  time_key_format %Y-%m-%dT%H:%M:%S.%NZ
</match>
```

Send an event:

```bash
echo '{"current_version":"v0.14", "versions":{"unstable":0.14, "stable":0.12}}' | bundle exec fluent-cat my.logs
```

Shown in kibana:

```json
      {
        "_index": "fluentd-20170921",
        "_type": "access_log",
        "_id": "AV6jid1WiRwmtXczfVC3",
        "_score": 1,
        "_source": {
          "current_version": "v0.14",
          "versions": {
            "unstable": 0.14,
            "stable": 0.12
          },
          "@timestamp": "2017-09-21T17:24:33.258487000+09:00",
          "@log_name": "my.logs"
        }
      },
```

**Comment by stszap** [comment]
```
Shown in kibana:
...
```
That's probably the _source field. Yes, the original value of "@timestamp" with nanoseconds is stored there, but elasticsearch converts it to milliseconds and then uses for search and ordering.

**Comment by cosmo0920** [comment]
@stszap This is an elasticsearch limitation.
ref: https://github.com/elastic/elasticsearch/issues/10005

**Comment by cosmo0920** [comment]
Now, ES plugin 2.x can handle nanosecond precision in Timestamp.
I'm closing this issue.
If there is any question for this issue, please let me know.
