### ISSUE TITLE
Bulk feature

### ISSUE THREAD

**Issue by MarcelHillmann** [uken/fluent-plugin-elasticsearch#301]
#### Problem
First off all, thank you so much for your implementation.

I could see in your source,  that you use the balk API.
I'm just wondering about some details:
1. Why the plugin is not calling "<Server-DNS>/_bulk"
2. Is there maybe an wrong Content-Type used?
   You use "application/json", but the specification say "application/x-ndjson"
   [out_elasticsearch.rb#L173](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L173)
   [out_elasticsearch_dynamic.rb#L52](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch_dynamic.rb#L52)
   [ES spec](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)

3. I see all the time an HEAD request from the plugin, but couldn't find the source.

Hopefully I'm not not dumb the read your source.

#### Using Fluentd and ES plugin versions
* Plugin '1.9.5'
* Fluentd v0.14
* ES plugin 5.0.4

**Comment by cosmo0920** [comment]
> Why the plugin is not calling "/_bulk"

elasticsearch-ruby will call `/_bulk` endpoint:
https://github.com/elastic/elasticsearch-ruby/blob/b0bf52552fa806f4356723643527468715b299cf/elasticsearch-api/lib/elasticsearch/api/actions/bulk.rb
This plugin relies on `elasticsearch-ruby` feature.

> Is there maybe an wrong Content-Type used?

Currently, `application/json` and `application/x-ndjson` are valid for ES 5.

> I see all the time an HEAD request from the plugin, but couldn't find the source.

This HEAD requests are generated from `elasticsearch-ruby`:
https://github.com/elastic/elasticsearch-ruby/blob/b8a45dc2ff810bc83f54c9f1e91cefdc03a25413/elasticsearch-api/lib/elasticsearch/api/actions/ping.rb

**Comment by MarcelHillmann** [comment]
Thanks for the answer.

Thanks Marcel
