### ISSUE TITLE
Inconsistency in time value notation in docs

### ISSUE THREAD

**Issue by hrak** [uken/fluent-plugin-elasticsearch#313]
#### Problem

The notation for the various timeout values is unclear. For example, the README mentions `flush_interval 60` and `request_timeout 15s` and `resurrect_after 5`

Do we or do we not add 's' after a time-in-seconds value?

#### Using Fluentd and ES plugin versions

* Fluentd v0.12
* ES plugin 1.9.5 & 2.0.0

**Comment by cosmo0920** [comment]
Their type are `time` in `config_param`.

`flush_interval 60` and `request_timeout 15s` and `resurrect_after 5` are valid.
`time` typed configuration parameters can handle normal digits, `s`, `m`, `h`, and `d` suffixed digits.
In more detail, please refer to the document: https://docs.fluentd.org/v0.12/articles/config-file#supported-data-types-for-values

**Comment by hrak** [comment]
Alright, its good to know that both are valid, but it might be nice to stick to one consistent notation in your documentation.
