### ISSUE TITLE
[Question] ES6.0 support?

### ISSUE THREAD

**Issue by hiscal2015** [uken/fluent-plugin-elasticsearch#319]
Hi,

Since es6.0 has been released, does this plugin support the new version?

**Comment by cosmo0920** [comment]
fluent-plugin-elasticsearch depends on elasticsearch-ruby gem to support transporting into elasticsearch.
This plugin does not lock dependency for elasticsearch-ruby.
You can use ES 6.0 with elasticsearch-ruby 6.0.

**Comment by hiscal2015** [comment]
@cosmo0920  Thanks.
