### ISSUE TITLE
messages dropped from sending to ES when upstream filter fails

### ISSUE THREAD

**Issue by cdaringe** [uken/fluent-plugin-elasticsearch#320]
#### Problem

- messages that fail a JSON filter parse are not sent to ES.

this seems obvious, however, they still are sent to file when a file output is configured.  it is expected that they still be sent to ES.  i _expect some message parses to fail_ and want to ignore those warnings and continue to all outputs regardless of parse success.

#### Steps to replicate

fluentd, per my config, will try to JSON parse the _log_ key.  it will fail to do so on this message, and rightfully warn me, as shown here:

```json
20171116T223251+0000	c44112aa8fa9	{"container_id":"c44112aa8fa9de9ba26912e5cadf2c2a682496d5f1ceb5cf2c22148e237b6b19","container_name":"/fluentdeskibana_loud-n-rad_1","source":"stdout","log":"> node src/index.js"}
20171116T223251+0000	fluent.warn	{"message":"pattern not match with data '\"> loud-n-rad@1.0.0 start /app\"'"}
20171116T223251+0000	fluent.warn	{"message":"pattern not match with data '\"> node src/index.js\"'"}
20171116T223251+0000	fluent.warn	{"message":"parse failed undefined method `delete' for nil:NilClass"}
```

despite this warning, i still scavenged this very text from my downstream file output.  the message as a whole is valid JSON, the filter just failed parsing the _log_ key's value.  **however**, this message never gets sent to ES.  i have a whole swath of other messages that fail this filter that also do not get sent.

messages that pass the JSON parse phase go thru to ES just fine.  for example:

```xml
20171116T223251+0000	c44112aa8fa9	{"source":"stdout","log":"{\"level\":\"info\",\"message\":\"it's go time.\",\"timestamp\":\"2017-11-16T22:32:51.861Z\"}","container_id":"c44112aa8fa9de9ba26912e5cadf2c2a682496d5f1ceb5cf2c22148e237b6b19","container_name":"/fluentdeskibana_loud-n-rad_1","level":"info","message":"it's go time.","timestamp":"2017-11-16T22:32:51.861Z"}
```

you can see that the key-value pairs have been flattened onto the root log message (see "level" & "message" keys).

my config is as follows:
```xml
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>
<filter **>
  @type parser
  format json
  key_name log # docker stdout lines go to "log"
  reserve_data true
</filter>
<match *.**>
  @type copy
  <buffer>
    @type file
  </buffer>
  <store>
    @type elasticsearch
    hosts http://elasticsearch:9200
    index_name fluentd
    flush_interval 5s
  </store>
  <store>
    @type stdout
  </store>
  <store>
    @type file
    @id output1
    path /fluentd/log/data.*.log
    symlink_path /fluentd/log/data.log
    append true
    time_slice_format %Y%m%d
    time_slice_wait 10m
    time_format %Y%m%dT%H%M%S%z
    buffer_path /fluentd/log/data.*.log
  </store>
</match>
```

#### Using Fluentd and ES plugin versions

* Fluentd v0.12
* ES plugin 1.9.2

**Comment by cosmo0920** [comment]
Thanks for using elasticsearch plugin.
You mean that you want to store records into elasticsearch event if upstream pserser plugin fails, right?

If so, to handle ES when failing upstream filter parser, you can use `emit_invalid_record_to_error` parameter to send `@ERROR` label and then store elasticsearch.

BTW, Fluentd v0.12 does not have `<buffer>` directive.

**Comment by cdaringe** [comment]
hi @cosmo0920,

thanks very much for the response.

- `emit_invalid_record_to_error` could work, but it's not really an error--it's a mixed type field.  because of this, i felt as though i should flip on [suppress_parse_error_log](https://docs.fluentd.org/v0.12/articles/filter_parser#suppress_parse_error_log) and still try n get the message thru.
  - maybe this is not supported at all by `filter`? perhaps [fluent-plugin-multi-format-parser](https://github.com/repeatedly/fluent-plugin-multi-format-parser) would be a better fit?
- thx for the buffer tip ;)

**Comment by cosmo0920** [comment]
It would be nice to share your expected behavior.
BTW, I'm *not* native English speaker.
Sometimes I felt your English is too complicated for me and contained slang words.

Thanks.

**Comment by cdaringe** [comment]
oh, i understand.  i will close now and re-open if needed.  thx again
