### ISSUE TITLE
How to set a string field as fielddata when logstash_format is true

### ISSUE THREAD

**Issue by vinkdong** [uken/fluent-plugin-elasticsearch#321]
#### Problem

I have to aggregation by a string filed, but if I use logstash format the `fielddata` property was false by default, How I can set it?

* Fluentd v0.14
* ES plugin 2.0.0

**Comment by cosmo0920** [comment]
What elasticsearch version do you use?

**Comment by VinkDong** [comment]
@cosmo0920 this is my elasticsearch info: 

```
{
  "name" : "xxx",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "xxxxx",
  "version" : {
    "number" : "5.5.0",
    "build_hash" : "260387d",
    "build_date" : "2017-06-30T23:16:05.735Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by cosmo0920** [comment]
This ES doc will help you?: https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html#_enabling_fielddata_on_literal_text_literal_fields

**Comment by VinkDong** [comment]
Thanks, But If I understanding correctly, it only works with existing index,  logstash_format will create a new index which ends with the date every day.

**Comment by cosmo0920** [comment]
Yup. You are right.
I have no idea to solve about this for now.

**Comment by cosmo0920** [comment]
Perhaps, you shuold use Elasticsearch template to fix mapping.
I think that like [this template](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template-es6x.json) can work ES plugin.

1. Prepare ES template
2. Specify template name and file in configuration: https://github.com/uken/fluent-plugin-elasticsearch#template_name

**Comment by cosmo0920** [comment]
I'd answered but no response for a long time. Closing.
