### ISSUE TITLE
Specify ElasticSearch index template

### ISSUE THREAD

**Issue by chschs** [uken/fluent-plugin-elasticsearch#33]
I'm using fluentd with the in_syslog plugin and elasticsearch plugin to get syslog into elasticsearch, with a kibana frontend.

One of the problems I'm having though, is that the fields are indexed in elasticsearch so when I add a terms dashboard in kibana to give me, say, the top-10 hostnames, hostnames with dashes in them are broken up. so mysql-test-01 would come across as three hostnames: mysql, test, and 01.

Logstash got around this issue by making a "raw" version of several fields that is set to not-analyzed upon creation, so that you can run your dashboards against that instead.

More information here: http://www.elasticsearch.org/blog/logstash-1-3-1-released/

With syslog messages going into ES with this plugin, I'm finding that I'd like to have a "raw" or non-analyzed host (hostname) field and ident field (gives me the application). Unfortunately right now both of those fields are analyzed and it's messing with our dashboards.

**Comment by stanhu** [comment]
+1 for making this built into the plugin.

This is the template used by logstash:

https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json

**Comment by aleks-v-k** [comment]
There is a valuable reason to make index template support built into the plugin: in a containerized environment we do not know when elasticsearch container will start and we have to PUT index template to it before fluentd will send data. There are some possible workarounds but every of them looks really ugly. So **+1** for making built in support of index templates. @pitr

**Comment by ssergiienko** [comment]
+1 for making built in support of index templates.

**Comment by pitr** [comment]
To implement this behaviour, this gem would need to do the following additional work before writing a record to elasticsearch:

1. Check if the index exists
2. If not, create the index and the mapping

Seems like that might impact the performance. What do you think @aleks-v-k @ssergiienko? What about deleting old indices?

Can you provide more information about how you run ElasticSearch in "containerized environment"? Is this something Cloudlinux is working on (I'm not familiar with their offerings)?

**Comment by stanhu** [comment]
The gem would only need to write the index templates once since a [wildcard match](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) could be used. As seen in the [Logstash template](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json#L2), just adding something like `fluentd-*` should take care of things.

**Comment by pitr** [comment]
Hmm, sounds like a good idea then

**Comment by aleks-v-k** [comment]
@pitr Thanks for reply and excuse me for late answer,
> To implement this behaviour, this gem would need to do the following additional work before writing a record to elasticsearch

I suppose there is some sort of initialization point in fluent plugin system, so it may be done there: not for each exact index, but for a group of indexes as @stanhu had mentioned.

> Can you provide more information about how you run ElasticSearch in "containerized environment"? Is this something Cloudlinux is working on (I'm not familiar with their offerings)?

It is a group of hosts, every of them runs docker daemon and has a pair of fluentd&elasticsearch containers to collect and access logs. It is not for CloudLinux OS, It is a part of [Kuberdock](http://kuberdock.com) project which uses [kubernetes](http://kubernetes.io/). We control configuration of elasticsearch and fluentd containers by our own docker images, but not manually start and stop them. They automatically run on every host added into a kuberdock cluster.

**Comment by MrMMorris** [comment]
would love to see this implemented. Using the `tag` log-opt in docker with {{.ImageName}} results in tags with -'s and :'s. I need to set the `tag` field to `not_analyzed`, but having to do it through the ES API does against my want to keep everything in source control.

**Comment by F21** [comment]
Any chance of this happening? Would love to contribute, but don't have enough time to learn Ruby at the moment.

**Comment by aerickson** [comment]
https://github.com/uken/fluent-plugin-elasticsearch/pull/194

**Comment by pitr** [comment]
implemented with #194 thanks @aerickson
