### ISSUE TITLE
Feature Request: Enable ttl in generated index(es)

### ISSUE THREAD

**Issue by datawrangl3r** [uken/fluent-plugin-elasticsearch#333]
This is more of a feature request. 
It would be really helpful if we happen to have an option in the elasticsearch plugin to set the expiration time of the generated indexes in elasticsearch.

**Comment by cosmo0920** [comment]
Since ES 2, `_ttl` per request had been marked as deprecated and removed in ES 5.
ref: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/mapping-ttl-field.html

Thus, this feature request *cannot accept* anymore.
Anyway, thank you for paying attention in this plugin! :smile:
