### ISSUE TITLE
timezone problem

### ISSUE THREAD

**Issue by lifekiller** [uken/fluent-plugin-elasticsearch#344]
Fluentd version: td-agent v3.1.1
ES plugin version: included in td-agent by default

I'm using rsyslogd in CentOS to collect network switch's log and transfer to fluentd, then Elasticsearch and kibana.

Now the problem is about the timestamp. My network switch(huawei) output syslog in utc time, such as "Dec 27 02:51:08 host msgxxxx"。the time stamp is utc time and my timezone is +08:00 so local time is 2017-12-27 10:51:08.

fluentd received syslog and treat that timestamp in my localtime, so the fluentd log as below:
2017-12-26T18:51:08Z    xxx.switch.local1.info       {"host":"xxxx","xxxxxxxxxxxxxxxxxxxxx"}

the timestamp is 8 hours earlier than the real time, how can i solve this problem.

fluentd's config:
```
<source>
  @type syslog
  port 5140
  tag xxx.switch
</source>

<match xxx.switch.**>
  @type copy
  <store>
    @type file
    path /var/log/fluent/xxxswitch
    <format>
      localtime false
    </format>
    <buffer time>
      timekey_wait 10m
      timekey 86400
      timekey_use_utc true
      path /var/log/fluent/xxxswitch
    </buffer>
  </store>
  <store>
    @type elasticsearch
    flush_interval 10s
    logstash_format true
    logstash_prefix xxxswitch
    include_timestamp true
    time_key vtm
    host 192.168.3.52
    port 9200
  </store>
</match>
```

rsyslogd conf:
local1.* @127.0.0.1:5140

**Comment by cosmo0920** [comment]
Follow issue template and you should provide Fluentd version and ES plugin version which you are using.
I'm not psychic, though. :(

**Comment by tremolo** [comment]
I had the same problem and one solution is to specify rfc5424 both on the client and the server.
for fluentd pick `rfc5424` or `auto` for the `message_format` parameter
https://docs.fluentd.org/v0.12/articles/in_syslog#message_format
```
<source>
  @type syslog
  port 5140
  bind 0.0.0.0
  tag system
 <parse>
    message_format auto
  </parse>
  protocol_type tcp
</source>
```

For the rsyslog configuration of the client this works for me:
`*.* @@192.168.100.10:5140;RSYSLOG_SyslogProtocol23Format`

Note that you have to use `RSYSLOG_SyslogProtocol23Format` to use rfc5424

**Comment by cosmo0920** [comment]
How about use `utc true` in `<parse>` directive within `<source>`?

```aconf
<source>
  @type syslog
  port 5140
  tag xxx.switch
  <parse>
    utc true
  </parse>
</source>

<match xxx.switch.**>
  @type copy
  <store>
    @type file
    path /var/log/fluent/xxxswitch
    <format>
      localtime false
    </format>
    <buffer time>
      timekey_wait 10m
      timekey 86400
      timekey_use_utc true
      path /var/log/fluent/xxxswitch
    </buffer>
  </store>
  <store>
    @type elasticsearch
    flush_interval 10s
    logstash_format true
    logstash_prefix xxxswitch
    include_timestamp true
    time_key vtm
    host 192.168.3.52
    port 9200
  </store>
</match>
```

**Comment by cosmo0920** [comment]
Hmm, It seems that larger time key causes timezone bug:
https://github.com/fluent/fluentd/pull/2054
https://github.com/fluent/fluentd/issues/1986

It is resloved in Fluentd v1.2.4.
Please try it.

If any timezone problem about this, feel free to reopen or add comments in this issue.
