### ISSUE TITLE
Custom index name doesn't work with nested field

### ISSUE THREAD

**Issue by ahrtr** [uken/fluent-plugin-elasticsearch#352]
The configuration file for fluentd is as below,
```
    <source>
      @type tail
      path /var/lib/docker/containers/*/*.log
      tag fluentd
      <parse>
        @type json
        time_key time
        keep_time_key true
      </parse>
      refresh_interval 5
    </source>
    <filter **>
        @type parser
        format json
        key_name log
        reserve_data true
        hash_value_field log
    </filter>
    <match fluentd>
      @type elasticsearch
      host elasticsearch
      port 9200
      flush_interval 10s
      index_name test-${log.tenantid}-%Y%m%d
      <buffer tag, log.tenantid, time>
         @type memory
         timekey 3600
      </buffer>
    </match>
```

I generated the following examle log entry,
`{"level":"info", "tenantid":"tenant1", "msg":"hello"}`

And docker converted the above log entry into:
`{"log": "{\"level\":\"info\", \"tenantid\":\"tenant1\", \"msg":\"hello\"}", "stream":"stderr", "time":"2018-01-27T02:38:16.382229755Z"`

Fluentd sent the log to elasticsearch successfully, and I could see the log on Kibana as well. But the issue was that the index name was "test--20180127", which wasn't what I expected. I was expecting to see the index name "test-tenant1-20180127". 

#### Using Fluentd and ES plugin versions
* OS version: Oracle Linux 7.3
* Fluentd image was built with the following Dockerfile:
```
FROM fluent/fluentd:v0.12.33-debian
......
gem install fluent-plugin-elasticsearch
......
```

**Comment by cosmo0920** [comment]
Nested record feature does not work for v0.12 branch(ES plugin version is 1.x).
This is work as expected, I think.

**Comment by ahrtr** [comment]
Thanks for the response, I just copied this issue to fluentd repository, 

> https://github.com/fluent/fluentd/issues/1836

**Comment by cosmo0920** [comment]
Awesome. Thank you!

**Comment by cosmo0920** [comment]
Solution: https://github.com/fluent/fluentd/issues/1836#issuecomment-361176947
