### ISSUE TITLE
Customize Elasticsearch template based on tag

### ISSUE THREAD

**Issue by kumaravel29** [uken/fluent-plugin-elasticsearch#355]
In my setup, I create indices on the elasticsearch cluster based on the tag name. I have a requirement to set the alias name also for the indices according to the tag name
eg - I am having a tagname as ABC.input and my index is named as logstash-ABC-2018.01 and wanted to push a template for ABC and with alias ABC_alias

#### Using Fluentd and ES plugin versions

* OS version -  **CoreOS**
* Fluentd v0.12 or v0.14/v1.0 - **td-agent 0.14.21**
* ES version - **ES 2.3.4 and planning to move to 5.6**
* ES plugin
 **fluent-plugin-elasticsearch (1.10.0)
fluent-plugin-forest (0.3.3)**

**Comment by cosmo0920** [comment]
Currently, ES plugin 1.x and 2.x install ES templates in `#configure`.
In `#configure`, we can install multiple ES templates with `templates` parameter's hash value.
Is this behavior is not expected for you?

Thanks.

**Comment by kumaravel29** [comment]
The `templates` parameter is useful for multiple static templates. I have an use case for setting dynamic templates.
As in my earlier comment, I use the appId(`ABC`) for setting the tag name(`ABC.input.tag`) and then create index based on the appId (i.e 1st part of tag `ABC`) and hence the index name is logstash-abc-2018.01 with a weekly rotation. 
To try the same in my local setup, I updated the following line in elasticsearch_index_template.rb
`file_contents = IO.read(template_file).gsub(/\n/,'')` --> `file_contents = IO.read(template_file).gsub(/\n/,'').gsub(/##alias_name##/,name)` and my template had the string `##alias_name##`

We can add a new parameter something like custom_template which can have something like `{"string_1": "subs_value_1", "string_2": "subs_value_2"}` and then the same can be used to generate the template.

**Comment by cosmo0920** [comment]
> We can add a new parameter something like custom_template which can have something like {"string_1": "subs_value_1", "string_2": "subs_value_2"} and then the same can be used to generate the template.

In your use case, should dynamic template parameters be fixed or determined in booting up time?
Or, they should be determined on each of bulk insert request?

**Comment by kumaravel29** [comment]
I would go with dynamic template in booting up time because for each bulk insert request might have performance impact

**Comment by cosmo0920** [comment]
Resolved on #431.
