### ISSUE TITLE
Content-Type application/json rather than application/x-ndjson

### ISSUE THREAD

**Issue by AdmiralGT** [uken/fluent-plugin-elasticsearch#366]
#### Problem

From v5.3, the documentation for the bulk API (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) has the following statement "When sending requests to this endpoint the Content-Type header should be set to application/x-ndjson."

Currently the content type is set to "application/json" per out_elasticsearch.rb line 210 and out_elasticsearch_dynamic.rb line 57

Happy to submit a pull request if needed.

**Comment by cosmo0920** [comment]
Content-Type application/json works on ES 2.x?
Some users still use ES 2.x.
If possible, we should add enum type parameter which specifies Content-Type.

**Comment by cosmo0920** [comment]
@AdmiralGT elasticsearch-ruby v6.0.2 will start to use `application/x-ndjson` in bulk operations.
If you use Elasticsearch 6.x, I recommend to upgrade elasticsearch gem.
Thanks!
