### ISSUE TITLE
[Feature request] Send log entries to different elasticsearch servers based on the tenantId

### ISSUE THREAD

**Issue by ahrtr** [uken/fluent-plugin-elasticsearch#369]
We deploy a separate elasticsearch cluster for each tenant user, so the fluentd instances need to send each log entry to the correct elasticsearch cluster based on the tenantid included in the log entry. 

The mappings are something as below,
tenant1 ---> http://elasticsearch-tenant1:9200 
tenant2 ---> http://elasticsearch-tenant2:9200 

So if the tenantid included in the log entry is "tenant1", then the log should be sent to http://elasticsearch-tenant1:9200. 

Please let me know if you have any comments or concerns, or Please kindly let me know if the feature has already been supported.

Thanks!

**Comment by cosmo0920** [comment]
I don't want to add feature which requires to evaluate dynamically.
If you want to add/use this feature, please send pull request.
Thanks.

**Comment by ahrtr** [comment]
I just get time to look into this issue, it seems that the Dynamic configuration (@type elasticsearch_dynamic) supports this scenario.  I will try it out and get back here later.  I wonder whether the existing configurations items, which are applied to @type elasticsearch, i.e. target_index_key, can be used for elasticsearch_dynamic?

**Comment by cosmo0920** [comment]
elasticsearch_dynamic plugin inherits and override elasticsearch plugin's class.
Thus, almost all configuration should be able to use in elasticsearch_dynamic.

**Comment by ahrtr** [comment]
@cosmo0920  Thanks for the quick response.  One more question, which versions is the elasticsearch_dynamic feature included?

Previously I did lots of tests for this plugin, and had some issues on fluentd >= 0.14.  I may need to do lots of test again, but I try not to waste time to do unnecessary tests.

**Comment by cosmo0920** [comment]
ES plugin which are between v1.1.0 to v1.16.1 contains elasticsearch_dynamic for Fluentd v0.12.
ES plugin v2.0.0 or later contains elasticsearch_dynamic for Fluentd v1/v0.14.

**Comment by cosmo0920** [comment]
And could you report your issue to evaluate on Fluentd >= v0.14?
It is welcomed to report issue on v1/v0.14 in this project.

**Comment by ahrtr** [comment]
Eventually it works when using the image fluent/fluentd-kubernetes-daemonset:v1.1-debian-elasticsearch, and the configuration is as below,
```
    <match audit.log>
      @type elasticsearch_dynamic
      host elasticsearch-${record['tenantid']}
      port 9200
      index_name ${record['target_index']}
      <buffer>
          @type memory
          retry wait  5
          retry_type periodic
          retry_randomize false
          retry timeout 24h

          flush_mode interval
          flush_interval 10s

          chunk_limit_size 1MB
          total_limit_size 64MB
          chunk_limit_records 10
      </buffer>
    </match>
```

Although the above configuration works, I still want to double confirm the following two items:
1. What's the correct format to configure 'chunk_limit_size'?  
2. The flush interval is configured as 10s, I assume that each chunk will also get flushed and transported immediately once the limitation of chunk_limit_size or chunk_limit_records is reached. Can you confirm this?

Thanks!

**Comment by cosmo0920** [comment]
> What's the correct format to configure 'chunk_limit_size'?

`chunk_limit_size` is `size` type configuration parameter.
We can specify numbers greater than 0 with KB, MB, GB, ... suffixes there.

> The flush interval is configured as 10s, I assume that each chunk will also get flushed and transported immediately once the limitation of chunk_limit_size or chunk_limit_records is reached. 

Yup. You are right.

**Comment by ahrtr** [comment]
@cosmo0920 Thanks a lot for the quick confirmation!

**Comment by cosmo0920** [comment]
Can we close this issue?
Or, we should leave as-is?

Because elasticsearch_dynamic uses `#eval` which causes performance degrade (#eval is slow!) and slower than non-dynamic elasticsearch plugin.

**Comment by ahrtr** [comment]
Thanks for the info!
