### ISSUE TITLE
Document mapping type name can't start with '_', found: [_doc]

### ISSUE THREAD

**Issue by martinssipenko** [uken/fluent-plugin-elasticsearch#376]
After upgrading to v2.8.0 ES started to return 400s with following error:

```json
{
  "type": "invalid_type_name_exception",
  "reason": "Document mapping type name can't start with '_', found: [_doc]"
}
```
I am using AWS ElasticSearch v6.0.1.

Reverting back to v2.7.0 fixed the issue.

**Comment by ymatsiuk** [comment]
the same issue here:
```
2018-03-06 12: 01: 42 +0000 [error]: #0 Could not push log to Elasticsearch: {
    "took"=>2,
    "errors"=>true,
    "items"=>[
        {
            "index"=>{
                "_index"=>"index-2018.03.06",
                "_type"=>"_doc",
                "_id"=>"AWH7MEyla3epn6q_f6J2",
                "status"=>400,
                "error"=>{
                    "type"=>"invalid_type_name_exception",
                    "reason"=>"Document mapping type name can't start with '_', found: [_doc]"
                }
            }
        },
        {
            "index"=>{
                "_index"=>"index-2018.03.06",
                "_type"=>"_doc",
                "_id"=>"AWH7MEyla3epn6q_f6J7",
                "status"=>400,
                "error"=>{
                    "type"=>"invalid_type_name_exception",
                    "reason"=>"Document mapping type name can't start with '_', found: [_doc]"
                }
            }
        }
    ]
}
```

**Comment by cosmo0920** [comment]
Please fill issue template. Please don’t ignore it.

Thanks.

**Comment by martinssipenko** [comment]
Sorry about ignoring it, but basically the issue is that plugin sends `_doc` where it sent `fluentd` before and ES for some reason does not like it. Note here that I'm using ES provider by AWS, which might be acting slightly different than self-hosted ES.

**Comment by ymatsiuk** [comment]
This is Dockerfile you can use to re-produce this behaviour:

```
FROM fluent/fluentd:v1.1.0-debian-onbuild

RUN buildDeps="sudo make gcc g++ libc-dev ruby-dev dh-autoreconf libltdl-dev" \
 && apt-get -qq update \
 && apt-get install -qqy --no-install-recommends $buildDeps \
 && sudo gem install fluent-plugin-elasticsearch \
 && sudo gem install fluent-plugin-record-modifier \
 && sudo gem install fluent-plugin-multi-format-parser \
 && sudo gem install fluent-plugin-systemd \
 && sudo gem install fluent-plugin-prometheus \
 && sudo gem sources --clear-all \
 && SUDO_FORCE_REMOVE=yes \
    apt-get purge -qqy --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem

COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
CMD exec fluentd -c /fluentd/etc/${FLUENTD_CONF} -p /fluentd/plugins $FLUENTD_OPT
```

**Comment by cosmo0920** [comment]
@ymatsiuk I cannot reproduce your environment.
Because your Dockerfile want to refer local fluentd.conf, and official fluentd Dockerfile does not refer fluent-plugin-elasticsearch: https://github.com/fluent/fluentd-docker-image/blob/master/v1.0/debian-onbuild/Dockerfile

**Comment by cosmo0920** [comment]
@martinssipenko Don't you specify type_name parameter explicitly in your Fluentd configuration?
 If you don't specify it, v2.8.0 affects in your environment.
And I'm planning to use `_doc` type_name in ES plugin v3 which is working on Fluentd v2.

**Comment by ymatsiuk** [comment]
@cosmo0920 adding `type_name fluentd` fixes the issue. Thanks.

**Comment by martinssipenko** [comment]
@cosmo0920 no I do not specify `type_name fluentd`, you can use `_doc` in v3, but if you do so in v2 it's a BC breaking change.

**Comment by cosmo0920** [comment]
I've released v2.8.1 to fix this issue.

**Comment by sandstrom** [comment]
You probably know already, but just wanted to note that under Elasticsearch 6.2 [using _doc works](https://github.com/elastic/elasticsearch/pull/27816).

**Comment by cosmo0920** [comment]
Thanks for the information.
But some users seems to use old ES 6.x  and not to be able to replace easily.
