### ISSUE TITLE
Dry run option returns header error and overwrites existing template

### ISSUE THREAD

**Issue by gvisniuc** [uken/fluent-plugin-elasticsearch#380]
#### Problem

When running the dry run command without having set the `content_type` field to `application/json` in the config file:
```
LOGGING_ES_CLUSTER_URL=https://es-host.example.com /sbin/td-agent --dry-run
```

The following error is shown:

```
2018-03-14 10:55:10 +0000 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2018-03-14 10:55:10 +0000 [info]: starting fluentd-1.0.2 as dry run mode ruby="2.4.2"
2018-03-14 10:55:10 +0000 [info]: [default_kibana_indexer] Connection opened to Elasticsearch cluster => {:host=>"es-host.example.com", :port=>443, :scheme=>"https"}
2018-03-14 10:55:10 +0000 [error]: dry run failed: [406] {"error":"Content-Type header [application/x-ndjson] is not supported","status":406}
```

After setting the `content_type` field to `application/json` the existing templates are overwritten:

```
2018-03-14 11:00:43 +0000 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2018-03-14 11:00:43 +0000 [info]: starting fluentd-1.0.2 as dry run mode ruby="2.4.2"
2018-03-14 11:00:43 +0000 [info]: [default_kibana_indexer] Connection opened to Elasticsearch cluster => {:host=>"es-host.example.com", :port=>443, :scheme=>"https"}
2018-03-14 11:00:43 +0000 [info]: [default_kibana_indexer] Template 'default_log_template' overwritten with /etc/td-agent/es-templates/default_log_template.json.
2018-03-14 11:00:43 +0000 [info]: [default_kibana_indexer] Detected ES 6.x: ES 7.x will only accept `_doc` in type_name.
```

...

#### Steps to replicate

Using the following template:

```
<match **>
  @id default_kibana_indexer
  @type elasticsearch
  hosts "#{ENV['LOGGING_ES_CLUSTER_URL']}"
  port 443
  include_tag_key true
  include_timestamp true
  tag_key @tag
  id_key @id
  logstash_format true
  logstash_dateformat %Y.%m.%d
  logstash_prefix fluentd
  template_name default_log_template
  template_file /etc/td-agent/es-templates/default_log_template.json
  template_overwrite true
  reload_on_failure false
  reload_connections false
  <buffer>
    flush_interval 10s
  </buffer>
</match>
```

`LOGGING_ES_CLUSTER_URL=https://es-host.example.com /sbin/td-agent --dry-run`

#### Expected Behavior or What you need to ask

I would expect that the dry run option:

- Would not check if the ES cluster is live (if an invalid cluster URL is provided the dry run will fail)
- Would not overwrite the existing templates (even though `template_overwrite`  is set to `true`)

#### Using Fluentd and ES plugin versions

CentOS Linux 7
td-agent 1.0.2

**Gems**
addressable (2.5.2)
aws-partitions (1.42.0)
aws-sdk (2.10.134)
aws-sdk-core (3.11.0, 2.10.134)
aws-sdk-kms (1.3.0)
aws-sdk-resources (2.10.134)
aws-sdk-s3 (1.8.0)
aws-sdk-sqs (1.3.0)
aws-sigv4 (1.0.2)
bigdecimal (default: 1.3.0)
bundler (1.16.0)
cool.io (1.5.3)
did_you_mean (1.1.0)
dig_rb (1.0.1)
elasticsearch (5.0.4)
elasticsearch-api (5.0.4)
elasticsearch-transport (5.0.4)
excon (0.60.0)
faraday (0.13.1)
fluent-logger (0.7.1)
fluent-plugin-cloudwatch-ingest (1.6.0)
fluent-plugin-elasticsearch (2.8.1, 2.8.0, 2.7.0, 2.6.1, 2.4.0)
fluent-plugin-kafka (0.6.5)
fluent-plugin-prometheus (1.0.1)
fluent-plugin-rewrite-tag-filter (2.0.1)
fluent-plugin-s3 (1.1.0)
fluent-plugin-td (1.0.0)
fluent-plugin-td-monitoring (0.2.3)
fluent-plugin-webhdfs (1.2.2)
fluentd (1.0.2, 0.14.25)
hirb (0.7.3)
http_parser.rb (0.6.0)
httpclient (2.8.2.4)
io-console (default: 0.4.6)
ipaddress (0.8.3)
jmespath (1.3.1)
json (default: 2.0.4)
ltsv (0.1.0)
mini_portile2 (2.3.0)
minitest (5.10.1)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7)
msgpack (1.2.0)
multi_json (1.12.2)
multipart-post (2.0.0)
net-telnet (0.1.1)
nokogiri (1.8.1)
ohai (6.20.0)
oj (3.3.9)
openssl (default: 2.0.5)
parallel (1.12.1)
power_assert (0.4.1)
prometheus-client (0.7.1)
psych (default: 2.2.2)
public_suffix (3.0.1)
quantile (0.2.0)
rake (12.0.0)
rdoc (default: 5.0.0)
ruby-kafka (0.5.1)
ruby-progressbar (1.9.0)
ruby_dig (0.0.2)
rubyzip (1.2.1)
serverengine (2.0.5)
sigdump (0.2.4)
statsd-ruby (1.4.0)
strptime (0.1.9)
systemu (2.5.2)
td (0.15.7)
td-client (1.0.4)
td-logger (0.3.27)
test-unit (3.2.3)
thread_safe (0.3.6)
tzinfo (1.2.4)
tzinfo-data (1.2017.3)
webhdfs (0.8.0)
xmlrpc (0.2.1)
yajl-ruby (1.3.1)
zip-zip (0.3)

**Comment by cosmo0920** [comment]
Fluentd'S `--dry-run` option is simply executing plugins `#configure`.
In plugin, it cannot recognize to be executed by dry-run option.

> 

> Would not overwrite the existing templates (even though template_overwrite is set to true)

It is impossible for current ES plugin implementations.
ES plugin executes template related setting up on `#configure`.

**Comment by gvisniuc** [comment]
@cosmo0920 Thank for the answer. Regarding the issue with the content type header, would it be possible to use the default content type `application/x-ndjson` but still be able to do a dry run?

**Comment by cosmo0920** [comment]
@gvisniuc You shouldn't change Content-Type with content_type parameter.
Due to my misunderstood, `content_type` parameter had been introduced but this value handling should be put in elasticsearch-ruby and elasticsearch-ruby v6.0.2 starts to use `application/x-ndjson` in bulk operations. https://github.com/elastic/elasticsearch-ruby/pull/514

I've reverted to default value of `content_type` parameter in ES plugin.
I reckon that with `application/json` Content-Type header, we can do a dry-run.

**Comment by gvisniuc** [comment]
@cosmo0920 👍 thanks
