### ISSUE TITLE
td-agent unable to communicate over SSL to elasticsearch

### ISSUE THREAD

**Issue by abhigp27** [uken/fluent-plugin-elasticsearch#384]
#### Problem
td-agent unable to communicate over SSL to elasticsearch. Elasticsearch is expecting TLSv1_2 ssl version but looks like td-agent is trying to communicate over SSL3.
With the certificates i am able to connect to elacticsearch from other clients.

**ERROR**
`2018-03-19 11:59:09 +0000 [warn]: #0 [demo_log] failed to flush the buffer. retry_time=8 next_retry_seconds=2018-03-19 11:59:09 +0000 chunk="567bd7e9d64cf7636e6d765f951bdc0e" error_class=Faraday::SSLError error="SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate unknown (OpenSSL::SSL::SSLError)"`

Already Posted in Google groups -
 https://groups.google.com/d/msg/fluentd/1Ko11CtJqHo/S34Ae0OmCAAJ

#### Conf file being used

```aconf
 #td-Agent Output config file
<match demo.*>
  @type elasticsearch_dynamic
  @id demo_elasticsearch_log
  hosts FQDN:Port
  scheme https
  ca_file /path/of/ca_cert/pem/file.pem
  client_cert /path/of/client_cert/pem/file.pem
  client_key /path/of/client_key/pem/file.pem
  ssl_version TLSv1_2
  logstash_format true
  type_name ${record['index_prefix']}
  logstash_prefix ${record['index_prefix']}
  logstash_dateformat %Y.%m.%d
  time_key Timestamp
  time_key_exclude_timestamp true
  <buffer>
    @type file
    chunk_limit_size XMB # https://groups.google.com/forum/#!topic/fluentd/-6Q8pPMU-Kc
    total_limit_size XGB
    flush_interval 10s
    overflow_action throw_exception
    flush_thread_count 4
  </buffer>
  request_timeout 15s
  remove_keys index_prefix
  reconnect_on_error true
  reload_on_failure true

  <secondary>
    @type secondary_file
    directory /path/of/some/dir
  </secondary>
</match>
```

#### Using Fluentd and ES plugin versions

* OS version
CentOS Linux release 7.3.1611 (Core)
* TD-Agent Version 
  td-agent 1.0.2

**Comment by cosmo0920** [comment]
Yeah, this is a bug of es_dynamic. 
Thank you for your report.

**Comment by abhigp27** [comment]
After installing the latest version it is producing the same error.

```
2018-03-22 09:19:40 +0000 [warn]: #0 [ovn_elasticsearch_log] failed to flush the buffer. 
retry_time=11 next_retry_seconds=2018-03-22 09:34:54 +0000 
chunk="567fac05d9bc45c0aae0d98bcd34f2d0" error_class=Faraday::SSLError 
error="SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate 
unknown (OpenSSL::SSL::SSLError)"
```

**Comment by cosmo0920** [comment]
@fujimotos Could you investigate this issue?
I don't have enough time to dive into root cause of this issue for now. :'(

**Comment by cosmo0920** [comment]
I've checked with the following TLS configuration guidance:
https://www.elastic.co/guide/en/elasticsearch/reference/6.x/configuring-tls-docker.html
But I didn't reproduce this issue...

**Comment by abhigp27** [comment]
Looks like my certificate has some issues.
Thanks

**Comment by danielcb** [comment]
This issue is still present, isn't it? I'm getting the same error, trying to connect to ES via https (through nginx as a reverse_proxy; ssl version in nginx set to TLSv1.2 TLSv1.3)
