### ISSUE TITLE
custom timestamp format - millisecs are down to 0

### ISSUE THREAD

**Issue by tmeinlschmidt** [uken/fluent-plugin-elasticsearch#39]
Hi,
I'm trying to insert custom `@timestamp` value into records, but need to use milliseconds, so using this format - `"@timestamp":"2014-05-16T10:43:52.207-04:00"`, but then in kibana it's shown without milliseconds (just as 10:43:52.000). 

Checked mappings:

```
          "@timestamp" : {
            "type" : "date",
            "format" : "dateOptionalTime"
          },
```

so instead of dateOptionalTime there should be dateTime (as in http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-date-format.html) ..

any idea?
Thanks

**Comment by superdump** [comment]
It seems that this has been overhauled in fluentd 0.14.0pre1 and timestamps with nanosecond accuracy are supported.

In any case, can someone provide exact information here about how to configure fluentd and fluent-plugin-elasticsearch with 0.12.x to write milliseconds into the @timestamp field?

**Comment by superdump** [comment]
A solution for 0.12.x could be:

```
<filter **>
  @type record_transformer
  enable_ruby
  <record>
    timestamp ${ require 'time'; Time.now.utc.iso8601(3) }
  </record>
</filter>
```

And then use `time_key timestamp` in the elasticsearch plugin config.

**Comment by tobilarscheid** [comment]
Hi @superdump and everyone else,

> It seems that this has been overhauled in fluentd 0.14.0pre1 and timestamps with nanosecond accuracy are supported.

does this mean using fluentd 0.14 with this plugin would give me nano or at least millisecond precision?

**Comment by crackmac** [comment]
I believe #223 will handle the nano sec issue once it is merged in. It look like some failed testing is all that is holding it back.
