### ISSUE TITLE
Hash Flattening simply does not work

### ISSUE THREAD

**Issue by chs-bnet** [uken/fluent-plugin-elasticsearch#393]
#### Problem
We have a bunch of data coming in through fluentd going to elasticsearch that has json objects. Sometimes this causes a lot of mapping issues and we'd like to simply utilize the hash flattening option to simply the data.

Here is an example of an object field [params]:
"params": {
      "logdata": {
        "library_version": "value",
        "account_id": "value",
        "account_username": "value",
        "system": "client",
        "session_id": "value",
      }
    }

#### Steps to replicate

We're using the elasticsearch output plugin, configured identical to the documentation. We are verifying that objects are going into ES such as the above.

But we never see the flattened fields.

#### Expected Behavior or What you need to ask
We would expect to see from the example above fields such as: [params_logdata_lobrary_version] or [params_logdata_system]. Those fields do not exist though. And there are no errors coming from the ES plugin going to the fluentd log. For all intents and purposes, it seems like it's simply not working, rather than erroring.

#### Using Fluentd and ES plugin versions

* OS version
Ubuntu 16.04 LTS
* Fluentd v0.12 or v0.14/v1.0
td-agent 1.1.1
* ES plugin 2.x.y or 1.x.y
elasticsearch (6.0.1)
elasticsearch-api (6.0.1)
elasticsearch-transport (6.0.1)
fluent-plugin-elasticsearch (2.8.1)
fluentd (1.1.1)
* ES version (optional)
5.6.7

**Comment by cosmo0920** [comment]
I've tried to reproduce above issue, but I could't. :'(

* OS version
  * macOS High Sierra 10.13.4
* Fluentd v1.1.3
* ES plugin 
  * fluent-plugin-elasticsearch (2.8.1)
* ES version
  * v6.2.3 (latest stable)

---

### Fluentd Configuration

```aconf
<source>
  @type forward
</source>
<match test.*>
  @type elasticsearch
  flatten_hashes true
  flush_interval 1s
</match>
```

### Result

```bash
$  curl http://localhost:9200/_search | jq . 
```

```log
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "fluentd",
        "_type": "fluentd",
        "_id": "VHg2qGIBveZz422TEMaF",
        "_score": 1,
        "_source": {
          "params_logdata_library_version": "value",
          "params_logdata_account_id": "value",
          "params_logdata_account_username": "value",
          "params_logdata_system": "client",
          "params_logdata_session_id": "value"
        }
      }
    ]
  }
}
```

**Comment by cosmo0920** [comment]
No response, Closing.
