### ISSUE TITLE
Could not push log to Elasticsearch - get log data

### ISSUE THREAD

**Issue by itielshwartz** [uken/fluent-plugin-elasticsearch#400]
#### Problem

`Could not push log to Elasticsearch` (Elastic companies:  `Can't get text on a START_OBJECT at 1:110"}`) sometimes occur, I guess some malformed data

#### Steps to replicate

Not sure - that's the issue.

#### Expected Behavior or What you need to ask
I want to see the data being sent in case of an error, is it currently possible?
to clarify:
See the data in case of failure to index document
#### Using Fluentd and ES plugin versions

* fluentd:v1.1.0-debian
* ES plugin2.7.0
* ES version 6.2.X

**Comment by cosmo0920** [comment]
Follow the issue template, please.

**Comment by itielshwartz** [comment]
@cosmo0920 just did, thanks

**Comment by cosmo0920** [comment]
Don't know how else to help here, it seems that lack of replicate step is not able to look into root cause of this issue. :'(

**Comment by itielshwartz** [comment]
@cosmo0920  i think the issue is in here:
https://github.com/uken/fluent-plugin-elasticsearch/blob/ea7a1d87f2885d7b64c8f7c97c638649dd2b780a/lib/fluent/plugin/out_elasticsearch_dynamic.rb#L220-L224

And i would like to also log the `dat`a which made the requests (other wise i can't understnad the problem)

**Comment by cosmo0920** [comment]
From [SO](https://stackoverflow.com/questions/41873672/updating-a-field-with-a-nested-array-in-elastic-search):

>  The message "Can't get text on a START_OBJECT" means that Elasticsearch was expecting an entry of type "string" but you are trying to give an object as input.

It seems that you send JSON object into string mapped record.

**Comment by itielshwartz** [comment]
Yeah but I don't know which string / msg...

**Comment by cosmo0920** [comment]
This error led by an invisible hand, though.... :confused:

**Comment by r4j4h** [comment]
This may be happening after the fact, but just incase it helps you might be able to use an `@ERROR` block and print the log line there..

```
    <label @ERROR>
      <match **>
        @type stdout
      </match>
    </label>
```

If this happens reliably or often then a dirty but workable method is to put a copy matcher and copy it both to the ES plugin and to stdout. Now whenever you see this failure from the ES plugin the root cause log entry should be present somewhere a little earlier in the logs from the stdout copy.

**Comment by itielshwartz** [comment]
hi thanks for the first advice @r4j4h !

**Comment by r4j4h** [comment]
My pleasure @itielshwartz I hope it helped to debug the problem! :)
