### ISSUE TITLE
Removal of mapping types in Elasticsearch 6.x

### ISSUE THREAD

**Issue by martin21** [uken/fluent-plugin-elasticsearch#412]
I think this is more of an best practice documentation issue, not an issue with fluentd / elasticsearch output plugin itself, but I am not sure. I am posting this here as issue first, but it may also be something to go into docs.fluentd.org or whatever.

#### Problem
When I use a simple Fluentd configuration that puts both internal fluentd log data and syslog data into one Elasticsearch index. Both sources appear to use different mapping types and have different fields. Elasticsearch bails out and won´t accept any more data, due to removal of mapping types (detailed error backtrace below):

https://www.elastic.co/guide/en/elasticsearch/reference/6.x/removal-of-types.html#_index_per_document_type

This only started to happen with todays update of fluentd gems (fluentd 1.11 to 1.13, probably also fluent-plugin-elasticsearch 2.8.0 to 2.9.2, I do not remember exactly) and Elasticsearch (6.2.3 to 6.2.4), so this appears to be caused by a new behavior due to an update.

#### Steps to replicate
Use a simple fluentd configuration like:

```
<source>
        @type forward
        @id forward_input
</source>

<source>
        @type syslog
        @id in_syslog
        port 5140
        protocol_type tcp
        message_format auto
        priority_key severity
        facility_key facility
        tag system
</source>

<match *.**>
        @type elasticsearch
        hosts elasticsearch1a,elasticsearch1b,elasticsearch1c
        port 9200
        logstash_format true
        logstash_prefix fluentd
        #index_name fluentd
        #type_name fluentd
</match>
```
Tell rsyslog to put some data into it, like this:

```
root@elasticsearch1a:/var/log/elasticsearch# cat /etc/rsyslog.d/remote.conf 
*.*     @@fluentd:5140
```

Fluentd puts internal logs tagged with `fluent.*` and syslog to one Elasticsearch index.

However as both sources seem to use different mapping types, this mails out with Elasticsearch 6.x:

```
[…][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [elasticsearch1a] failed to put mappings on indices [[[fluentd-2018.04.25/0_ocsBGWTE-Ga9cNQ7A81A]
]], type [fluentd]
java.lang.IllegalArgumentException: Rejecting mapping update to [fluentd-2018.04.25] as the final mapping would have more than 1 type: [_doc, fluentd]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:501) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:285) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:313) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) [elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) [elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) [elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [e
lasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [elasticsearch-6.2.4.jar:6.2.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

#### Expected Behavior or What you need to ask
Elasticsearch just puts it all into one index as before ("don´t break userspace")… however… due to removal of mapping types by Elasticsearch developers, this may need a different approach:

For now I use different indices for each log source. This however means more indices in Elasticsearch cluster, which for fluent internal logs with just a few messages usually can mean more primary shards than necessary: "Of course, there is a limit to how many primary shards can exist in a cluster so you may not want to waste an entire shard for a collection of only a few thousand documents" (see again: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/removal-of-types.html#_index_per_document_type). Of course I could mitigate this by rotating the fluentd-internal indices not once per day but quicker.

The currently working configuration looks like this:

```
<source>
        @type syslog
        @label @SYSLOG
        tag syslog
        port 5140
        protocol_type tcp
        message_format auto
        priority_key severity
        facility_key facility
</source>

<label @SYSLOG>
        <match syslog.**>
                @type elasticsearch
                hosts elasticsearch1a,elasticsearch1b,elasticsearch1c
                port 9200
                logstash_format true
                logstash_prefix fluentd-syslog
        </match>
</label>

<label @FLUENT_LOG>
        <match fluent.**>
                @type elasticsearch
                hosts elasticsearch1a,elasticsearch1b,elasticsearch1c
                port 9200
                logstash_format true
                logstash_prefix fluentd-internal
        </match>
</label>
```

#### Using Fluentd and ES plugin versions
* Debian Stretch 9.4
* Fluentd v1.1.3
* Elasticsearch 6.2.4

```
bigdecimal (1.3.4, 1.2.8)
cool.io (1.5.3)
did_you_mean (1.0.0)
dig_rb (1.0.1)
elasticsearch (6.0.2, 6.0.1, 6.0.0)
elasticsearch-api (6.0.2, 6.0.1, 6.0.0)
elasticsearch-transport (6.0.2, 6.0.1, 6.0.0)
excon (0.62.0, 0.60.0)
faraday (0.15.0, 0.14.0)
fluent-plugin-elasticsearch (2.9.2, 2.8.0, 2.6.0, 2.4.1)
fluentd (1.1.3, 1.1.1, 1.1.0)
http_parser.rb (0.6.0)
io-console (0.4.6, 0.4.5)
json (2.1.0, 1.8.3)
minitest (5.11.3, 5.9.0)
msgpack (1.2.4, 1.2.2)
multi_json (1.13.1)
multipart-post (2.0.0)
net-telnet (0.1.1)
power_assert (1.1.1, 0.2.7)
psych (3.0.2, 2.1.0)
rake (12.3.1, 12.3.0, 10.5.0)
rdoc (6.0.3, 6.0.1, 4.2.1)
serverengine (2.0.6)
sigdump (0.2.4)
strptime (0.2.3)
test-unit (3.2.7, 3.1.7)
thread_safe (0.3.6)
tzinfo (1.2.5, 1.2.4)
tzinfo-data (1.2018.4, 1.2018.3, 1.2017.3)
yajl-ruby (1.3.1)
```

**Comment by cosmo0920** [comment]
Currently, ES plugin v2.9.2 uses fixed `type_name` for ES 7 or above.
For ES 6.x, it doesn't have any constraint for `type_name`.
Should we have a cache to check last used `type_name` value?

**Comment by martin21** [comment]
Hmmm, I wondered about using the same `type_name` as another way to handle the removal of mapping types and still stuff different kind of documents into the same index. Actually I do not yet have a clear idea on what best practice would be here. I bet it depends on the circumstances like the amount of documents of each type. I somewhat tend to think that it would be good to keep Fluentd + Elasticsearch setups with `<match **>` running, instead of breaking them (and yeah, the I know the breaking change was in ES).

**Comment by cosmo0920** [comment]
One idea is:

For ES 6.x, ES plugin specifies fixed `doc`  in `type_name`.
For ES 7.x, ES plugin specifies fixed `_doc` in `type_name`.

**Comment by cosmo0920** [comment]
> we have a cache to check last used type_name value?

Another idea

**Comment by cosmo0920** [comment]
Ah, your configuration seems to be bad.
`<match *.**>` handles Fluentd system message.
You should reject system message in `<match>` directive in most cases:

```aconf
<match syslog.**> 
        @type elasticsearch
        hosts elasticsearch1a,elasticsearch1b,elasticsearch1c
        port 9200
        logstash_format true
        logstash_prefix fluentd
        #index_name fluentd
        #type_name fluentd
</match>
```

**Comment by martin21** [comment]
@cosmo0920 That is how I changed the configuration then, please reread my initial issue description. However, as it worked before the upgrade, and does not work afterwards, it may be some thing to mention in the documentation. That is also why I mentioned that it may not need a change in the code, but some hint about this behavioral change would be good for existing users. Cause it breaks existing setups that always stuffed everything into one index.

**Comment by cosmo0920** [comment]
Ah, I got it.
v2.8.0 is wrongly changed default value of mapping type.
This is similar issue against https://github.com/uken/fluent-plugin-elasticsearch/issues/376.
Only v2.8.0 contains bug which is originated from my misunderstanding.
Could you migrate `_doc` indexed indices into `fluentd`?

**Comment by cosmo0920** [comment]
No response, Closing.

**Comment by UncleTawnos** [comment]
still happens in 2.11

**Comment by cosmo0920** [comment]
@UncleTawnos Could you open a new issue?
