### ISSUE TITLE
Documentation is missing for deprecation warnings

### ISSUE THREAD

**Issue by sradco** [uken/fluent-plugin-elasticsearch#415]
#### Problem

We get the following warning

[warn]: 'port' parameter is deprecated: User <server> host xxx </server> instead.
[warn]: 'host' parameter is deprecated: Use <server> port xxx </server> instead.

But the documentation does not reflect the change required.

#### Steps to replicate

Example config and message
(We populate the values using Ansiblle)

```aconf
<match project.ovirt-metrics**>
  @type elasticsearch
  scheme https
  host {{ fluentd_elasticsearch_host }}
  {% if fluentd_elasticsearch_port is defined %}
  port {{ fluentd_elasticsearch_port }}
  {% endif %}
  client_cert {{ fluentd_elasticsearch_client_cert_path }}
  client_key {{ fluentd_elasticsearch_client_key_path }}
  ca_file {{ fluentd_elasticsearch_ca_cert_path }}
  ssl_verify {{ fluentd_elasticsearch_ssl_verify|lower }}
  target_index_key {{ fluentd_elasticsearch_target_index_key }}
  remove_keys {{ fluentd_elasticsearch_remove_keys }}
  type_name {{ fluentd_elasticsearch_type_name_metrics }}
  request_timeout {{ fluentd_elasticsearch_request_timeout_metrics }}

# Buffer configurations
  flush_interval {{ fluentd_flush_interval_metrics }}
  buffer_chunk_limit {{ fluentd_buffer_chunk_limit_metrics }}
  buffer_queue_limit {{ fluentd_buffer_queue_limit_metrics }}
  buffer_queue_full_action {{ fluentd_buffer_queue_full_action_metrics }}
  retry_wait {{ fluentd_retry_wait_metrics }}
  retry_limit {{ fluentd_retry_limit_metrics }}
  disable_retry_limit {{ fluentd_disable_retry_limit_metrics }}
  max_retry_wait {{ fluentd_max_retry_wait_metrics }}
  flush_at_shutdown {{ fluentd_flush_at_shutdown_metrics }}
  num_threads {{ fluentd_num_threads_metrics }}
  slow_flush_log_threshold {{ fluentd_slow_flush_log_threshold_metrics }}
</match>
```

#### Expected Behavior or What you need to ask

There is no  mentioning in the README for the changes required.

#### Using Fluentd and ES plugin versions

* OS version
* Fluentd v0.12 or v0.14/v1.0
  * Fluentd v0.12
* ES plugin 2.x.y or 1.x.y
  * fluent-plugin-elasticsearch 1.9.5
* ES vrsion (optional)
  * ES 2.4.4

**Comment by cosmo0920** [comment]
Could you paste entire log without sensitive information?

**Comment by sradco** [comment]
This is a fluentd secure forward issue. Sorry.

**Comment by cosmo0920** [comment]
No problem.
Please feel free to register issue.
Thanks! :smile:

**Comment by cosmo0920** [comment]
Ah, if you still got deprecated warnings, could you register documentation issue in [Fluentd documentation repository](https://github.com/fluent/fluentd-docs)?
