### ISSUE TITLE
no implicit conversion of Fluent::EventTime into String

### ISSUE THREAD

**Issue by mattheworiordan** [uken/fluent-plugin-elasticsearch#423]
#### Problem

I have a huge volume of time parsing errors since upgrading this plugin, and am at a bit of a loss as to how I can get to the bottom of the issue as I don't really understand the tool chain for debugging fluentd and plugins.

The error I am seeing at a rate of literally 50+ per second per `fluentd` process (I run 8):

```
2018-05-21 21:52:33 +0000 [warn]: #0 dump an error event: error_class=TypeError error="no implicit conversion of Fluent::EventTime into String" location="/var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-2.10.1/lib/fluent/plugin/out_elasticsearch.rb:222:in `parse'" tag="Fluent::ElasticsearchOutput::TimeParser.error" time=#<Fluent::EventTime:0x00007f41bab45ed0 @sec=1526939553, @nsec=948145538> record={"tag"=>"fluent.warn", "time"=>#<Fluent::EventTime:0x00007f41bab45048 @sec=1526939431, @nsec=117101150>, "format"=>nil, "value"=>#<Fluent::EventTime:0x00007f41bab44648 @sec=1526939431, @nsec=117075662>}
```

#### Steps to replicate

The problem I have is that I don\t know how to work out which of my log sources is causing this problem.  Any advice on how to enabled debugging mode, or perhaps output the log lines that are causing these failures, will help me very quickly figure out what is causing the issue.

The `fluentd.conf` is at https://gist.github.com/mattheworiordan/08c16983b62a9a84f01e420001cf50db.  Note it's an ERB file, so all `<%=%>` get replaced at runtime.

#### Expected Behavior or What you need to ask

I would like to know which log entries are causing this error (lots of logs are coming through) so that I can help fix it.

#### Using Fluentd and ES plugin versions

* OS version - Ubuntu 14 in a Docker container
* Fluentd v0.14.25
* ES plugin 2.10.1
```
$ bundle list
Gems included by the bundle:
  * bundler (1.16.0)
  * cool.io (1.5.3)
  * elasticsearch (6.0.2)
  * elasticsearch-api (6.0.2)
  * elasticsearch-transport (6.0.2)
  * excon (0.62.0)
  * faraday (0.15.1)
  * fluent-plugin-color-stripper (0.0.3 a1ac8dd)
  * fluent-plugin-elasticsearch (1.16.1)
  * fluent-plugin-out-file-copy (0.0.1 b0412d3)
  * fluent-plugin-rewrite-tag-filter (2.0.2)
  * fluentd (0.14.25)
  * http_parser.rb (0.6.0)
  * msgpack (1.2.4)
  * multi_json (1.13.1)
  * multipart-post (2.0.0)
  * ruby_dig (0.0.2)
  * serverengine (2.0.6)
  * sigdump (0.2.4)
  * strptime (0.1.9)
  * thread_safe (0.3.6)
  * tzinfo (1.2.5)
  * tzinfo-data (1.2018.5)
  * yajl-ruby (1.4.0)
```
* ES version 6.2.4

---

Thanks for your help.  I am happy to help debug and even fix this, but any advice on how you would go about catching the offending logs would be hugely appreciated.

**Comment by cosmo0920** [comment]
I've confirmed that this issue is reproducible by the following config and code:

```aconf
<source>
  @type forward
</source>
<match test.*>
  @type elasticsearch
  host localhost
  port 9200
  time_key time
  logstash_format true
  <buffer>
    @type memory
    flush_interval 1s
  </buffer>
</match>
```

```ruby
require 'fluent/time'
require 'flient-logger'

record = {"tag"=>"fluent.warn", "time"=>Fluent::EventTime.now, "format"=>nil, "value"=>Fluent::EventTime.now}

log = Fluent::Logger::FluentLogger.new(nil)
log.post("test.elastic", record)
```

**Comment by cosmo0920** [comment]
It seems that  `time_key` field contains  a `Fluent::EventTime` instance.
It is not able to parse with `#parse_time`.

Umm..., I have no idea for now. :confounded:

**Comment by cosmo0920** [comment]
> I would like to know which log entries are causing this error (lots of logs are coming through) so that I can help fix it.

You can get log entries which cause this error:

```aconf
<label @ERROR>
  <match **> 
    @type stdout
  </match>
</label>
```

**Comment by mattheworiordan** [comment]
Thanks @cosmo0920.  I will make some time shortly to look into this and get back to you.

**Comment by tamer-hassan** [comment]
in my case my log filled up quickly with same messages
but the real/main issue was that messages were not getting accepted by ES 6.x, because of conflict over the "type" posted to the logstash index of the day, with "type" being set to "fluentd", where other kubernetes pods have previously posted to the same logstash index with a "events" type.

Noticed you're missing an explicit "type_name" as well in your config. Mine which works when nothing else is updating the logstash index with different type than "fluentd".
```
<match **>
  @type elasticsearch
  host elasticsearch-logging.kube-system
  port 9200
  logstash_format true
  time_key time
  type_name fluentd
  include_tag_key true
  flush_interval 2s
</match>
```

If you do not set the type_name set as the same type that was previously posted to the same logstash index, another way to get around it would be to delete the index and let fluentd re-submit messages with whatever type_name defaults to. example:
$ curl -X DELETE "elasticsearch-logging.cluster-name:9200/logstash-2018.08.20"

**Comment by pathikritmodak** [comment]
@mattheworiordan Were you able to fix the issue? I am facing the same error, and doesn't seem like the above solution is pertinent for me. I already have an explicit type_name.

**Comment by cosmo0920** [comment]
@bderickson In @mattheworiordan's case, [this line](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L369) is called not your pointed one.

**Comment by cosmo0920** [comment]
v3.4.1 includes this fix.
