### ISSUE TITLE
Raise Fluent::UnrecoverableError for unrecoverable Elasticsearch errors

### ISSUE THREAD

**Issue by repeatedly** [uken/fluent-plugin-elasticsearch#432]
Fluentd v1.2.0 supports UnrecoverableError handling to avoid unnecessary retry.

https://docs.fluentd.org/v1.0/articles/buffer-plugin-overview#handling-unrecoverable-errors

`Fluent::UnrecoverableError` is introduced since v0.14 so using it doesn't break existing v1 environment.
I'm not sure which errors are unrecoverable in Elaticsearch, but some users hit unrecoverable error and it consumes flush threads. This is not good.

https://github.com/fluent/fluentd/issues/1967

From above, mapping error is one unrecoverable case. So if the response contains such error, elasticsearch plugin should raise `Fluent::UnrecoverableError`.

**Comment by cosmo0920** [comment]
I think that this issue should solve with https://github.com/uken/fluent-plugin-elasticsearch/pull/433.
But I have no enough confidence to close this issue for now.
So, I leave as-is.

**Comment by cosmo0920** [comment]
No issue registered about #433.
I'm closing for now.
