### ISSUE TITLE
Bulk errorhandling with mismatched response count leaves plugin stuck processing chunk

### ISSUE THREAD

**Issue by jcantrill** [uken/fluent-plugin-elasticsearch#434]
#### Problem
Bulk requests that fail have no mechanism to uniquely associate an entry in the request with an entry in the response.  Subsequently, we make the assumption the number of entries in the response are equal to those in the request and the returned order is the same as the order submitted.  The plugin can still become stuck retrying a chunk if the number of messages in the request do not equal the number in the response [1], ref [2].

The assumption here is that either Elasticsearch has an issue where it is not returning the proper number of responses or there is a bug in the plugin code.

I would propose one of the following:

* add a unique or ordinal id for the bulk submission to correlate to the response
or
* when there is a mismatch, send the whole chunk back through the retry

[1] https://github.com/uken/fluent-plugin-elasticsearch/blob/v0.12/lib/fluent/plugin/elasticsearch_error_handler.rb
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1562004#c30

#### Using Fluentd and ES plugin versions

* OS version  - rhel/centos7
* Fluentd v0.12
* ES plugin 1.16.1
* ES version 2.4.4

**Comment by jcantrill** [comment]
cc @portante @richm @cosmo0920

**Comment by jcantrill** [comment]
It appears this case occurs when the plugin is configured for create or update operation and does not have an `_id` field in the record.  The bulk count is improperly bumped even though a record was not added to the bulk request

[1] https://github.com/uken/fluent-plugin-elasticsearch/blob/v0.12/lib/fluent/plugin/out_elasticsearch.rb#L273

**Comment by cosmo0920** [comment]
> add a unique or ordinal id for the bulk submission to correlate to the response

In Fluentd world, it is hard to implement it.

> when there is a mismatch, send the whole chunk back through the retry

It seems that this approach is better.

**Comment by cosmo0920** [comment]
>>   add a unique or ordinal id for the bulk submission to correlate to the response

> In Fluentd world, it is hard to implement it.

For Fluentd v1, we can use counter API to obtain a unique or ordinal id. But, Fluentd v0.12 does not have this mechanism.

**Comment by cosmo0920** [comment]
>>>  add a unique or ordinal id for the bulk submission to correlate to the response

>>   In Fluentd world, it is hard to implement it.

> For Fluentd v1, we can use counter API to obtain a unique or ordinal id. But, Fluentd v0.12 does not have this mechanism.

Or, we can use bundled `elasticsearch_genid` fiter plugin to add unique ids into `_id` field.

**Comment by cosmo0920** [comment]
For v0.12, fixed in https://github.com/uken/fluent-plugin-elasticsearch/pull/437.
