### ISSUE TITLE
Feature request : copying/renaming specified key to @timestamp

### ISSUE THREAD

**Issue by HeartSaVioR** [uken/fluent-plugin-elasticsearch#44]
Hello!

Currently plugin allows @timestamp key, and use it instead of creating to store to ES when it exists.
But it seems that specifying @timestamp key is very hard for me because of limitation of Fluentd,
(I've posted to Fluentd Google Groups for help : https://groups.google.com/d/msg/fluentd/aJXskFkUtiU/fDnCkSvkVaIJ)

So it could be cool to copy/rename specified key to @timestamp key.
How about it?

**Comment by Rohlik** [comment]
How to do the same in case you do **not** have `logstash_format` set to  `true` 🤔 ?
