### ISSUE TITLE
Support rest.action.multi.allow_explicit_index: false

### ISSUE THREAD

**Issue by dcrn** [uken/fluent-plugin-elasticsearch#444]
When using the Elasticsearch Service on AWS, we have the ability to control user access depending on the index. This allows several services to utilize the same ES server without the possibility of one modifying data in the wrong index.

However, fluent-plugin-elasticsearch uses the `_bulk` endpoint without any index specified. Allowing one user to use the _bulk endpoint also gives them permissions to modify any index (as the index is specified in the request data), unless `rest.action.multi.allow_explicit_index` is set to `false`.

Setting the ElasticSearch configuration `rest.action.multi.allow_explicit_index` to `false` adds a requirement that the indices specified in the request data must match the index in the URL, e.g. `/{index}/{type}/_bulk`. After testing, it seems that it is currently not supported in fluent-plugin-elasticsearch. It would be great to have, especially for AWS users.

#### Using Fluentd and ES plugin versions

* OS version: Amazon Linux 2
* Fluentd v1.2.2
* ES plugin 2.10.3
* ES version: 6.2

**Comment by cosmo0920** [comment]
I'm not familiar with AWS Elasticsearch Searvice.
Can ES plugin connect to this service?
If not so, this issue should be reported in https://github.com/atomita/fluent-plugin-aws-elasticsearch-service.

**Comment by badyli** [comment]
We're using a simple proxy to add necessary headers, so you should treat it as normal ES instance (tested and no problems here).

Problem is, as described, the address of the endpoint. If we want to make our instance slighlty more secure we can use access policies to limit which index user can access. Currently the ES plugin is using main _bulk endpoint, e.g. ```http://localhost:9200/_bulk```. If the ```rest.action.multi.allow_explicit_index``` is set to ```false``` this action will fail. 
On the other hand, if the index operations in _bulk request always use the same index endpoint it should be possible to form the URL with index ```http://localhost:9200/_myindex/_bulk``` and process the operation without failing.

**Comment by dcrn** [comment]
The proxy described above: https://github.com/abutaha/aws-es-proxy
This handles all of the authentication required for the AWS Elasticsearch Service, and essentially gives us a standard Elasticsearch endpoint.

**Comment by cosmo0920** [comment]
fluent-plugin-elasticsearch does not use bulk URL explicitly.
So, you can send this feature request into [elasticsearch-ruby](https://github.com/elastic/elasticsearch-ruby).
Thanks.

**Comment by dcrn** [comment]
I believe this is more about how elasticsearch-ruby is utilized. As specified in the elasticsearch-ruby [documentation](https://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Actions#bulk-instance_method), there are arguments to provide the index and type while performing bulk requests.

fluent-plugin-elasticsearch only uses the `body` argument (seen [here](https://github.com/uken/fluent-plugin-elasticsearch/blob/533d490c157d0ea24f1c5a654a92884e417c59a9/lib/fluent/plugin/out_elasticsearch_dynamic.rb#L222)).

**Comment by cosmo0920** [comment]
Patch is welcome.

**Comment by fujimotos** [comment]
@dcrn  @badyli  I have implemented an option `include_index_in_url` that
tells Fluentd to manifest the target index name in the request URL (rather than
in the request body).

This feature was included in the latest release (v2.11.3), so you can test it already.
If you find anything with it, please let me know.

https://github.com/uken/fluent-plugin-elasticsearch#include_index_in_url

**Comment by dcrn** [comment]
@fujimotos Thanks!
