### ISSUE TITLE
Date is not getting substituted in custom index name in Elasticsearch

### ISSUE THREAD

**Issue by balan2010** [uken/fluent-plugin-elasticsearch#449]
#### Problem
index_name not getting created as expected in Elasticsearch 6.3.0

Configuration:

<match logtest>
        @id elasticsearch
        @type elasticsearch
        @log_level info
        include_tag_key true
        host "#{ENV['OUTPUT_HOST']}"
        port "#{ENV['OUTPUT_PORT']}"
        index_name fluentd.${tag}.%Y%m%d
</match>

Index Name on ES : "fluentd.logtest.%y%m%d"

Expected Index name : "fluentd.logtest.20180505"

#### Using Fluentd and ES plugin versions

* OS version
* Fluentd v1.1.0
* ES plugin 2.4.1
* ES version 6.3.0

**Comment by balan2010** [comment]
Figured it out 
had to use logstash_prefix to set my custom index name.

**Comment by Siete-F** [comment]
> 
> 
> Figured it out
> had to use logstash_prefix to set my custom index name.

Hi, would it be possible to elaborate on that a bit more? So what is the working format?
What I find strange is that the plugin uses the name 'logstash' while the 'logstash' application has nothing to do with it (as far as I understand).
Thanks in advance.

**Comment by kumkumsharma** [comment]
You need to include following in <match> tag and it will result an index with name "fluentd-20200510" (fluentd-yyyymmdd).
  index_name fluentd
  type_name fluentd
  logstash_format true
  logstash_prefix fluentd
  logstash_dateformat %Y%m%d

**Comment by thepoppingone** [comment]
Still facing the issue, when I used a diff index name from logstash the index doesnt get captured by elasticsearch even though logs say that its sending succesfully
