### ISSUE TITLE
pushing to elasticsearch, random issues with kube-apiserver audit logs

### ISSUE THREAD

**Issue by billiaz** [uken/fluent-plugin-elasticsearch#452]
#### Problem

My Fluent D throws random exception when parsing auditlog of kube-apiserver
example:
```
[warn]: dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch" location=nil tag="kube-apiserver-audit" time=2018-07-28 23:15:39.000000000 +0000 record={"kind"=>"Event", "apiVersion"=>"audit.k8s.io/v1beta1", "metadata"=>{"creationTimestamp"=>"2018-07-28T23:15:39Z"}, "level"=>"Request", "auditID"=>"e86aa05a-8ef4-4df3-852d-d166d8c1f0e3", "stage"=>"ResponseComplete", "requestURI"=>"/api/v1/nodes/master2/status?timeout=10s", "verb"=>"patch", "user"=>{"username"=>"system:node:master2", "groups"=>["system:nodes", "system:authenticated"]}, "sourceIPs"=>["195.201.138.121"], "objectRef"=>{"resource"=>"nodes", "name"=>"master2", "apiVersion"=>"v1", "subresource"=>"status"}, "responseStatus"=>{"metadata"=>{}, "code"=>200}, "requestObject"=>{"status"=>{"$setElementOrder/conditions"=>[{"type"=>"NetworkUnavailable"}, {"type"=>"OutOfDisk"}, {"type"=>"MemoryPressure"}, {"type"=>"DiskPressure"}, {"type"=>"PIDPressure"}, {"type"=>"Ready"}], "conditions"=>[{"lastHeartbeatTime"=>"2018-07-28T23:15:39Z", "type"=>"OutOfDisk"}, {"lastHeartbeatTime"=>"2018-07-28T23:15:39Z", "type"=>"MemoryPressure"}, {"lastHeartbeatTime"=>"2018-07-28T23:15:39Z", "type"=>"DiskPressure"}, {"lastHeartbeatTime"=>"2018-07-28T23:15:39Z", "type"=>"PIDPressure"}, {"lastHeartbeatTime"=>"2018-07-28T23:15:39Z", "type"=>"Ready"}], "images"=>[{"names"=>["docker.io/rook/ceph@sha256:c6dd35b680bb51ac3cd3496d69a43f8e4b57fbd3333e0eebc58939b895c7d55a", "docker.io/rook/ceph:v0.8.0-15.g986e930", "docker.io/rook/ceph:master"], "sizeBytes"=>259812635}, {"names"=>["docker.io/rook/ceph@sha256:42378847b49092f858b7345a9d72d20c7e9175f1634ecafd8d19946036cfb3ba", "docker.io/rook/ceph:v0.8.0-21.gadd4bd2"], "sizeBytes"=>236045745}, {"names"=>["k8s.gcr.io/hyperkube@sha256:f500aefa0ae532538052751314148185c0304a55d635ac375e56c14358756ae4", "k8s.gcr.io/hyperkube:v1.11.1"], "sizeBytes"=>189811506}, {"names"=>["docker.io/fluent/fluentd-kubernetes-daemonset@sha256:fd130ef5a2a1582cd96d4ca780c089e1ab8c9ab0047b9c1bfd56f0d7e7918344", "docker.io/fluent/fluentd-kubernetes-daemonset:v1.2-debian-elasticsearch"], "sizeBytes"=>76552906}, {"names"=>["gcr.io/stackdriver-agents/stackdriver-metadata-agent@sha256:1a719672ccdd064e28c1adf78ef527eba87370405af5282cbb056b7b5a189a25", "gcr.io/stackdriver-agents/stackdriver-metadata-agent:0.2-0.0.19-1"], "sizeBytes"=>63248522}, {"names"=>["docker.io/onlabnl/fluentd-es@sha256:e3f2bb2c2ad75b5241bb2b345fecb9661de3267b0ff35ad3057cdb4a243f4a8b", "docker.io/onlabnl/fluentd-es:1.2.3"], "sizeBytes"=>51542496}, {"names"=>["k8s.gcr.io/fluentd-elasticsearch@sha256:a54e7a450c0bdd19f49f56e487427a08c50f99ea8f8846179acf7d4182ce1fc0", "k8s.gcr.io/fluentd-elasticsearch:v2.2.0"], "sizeBytes"=>50588374}, {"names"=>["docker.io/weaveworks/weave-kube@sha256:3c45b339ab2dc9c11c9c745e44afce27806dc1d8ecd1da84a88deb36756ac713", "docker.io/weaveworks/weave-kube:2.4.0"], "sizeBytes"=>37012556}, {"names"=>["docker.io/fluent/fluentd-kubernetes-daemonset@sha256:808cf5c6b9ee12f26099345f6be5bd18af0f1f69200de8272c2c7f25e0aa3559", "docker.io/fluent/fluentd-kubernetes-daemonset:elasticsearch"], "sizeBytes"=>35614753}, {"names"=>["docker.io/weaveworks/weave-kube@sha256:b3af3b8a1b02bc474535e546aeb8a4ce8cfafbeffa3ef6f6cf5fb87ec4c4be4c", "docker.io/weaveworks/weave-kube:2.3.0"], "sizeBytes"=>29771027}, {"names"=>["docker.io/weaveworks/weave-npc@sha256:715b03e14874355f1f793f7bc11d843a00b390b2806bd996f1e47e8acb1020aa", "docker.io/weaveworks/weave-npc:2.4.0"], "sizeBytes"=>13399418}, {"names"=>["docker.io/weaveworks/weave-npc@sha256:f240d7b4f3fce679366dd9509247aa7249f8f4d67c5d99a82c93a23324c4dff3", "docker.io/weaveworks/weave-npc:2.3.0"], "sizeBytes"=>13089204}, {"names"=>["docker.io/metallb/speaker@sha256:10779d01d5a207b2500ce72f99d591462b2bc9b47479dde8957632c9262266bd", "docker.io/metallb/speaker:v0.7.1"], "sizeBytes"=>11216180}, {"names"=>["docker.io/prom/node-exporter@sha256:55302581333c43d540db0e144cf9e7735423117a733cdec27716d87254221086", "docker.io/prom/node-exporter:v0.16.0"], "sizeBytes"=>8290040}, {"names"=>["k8s.gcr.io/pause@sha256:f78411e19d84a252e53bff71a4407a5686c46983a2c2eeed83929b888179acea", "k8s.gcr.io/pause:3.1"], "sizeBytes"=>317164}]}}, "requestReceivedTimestamp"=>"2018-07-28T23:15:39.520559Z", "stageTimestamp"=>"2018-07-28T23:15:39.537951Z", "annotations"=>{"authorization.k8s.io/decision"=>"allow", "authorization.k8s.io/reason"=>""}}
```

Not all events but many

#### Steps to replicate

Use this config to gather Audit logs of kube api server

```
    <source>
      @id kube-apiserver-audit.log
      @type tail
      format json
      path /var/log/kubernetes/apiserver-audit.log
      pos_file /var/log/fluentd-kube-apiserver-audit.log.pos
      time_key timestamp
      time_format %Y-%m-%dT%H:%M:%SZ
      tag kube-apiserver-audit
    </source>
```
Source and elastic config:

```
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level error
      include_tag_key true
      host elasticsearch.default
      port 9200
      logstash_format true
      user fluentd
      password ay7aevojoeRee5pe
      logstash_prefix fluent
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 3
        flush_interval 60s
        retry_forever
        retry_max_interval 30
        overflow_action block
      </buffer>
    </match>
```

Full gem list:
```
activesupport (5.2.0)
addressable (2.5.2)
bigdecimal (1.2.8)
concurrent-ruby (1.0.5)
cool.io (1.5.3)
did_you_mean (1.0.0)
dig_rb (1.0.1)
domain_name (0.5.20180417)
elasticsearch (6.1.0)
elasticsearch-api (6.1.0)
elasticsearch-transport (6.1.0)
excon (0.62.0)
faraday (0.15.2)
ffi (1.9.25)
fluent-plugin-detect-exceptions (0.0.11)
fluent-plugin-elasticsearch (2.11.3, 2.10.5)
fluent-plugin-kubernetes_metadata_filter (2.1.2)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-prometheus (1.0.1)
fluent-plugin-systemd (1.0.1)
fluentd (1.2.3, 1.2.2)
http (0.9.8)
http-cookie (1.0.3)
http-form_data (1.0.3)
http_parser.rb (0.6.0)
i18n (1.0.1)
io-console (0.4.5)
json (1.8.3)
kubeclient (1.1.4)
lru_redux (1.1.0)
mime-types (3.1)
mime-types-data (3.2016.0521)
minitest (5.11.3, 5.9.0)
msgpack (1.2.4)
multi_json (1.13.1)
multipart-post (2.0.0)
net-telnet (0.1.1)
netrc (0.11.0)
oj (3.6.3)
power_assert (0.2.7)
prometheus-client (0.8.0)
psych (2.1.0)
public_suffix (3.0.2)
quantile (0.2.1)
rake (10.5.0)
rdoc (4.2.1)
recursive-open-struct (1.0.0)
rest-client (2.0.2)
serverengine (2.0.6)
sigdump (0.2.4)
strptime (0.2.3)
systemd-journal (1.3.2)
test-unit (3.1.7)
thread_safe (0.3.6)
tzinfo (1.2.5)
tzinfo-data (1.2018.5)
unf (0.1.4)
unf_ext (0.0.7.5)
yajl-ruby (1.4.0)
```

Boot log is clean no complains or logging

**Comment by cosmo0920** [comment]
What did Elasticsearch cluster or container complain about this issue?
Could you show us your ELasticsearch's log without sensitive information?

**Comment by alkar** [comment]
I'm seeing the same error message. From what I can tell, some elements of the log structure are variable ([like the various status fields](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/audit/v1beta1/types.go#L112). For instance, `responseObject.status` can be either an object or a string. From what I understand ES will autodetect type based on what it receives first and then if any of the following documents do not match the schema, it rejects them with a 400.

I'm not very familiar with ES so I still have not figured out how to work around this but I believe the reason is the above.

**Comment by cosmo0920** [comment]
Thanks for digging this issue!

> I'm seeing the same error message. From what I can tell, some elements of the log structure are variable (like the various status fields). For instance, responseObject.status can be either an object or a string. From what I understand ES will autodetect type based on what it receives first and then if any of the following documents do not match the schema, it rejects them with a 400.

Yep, ES rejects a value which differs from data schema.

If `ResponseStatus *metav1.Status` is assumed to integer type, we might able to avoid 400 error with re-index with `ResponseStatus *metav1.Status` to be string type.

**Comment by alkar** [comment]
In my case, it's indexed as a string which causes all the records that have an object status be rejected. Ideally, this should be fixed upstream by changing to a fixed structure for the audit log messages. For the time being are there any workarounds? Perhaps asking ES to *not* index the culprit fields?

**Comment by discordianfish** [comment]
I'm evaluating EFK (on k8s, based on the fluentd-es cluster addon) right now as an alternative to managed solutions and just ran into the same error, just with a regular pod.

It looks like fluentd also parses my application errors. Maybe the exception logger logs some fields differently, causing this schema conflict.

I don't really understand how this is suppose to work. It's not even that my schema changed, just that whatever ES guessed isn't the right schema. And even if this would match, what do I do if I ever need to change the schema?

I should possibly look into disabling the parsing of the logs themselves. I'd be good for now with just raw logs tagged with the kubernetes metadata.

**Comment by cosmo0920** [comment]
> For the time being are there any workarounds? Perhaps asking ES to not index the culprit fields?

Maybe you can remove or modify the culprit field with record_transformer.

**Comment by discordianfish** [comment]
@cosmo0920 Thanks, I'll look into this. But is it possible to prevent it from parsing the log field completely? E.g only give me the raw log output of a container as string and only have the metadata as fields?

**Comment by cosmo0920** [comment]
Currently, no way to prevent it.

**Comment by alkar** [comment]
@discordianfish you should be able to just process the log entries as strings I suppose but that defeats the whole purpose of ES.

Have you come up with a workaround?

**Comment by xanonid** [comment]
A workaround is to use own dynamic mapping templates where the `enabled` setting for problematic fields like `requestObject` are set to `false`. The other fields are then still searchable.

**Comment by alkar** [comment]
@xanonid I'm currently trying to get it to work that way, using `enabled` as you say. Having some issues with top-level fields but I'll post the template here for reference when complete.

**Comment by alkar** [comment]
This is the template I've gone with:
```
    {
      "template": "logstash-*",
      "mappings": {
        "fluentd": {
          "dynamic_templates": [
            {
              "default_no_index": {
                "path_match": "^.*$",
                "path_unmatch": "^(@timestamp|kubernetes_cluster|auditID|level|stage|requestURI|sourceIPs|metadata|objectRef|user|verb)(\\..+)?$",
                "match_pattern": "regex",
                "mapping": {
                  "index": false,
                  "enabled": false
                }
              }
            }
          ]
        }
      }
    }
```
Hope this helps!

**Comment by waseem-h** [comment]
@alkar I'm facing the same issue. However, I only have a kibana index in my elasticsearch cluster. Kibana manages the `logstash-*` index. Is there a way I can apply the above template in that case?

**Comment by gangseok514** [comment]
In my cases, audit log had too much fields. so I increased field limit of elasticsearch

**Comment by mindw** [comment]
Run into the same problem which has two parts:
1. ES rejecting logs with variable fields.
After playing with the above suggested methods I came up with the following filer which retained the info without causing errors:
```
<filter kube-apiserver-audit>
  @id kube_api_audit_normalize
  @type record_transformer
  auto_typecast false
  enable_ruby true
  <record>
    host "#{ENV['K8S_NODE_NAME']}"
    responseObject ${record["responseObject"].nil? ? "none": record["responseObject"].to_json}
    requestObject ${record["requestObject"].nil? ? "none": record["requestObject"].to_json}
    origin kubernetes-api-audit
  </record>
</filter>
```
1. duplicate entries (the audit log is picked up from all k8s apiservers in a HA config)
Here I used the plugin's advice on custom hash:
```
<filter kube-apiserver-audit>
  @id kube_api_audit_normalize
  @type record_transformer
  auto_typecast false
  enable_ruby true
  <record>
    host "#{ENV['K8S_NODE_NAME']}"
    responseObject ${record["responseObject"].nil? ? "none": record["responseObject"].to_json}
    requestObject ${record["requestObject"].nil? ? "none": record["requestObject"].to_json}
    origin kubernetes-api-audit
  </record>
</filter>

<match **>
...
      # prevent duplicate log entries and updates
      id_key _hash
      remove_keys _hash
      write_operation create

      include_tag_key false
...
</match
```
Hope this helps.

**Comment by JeremyMarshall** [comment]
The above worked for us, but don't forget to roll over your index if using a pipeline!

**Comment by cosmo0920** [comment]
Great news. :smile:

Is anyone interested in adding FAQs for this issue?
This issue is too complicated to solve ES plugin alone.
But @mindw shows that using `record_transformer`, `elasticsearch_genid`, and `genhashvalue` plugins, and some ES plugin configuration combanation can solve this issue.

I think that this issue should close when adding FAQ for this phenomenon.

**Comment by cosmo0920** [comment]
I've addeda FAQ for this issue:
https://github.com/uken/fluent-plugin-elasticsearch/pull/614

**Comment by cosmo0920** [comment]
I'm closing this due to https://github.com/uken/fluent-plugin-elasticsearch/pull/614.
