### ISSUE TITLE
Connection for sending data to Elasticsearch does not use keep-alive / persistent option

### ISSUE THREAD

**Issue by BernhardBerbuir** [uken/fluent-plugin-elasticsearch#454]
#### Problem

At the NGinX logs I see a lot (several per second) of the following messages:

    2018/08/01 09:56:04 [info] 14#0: *3068590 client 10.1.2.3 closed keepalive connection

After looking at the [source code](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch_dynamic.rb#L49), it seems that the connection is not created with keep-alive / persistent option. excon [documentation](https://github.com/excon/excon#getting-started) states that the default for connection is __non-persistent__.

#### Steps to replicate

Use an NGinX in front of Elasticsearch, set log level to `info`

#### Expected Behavior or What you need to ask

A keep-alive / persistent connection should be used for sending data to Elasticsearch via NGinX

#### Using Fluentd and ES plugin versions

* OS version: CentOS Linux release 7.5.1804 (Core)
* Installed gems:

        activesupport (5.2.0)                                                                                                                                                                        
        addressable (2.5.2)                                                                                                                                                                          
        bigdecimal (1.3.0)                                                                                                                                                                           
        concurrent-ruby (1.0.5)                                                                                                                                                                      
        cool.io (1.5.3)                                                                                                                                                                              
        did_you_mean (1.1.0)                                                                                                                                                                         
        dig_rb (1.0.1)                                                                                                                                                                               
        domain_name (0.5.20180417)                                                                                                                                                                   
        elasticsearch (6.1.0)                                                                                                                                                                        
        elasticsearch-api (6.1.0)                                                                                                                                                                    
        elasticsearch-transport (6.1.0)
        excon (0.62.0)
        faraday (0.15.2)
        fluent-plugin-elasticsearch (2.10.3)
        fluent-plugin-kubernetes_metadata_filter (2.0.0)
        fluent-plugin-prometheus (1.0.1)
        fluent-plugin-record-reformer (0.9.1)
        fluentd (1.2.3)
        http (0.9.8)
        http-cookie (1.0.3)
        http-form_data (1.0.3)
        http_parser.rb (0.6.0)
        i18n (1.0.1)
        io-console (0.4.6)
        json (2.0.4)
        kubeclient (1.1.4)
        lru_redux (1.1.0)
        mime-types (3.1)
        mime-types-data (3.2016.0521)
        minitest (5.11.3)
        msgpack (1.2.4)
        multi_json (1.13.1)
        multipart-post (2.0.0)
        netrc (0.11.0)
        openssl (2.0.5)
        prometheus-client (0.8.0)
        psych (2.2.2)
        public_suffix (3.0.2)
        quantile (0.2.1)
        rdoc (5.0.0)
        recursive-open-struct (1.0.0)
        rest-client (2.0.2)
        serverengine (2.0.7)
        sigdump (0.2.4)
        strptime (0.2.3)
        thread_safe (0.3.6)
        tzinfo (1.2.5)
        tzinfo-data (1.2018.5)
        unf (0.1.4)
        unf_ext (0.0.7.5)
        yajl-ruby (1.4.1)

* ES version: 5.6

**Comment by emaste-r** [comment]
how to check weather use keep-alive  or not with tcpdump?
