### ISSUE TITLE
insert data to elasticsearch through logstash

### ISSUE THREAD

**Issue by sergeyglazyrindev** [uken/fluent-plugin-elasticsearch#457]
#### Problem

We want to be able to send records to elasticsearch through logstash. We have a working system (non containerized openstack)and in our case logstash does some changes in fields, etc and we want to get the same behaviour in our new containerized openstack with fluentd logging. When I point plugin to send data to the logstash port, it simply doesn't work and in records no message about connection to elasticsearch (and it's obvious that it's not elasticsearch connection)

#### Expected Behavior or What you need to ask

We'd like to have an option to send data using simple http post request. It may be configured with extra option: connection_type: elasticsearch|logstash|etc and then based on this option we will send data using different ways
Would be such thing interesting for community ? We are able to do such changes in plugin.

**Comment by cosmo0920** [comment]
Fluentd can send its events through tcp connection with out_forward plugin.

openstack -> Fluentd (out_forward with time_as_integer option) -> logstash (in: tcp, codec: logstash-codec-fluent, out: elasticsearch) -> Elasticsearch

**Comment by cosmo0920** [comment]
> option: connection_type: elasticsearch|logstash|etc and then based on this option we will send data using different ways

IMO, :-1: for this.
Because, in Fluentd world, plugins should not be monolithic but be like heterogeneous or motley.

**Comment by cosmo0920** [comment]
I decide decline this request.

> Because, in Fluentd world, plugins should not be monolithic but be like heterogeneous or motley.
