### ISSUE TITLE
Allow daily splitting of index even if not logstash

### ISSUE THREAD

**Issue by tommiatplayfish** [uken/fluent-plugin-elasticsearch#47]
I might be using fluentd to pass some json-formatted data to ES, but it's definitely not in syslog/logstash format (wouldn't make any sense anyway)

So I did a quick hack to allow splitting, would be nice if this was done in more ...adjustable way. I don't want indexes split at UTC but other people might:

        config_param :split_daily, :bool, :default => false

        if @split_daily
          target_index = @index_name + Time.at(time).strftime("%Y-%m-%d")
        else
        target_index = @index_name
        end

**Comment by dterror** [comment]
If I understood correctly, logstash format does what you need. It doesn't require a specific schema. At this point, it simply does what you need: partitions the indexes by day.
