### ISSUE TITLE
Fluentd is not sending @timestamp, when we set value logstash_format false and index parameter used

### ISSUE THREAD

**Issue by jain108shubhamtbt** [uken/fluent-plugin-elasticsearch#472]
{
"_index" : "fluentd-2014.10.18",
"_type" : "fluentd",
"_id" : "id",
"_score" : 3.0,
"_source" : {
"message" : "some log message",
"@timestamp" : "time"
}
}
I mention "path" in input config, then why fluentd is not sending path with above json data.

Need : data like that format

{
"_index" : "fluentd-2014.10.18",
"_type" : "fluentd",
"_id" : "id",
"_score" : 3.0,
"_source" : {
"message" : "some log message",
"path" : "path"
"@timestamp" : "time"
"host" : "hostname"
}
}

we need host, @timestamp, path by default.
How to get it. is there any configure

**Comment by cosmo0920** [comment]
This does not contain issue template.
I’m closing then.

**Comment by jain108shubhamtbt** [comment]
where is issue template, how to fill, please suggest.
