### ISSUE TITLE
Plugin 2.11.9+ fails when connecting to Humio ES bulk API

### ISSUE THREAD

**Issue by kapodes** [uken/fluent-plugin-elasticsearch#478]
#### Problem
Fluentd fails to start because of plugin error when used with Humio's ElasticSearch Bulk API ingress.

`2018-10-04 11:31:11 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"humio.domain.domain", :port=>9200, :scheme=>"http", :user=>"***", :password=>"obfuscated", :path=>"/api/v1/dataspaces/sandbox/ingest/elasticsearch"}
/usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.11.9/lib/fluent/plugin/out_elasticsearch.rb:265:in 'detect_es_major_version': undefined method '[]' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.11.9/lib/fluent/plugin/out_elasticsearch.rb:212:in 'configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.5/lib/fluent/plugin.rb:164:in 'configure'`

#### Steps to replicate

    <match kube.**>
      @type elasticsearch
      scheme http
      host humio.domain.domain
      port 9200
      path /api/v1/dataspaces/sandbox/ingest/elasticsearch
      user token-token
      password none
      logstash_format true
    </match>

#### Expected Behavior or What you need to ask

Fluentd starts and sends logs to Humio.

#### Using Fluentd and ES plugin versions

FROM fluent/fluentd:v1.2
RUN fluent-gem install fluent-plugin-elasticsearch (2.11.10)

My researches led to this commit which changes error handling
https://github.com/uken/fluent-plugin-elasticsearch/commit/10b760a501adbb32414b75a484d21f651803b24b

I think that Humio API doesn't provide version so plugin fails to resolve major version and fails.

If I install version 2.11.8 that doesn't contain this commit everything works fine.

**Comment by cosmo0920** [comment]
Thanks for your report!
It's perfect report! :100:
I'll write a patch to fix this.

**Comment by cosmo0920** [comment]
I've released v2.11.11.
Could you check it?

**Comment by kapodes** [comment]
`2018-10-17 14:14:21 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"humio.***", :port=>9200, :scheme=>"http", :user=>"***", :password=>"obfuscated", :path=>"/api/v1/dataspaces/sandbox/ingest/elasticsearch"}
2018-10-17 14:14:21 +0000 [warn]: #0 Could not connect Elasticsearch or obtain version. Assuming Elasticsearch 5.`
started successfully!
