### ISSUE TITLE
ES - Wrong sort on timestamp

### ISSUE THREAD

**Issue by bappr** [uken/fluent-plugin-elasticsearch#480]
#### Problem
Running this query against ES
```
{
  "sort": [{ "@timestamp": "asc" }],
}
```
will result of
`"@timestamp": "2018-10-09T08:24:04.102859754+00:00"` being above `"2018-10-09T08:24:04.102846296+00:00"`. Seems that the microseconds are not taken into account.

#### Steps to replicate
In fluentd:
```
<source>
  @id fluentd-containers.log
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  read_from_head true
  format json
</source>
<filter **>
  @type kubernetes_metadata
  cache_ttl 1
  watch true
</filter>
<filter kinto.argo.build.**>
  @type record_transformer
  enable_ruby true
  <record>
    @target_index ${record["kubernetes"]["labels"]["app"]}-${time.strftime("%Y.%m.%d")}
  </record>
</filter>
<match kinto.**>
  @type copy
  <store>
    @id elasticsearch_kubernetes
    @type elasticsearch
    @log_level info
    include_tag_key true
    host "#{ENV['OUTPUT_HOST']}"
    port "#{ENV['OUTPUT_PORT']}"
    logstash_format true
    target_index_key @target_index
    index_name fallback
    <buffer>
      @type file
      path /var/log/fluentd-buffers/kubernetes.system.buffer
      flush_mode interval
      retry_type exponential_backoff
      flush_thread_count 2
      flush_interval 5s
      retry_forever
      retry_max_interval 30
      chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
      queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
      overflow_action block
    </buffer>
  </store>
  # <store>
  #   @type stdout
  # </store>
</match>
```

#### Using Fluentd and ES plugin versions

* Fluentd v0.12 or v0.14/v1.0
`fluentd 1.2.2`
* ES plugin 2.x.y or 1.x.y
`fluent-plugin-elasticsearch (2.10.5)`
* ES version (optional)
`6.2.4`

**Comment by cosmo0920** [comment]
Could you share more example log or data?

**Comment by cosmo0920** [comment]
Or, when you use a ES template, please share it with us.

**Comment by cosmo0920** [comment]
Ah, I got it.
Your examples have nanosecond precision timestamp which are same in millisecond precision.
Elasticsearch cannot handle microsecond precision time or nanosecond precision time.
This is exoected Elasticsearch behavior for now.
See also: https://github.com/elastic/elasticsearch/issues/10005

**Comment by bappr** [comment]
That s exactly what I found out and I was gonna reply you. :-(
Thanks a lot :-)
Will try to deal with it differently!
