### ISSUE TITLE
Time pattern in index_name is not expanded

### ISSUE THREAD

**Issue by martin21** [uken/fluent-plugin-elasticsearch#481]
#### Problem
Time patterns aka "%Y%m%d" in index_name is not expanded. Are these not supported anymore

References:
- https://docs.fluentd.org/v1.0/articles/out_elasticsearch documents `index_name` option and mentions these patterns there.
- https://github.com/uken/fluent-plugin-elasticsearch uses these patterns in examples, but does not document `index_name` option

#### Steps to replicate
Have some input.

Output it to Elasticsearch:

```
<match *.*>
  @type elasticsearch
  hosts tuxdebian40:9200,tuxdebian41:9200,tuxdebian42:9200
  index_name fluentd.${tag}.%Y%m%d
</match>
```

Results in

```
 
# esindices fluent
health status index                       uuid                   pri rep docs.count docs.deleted store.size pri.store.size
[…]
green  open   fluentd.fluent.info.%y%m%d  Rzo0iZ9TTlytlh1asyiwmw   5   1          1            0      9.5kb          4.7kb
green  open   fluentd.fluent.warn.%y%m%d  Qdx1Kt0JTX2zjMOC8w3Iqg   5   1         11            0     36.5kb         18.2kb
> > 
```
(esindices is a shell function I use for listing indices via curl request to Elasticsearch cluster)

```
function esindices {
        if [[ -z $1 ]]; then
                curl -sXGET "$ESHOST:9200/_cat/indices?v" | (read -r; printf "%s\n" "$REPLY"; sort -k3 ) 
        else
                curl -sXGET "$ESHOST:9200/_cat/indices?v" | (read -r; printf "%s\n" "$REPLY"; sort -k3 ) | egrep "health|$1"
        fi
}
```

#### Expected Behavior or What you need to ask
I expect the time pattern to be expanded (or the documentation to be updated).

#### Using Fluentd and ES plugin versions
* OS version: Debian 9.5
* Fluentd 1.2.6
* ES plugin 2.11.11
* ES version: 6.4.2

**Comment by martin21** [comment]
Looks good. Thank you.

**Comment by cosmo0920** [comment]
https://github.com/fluent/fluentd-docs/pull/575 is merged. Closing.
