### ISSUE TITLE
fluentd creates old elasticsearch indexes at startup

### ISSUE THREAD

**Issue by dlbarduzzi** [uken/fluent-plugin-elasticsearch#482]
#### Problem

First, I wanted to say that I don't think this is a problem. It's me looking for help.

Every time I re-deploy fluentd into kubernetes, it starts creating old elasticsearch indexes. By that I mean:

for example today's date: 2018/10/10
fluentd creates an index name "fluentd-2018.10.10"  which is expected. But then it also creates old index dates such as "fluentd-2018.10.09, "fluentd-2018.10.08", "fluentd-2018.10.07 ..."

I believe this is because some containers still have logs from those dates. What I would like to happen is to only create the current's date index.

#### Steps to replicate

Explained above. Deploy fluentd and check elasticsearch indexes.

#### Expected Behavior or What you need to ask

Create only current date's index, and not older indexes.

#### Using Fluentd and ES plugin versions

* Fluentd v0.12

**Comment by cosmo0920** [comment]
> I believe this is because some containers still have logs from those dates. What I would like to happen is to only create the current's date index.

Yep. You are right.
Some old date logs still present log or buffer in your environment.

If it is forcibly to set current date, it breaks time order for log.

**Comment by dlbarduzzi** [comment]
Thanks @cosmo0920 for the reply.

> If ES plugin forcibly sets current date, it breaks time order for log.

Can you please clarify the statement above? And if I'm forwarding logs to ES, wouldn't that be recommended so that I know the amount of logs per day, the index clean up process is easier, etc...

**Comment by cosmo0920** [comment]
> > If ES plugin forcibly sets current date, it breaks time order for log.
> 
> Can you please clarify the statement above? And if I'm forwarding logs to ES, wouldn't that be recommended so that I know the amount of logs per day, the index clean up process is easier, etc...

If the logs are stored in Fluentd buffer:

|log|
|---|
[log 0 at day before yesterday]
[log 1 at yesterday]
[log 2 at today]

then Fluentd suddenly received logs in no particular order:

|log|
|---|
[log 2 at today]
[log 0 at day before yesterday]
[log 1 at yesterday]

Current ES plugin implementation works as:



|log|inserted index|
|---:|:---|
[log 2 at today]|`logstash-<today date>`
[log 0 at day before yesterday]|`logstash-<day before yesterday>`
[log 1 at yesterday] | `logstash -<yesterday date>`


But your suggestion causes:

|log|inserted index|
|---:|:---|
[log 2 at today]| `logstash-<today date>`
[log 0 at day before yesterday] | `logstash-<today date>`
[log 1 at yesterday]| `logstash-<today date>`


Is this expected your behavior?

**Comment by dlbarduzzi** [comment]
Well, what I'm expecting is the following...

1. I deploy fluentd into kubernetes today (current date 10/12/2018)
    - my fluentd config has the following:
        * read_from_head false : which should only read logs from now (and not logs already logged)
2. Create only index from today, such as logstash-2018.10.12

And that is about it. Tomorrow, obviously create a new index logstash-2018.10.13 and so on (which is what currently happens).

But that is not the case. If I deploy today with the settings above, I see old indexes created. Indexes from days/weeks/and even months ago. That causes an issue at the startup because these indexes have shards and it is just a lot for the ES nodes to handle all at the same time. I need to keep deleting these old indexes (since I don't care about them) until everything stabilizes and no more old indexes get created (I don't know why).

**Comment by cosmo0920** [comment]
I can't help you because I don't know your Fluentd configuration.
Fluentd itself handles data at runtime.
So I can only say just a general theory for Fluentd mechanism.

**Comment by dlbarduzzi** [comment]
Here is my Fluentd configuration.

### fluent.conf ###

@include kubernetes.conf
@include systemd.conf

<match **>
  @type elasticsearch
  @id out_es
  include_tag_key true
  host "#{ENV['ES_HOST']}"
  port "#{ENV['ES_PORT']}"
  scheme "#{ENV['ES_SCHEME']}"
  ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
  ssl_version TLSv1_2
  reload_connections false
  logstash_prefix "fluentd-#{ENV['ES_INDEX_NAME']}"
  logstash_format true
  request_timeout 60
  slow_flush_log_threshold 60.0
  num_threads 8
  flush_interval 5s
  buffer_chunk_limit 4M
  buffer_queue_limit 100
  max_retry_wait 30
  disable_retry_limit false
  buffer_queue_full_action drop_oldest_chunk
</match>

### kubernetes.conf ###

<match fluent.**>
  @type null
</match>

<source>
  @type tail
  @id in_tail_container_logs
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-containers.log.pos
  tag kubernetes.*
  read_from_head false
  format json
  time_format %Y-%m-%dT%H:%M:%S.%NZ
</source>

<filter kubernetes.**>
  @type kubernetes_metadata
  @id filter_kube_metadata
</filter>

### systemd.conf ###

<source>
  @type systemd
  @id in_systemd_kubelet
  filters [{ "_SYSTEMD_UNIT": "kubelet.service" }]
  pos_file /var/log/fluentd-journald-kubelet.pos
  strip_underscores true
  read_from_head false
  tag kubelet
</source>

**Comment by dlbarduzzi** [comment]
I figured out what the problem was. The issue is that when fluentd runs, it creates the pos_file to keep track of last time it read the file. If you remove fluentd, in my case deleting the daemonset from kubernetes, the pos_files are not deleted from /var/log/ location. And when fluentd is added again to kubernetes, it reads these old pos_files creating old indexes. To fix my issue, I simply add a command to my daemonset payload to delete any fluentd- related file inside /var/log/ before deploying fluentd.

**Comment by SayonB** [comment]
@ghost would you mind posting what exactly you did?
