### ISSUE TITLE
how to merge two records according id

### ISSUE THREAD

**Issue by like-inspur** [uken/fluent-plugin-elasticsearch#484]
There are two records in service log like this:
2018-10-10 unique_id_01  start
2018-10-10 unique_id_01  stop success
I want to merge two records into one record like this:
2018-10-10 unique_id_01  start stop success
But however I config any value for write_operation in elasticsearch output, it doen't work as I expect. The config of elasticsearch output is like this:
```aconf
<match **>
  @id elasticsearch
  @type elasticsearch
  @log_level info
  include_tag_key true
  host 158.158.21.174
  port 9200
  logstash_format true
  logstash_prefix td
  validate_client_version true
  reconnect_on_error true
  flush_interval 1s
  id_key id
  write_operation upsert
</match>
```

**Comment by like-inspur** [comment]
thank you, I ask fluent-plugin-concat community for help

**Comment by cosmo0920** [comment]
Delegated to https://github.com/fluent-plugins-nursery/fluent-plugin-concat/issues/60.
And found a solution: https://github.com/fluent-plugins-nursery/fluent-plugin-concat/issues/60#issuecomment-430837787. Closing.
