### ISSUE TITLE
Decoupling the custom template and rollover index creation

### ISSUE THREAD

**Issue by kumaravel29** [uken/fluent-plugin-elasticsearch#485]
#### Problem
Feature Request - As per the feature request #355, we had added the capability to customize the templates. But the creation of rollover index(without any option to customize it) was introduced in it.
So whenever the customize template feature was used, default rollover was created in the format <logstash-default-{now/d}-000001> and a deflector alias **<template_name>-current** was assigned to the index.
I am trying to decouple this, so that users can have an option to customize this.
...

#### Expected Behavior or What you need to ask
I wanted this to be decoupled and give an option to the user for creation of index and customize it.
...

#### Using Fluentd and ES plugin versions

* OS version - Linux
* Fluentd v0.12 or v0.14/v1.0 
_gem 'fluentd' version '1.2.0'_
* ES plugin 2.x.y or 1.x.y
_{"time":"2018-10-15 13:02:00 +0530","level":"info","message":"parsing config file is succeeded path=\"/etc/td-agent/td-agent.conf\""}
{"time":"2018-10-15 13:02:01 +0530","level":"info","message":"starting fluentd-1.2.0 pid=591 ruby=\"2.1.10\""}
{"time":"2018-10-15 13:02:01 +0530","level":"info","message":"spawn command to main:  cmdline=[\"/opt/td-agent/embedded/bin/ruby\", \"-Eascii-8bit:ascii-8bit\", \"/usr/sbin/td-agent\", \"--log\", \"/var/log/td-agent/td-agent.log\", \"--daemon\", \"/var/run/td-agent/td-agent.pid\", \"--under-supervisor\"]"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluent-mixin-plaintextformatter' version '0.2.6'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluent-plugin-copy_ex' version '0.1.0'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluent-plugin-elasticsearch' version '2.11.11'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluent-plugin-forest' version '0.3.3'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluent-plugin-kafka' version '0.6.1'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluent-plugin-mongo' version '0.8.1'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluent-plugin-rewrite-tag-filter' version '1.5.6'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluent-plugin-s3' version '0.8.5'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluent-plugin-scribe' version '0.10.14'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluent-plugin-td' version '0.10.29'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluent-plugin-td-monitoring' version '0.2.3'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluent-plugin-webhdfs' version '0.7.1'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"gem 'fluentd' version '1.2.0'"}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"adding match pattern=\"**.baminsights\" type=\"copy_ex\""}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"adding source type=\"http\""}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"starting fluentd worker pid=1365 ppid=1353 worker=0","worker_id":0}
{"time":"2018-10-15 13:02:04 +0530","level":"info","message":"fluentd worker is now running worker=0","worker_id":0}_

* ES version (optional) - **5.6.4**

**Comment by cosmo0920** [comment]
Shipped in v2.12.0.
