### ISSUE TITLE
Fluentd Can not reach Elasticsearch cluster

### ISSUE THREAD

**Issue by qasmi** [uken/fluent-plugin-elasticsearch#491]
#### Problem

I try to redirect traffic from fluentd to elasticsearch. My cluster elasticsearch use searchguard, so in fluentd conf I use :

 ```
<match apache.access>
  @type             elasticsearch
  host                monitoring-elasticsearch-sg-....net
  scheme            https
  ssl_verify        false
  user              fluentd
  password          changeme
  port              80
  index_name        fluent.web-01
  type_name         _doc #For ES 7
  include_timestamp true
  utc_index         true
  flush_interval 1s
  buffer_chunk_limit 1M
  buffer_queue_limit 512
  <buffer>
    flush_interval 1s
    buffer_chunk_limit 1M
    buffer_queue_limit 512
  </buffer>
</match>
```

But i have this error message : 

2018-10-22 14:20:16 +0200 [warn]: #0 failed to flush the buffer. retry_time=10 next_retry_seconds=2018-10-22 14:20:15 +0200 chunk="578d009d721014c4d22a5b76f701c617" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"https\", :user=>\"fluentd\", :password=>\"obfuscated\"})!"

in sg_roles.yml :
fluentd_user:
        cluster:
          - ES_INPUT
        indices:
          "*fluentd-*":
            "*":
              - INDEX_OWNER

Any help please ?

**Comment by cosmo0920** [comment]
Please try to use `ssl_version TLSv1_2`.

**Comment by qasmi** [comment]
It work !! thanks @cosmo0920 for help
