### ISSUE TITLE
Question about id_key parameter

### ISSUE THREAD

**Issue by sergeyarl** [uken/fluent-plugin-elasticsearch#498]
Hi! 

I have a question regarding id_key parameter. However I'm not sure if I'm asking this in the right place. I'm sorry if I don't . 

The documentation says that when Fluentd reemits events that failed to be indexed/ingested, with auto-generated IDs it might cause duplicate records in ES index. One of the ways to solve this is to generate static IDs for the records before sending them to ES.

We use this approach, but as our index gets bigger we recently started to notice big amount of disk read ops (up to 10k) on our ES data nodes.  While the amount of writes is rather low (100-200 ops). 

ES [documentation says](https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-indexing-speed.html)  that using manually generated IDs reduces the performance of indexing. As ES 

> needs to check whether a document with the same id already exists within the same shard, which is a costly operation and gets even more costly as the index grows.

So as I understand this is our case. Therefore my question is - if there are other ways to avoid having duplicates without using IDs generated by Fluentd. 

Thank you! 

Regards,
Sergey

**Comment by cosmo0920** [comment]
> So as I understand this is our case. Therefore my question is - if there are other ways to avoid having duplicates without using IDs generated by Fluentd.

AFAIK, using generated IDs is only way to prevent duplicate records.

**Comment by cosmo0920** [comment]
No response. Closing.
