### ISSUE TITLE
How to filter some logs that i do not want send it to es

### ISSUE THREAD

**Issue by reesechou2014** [uken/fluent-plugin-elasticsearch#499]
#### Problem
How to filter some logs that i do not want send it to es?
some like the logs 2 days ago 

...

#### Using Fluentd and ES plugin versions

* OS version
centos7.2

* Fluentd v1.0
  
* ES plugin 2.x

**Comment by cosmo0920** [comment]
How about using [filter_grep](https://docs.fluentd.org/v1.0/articles/filter_grep), which is built-in plugin, in your Fluentd pipeline?

**Comment by cosmo0920** [comment]
ES plugin does not have filtering funtionality because we dno't like monolithic plugin.

**Comment by reesechou2014** [comment]
> How about using [filter_grep](https://docs.fluentd.org/v1.0/articles/filter_grep), which is built-in plugin, in your Fluentd pipeline?

ok,i think that's the right way to get what i want ,thank you
