### ISSUE TITLE
multi threads don't take effect

### ISSUE THREAD

**Issue by like-inspur** [uken/fluent-plugin-elasticsearch#505]
I have configed num_threads 5 in output elasticsearch config, but I want to know how to verify there are multi threads running, and what benefit of doing this?

**Comment by cosmo0920** [comment]
Ruby multithreading works only I/O situation. 
Otherwise, MRI blocks threads and permit to run one thread. `num_threads` works well in many retrying to push events into Elasticsearch.

**Comment by cosmo0920** [comment]
@like-inspur Is this issue still active?

**Comment by like-inspur** [comment]
No, thank you
