### ISSUE TITLE
Return statement ignores rollover setup when overwrite is true

### ISSUE THREAD

**Issue by jahmad-fareportal** [uken/fluent-plugin-elasticsearch#506]
https://github.com/uken/fluent-plugin-elasticsearch/blob/573c39a757c2ef11449e327daa88f87e9961c4ee/lib/fluent/plugin/elasticsearch_index_template.rb#L76

**Comment by cosmo0920** [comment]
Fill the issue template and write an issue description, please.

**Comment by kumaravel29** [comment]
I will check on this and try fixing it.

**Comment by cosmo0920** [comment]
Patch is merged. Closing.
