### ISSUE TITLE
Does fluent-plugin-elasticsearch create @timestamp field?

### ISSUE THREAD

**Issue by jwp23** [uken/fluent-plugin-elasticsearch#508]
We're trying to resolve issues with our watches in elasticsearch not catching critical log errors. Our theory is there is a delay between the timestamp in the log file and the time the log is ingested. To do this, I use the regexp parser to add a "logtime" field and do not specify a time key. Does fluentd automatically add a @timestamp field or will that be done on the elasticsearch side? I looked at the documentation at https://github.com/uken/fluent-plugin-elasticsearch#time_key_format but wasn't sure if it meant fluentd generated the timestamp field.

My configuration is below:

Parser:
```
<parse>
    @type multiline
    format multiline
    format_firstline /\d{8} \d{2}:\d{2}:\d{2}\.\d{9}/
    format1 /^(?<logtime>\d{8} \d{2}:\d{2}:\d{2}\.\d{9}) (?<sev>-[a-zA-Z]-) (?<msg>.*)/
  </parse>
```
Elasticsearch output (it's an ansible template):
```
<match .**>
  @type elasticsearch
  host xxx
  port 9243
  scheme https
  user {{ elastic_fluentd_user }}
  password {{ elastic_fluentd_password }}
  logstash_format true
  logstash_prefix xxx-{{ es_env_prefix }}
  type_name _doc
  <buffer>
    @type memory
    flush_thread_count 4
    flush_interval 3s
    chunk_limit_size 2m
    queue_limit_length 4096
  </buffer>
</match>
```

**Comment by cosmo0920** [comment]
Fluentd's core only managements its plugins.
`@timestamp` will be added by ES plugin:
https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L550-L562

**Comment by jwp23** [comment]
Thanks for the explanation. It looks like I would need to set up an ingest node if I want elasticsearch to add a timestamp at the point it ingests the logs.
