### ISSUE TITLE
Support ILM (Index Lifecycle Management) for Elasticsearch 7.x

### ISSUE THREAD

**Issue by cosmo0920** [uken/fluent-plugin-elasticsearch#540]
#### Problem

This is a future task.

ref: https://www.elastic.co/guide/en/elasticsearch/reference/6.x//getting-started-index-lifecycle-management.html

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

**OR**

Provide example config and message

#### Expected Behavior or What you need to ask

ILM is supported.

#### Using Fluentd and ES plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others?
* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
* ES plugin 2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
  * ES plugin 3.x
* ES version (optional)
  ES 7.x or later

**Comment by prestonvanloon** [comment]
How far in the future are we talking about? :)

**Comment by cosmo0920** [comment]
No ETA yet. Patch is welcome. :sweat:

**Comment by jeffdesc** [comment]
Hey @cosmo0920, where are you stuck with this? What are you missing to proceed?
We're waiting for this to deploy a pretty big ES cluster with input from td-agent. Everything is done, except we really need ILM.

Hope you could take some time for this, if you need any information, I am happy to provide it to you.

**Comment by cosmo0920** [comment]
Currently, I'm not working on this.
Nothing patch exists.
If you can write a patch, I can review it.

**Comment by cosmo0920** [comment]
Currently, elasticsearhc-ruby cannot not call ILM endpoint.
I've created a PR to implement ILM API at elasticsearch-xpack gem:
https://github.com/elastic/elasticsearch-ruby/pull/729

**Comment by jeffdesc** [comment]
Great @cosmo0920, thanks for jumping on it!

**Comment by cosmo0920** [comment]
ILM patch is here: https://github.com/uken/fluent-plugin-elasticsearch/compare/support-index-lifecycle-management
Note that this patch depends on https://github.com/elastic/elasticsearch-ruby/pull/729.

**Comment by fpytloun** [comment]
I am trying your patch and I think deflector_alias (and application_name) should support `${tag}` placeholder in the same manner as we can use `index_name` without rollover capability. That would require to create rollover index and template on the fly and move the code into `process_message`.

Otherwise currently only single index naming is supported.

**Comment by fpytloun** [comment]
Ok, so I tried to update your patch to add support for placeholders for on-the-fly creation of templates and rollover indexes: https://github.com/uken/fluent-plugin-elasticsearch/pull/651

Tested and so far it seems to be working nicely using this configuration:
```
        <store>
          @type elasticsearch
          @id out_es
          @log_level info
          id_key _hash
          remove_keys _hash
          log_es_400_reason true
          include_tag_key true
          include_timestamp true
          time_key time
          flatten_hashes true
          flatten_hashes_separator .
          index_name fluentd-${tag}
          # Rollover index configuration
          rollover_index true
          deflector_alias fluentd-${tag}
          index_prefix fluentd
          application_name ${tag}
          index_separator "."
          index_date_pattern "now/d"
          enable_ilm true
          # Policy is already created by init container so fluentd will skip it's creation
          ilm_policy_id fluentd-policy
          ilm_policy {}
          # Template name is not used if ilm is in effect but it's mandatory parameter
          template_name fluentd
          template_file /fluentd/etc/fluentd-template.json
          customize_template {"<<index_prefix>>": "fluentd"}

          host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
          port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
          reconnect_on_error true
          reload_on_failure true
          type_name fluentd
          request_timeout 120s
          <buffer tag,time>
            @type memory
            timekey 60
            total_limit_size 128M
            chunk_limit_size 32M
            overflow_action block
            chunk_full_threshold 0.9
            compress gzip       # text,gzip
            flush_mode interval
            flush_interval 10s
            flush_at_shutdown true
            flush_thread_count 4
          </buffer>
        </store>
```

**Comment by SergeyD** [comment]
@fpytloun 

It is not clear for me who will actually responsible for index rollover when using ILM + rollover_index parameters of this plugin and why should I specify both.

If I have ILM functionality available via X-Pack then it is Elasticsearch itself will rollover index according to ILM policies installed by `fluent-plugin-elasticsearch` plugin.

If I have NO ILM via X-Pack available, then rollover is reposnsibility of `fluent-plugin-elasticsearch` plugin itself and is driven by following it's params (`rollover_index`, `index_date_pattern`, `deflector_alias`, ...). I assume this done by periodically calling rollover API.

In your example there is `index_date_pattern` param used. From the plugin documentation for this param:

```Overriding this changes the rollover time period. Setting "now/w{xxxx.ww}" would create weekly rollover indexes instead of daily.```

As I understood this states that plugin will rollover indices according to `index_date_pattern`.
But at the same time ILM policy defines rollover period by itself:

```
PUT _ilm/policy/datastream_policy   
{
  "policy": {                       
    "phases": {
      "hot": {                      
        "actions": {
          "rollover": {             
            "max_size": "50GB",
            "max_age": "30d"
          }
        }
      }
    }
  }
}
```

**Comment by fpytloun** [comment]
Yes, ILM will rollover index but it does not create initial index with alias. That's what rollover feature is for.

So you are using this plugin's rollover capability to create index (eg. `fluentd-000001`) and alias (eg. `fluentd`) pointing to that index if it does not already exist, that's it.

ILM is then used to do actions on indexes (eg. perform rollover) when conditions are met. It basically does the same thing as Curator does but as a native part of Elasticsearch. You can use rollover feature without ILM but you need to have custom script or other way how to perform rollover based on some conditions. As mentioned this plugin doesn't handle rollover by itself, it only creates rollover-enabled indexes (with alias pointing to it and index template), and creates ILM policy if enabled.

**Comment by SergeyD** [comment]
@fpytloun thanks for the explanation!
