### ISSUE TITLE
Http_backend problem

### ISSUE THREAD

**Issue by chenjienn** [uken/fluent-plugin-elasticsearch#541]
after adding the option `http_backend typhoeus` to config , i got error and failed to start fluentd, the error message is 

```
2019-02-11 18:15:03 +0800 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2019-02-11 18:15:03 +0800 [error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="You must install typhoeus gem."
```
but i have already install typhoeus through the `gem install 'typhoeus'` 
#### Using Fluentd and ES plugin versions

* CentOS 7
* td-agent 3.2.1

**Comment by cosmo0920** [comment]
Could you try `td-agent-gem install typhoeus`?

**Comment by chenjienn** [comment]
thanks a lot ,  and I suggest this shell script should be added to document

**Comment by cosmo0920** [comment]
There is already Official documents about this issue: https://docs.fluentd.org/v1.0/articles/plugin-management

But this document is difficult to find from Google or Baidu or another search engine?

**Comment by chenjienn** [comment]
emmmm......  maybe we can suggest this in the td-agent.log , when user see the log first they probably  use `gem install 'xxx' ` but not the `td-agent-gem install xxx`

**Comment by cosmo0920** [comment]
Ummm..., some users use vanilla Fluentd instead of td-agent.
Just describing to use td-agent for typhoeus installation may be inappropriate.

**Comment by chenjienn** [comment]
and .....  could you help me resolve another problem related to #534 ?
