### ISSUE TITLE
How to send message to different index depending on the message field

### ISSUE THREAD

**Issue by chenjienn** [uken/fluent-plugin-elasticsearch#546]
#### Problem

when i use logstash before,  i can use the grok syntax to read some of the message field value and send to different index in es, such as:

```
if "com.test.log" ==[json][class] {
            elasticsearch{
                user=>"elastic"
                password=>"xxx"
                hosts=>["10.23.33.35:19200","10.23.33.36:19200","10.23.33.37:19200"]
                index=>"test-log-%{+YYYY.MM.dd}"
            }
}
```

#### Using Fluentd and ES plugin versions

* CentOS 7
* td-agent 3.2.1

**Comment by cosmo0920** [comment]
In Fluentd world, we cannot use message field value to handle specific situation for now.

But, we can handle filed value with built-in placeholders:

```aconf
<match xxx>
  @type elasticsearch
  with_transporter_log true
  verify_es_version_at_startup false
  default_elasticsearch_version 6
  hosts 10.18.1.53:9200,10.18.1.54:9200
  user elastic
  password 123456
  scheme http
  http_backend typhoeus
  ssl_verify false
  # replace with a value of record['a']['some']['field']['key']
  logstash_prefix ${$.a.some.field.key}
  <buffer tag, $.a.some.field.key> # Also can handle a nested field key
    @type memory
    timekey 10s
    timekey_wait 0s
  </buffer>
  flush_interval 10s
  logstash_format true
  time_key @timestamp
  logstash_prefix xxx
  target_index_key es_index
</match>
```

**Comment by chenjienn** [comment]
you mean i could only use the field value to replace some part of the index name , but can not handle it as a expression

**Comment by cosmo0920** [comment]
> you mean i could only use the field value to replace some part of the index name , but can not handle it as a expression

Yup. Only using ES plugin, we cannot handle it as an expression.

**Comment by chenjienn** [comment]
emmm..... do you know other plugins that can resolve this problem ？

**Comment by cosmo0920** [comment]
To implement similar usability, it need to use Fluentd DSL configuration syntax.
But it is not well-documented and I'm not familiar with DSL syntax.... :confounded:

**Comment by chenjienn** [comment]
do you familiar with fluentd-prometheus ? i have a question .....

**Comment by cosmo0920** [comment]
No, I don't. You should send your question into [Fluentd community slack](https://slack.fluentd.org) or [mailing list](https://groups.google.com/forum/?fromgroups#!forum/fluentd).
