### ISSUE TITLE
Use Placeholder to set index name

### ISSUE THREAD

**Issue by chenjienn** [uken/fluent-plugin-elasticsearch#548]
#### Problem

when i use placeholder to set `logstash_prefix` , the message can not write into es
the error is : 

`2019-02-18 11:17:49 +0800 [warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch" location=nil tag="xxxx-applog-busi-server" time=2019-02-18 11:04:20.165000000 +0800 record={"app-info"=>"busi-server,c8e8b663164d646f,c8e8b663164d646f,false", "pid"=>"78356", "thread"=>"io-9008-exec-10", "class"=>"c.c.c.interceptor.MvcMethodLogAdvice", "level"=>"aroundAdvice", "line-num"=>"46", "message"=>"\xE6\x96\xB9\xE6\xB3\x95[EacQuartzController.exeAsyndealJob]\xE7\xBB\x93\xE6\x9D\x9F\xEF\xBC\x8C\xE8\x80\x97\xE6\x97\xB6:4ms\xEF\xBC\x8C\xE5\x9B\x9E\xE5\x8F\x82:{\"code\":\"0000\",\"codeMsg\":\"\xE6\x97\xA0\xE6\x95\xB0\xE6\x8D\xAE(\xE5\xBC\x82\xE6\xAD\xA5\xE8\xB4\xA6\xE6\x95\xB0\xE6\x8D\xAE)\",\"data\":null,\"page\":null} "}`

the dest fluentd setting is : 

```
<match *>
  @type copy
  <store>
  @type elasticsearch
  with_transporter_log true
  verify_es_version_at_startup false
  default_elasticsearch_version 6
  hosts 10.18.1.53:9200,10.18.1.54:9200
  user elastic
  password 123456
  scheme http
  http_backend typhoeus
  ssl_verify false
  <buffer>
    @type memory
    timekey 10s
    timekey_wait 0s
    flush_thread_count 4
  </buffer>
  flush_interval 10s
  logstash_format true
  time_key @timestamp
  logstash_prefix ${tag}
  </store>
  <store>
    @type prometheus
    <metric>
      name fluentd_output_status_num_records_total
      type counter
      desc The total number of outgoing records
      <labels>
        tag ${tag}
        hostname ${hostname}
      </labels>
    </metric>
  </store>
</match>
```

#### Using Fluentd and ES plugin versions

* CentOS 7
* td-agent 3.2.1
* ES 6.5.4

**Comment by chenjienn** [comment]
by the way ,  the index has been created and could be searched in kibana

**Comment by chenjienn** [comment]
i found the problem .....

**Comment by ZMMWMY** [comment]
> i found the problem .....

could you tell me how to custom index name by placeholder.i can not find the document of the placeholder
