### ISSUE TITLE
Question about posting message to es

### ISSUE THREAD

**Issue by chenjienn** [uken/fluent-plugin-elasticsearch#549]
#### Problem

after i set `action.auto_create_index : false` and corresponding index template in es, the fluentd can not post messages to es and the error is : 

`{"index":{"_index":"applog-busi-server-2019.02.18","_type":"fluentd","_id":null,"status":404,"error":{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"applog-busi-server-2019.02.18","index_uuid":"_na_","index":"applog-busi-server-2019.02.18"}}}`

but i can use `PUT applog-busi-server-2019.02.18` to create index , so when the index is restrict like this, how could the fluentd post messages ?

#### Using Fluentd and ES plugin versions

* CentOS 7
* td-agent 3.2.1
* ES 6.5.4

**Comment by cosmo0920** [comment]
I guess that you can use `create` operation for restricted indices.
Note that this operation requires to add unique `_id` field.

```aconf
<filter **>
  @type elasticsearch_genid
  hash_id_key _hash    # storing generated hash id key (default is _hash)
</filter>
<match **>
  @log_level debug
  @type elasticsearch
  id_key _hash # specify same key name which is specified in hash_id_key
  remove_keys _hash # Elasticsearch doesn't like keys that start with _
  with_transporter_log true
  write_operation create
  # and other configurations
</match>
```

ref: https://github.com/uken/fluent-plugin-elasticsearch#generate-hash-id

**Comment by chenjienn** [comment]
the create and index(default) operation, who is more efficient when collect huge number of log from other source

**Comment by cosmo0920** [comment]
I have no idea about your question. :'(
I have no Elasticsearch cluster for huge amount of data....

**Comment by chenjienn** [comment]
ok  thank you anyway
