### ISSUE TITLE
Deprecated field [template] used.

### ISSUE THREAD

**Issue by KristianZH** [uken/fluent-plugin-elasticsearch#551]
#### Problem
I  have a lot of warnings `Deprecated field [template] used, replaced by [index_patterns]`

#### Steps to replicate

Deploy a fluentd which talks with elasticsearch

#### Expected Behavior or What you need to ask
I expect not to get this type of warnings.

#### Using Fluentd and ES plugin versions

* OS version Debian GNU/Linux 9
* Bare Metal or within Docker or Kubernetes or others? Docker image in Kubernetes
* Fluentd fluentd 1.3.3
* ES plugin 3.0.2
* ES version (optional) 6.5.4

**Comment by cosmo0920** [comment]
Could you show us your using Elasticsearch template?
It seems that it is caused by your Elasticsearch template.

ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html
