### ISSUE TITLE
Index template does not work with dynamic host

### ISSUE THREAD

**Issue by ialidzhikov** [uken/fluent-plugin-elasticsearch#565]
#### Problem
Index template does not work with dynamic host.

#### Steps to replicate

1. Start fluentd with conf:

```
<source>
  @type forward
  @id forward_input
</source>

<match elastic.**>
  @id elasticsearch_dynamic
  @type elasticsearch

  host ${key1}

  port 9200
  logstash_format true

  reconnect_on_error true

  template_name gardener
  template_file /Users/i331370/default.template

  <buffer tag, key1, time>
    @type memory
  </buffer>
</match>
```

2. Ensure that the start fails with:

```
2019-03-21 15:34:12 +0200 [error]: #0 unexpected error error_class=URI::InvalidURIError error="bad URI(is not URI?): http://${key1}:9200"

// stacktrace omitted
```

#### Expected Behavior or What you need to ask
Index template to work with dynamically configured host and to create the index template for each host.

#### Using Fluentd and ES plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others?
* Fluentd v0.12 or v0.14/v1.0 - `fluentd 1.4.0`
  * paste result of ``fluentd --version`` or ``td-agent --version``
* ES plugin 3.x.y/2.x.y or 1.x.y - `3.3.3`
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
* ES version (optional)
* ES template(s) (optional)

**Comment by cosmo0920** [comment]
This is because index template installation is working on #configure phase not #write phase.
This is plugin limitation and we cannot handle #configure phase because dynamic host feature is non-determistic on #configure.

Do you have any incredible solution?
I have no idea for now. :cry:

**Comment by cosmo0920** [comment]
This is known issue for elasticsearch_dynamic plugin.
out_elasticsearch inherits ES dynamic plugin behavior.
If we want to install ES templates, we should specify ES host candidates in #configura phase.

**Comment by cosmo0920** [comment]
I decided that this issue should be treated as "plugin limitation".
Fluentd philosophy requests that plugin's `#configure` phase handles deterministic configurations and validates its configurations.

But to support your feature requests, it needs to supply host candidates information to extract placeholders with created metadata where `#configure`.

If this feature will be supported, `#configure` phase too long to wait Fluentd boot, I think.
(In your usecase seems to have to handle 100+ servers.)

**Comment by cosmo0920** [comment]
@ialidzhikov I decided that this issue should be treated as "plugin limitation" for now.
If we want to support this feature, we should move template installation within `#write` method.
what do you think of it?

**Comment by ialidzhikov** [comment]
@cosmo0920 , thank you for your PR, at least now we will have a good message.
One approach is to have the mapping `host` => `index_template_created` and if for the given host the index template is not created, then the logic will apply the template. This approach will cause a performance pitfall for the initial write. And also this mapping should be synced between the different fluentd instances - this actually makes implementation of this feature request hard. 
WDYT? We should also check if logstash or any other log aggregator supports this scenario and if yes, how they do it.

**Comment by cosmo0920** [comment]
> One approach is to have the mapping `host` => `index_template_created` and if for the given host the index template is not created, then the logic will apply the template. This approach will cause a performance pitfall for the initial write.

Yes. I'm thinking of this approach.

> And also this mapping should be synced between the different fluentd instances - this actually makes implementation of this feature request hard.

Fluentd multiple worker feature uses fork (In Windows, it uses spawn).
https://github.com/treasure-data/serverengine
I'm not familiar with ServerEngine implementation for now.



> We should also check if logstash or any other log aggregator supports this scenario and if yes, how they do it.

Yep. I'll check logstash-output-elasticsearch implementation.

**Comment by cosmo0920** [comment]
logstash-output-elasticsearch doesn't handle placeholders in hosts.
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/common_configs.rb#L98
`hosts` config is validated with `LogStash::Util::SafeURI`:
https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/config/mixin.rb#L508-L513 
https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/util/safe_uri.rb#L9

So, hosts parameter denies to handle `%`, `{`, `}` characters.
