### ISSUE TITLE
ElasticsearchDynamic not handling ES errors 

### ISSUE THREAD

**Issue by tscolari** [uken/fluent-plugin-elasticsearch#568]
#### Problem

There's no error handling when using the `elasticsearch_dynamic` plugin.
The normal `elasticsearch` one goes through the `ElasticsearchErrorHandler` class, but the dynamic one just goes to limbo when something gets a 400 from the ES cluster.

This makes it impossible to monitor the index and detect conflict errors that might be happening at the moment.

#### Steps to replicate

* use `elasticsearch_dynamic`
* have a `<label @ERROR>` just to report error events that got emitted 
* try to push some obvious conflicting entries that would cause ES to reject the entry:
```
{ "hello": 1000 }
{ "hello": 10.40 }
{ "hello": "not really" }
{ "hello": { "what" : "yes" } }
{ "hello": true }
```
* there're no error events getting emitted because how the dynamic plugin handles them: https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch_dynamic.rb#L214-L216

#### Expected Behavior or What you need to ask

* To have error events being emitted like they are in the `elasticsearch` plugin itself: https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L685-L688

#### Using Fluentd and ES plugin versions

* We're using the latest version of the plugin.

## Fix example:

We did a dirty and fast workaround to handle the errors in the dynamic here (https://github.com/gocardless/fluent-plugin-elasticsearch/commit/270644a4d3adba22e515cfca10583ec11db9bed7). It's not ideal but it looked like dynamic and non-dynamic have diverged quite a bit in the `send_bulk` method.

**Comment by cosmo0920** [comment]
Is there any lack of out_elacticsearch from out_elasticsearch_dynamic?
I want to mark elasticsearch_dynamic as deprecated in the near future.

**Comment by tscolari** [comment]
@cosmo0920 I believe the main reason for us to use dynamic is so we can set the `logstash_prefix` based on some kubernetes labels from the log line:

```
logstash_prefix logstash-${(record || Hash.new).dig('kubernetes', 'namespace_labels', 'logstash') || 'platform'}
```

Do you have a suggestion to get around this using `out_elasticsearch` instead?

**Comment by cosmo0920** [comment]
With record_modifier, we can handle your use case:

```aconf
<filter **>
  @type record_modifier
  <record>
    _logstash_prefix logstash-${record['kubernetes']['namespace_labels']['logstash'] rescue 'platform'}
  </record>
</filter>
<match **>
  @type elasticsearch
  logstash_format true
  host your_es_host
  logstash_prefix ${_logstash_prefix}
  remove_keys _logstash_prefix # Elasticsearch doesn't like keys that start with _
  <buffer tag, _logstash_prefix>
    @type memory # or memory
    # bra bra 
  </buffer>
</match>
```

**Comment by tscolari** [comment]
So I've tried this config but it seems that the value of `${_logstash_prefix}` only gets evaluated when using the `elasticsearch_dynamic`.

Do you know why?
If using only `elasticsearch` it actually prefixes the string "${_logstash_prefix}" to the index, instead of evaluating its content.

**Comment by cosmo0920** [comment]
Fluentd build-in placeholders depends on chunk metadata to extract placeholders.
Could you check buffer section attribute usage?

```aconf
  <buffer tag, _logstash_prefix> # This section and attributes are needed.
    @type memory # or memory
    # bra bra 
  </buffer>
```

**Comment by tscolari** [comment]
That worked!
Do you know where I can find more documentation about the attributes `<buffer>` takes?
Fluentd documentation seems to be very scarce, I'm mostly interested if there're any side-effects for this, like performance for example (we use buffer @type file).

**Comment by cosmo0920** [comment]
You can find buffer section's parameter documentaion here:
https://docs.fluentd.org/v1.0/articles/buffer-section

**Comment by cosmo0920** [comment]
> Fluentd documentation seems to be very scarce, I'm mostly interested if there're any side-effects for this, like performance for example (we use buffer @type file).

Ah, performance impact for buffer attributes is not documented for now....

I've heared that buffer chunk handling may increase I/O, but it depends on users' Fluentd configuration.... :confounded:

**Comment by cosmo0920** [comment]
No response and seems to be resolved. Closing.
