### ISSUE TITLE
Warning from comparing DEFAULT_TYPE_NAME_ES_7x with type_name

### ISSUE THREAD

**Issue by haoyujiang1994** [uken/fluent-plugin-elasticsearch#574]
#### Problem

I have tried to install fluent 1.3 and ES 7.0.0 on gcp. I have set the type_name to "_doc" in fluent config map while logs from daemonSet of fluent keep showing the warning "Detected ES 7.x or above: `_doc` will be used as the document `_type`.".

#### Steps to replicate

The config file of fluent:

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-logging
  labels:
    app: fluentd
data:
  fluent.conf: |
    @include kubernetes.conf

    <match **>
      @type elasticsearch
      @id out_es
      @log_level info
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
      user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
      password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
      reload_connections false
      reconnect_on_error true
      reload_on_failure true  
      logstash_format true
      include_timestamp true
      type_name _doc
      <buffer>
        flush_thread_count "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT'] || '8'}"
        flush_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL'] || '5s'}"
        chunk_limit_size "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE'] || '2M'}"
        queue_limit_length "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH'] || '32'}"
        retry_max_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL'] || '30'}"
      </buffer>
    </match>

kubernetes.conf: |
    <match fluent.**>
      @type null
    </match>

    <source>
      @type tail
      @id in_tail_container_logs
      path "/var/log/containers/*.log"
      pos_file "/var/log/fluentd-containers.log.pos"
      tag "kubernetes.*"
      read_from_head true
      <parse>
        @type "json"
        time_format "%Y-%m-%dT%H:%M:%S.%NZ"
        time_type string
      </parse>
    </source>

#### Expected Behavior or What you need to ask

The warning logs should disappear.

#### Using Fluentd and ES plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others?
* Fluentd v1.3
  * paste result of ``fluentd --version`` or ``td-agent --version``
* ES plugin 3.x.y/2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
* ES version (optional)
* ES template(s) (optional)

**Comment by cosmo0920** [comment]
Already suppressing this warning on master:
https://github.com/uken/fluent-plugin-elasticsearch/commit/0f97de80e5e2161709bb3f26f0129734341e11ac

Could you report this issue for fluentd-kubernetes-daemonset repository?

**Comment by haoyujiang1994** [comment]
Thanks for your reply.
I have tried again while the logs of daemonSet on gcp still keep showing this warning log. I wonder if I set the wrong type_name or @type_name is different from type_name?

**Comment by cosmo0920** [comment]
Issue had been solved. Closing.
