### ISSUE TITLE
Elastic Failover Instance Configuration incase the primary is down, so that fluentd can output the data

### ISSUE THREAD

**Issue by nreddy67** [uken/fluent-plugin-elasticsearch#576]
Hi,

Currently I was not able to see any documentation around the failover mechanism implementation to route the traffic to secondary Elastic instance from Fluentd in case of any primary Elastic failover . Can you please point me to the necessary fluentd.conf that allows this configuration.

As I see through the below documentation, it only allows RR. But my usecase is that secondary should receive the traffic from fluentd only when primary is down.

----------------------------
hosts host1:port1,host2:port2,host3:port3
You can specify multiple Elasticsearch hosts with separator ",".

If you specify multiple hosts, this plugin will load balance updates to Elasticsearch. This is an elasticsearch-ruby feature, the default strategy is round-robin.

**Comment by nreddy67** [comment]
Hi,

I have tried the following, but doesn't seem to be working.

<match sample.**>
  @type elasticsearch
  host host.docker.internal
  port 9200
  index_name sample
  type_name book
  id_key bookNumber
    <secondary>
      @type elasticsearch
      host 96749bbc7dd34f278e2f9be4dc280b34.xyz.abc.com
      user elastic
      password XXXXX
        port 9200
        index_name sample
        type_name book
        id_key bookNumber
    </secondary>

</match> 

Can you suggest me the best feasible option.

**Comment by cosmo0920** [comment]
> I have tried the following, but doesn't seem to be working.

Could you show your failure log?
I cannot debug with only the above sentence. Thanks.

**Comment by cosmo0920** [comment]
> If you specify multiple hosts, this plugin will load balance updates to Elasticsearch. This is an elasticsearch-ruby feature, the default strategy is round-robin.

elasticsearch-ruby and ES plugin does not have fail-over functionality.
Fluentd's secondary output feature will be fired after many flushing failures.
If you want to emulate ES server failover, I recommend to use nginx as a load balancer:
https://gist.github.com/ZoidQC/20b234cec147a4413117b929302d95b7

**Comment by cosmo0920** [comment]
Fluentd will support service discovery feature:
https://github.com/fluent/fluentd/pull/2541
fluent-plugin-elasticsearch v3.6 or later will support this.
