### ISSUE TITLE
EHOSTUNREACH error: fluentd tries to connect to pod IP in a different k8s cluster

### ISSUE THREAD

**Issue by zenglian** [uken/fluent-plugin-elasticsearch#577]
**Version:**
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch.yaml

**Configuration:**
default, except the `elasticsearchhost = external-es.example.com:9200` . Note this elasticsearch runs in a **different** kubernetes cluster (nodeport).

**Sympton**
After running several hours, it got below error. When it occurs, no more events received by elastich search.
2019-04-16 07:08:24 +0000 [warn]: #0 [out_es] failed to flush the buffer. retry_time=1476 next_retry_seconds=2019-04-16 07:08:52 +0000 chunk="5869ecacffab3db4a502b2a3a36515b1" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>"external-es.example.com", :port=>9200, :scheme=>"http", :path=>""}): No route to host - connect(2) for 10.244.0.111:9200 (Errno::EHOSTUNREACH)"

**Diagnosis**
The log message shows "No route to host - connect(2) for 10.244.0.111:9200" --- but "10.244.0.111" is the pod IP of ES which is in a different cluster, which is unreachable of course. It should use external IP to connect ES.

**Comment by zenglian** [comment]
Looks like it's a known issue https://github.com/uken/fluent-plugin-elasticsearch#reload_connections

**Comment by cosmo0920** [comment]
@zenglian Could you specify `reload_connection` as false and related parameters?
https://github.com/uken/fluent-plugin-elasticsearch#stopped-to-send-events-on-k8s-why

**Comment by kannanvr** [comment]
@zenglian , How did you resolve this issue? I am also having a setup similar as mentioned above. I am also facing the similar issue .
Please help me to resolve the issue
