### ISSUE TITLE
Remove the 'message' key and get nested value

### ISSUE THREAD

**Issue by ISChetverikov** [uken/fluent-plugin-elasticsearch#578]
#### Problem

Hi,
When I am writing to the elasticsearch all required json message is wrapped with key 'message'. I want to get rid of it. Stdout output has formatter called single_value, which works fine, but elastic_dynamic plugin has no such formatter in use. Can you tell me, please, how can I get such a behavior with this plugin?

{"message":"Hello from Fluentd!"} => "Hello from Fluentd!"

#### My config:
```
<source>
	@type http
	port 9880
	bind 0.0.0.0
</source>

<source>
	@type tail
	path C:/Trash/**/log-%Y%m%d.txt
	pos_file C:/Trash/fluentd.pos
	refresh_interval 5s
	tag files
	<parse>
		@type json
	</parse>
</source>

<filter rewrited.**>
	@type parser
	key_name record
	reserve_data false
	<parse>
		@type none
	</parse>
</filter>

<label @FLUENT_LOG>
  <match fluent.*>
    @type stdout
  </match>
</label>

<match rewrited.**>
	@type copy	
	<store>                                                 
		@type stdout
		<format>
			@type single_value
			message_key message
		</format>
	</store> 
	<store>
		@type elasticsearch_dynamic
		host kis-mm-stats.avp.ru
		port 9200
		logstash_prefix test #fluentd_${tag_parts[1]}
		logstash_format true
		type_name logevent
		<buffer>
			flush_interval 1s
		</buffer>
		<format>
			@type single_value
			message_key message
		</format>
	</store>
</match>

<match >
  @type rewrite_tag_filter
  <rule>
    key $.source
	pattern /^(\w+)$/
    tag rewrited.$1
  </rule>
</match>

```
#### Using Fluentd and ES plugin versions

* Windows 10
* fluentd 1.2.6
* ES plugin 2.11.11

**Comment by cosmo0920** [comment]
Please use fluent-plugin-record-modifier to remove `message` key:
https://github.com/repeatedly/fluent-plugin-record-modifier#remove_keys

**Comment by cosmo0920** [comment]
> Stdout output has formatter called single_value, which works fine, but elastic_dynamic plugin has no such formatter in use. Can you tell me, please, how can I get such a behavior with this plugin?

ES plugin and ES dynamic plugin does not handle formatter.
Instead, you can use fluent-plugin-record-modifier in your Fluentd pipeline:
https://github.com/repeatedly/fluent-plugin-record-modifier#remove_keys

**Comment by cosmo0920** [comment]
We cannot remove `message` key because ES bulk API request to use x-ndjson(newline delimited json).
This is Elasticsearch bulk API limitation.
