### ISSUE TITLE
How can I send message to different type depending on keys in record

### ISSUE THREAD

**Issue by yanrong1990** [uken/fluent-plugin-elasticsearch#580]
#### Problem

I make the configuration like this:

```
<match my.log>
  @type elasticsearch
  hosts 10.23.xx.xx:9200,10.23.xx.xx:9200,10.23.xx.xx:9200
  flush_interval 10s
  target_index_key es_index
  target_type_key es_type
</match>
```

```
And the input is :
	var data = map[string]string{
		"es_index": "fluentd.dynamic",
		"es_type": "estype",
		"foo":      "bar",
		"hoge":     "hoge"}
```

While the _type is the default value : "fluentd" , not the value I set. And the output is 
```
      {
        "_index" : "fluentd.dynamic",
        "_type" : "fluentd",
        "_id" : "l0wTQ2oBhtT3cdUXXXXX",
        "_score" : 1.0,
        "_source" : {
          "foo" : "bar",
          "hoge" : "hoge"
        }
      },
```

Is there something wrong with my configuration ? Any suggestion will be helpful. Thanks.
...

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

**OR**

Provide example config and message

#### Expected Behavior or What you need to ask

...

#### Using Fluentd and ES plugin versions
CentOS 7
td-agent 3.2.1

* OS version
* Bare Metal or within Docker or Kubernetes or others?
* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
* ES plugin 3.x.y/2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
* ES version (optional)
* ES template(s) (optional)

**Comment by cosmo0920** [comment]
It depends on using ES version.
Do you use Elasticsearch 6?
If you use Elasticsearch 6, you should use fixed `type_name` instead of dynamic `type_name` such as `target_type_key`.
And ES plugin uses default `fluentd` type forcibly.

ref: https://www.elastic.co/guide/en/elasticsearch/reference/6.7/removal-of-types.html

**Comment by yanrong1990** [comment]
Thanks a lot.
Yes,I use the ElasticSearch 6.X and I have changed the configurration .
Besides I want to know ,does all kinds of fluentd-plugin support placeholder? such as:
[https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch.yaml](url)
Thanks a lot.

**Comment by yanrong1990** [comment]
have solved by : 
[](https://github.com/uken/fluent-plugin-elasticsearch/issues/458)

thanks a lot @cosmo0920
