### ISSUE TITLE
can I binding my hostname to index_name or logstash_format ,because I have many vm instances which have same application running

### ISSUE THREAD

**Issue by zffocussss** [uken/fluent-plugin-elasticsearch#594]
#### Problem
I can send logs to es directly,but I can not specify the index name with hostname,as I want to make it unique so that I can do the job on kibana
...

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

**OR**

Provide example config and message
```aconf
<match uwsgi.**>
 @type elasticsearch
 host localhost
 port 9200
 flush_interval 10s
 index_name ${tag}-%Y.%m.%d
 type_name ${tag}-%Y.%m.%d
 logstash_format true
# logstash_prefix ${tag}-"#{Socket.gethostname}"
 logstash_prefix ${tag}
 include_tag_key true
 tag_key @log_name
 <buffer tag, time>
   timekey 1h
 </buffer>
</match>
```
#### Expected Behavior or What you need to ask

...

#### Using Fluentd and ES plugin versions

* OS version
ubuntu 16.04
* Fluentd version
google-fluentd 1.2.5

* ES plugin 3.x.y/2.x.y or 1.x.y
elasticsearch (7.1.0)
elasticsearch-api (7.1.0)
elasticsearch-transport (7.1.0)
fluent-plugin-elasticsearch (3.5.2)

**Comment by cosmo0920** [comment]
How about use `filter_record_modifier` to get hostname and use it?

```aconf
<filter pattern>
  @type record_modifier

  <record>
    hostname "#{Socket.gethostname}"
  </record>
</filter>

<match uwsgi.**>
 @type elasticsearch
 host localhost
 port 9200
 flush_interval 10s
 index_name ${tag}-%Y.%m.%d
 type_name ${tag}-%Y.%m.%d
 logstash_format true
 logstash_prefix ${tag}-${hostname}
 include_tag_key true
 tag_key @log_name
 # Note that hostname chunk_key is needed!
 <buffer tag, time, hostname>
   timekey 1h
 </buffer>
</match>
```

**Comment by cosmo0920** [comment]
@zffocussss ping?

**Comment by cosmo0920** [comment]
No response. Closing.
