### ISSUE TITLE
[Generate Hash ID]「_hash」 is registered at output destination other than Elasticsearch

### ISSUE THREAD

**Issue by taku333** [uken/fluent-plugin-elasticsearch#598]
#### Problem

Hi ,Thank you for always using it.

The other day a problem occurred.
Currently using fluentd to register data in Elasticsearch and other.

At that time, there was something like the following.
「_hash」 is registered at output destination other than Elasticsearch.

It is tough in "fluent-plugin-elasticsearch" to avoid this kind of movement, right?

I read the following source and saw it.

https://github.com/uken/fluent-plugin-elasticsearch/blob/e377f2d9ac136884cde43d0fce08e9672df4c9ba/lib/fluent/plugin/filter_elasticsearch_genid.rb

https://github.com/fluent/fluentd/blob/b593e6f4adb08dd9f2d2fd69f83fe7a6a1514d43/lib/fluent/plugin/filter.rb

#### Steps to replicate

1.Set filter and output as below

※other contains other destinations.

```
<filter aaa>
  @type elasticsearch_genid
  hash_id_key _hash
</filter>

<match aaa>
  type copy
  <store>
    @type other
    ・・・・
    ・・・・
    ・・・・
    </secondary>
  </store>
  <store>
    @type elasticsearch
    ・・・・
    ・・・・
    ・・・・
   </store>
</match>

```

2.Start fluentd!!!

#### Using Fluentd and ES plugin versions

* OS version :CentOs6
* Fluentd v0.12
* ES plugin 1.18.0
* ES version 6.7.1

**Comment by cosmo0920** [comment]
> At that time, there was something like the following.
> 「_hash」 is registered at output destination other than Elasticsearch.
> 
> It is tough in "fluent-plugin-elasticsearch" to avoid this kind of movement, right?

Sorry for being late.
But I didn't understand what you mean in the above sentences.

In addition, what is the plugin related for this issue that you thought? filter_elasticsearch_genid? out_elasticsearch?
In generally speaking, out_elasticsearch does not known the former pipeline plugins.
It just handle events which is in the stream from the previous pipeline.

Pipeline flow control is not for ES plugin role.

BTW, Fluentd v0.12 and ES plugin 1.18.0 is ancient versions. Please check FLuentd v1.6.0 and ES plugin v3.5.2.

**Comment by taku333** [comment]
Thanks for answer!!

Sorry, I am not very good at English, so please write in Japanese.
分かりにくい英語ですみません。

現在上記のconf設定で、Elasticsearchともう一つのデータストアにfluentdよりデータを送っています。

Elasticsearchに登録するデータの重複排除の設定のため、「Generate Hash ID」をREADMEの通りに登録しました。

そしたら、Elasticserachの方のデータは問題ないのですが、もう一つのデータストアに「filter_elasticsearch_genid」で作成した「_hash」が入ってしまいました。（まるで、record_transformerみたいに）

「filter_elasticsearch_genid」側でどうにかできないかと、原因を探るため、下記のソースを読んだのですがどうもこれ以上無理な気がしました

https://github.com/uken/fluent-plugin-elasticsearch/blob/e377f2d9ac136884cde43d0fce08e9672df4c9ba/lib/fluent/plugin/filter_elasticsearch_genid.rb

https://github.com/fluent/fluentd/blob/b593e6f4adb08dd9f2d2fd69f83fe7a6a1514d43/lib/fluent/plugin/filter.rb

この件は、もう一つのデータストアのoutput箇所に問題があり「filter_elasticsearch_genid」では回避不能という認識で正しいでしょうか？

**Comment by cosmo0920** [comment]
> この件は、もう一つのデータストアのoutput箇所に問題があり「filter_elasticsearch_genid」では回避不能という認識で正しいでしょうか？

No, this is your data pipeline issue.
filter_elasticsearch_genid generate unique id into `_hash` key like as record_transformer or record_modifier.
Inseriting mechanism is same as them.

So, if you want to avoid this issue, I recommend to use out_relabel in out_copy and then filter_elasticsearch_genid and out_elasticsearch in the relabeled pipeline as follows:

```aconf
<match aaa>
  type copy
  <store>
    @type other
    ・・・・
    ・・・・
    ・・・・
    </secondary>
  </store>
  <store>
    @type relabel
    @label @ESOUTPUT
   </store>
</match>

<label @ESOUTPUT>
  <filter aaa>
    @type elasticsearch_genid
    hash_id_key _hash
  </filter>
  <match **>
    @type elasticsearch
    # snip
  </match>
</label>
```

I hope this helps.

**Comment by taku333** [comment]
Thanks for answer!!!!

My data pipeline was wrong.
Close this issue.
