### ISSUE TITLE
Multiple indexes per day

### ISSUE THREAD

**Issue by dborysenko** [uken/fluent-plugin-elasticsearch#604]
Firstly thanks for awesome module, we use it and like it a lot.
Now the question, We use elasticsearch plugin to write logs to elasticsearch on a daily basis. Some of our indexes become huge (around billion docs and ~500Gb size a day). Writing to such index becomes challenging. We see high read I/O on data nodes. We suspect elasticsearch_genid makes hard times for elasticsearch, since ES has to make sure doc ID is unique. 
Now actual question, is there a way to set fluent to create multiple indexes per day. Either hourly or even configurable number of indexes per day?

Below is our fluent-elasticsearch plugin config.
Version: fluent-plugin-elasticsearch:3.4.3
ES version: 6.6.0
```
# Read App Kafka topic
<source>
  @type kafka_group
  brokers broker1:9092,broker2:9092
  consumer_group CG-1
  topics app.nginx
  format json
  use_record_time true
  time_format "%s.%L"
  max_bytes 500000
  fetcher_max_queue_size 100
  start_from_beginning true
  session_timeout 120
</source>

# Prometheus exposure
<source>
  @type prometheus
</source>

<source>
  @type prometheus_output_monitor
</source>

# Generate record hash to avoid duplicates
<filter **>
  @type elasticsearch_genid
  hash_id_key _hash
</filter>

<match app.**>
  @type elasticsearch
  hosts eshost1:9200,eshost2:9200,eshost3:9200
  logstash_format true
  logstash_prefix app.nginx
  write_operation create
  <buffer>
    @type memory
    chunk_limit_size 10m
    total_limit_size 60m
    flush_thread_count 8
    flush_mode interval
    flush_interval 10s
    overflow_action block
    retry_forever true
    retry_type periodic
    retry_wait 120s
    retry_randomize true
  </buffer>
  id_key _hash
  remove_keys _hash, time
  request_timeout 100s
  template_name app.nginx
  template_file /fluentd/etc/app.nginx.template
  template_overwrite true
</match>
```

Template config:
```
{
  "index_patterns": [
    "app.nginx*"
  ],
  "settings": {
    "number_of_shards": 16,
    "number_of_replicas": 1,
    "refresh_interval": "30s"
  },
  "mappings": {
    "fluentd": {
      "properties": {
        "@timestamp": {
          "type": "date"
        },
----skipped----
```
Thanks.

**Comment by cosmo0920** [comment]
How about use time chunk_key in buffer and specify user-defined logstash_dateformat?

```aconf
<match app.**>
  @type elasticsearch
  hosts eshost1:9200,eshost2:9200,eshost3:9200
  logstash_format true
  logstash_dateformat "%Y.%m.%d-%H"
  logstash_prefix app.nginx
  write_operation create
  <buffer tag, time>
    @type memory
    chunk_limit_size 10m
    total_limit_size 60m
    flush_thread_count 8
    flush_mode interval
    flush_interval 10s
    overflow_action block
    retry_forever true
    retry_type periodic
    retry_wait 120s
    retry_randomize true
    timekey 3600 # An hour
  </buffer>
  id_key _hash
  remove_keys _hash, time
  request_timeout 100s
  template_name app.nginx
  template_file /fluentd/etc/app.nginx.template
  template_overwrite true
</match>
```

**Comment by dborysenko** [comment]
Thanks, @cosmo0920 
Great suggestion. Even though I have not tested it yet, in theory looks good. 
As of now, we’ve end-up using rollover approach to not let heavy log flow to grow higher than 500Mil in single index. 

Btw, I know it is not an elasticsearch repo, but question is really related. Do you have any suggestion on why elasticsearch could dramatically slow down ingestion speed once index approaching 1B docs? I though it might be related to record ID being generated externally (so elasticsearch has to ensure ID is unique within the shard), but in theory creating index with more shards should help. Which is not in my case. Index with 8 and 16 shards behave the same, slowing down approaching 1B records (500Gb in size).

**Comment by cosmo0920** [comment]
> Btw, I know it is not an elasticsearch repo, but question is really related. Do you have any suggestion on why elasticsearch could dramatically slow down ingestion speed once index approaching 1B docs? I though it might be related to record ID being generated externally (so elasticsearch has to ensure ID is unique within the shard), but in theory creating index with more shards should help. Which is not in my case. Index with 8 and 16 shards behave the same, slowing down approaching 1B records (500Gb in size).

I have no idea about this.
I suspect that very huge index should cause slow down due to ES server cannot operate search in-memory.

If you want to determine why huge indexes cause slow down, you can use vmstat or other profiler to obtain system information.
Huge files (and other huge object?) increases file I/O, then it makes reducing system throughput.

**Comment by cosmo0920** [comment]
Any news? @dborysenko

**Comment by dborysenko** [comment]
Hi @cosmo0920,
I believe we can close this one. Even though I still have not had a chance to test time as a key for buffer, the main question in an issue has been answered.
Thank you much for your support!
