### ISSUE TITLE
how to install typhoeus usccessfully?

### ISSUE THREAD

**Issue by yanrong1990** [uken/fluent-plugin-elasticsearch#608]
#### Problem
I would build my own fluentd image and set http_backend.This is my Dockerfile to install typhoeus

```
FROM fluent/fluentd:v1.5-1

# Use root account to use apk
USER root

# below RUN includes plugin as examples elasticsearch is not required
# you may customize including plugins as you wish
RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install fluent-plugin-elasticsearch \
 && sudo gem install typhoeus \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

COPY fluent.conf /fluentd/etc/

USER fluent
```
Also I add 'http_backend typhoeus' into fluent.conf. But the image cannot work at all and say: no typhoeus found.
Is there any problem with it? any suggestion will be helpful.
...

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

**OR**

Provide example config and message

#### Expected Behavior or What you need to ask

...

#### Using Fluentd and ES plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others?
Kubernetes
* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
v0.12
* ES plugin 3.x.y/2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
* ES version (optional)
ES 6.5.4 
* ES template(s) (optional)

**Comment by cosmo0920** [comment]
You should add a line to install libcurl. Because typhoeus requests to load libcurl.so.

```dockerfile
FROM fluent/fluentd:v1.5-1

# Use root account to use apk
USER root

# below RUN includes plugin as examples elasticsearch is not required
# you may customize including plugins as you wish
RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 # This line is needed.
 && apk add libcurl \
 && sudo fluent-gem install fluent-plugin-elasticsearch \
 && sudo fluent-gem install typhoeus \
 && sudo fluent-gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

COPY fluent.conf /fluentd/etc/

USER fluent
```
