### ISSUE TITLE
how to control the rate of fluentd sending to elasticsearch? 

### ISSUE THREAD

**Issue by ted222** [uken/fluent-plugin-elasticsearch#610]
#### Problem

Is there any config para to control the rate that the fluentd sends to elasticsearch? If the data is large, how to prevent the elasticsearch burst from the large data that come from fluentd?
...

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

**OR**

Provide example config and message

#### Expected Behavior or What you need to ask

...

#### Using Fluentd and ES plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others?
* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
* ES plugin 3.x.y/2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
* ES version (optional)
* ES template(s) (optional)

**Comment by cosmo0920** [comment]
> Is there any config para to control the rate that the fluentd sends to elasticsearch?

No. There is no flow rate control parameter yet.


> If the data is large, how to prevent the elasticsearch burst from the large data that come from fluentd?

But you can determine threshold to split large data with:
https://github.com/uken/fluent-plugin-elasticsearch#bulk_message_request_threshold

**Comment by cosmo0920** [comment]
Fluentd core does not support flow rate control feature.
We will not support this.
