### ISSUE TITLE
Elasticsearch Output Non-Buffered

### ISSUE THREAD

**Issue by lcrash** [uken/fluent-plugin-elasticsearch#612]
My configuration is 
Fluent-bit -> Kafka -> FluentD -> Elasticsearch 

I want to setup FluentD that in case any issue with Elasticsearch FluentD will not move kafka offset.  

I'm not able to find but it is possible to user Elasticsearch plugin with Non-Buffered configuration. 

Similar to 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/fluentd/VBfQcCFDXHo/oMFAjpx_CAAJ

**Comment by cosmo0920** [comment]
ES plugin won't support non-buffered plugin because it's not efficient to send events.
