### ISSUE TITLE
fluentd crashes on undefined method `has_key?'

### ISSUE THREAD

**Issue by fahedouch** [uken/fluent-plugin-elasticsearch#619]
Hello,

previous ticket : https://github.com/fluent/fluentd/issues/2506

#### Problem

I have a fluent-bit, which forward logs to fluentd, but my fluentd crash after a few minutes.

####### Configuaration
 My fluentd  configuration is

```
<source>
  @type         forward
  port          24224
  bind          0.0.0.0
</source>
<source>
  @type prometheus
  bind 0.0.0.0
  port 24231
  metrics_path /metrics
</source>
<source>
  @type prometheus_output_monitor
  interval 10
  <labels>
    hostname ${hostname}
  </labels>
</source>
# Rename all keys begining by _ (underscore)
# as old elasticsearches don't support those
<filter **>
  @type rename_key
  rename_rule1 ^_(.+) ${md[1]}
</filter>


<match **>
  @id elasticsearch
  @type elasticsearch
  @log_level trace
  log_es_400_reason true
  include_tag_key true
  type_name doc
  logstash_format true
  logstash_prefix "box-default"
  target_index_key @target_index
  host "elasticsearch.infra.ritmx.ninja"
  port "9200"
  scheme "http"
  ssl_version: "TLSv1_2"
  reconnect_on_error true
  request_timeout 60s
  slow_flush_log_threshold 60.0
  # Liveness probe is based on file buffers under /var/log/fluentd-buffers
  # as a result, don't use in memory buffer otherwise, fluentd will crash loop
  <buffer>
    @type file
    path /var/log/fluentd-buffers/kubernetes.system.buffer
    flush_mode interval
    retry_type exponential_backoff
    flush_thread_count 2
    flush_interval 5s
    retry_forever
    retry_max_interval 30
    chunk_limit_size "10M"
    queue_limit_length "64"
    overflow_action block
  </buffer>
</match> 
```

######## Error log
``` 2019-07-18 08:30:08 +0000 [warn]: #0 [elasticsearch] failed to flush the buffer. retry_time=18 next_retry_seconds=2019-07-18 08:30:41 +0000 chunk="58ded62cb61f43db06e78e4bd63ad546" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch.infra.ritmx.ninja\", :port=>9200, :scheme=>\"http\"}): undefined method `has_key?' for #<String:0x0000562784617b30>" ```

#### Using Fluentd and ES plugin versions

fluentd 1.3.3
fluent-bit version : fluent-bit:0.1.5
fluent-plugin-elasticsearch (3.0.2)

**Comment by cosmo0920** [comment]
Could you testing with fluent-plugin-elasticsearch 3.5.4?

And could you capture problematic response?

**Comment by cosmo0920** [comment]
You can capture Elasticsearch response with:

```diff
diff --git a/lib/fluent/plugin/elasticsearch_error_handler.rb b/lib/fluent/plugin/elasticsearch_error_handler.rb
index 101dd97..1c4e8a2 100644
--- a/lib/fluent/plugin/elasticsearch_error_handler.rb
+++ b/lib/fluent/plugin/elasticsearch_error_handler.rb
@@ -32,6 +32,7 @@ class Fluent::Plugin::ElasticsearchErrorHandler
   end
 
   def handle_error(response, tag, chunk, bulk_message_count, extracted_values)
+    p response
     items = response['items']
     if items.nil? || !items.is_a?(Array)
       raise ElasticsearchVersionMismatch, "The response format was unrecognized: #{response}"
```

**Comment by cosmo0920** [comment]
@fahedouch ping?

**Comment by cosmo0920** [comment]
This issue seems to be the similar problem which is:
https://discuss.elastic.co/t/clusterblockexception-blocked-by-service-unavailable-1-state-not-recovered-initialized/59793

```json
    {
      "took" : 0,
      "errors" : true,
      "items" : [
        {
          "create" : {
            "_index" : "foo",
            "status" : 503,
            "error" : "ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]"
          }
        }
      ]
     }
```

```json
    {
      "took" : 0,
      "errors" : true,
      "items" : [
        {
          "create" : {
            "_index" : "foo",
            "status" : 503,
            "error" : "ClusterBlockException[blocked by: [FORBIDDEN/8/index write (api)];]"
          }
        }
      ]
     }
```

But how we should do the next step?
Elasticsearch server seems to be exhausted. Simply retrying is not helphul in this case.

**Comment by cosmo0920** [comment]
Could you try this patch, @fahedouch ?
https://github.com/uken/fluent-plugin-elasticsearch/pull/621

**Comment by cosmo0920** [comment]
I'd published a patch for this issue as v3.5.5.

**Comment by fahedouch** [comment]
thank you for the patch i Will upgrade the version and give you a feedback as soon as possible.

**Comment by cosmo0920** [comment]
No response. Closing.
If you encounter this issue again, please feel free to comment on this issue ticket.
