### ISSUE TITLE
'read timeout reached' error issue

### ISSUE THREAD

**Issue by yechanpark** [uken/fluent-plugin-elasticsearch#620]
(check apply)
- [x] read [the contribution guideline](CONTRIBUTING.md)

#### Problem
i'm storing 570 ~ 600GB in 24 hours. (calculated by only string log size)
and my td-agent has two responsibility.
 - storing string logs as files
 - storing string logs as elasticsearch documents (of course, indicec has mapping)

file logs content is the same as elasticsearch documents. (1:1 match)
and my elasticsearch node is only 1(master, data, coordination all in one, this can be scaled out after day).

cpu usage avg is 10~20%.
8core, 64GB ram.

sometimes, when i push documents in elasticsearch via fluentd, 'read timeout reached' error  caused.

and after a while, 'retry succeed' log has caused and input success.

but above error and warning is caused everytime.

in this time, buffer never flushed. just append as buffer files.

and after a while, buffer files too many created to input elasticsearch.

as a result, buffer files are infinitely increasing.

```buffer files create speed``` >>>>> ```buffer files flush speed```

it seems not just input-output data speed problem.

following is td-agent.log
```
2019-08-06 08:55:04 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-08-06 08:55:05 +0900 chunk="58f676f133358450d1be0ce8155101fa" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"127.0.0.1\", :port=>9200, :scheme=>\"http\"}): read timeout reached"
  2019-08-06 08:55:04 +0900 [warn]: #0 suppressed same stacktrace
2019-08-06 08:55:05 +0900 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2019-08-06 08:55:06 +0900 chunk="58f676f13352848f9efc996bbafcb211" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"127.0.0.1\", :port=>9200, :scheme=>\"http\"}): read timeout reached"
  2019-08-06 08:55:05 +0900 [warn]: #0 suppressed same stacktrace
2019-08-06 08:55:06 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-08-06 08:55:07 +0900 chunk="58f650dc7d3fb60fde13ad3f6a8a39d6" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"127.0.0.1\", :port=>9200, :scheme=>\"http\"}): read timeout reached"
  2019-08-06 08:55:06 +0900 [warn]: #0 suppressed same stacktrace
2019-08-06 08:55:08 +0900 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2019-08-06 08:55:09 +0900 chunk="58f650daeb7216733a89c42a421490cf" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"127.0.0.1\", :port=>9200, :scheme=>\"http\"}): read timeout reached"
  2019-08-06 08:55:08 +0900 [warn]: #0 suppressed same stacktrace
2019-08-06 08:55:16 +0900 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2019-08-06 08:55:18 +0900 chunk="58f676f13352848f9efc996bbafcb211" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"127.0.0.1\", :port=>9200, :scheme=>\"http\"}): read timeout reached"
  2019-08-06 08:55:16 +0900 [warn]: #0 suppressed same stacktrace
2019-08-06 08:55:16 +0900 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2019-08-06 08:55:20 +0900 chunk="58f676f133358450d1be0ce8155101fa" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"127.0.0.1\", :port=>9200, :scheme=>\"http\"}): read timeout reached"
  2019-08-06 08:55:16 +0900 [warn]: #0 suppressed same stacktrace
2019-08-06 08:55:20 +0900 [warn]: #0 retry succeeded. chunk_id="58f650dc7d3fb60fde13ad3f6a8a39d6"

```
in ```08:55:04``` ~ ```08:55:16```, 'could not push logs to Elasticsearch cluster ({:host=>\"127.0.0.1\", :port=>9200, :scheme=>\"http\"}): read timeout reached' error has caused.

so, in this time, buffer has not been flushed.

in this time, destination index documents count was not increased.
(i check this via kibana)

this state is maintained until ```08:55:20``` and buffer files are continually created.

and ```08:55:20```, there is ```retry succeeded``` log has been occurred.

in this time, i checked buffer files directory, and buffer files was flushed in destination index
(i check this via kibana)

but buffer files flushed a liitle, and after a while, ```read timeout reached``` occurred. 

#### Steps to replicate
 - ```td-agent.conf```
```
<match log.**>
        @type copy
        <store>
                @type forest
                subtype elasticsearch

                <template>
                         index_name ${tag}_%Y.%m.%d

                         <buffer tag, time>
                                @type file
                                path /log/${tag}.buffer

                               timekey_use_utc false
                               timekey_zone +0900

                               chunk_limit_size 51m # forward server's max chunk size is '50m', and forwarding every 1 second
                               flush_mode interval
                               flush_interval 1s

                               flush_thread_count 8

                               timekey 1m # chunks per hours ("3600" also available)
                        </buffer>

                        host 127.0.0.1
                        port 9200

#                       reconnect_on_error true  # default : false
#                       reload_on_failure true   # default : false
#                       reload_connections false # default : true
#                       request_timeout 10s # default : 5s

                        <secondary>
                                @type file
                                path /log/failed/${tag}.buffer
                        </secondary>
                </template>

        </store>
</match>

<source>
        @type forward
        port 24224
</source>
```

#### Expected Behavior or What you need to ask
how can i handle this error? any idea??

i tried ```request_timeout```and
 ```
reconnect_on_error true
reload_on_failure true
reload_connections false
```

but this options cant help me now.

```request_timeout``` never given more then ```10s```. i will try more bigger value (example, ```20s```).
(but i am worried about this. i will try this later.)

and ```chunk_limit_size``` is ```51m``` now, because log send server's forward chunk limit size is ```50m```. 
(forwarding server to receiving server flush_interval 1s,
receiving server to elasticsearch flush_interval 1s.)

i set receiving server's ```chunk_limit_size``` as ```4m``` before.
but if forwarding server's data's chunk size exceed ```4m```, my receiving server's td-agent occurred following error.
```
2019-08-06 05:33:27 +0900 [warn]: #0 chunk bytes limit exceeds for an emitted event stream: 5665793bytes
```
(5665793bytes = 5.4MB.)

...

#### Using Fluentd and ES plugin versions
Fluentd : 1.3.3  (td-agent 3)
ES : 6.7

* OS version
CentOS 7.6

* Bare Metal or within Docker or Kubernetes or others?
neither Docker nor Kubernetes

* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
td-agent 1.3.3

* ES plugin 3.x.y/2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
elasticsearch (6.1.0)
elasticsearch-api (6.1.0)
elasticsearch-transport (6.1.0)
fluent-plugin-elasticsearch (3.0.1)

* ES version (optional)
ES 6.7

* ES template(s) (optional)

**Comment by cosmo0920** [comment]
> how can i handle this error? any idea??

Could you share your error log before the below messages?

```
2019-08-06 08:55:04 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-08-06 08:55:05 +0900 chunk="58f676f133358450d1be0ce8155101fa" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"127.0.0.1\", :port=>9200, :scheme=>\"http\"}): read timeout reached"
  2019-08-06 08:55:04 +0900 [warn]: #0 suppressed same stacktrace
```

You issue report says that just occurring flushing buffer failure and retry succeeded chunk for `58f650dc7d3fb60fde13ad3f6a8a39d6`.

**Comment by yechanpark** [comment]
I solved this problem.

exactly, i didn't solved 'read timeout reached' problem.

but, no more buffer stacked. (both sender and receiver server)

the problem is my td-agent has two heavy reponsibility.
 - storing string log as file logs
 - storing string log as elasitcsearch documents

these logs are same each other. (1:1 match)

as a result, td-agent has been bottlenecked.

 - sender server
sender server's td-agent success request intermittently, so td-agent retry everytime.
sometimes request success, sometimes request failed.

in this time, sender server's td-agent buffer had been stacked, and overflow.
after 72h later, all buffer files are moved to <secondary> directories.

 - receive server
td-agent cant received sender server's request perfectly (because bottlenecked)
but not killed process yet.
indeed, receive server's td-agent receiving all of senders request.

receive server flushing buffer hardly, but there are too many responsbilities, so it's entire performance is low.


following is what i was tried.

1. do not store logs as elasticsearch documents, but file.
working perfectly, receive server's td-agent buffer will be increased, but not faster then buffer flush speed.
```buffer files create speed``` <<<<< ```buffer files flush speed```

as a result, storing only files strategy is working.


2. do not store logs as file, but elasticsearch documents
working perfectly, receive server's td-agent buffer will be increased, but not faster then buffer flush speed. (the same as storing files)
```buffer files create speed``` <<<<< ```buffer files flush speed```

as a result, storing only elasticsearch documents strategy is working.

my ES cluster and td-agent are stabilized now.
i will separate this responsibility.

```but```, still 'read timeout reached' error occurred.

if someone under this situation,  check my suggestion.

1. how many heavy responsiblities has your td-agent?
 - if your td-agent has a lot of heavy reponsibilities, separate this to other server's td-agent.
 - for example, server1 will be save only file, server2 will be save only elasticsearch.
 - for example, if you can't separate responsibility, approach other strategy. td-agent storing only file, and make your own scirpt for using elasticsearch ````_bulk```` API. and running script that read files and use ```_bulk``` API to insert documents in elasticsearch. in this case, if you can handle concurrency control for thread-safety operation about file access, you can use not only thread but also use multi-process.

2. how many running td-agent node?
 - generally, td-agent process will be exist only one in one node. td-agent support thread numbers. but as i posted, just increasing thread number is not can be solution.

closing issue, and i wish someone solve the same situation via this issue.

**Comment by yechanpark** [comment]
> > how can i handle this error? any idea??
> 
> Could you share your error log before the below messages?
> 
> ```
> 2019-08-06 08:55:04 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-08-06 08:55:05 +0900 chunk="58f676f133358450d1be0ce8155101fa" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"127.0.0.1\", :port=>9200, :scheme=>\"http\"}): read timeout reached"
>   2019-08-06 08:55:04 +0900 [warn]: #0 suppressed same stacktrace
> ```
> 
> You issue report says that just occurring flushing buffer failure and retry succeeded chunk for `58f650dc7d3fb60fde13ad3f6a8a39d6`.

@cosmo0920 , thank for your response. this is just caused by bottleneck. i separated td-agent responsibilities, and working as i intended.

**Comment by cosmo0920** [comment]
> if this error causing other problem, i will issue the new issue.

Sure thing. :+1:

**Comment by yechanpark** [comment]
> (check apply)
> 
> * [x]  read [the contribution guideline](CONTRIBUTING.md)

@cosmo0920, and i cant access this page.

**Comment by cosmo0920** [comment]
Oops. Thanks for notifying it.
I've fixed with this commit:
https://github.com/uken/fluent-plugin-elasticsearch/commit/56b9895e61e9f7467e9af8799bd9f88ef97731c3

**Comment by yechanpark** [comment]
i tried more option about this issue.

as a result, 'read timeout reached' error has gone by configuring ```request_timeout``` bigger value.

```request_timeout``` option's default value is ```5s```.

i tried to config this option's value as ```10s``` as i mentioned.

when i configed this value as ```20s```, error has gone and bulk api working with no retry.

but, this can be slow. because my buffer size (per flush) average is 8MB.

so, there are some warning.
```
2019-08-09 14:08:52 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=20.090474270982668 slow_flush_log_threshold=20.0 plugin_id="object:3fb797ed07f4"
```

but there are not 'read timeout reached' error.

to resolve ```slow_flush_log_threshold``` error, increasing more ```thread_numbers```.

i posted this value as ```8``` , and i increased to ```16```.

now, my td-agent has no error or warning, and stabilized.

i hope someone resolve the same issue.

**Comment by cosmo0920** [comment]
Thank you for providing additional information.
Some users increase `request_timeout` to 2^31 (2147483648):
https://github.com/openshift/origin-aggregated-logging/blob/1a5481f25b91c38cf3a8d2b3522cffecb84bfa66/fluentd/configs.d/openshift/output-es-config.conf#L30

**Comment by sharon-vendrov** [comment]
@cosmo0920 @yechanpark  - Thanks! 

This did the work for me:
> Some users increase request_timeout to 2^31 (2147483648)
