### ISSUE TITLE
Is it possible to specify the index.codec configuration?

### ISSUE THREAD

**Issue by ulyr** [uken/fluent-plugin-elasticsearch#624]
(check apply)
- [v] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
Not being able to specify the code [index.codec](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#_static_index_settings) which causes indices to have the default `index.codec` which is sub optimal for long term storage.

#### Expected Behavior or What you need to ask
Being able to specify the configuration of the index fluentd-elasticsearch creates.

**Comment by cosmo0920** [comment]
No, it isn't.
elasticsearch-ruby does not provide `index.codec` specifying API.
We will not support it until elasticsearch-ruby supports `index.codec` API.

**Comment by ulyr** [comment]
@cosmo0920 
It seems possible looking at [this piece of code](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-api/lib/elasticsearch/api/actions/indices/create.rb)
Looking at the source code for [index creation in fluent-plugin-elasticsearch](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/elasticsearch_index_template.rb#L59) it looks like it's using the default configuration without passing extra parameters

**Comment by cosmo0920** [comment]
We use bulk API instead of create API to send events into Elasticsearch.

**Comment by cosmo0920** [comment]
I believe that index.codec should be specified by template.
Indexcreation should not be used for this case.
Because index.codec in the live index is not changed by client.indices.create API.

The following settings and template can handle index.codec:

```aconf
  template_name best_compression_tmpl
  template_file compression.json
```

#### compression.json

```json
{
  "order": 100,
  "index_patterns": [
    "logstash-*"
  ],
  "settings": {
    "index": {
      "codec": "best_compression"
    }
  }
}
```

```
% curl -XGET 'http://localhost:9200/logstash-2019.12.06/_settings?pretty'
```
```json
{
  "logstash-2019.12.06" : {
    "settings" : {
      "index" : {
        "codec" : "best_compression",
        "number_of_shards" : "1",
        "provided_name" : "logstash-2019.12.06",
        "creation_date" : "1575622843875",
        "number_of_replicas" : "1",
        "uuid" : "SJGM_No8QzCAaR0k8ff00w",
        "version" : {
          "created" : "7040099"
        }
      }
    }
  }
}
```
