### ISSUE TITLE
ArgumentError error="path does not exist"

### ISSUE THREAD

**Issue by xidiandb** [uken/fluent-plugin-elasticsearch#631]
hi , I got an error like :
`2019-08-23 07:42:06 +0000 [warn]: dump an error event: error_class=ArgumentError error="path does not exist" location=nil tag="dns" time=2019-08-23 07:34:09.372982758 +0000 record={"service_type"=>"dns", "Payload"=>"2019-08-23T07:34:08.667Z [INFO] 10.151.51.0:54721 - 8197 \"A IN kafka-2.kafka-svc.svc.cluster.local. udp 53 false 512\" NXDOMAIN qr,rd 146 0.000571135s\n", "cluster_name"=>"xxxxxxxx-3", "cluster_id"=>"xxxxxxxxx-389c-4b96-9ae0-1772c4548b19", "Hostname"=>"master2", "timestamp"=>"2019-08-23T07:34:09.372887317+0000"}
`

```
and my conf like that :

 <filter dns>
      @type parser
      key_name path
      reserve_data true
      remove_key_name_field true
      <parse>
        @type regexp
        expression /^.*core(?<service_type>.+)-/
      </parse>
    </filter>


    <filter k8s dns>
      @type record_modifier
      <record>
        Payload ${record['log']}
      </record>
      whitelist_keys Payload,service_type
    </filter>

```

**Comment by cosmo0920** [comment]
Closing this due to contribute guideline violation.

https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md
