### ISSUE TITLE
Clarify effect of disable_retry_limit flag

### ISSUE THREAD

**Issue by mightyguava** [uken/fluent-plugin-elasticsearch#632]
We are seeing occasional OOMs on fluentd, and are trying to track down the problem.

I noticed the statement:

> **Note**: If you use `disable_retry_limit` in v0.12 or `retry_forever` in v0.14 or later, please be careful to consume memory inexhaustibly.

Could you clarify this statement? In my understanding, if we set a `buffer_chunk_limit`, that should prevent us from running out of memory even if we allow for infinite retries. How would it consume memory inexhaustibly?

**Comment by cosmo0920** [comment]
> How would it consume memory inexhaustibly?

Please consider file buffer instead of default memory buffer.

**Comment by mightyguava** [comment]
I understand if we use file buffer the memory usage is reduced. But if we use do use memory buffer, does it cause excessive memory usage, or just cause a limited amount of memory to be held for a long time?

**Comment by cosmo0920** [comment]
When using memory buffer on limited machine memory resource environment, Fluentd will be killed by OOM killer.
Some users reported this phenomenon.

**Comment by mightyguava** [comment]
ok, thank you!
