### ISSUE TITLE
[out_elasticsearch_dynamic] not parsing timestamp properly, causing @timestamp field to be mapped as `keyword`

### ISSUE THREAD

**Issue by asdonation** [uken/fluent-plugin-elasticsearch#638]
#### Problem
out_elasticsearch_dynamic does not parse by parameters `time_key` and `time_key_format` as out_elasticsearch does. 

This causes the field `@timestamp` under indices created by out_elasticsearch_dynamic to be mapped as `keyword`. 

#### Steps to replicate

fluentd elasticsearch configuration:
```
 @type elasticsearch_dynamic
  host elasticsearch-client.logging.svc
  port 9200
  logstash_format false
  type_name mylog
  index_name activity.${record['tenant'].downcase}-${Time.at(time).getutc.strftime(@logstash_dateformat)}
  time_key_format %Y/%m/%d %H:%M:%S.%N
  time_key timestamp
  include_timestamp true
  log_es_400_reason true
  <buffer>
    flush_thread_count "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT'] || '8'}"
    flush_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL'] || '5s'}"
    chunk_limit_size "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE'] || '2M'}"
    queue_limit_length "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH'] || '32'}"
    retry_max_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL'] || '30'}"
    retry_forever true
  </buffer>
```

for a given log, the record will contain a `timestamp` field with the value: `2019/08/27 17:24:45.325920`

This results in index created with bad mapping:
```
"mappings" : {
      "log" : {
        "properties" : {
          "@timestamp" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
```

If you change the type - `elasticsearch_dynamic` to `elasticsearch` (and remove the dynamic record access in `index_name`), this results mapping of `date` type to `@timestamp` field (as shown in expected behavior section).

#### Expected Behavior or What you need to ask

Expected mapping:
```
"mappings" : {
      "log" : {
        "properties" : {
          "@timestamp" : {
            "type" : "date"
          },
```

#### Using Fluentd and ES plugin versions

* Bare Metal or within Docker or Kubernetes or others? Kubernetes
* Fluentd fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1

Thanks!

**Comment by Semmix** [comment]
+1 having the same issue exactly

**Comment by yoni1306** [comment]
Same here

**Comment by cosmo0920** [comment]
FYI: out_elasticsearch already supports built-in placeholders.
It uses buffer metadata.
To apply built-in placeholder in your configuration, it needs to specify `tag, time, tenant` into buffer attributes:

```aconf
 @type elasticsearch
  host elasticsearch-client.logging.svc
  port 9200
  logstash_format false
  type_name mylog
  index_name activity.${tenant}-%Y.%m.%d
  time_key_format %Y/%m/%d %H:%M:%S.%N
  time_key timestamp
  include_timestamp true
  log_es_400_reason true
  <buffer tag, time, tenant>
    flush_thread_count "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT'] || '8'}"
    flush_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL'] || '5s'}"
    chunk_limit_size "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE'] || '2M'}"
    queue_limit_length "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH'] || '32'}"
    retry_max_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL'] || '30'}"
    retry_forever true
    timekey 1h
  </buffer>
```

If you want to change `tenant` to down cases, you should use fluent-plugin-record-modifier or such record manipulation plugin.
ref: https://github.com/repeatedly/fluent-plugin-record-modifier#replace_keys_value

BTW, we will plan to make deprecated out_elasticsearch_dynamic in the future version.

**Comment by asdonation** [comment]
That made everything work. Thanks for the quick and informative response!
