### ISSUE TITLE
fluentd-elasticsearch-plugin could not rollover index

### ISSUE THREAD

**Issue by ljt2016** [uken/fluent-plugin-elasticsearch#642]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

I found that fluentd-elasticsearch-pluging has rollover_index parameter, so I want to add rollover feature to my EFK stack.
However, after I configured fluentd's output config file and started fluentd, I find this message in fluentd logs:

parameter 'application_name' in <match **>
  1021    @id elasticsearch
  1022    @type elasticsearch
  1023    @log_level "info"
  1024    type_name "flatten"
  1025    include_tag_key true
  1026    host "elasticsearch-logging"
  1027    port 9200
  1028    template_file "/etc/fluent/config.d/template.json"
  1029    template_name "hc-template"
  1030    customize_template {"--appid--":"hc-logs","--index_prefix--":"hc-logs"}
  1031    rollover_index true
  1032    deflector_alias hot-cold-alias
  1033    index_prefix "hc"
  1034    application_name hc-es
  1035    flatten_hashes true
  1036    flatten_hashes_separator "_"
  1037    <buffer>
  1038      @type "file"
  1039      path "/var/log/fluentd-buffers/kubernetes.rollover.buffer"
  1040      flush_mode interval
  1041      timekey 1h
  1042      retry_type exponential_backoff
  1043      flush_thread_count 4
  1044      flush_interval 5s
  1045      retry_timeout 1h
  1046      retry_max_interval 30
  1047      chunk_limit_size 2M
  1048      queue_limit_length 100
  1049      overflow_action block
  1050    </buffer>
  1051    <secondary>
  1052      @type "secondary_file"
  1053      directory "/tmp/fluentd"
  1054      basename "bad-chunk-${chunk_id}"
  1055    </secondary>
  1056  </match> is not used.

And the rollover format index hc-hc-template-2019.09.04-000001 was created and it had two aliases "hc-rollover-search"(claimed in template.json) and "hc-template-current".
And fluentd does not send logs to this index, but send all logs to a index called **fluentd**.

Is there any one could give me a rollover demo, thanks.

#### Using Fluentd and ES plugin versions

* Kubuenetes 1.14
* Fluentd v1.2.4
* elasticsearch (6.1.0)
* elasticsearch-api (6.1.0)
* elasticsearch-transport (6.1.0)
* ES version 6.3.0

**Comment by cosmo0920** [comment]
Does anyone know how to fix this problem?
Rollover index feature is contributed by user, @kumaravel29 .
So Rollover index support should work on basic setup but I'm not sure what is wrong.

**Comment by fpytloun** [comment]
Had same issue when I tried to use this feature.

**Comment by mcortinas** [comment]
it seems so interesting use rollover in order to use shards with the same size, any plans in order to fix it....

**Comment by fpytloun** [comment]
@mcortinas try to check my comment with working example here: https://github.com/uken/fluent-plugin-elasticsearch/issues/540#issuecomment-545014739

You will need to build custom fluentd image with patched elasticsearch-ruby: https://github.com/uken/fluent-plugin-elasticsearch/pull/651#issuecomment-545821967

**Comment by cosmo0920** [comment]
ILM feature is supported. Closing.
