### ISSUE TITLE
unrecoverable_error_types can't be used

### ISSUE THREAD

**Issue by like-inspur** [uken/fluent-plugin-elasticsearch#643]
I config unrecoverable_error_types ["out_of_memory_error"] in output elasticsearch section, but it outputs error like this:
```
2019-09-04 09:16:13 +0000 [warn]: parameter 'unrecoverable_error_types' in <match res>
  @id es-res
  @type elasticsearch
  @log_level "warn"
  host "elasticsearch"
  logstash_format true
  validate_client_version true
  reconnect_on_error true
  reload_connections false
  reload_on_failure true
  logstash_prefix "res"
  unrecoverable_error_types ["out_of_memory_error"]
  slow_flush_log_threshold 120.0
  request_timeout 120s
  with_transporter_log true
  <buffer>
    @type "file"
    path "/fluentd/elasticsearch/res"
    total_limit_size 16G
    chunk_limit_size 15M
    queued_chunks_limit_size 64
    retry_type periodic
    retry_wait 60
    flush_mode interval
    flush_interval 60s
    flush_thread_count 2
    retry_forever true
    overflow_action block
  </buffer>
</match> is not used.
```

**Comment by cosmo0920** [comment]
Please don't ignore issue template. Thanks!!

**Comment by cosmo0920** [comment]
If you ignore issue template in the next time, I'll close your issue without no response.
https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md#found-a-bug

**Comment by like-inspur** [comment]
@cosmo0920 sorry, I have adjusted format of fluentd config

**Comment by like-inspur** [comment]
@cosmo0920 hello，I have adjusted format of issue, could you remove incomplete label

**Comment by cosmo0920** [comment]
It seems to be still incomplete. Please don't use custom format and follow the issue template:
https://github.com/uken/fluent-plugin-elasticsearch/blob/master/ISSUE_TEMPLATE.md

**Comment by like-inspur** [comment]
os version: Ubuntu 18.04
kubernetes version: 1.14.3
fluentd version: 1.2.4
fluent-plugin-elasticsearch verison: 2.11.11
es version: 6.5.4

**Comment by like-inspur** [comment]
@cosmo0920

**Comment by cosmo0920** [comment]
This feature should be 2.12.1.

**Comment by like-inspur** [comment]
I found that fluend don't output error on x86 environment, but output error on arm64 environment
