### ISSUE TITLE
Wrong document order in elastic

### ISSUE THREAD

**Issue by igortin** [uken/fluent-plugin-elasticsearch#646]
#### 
Problem
In LogTrail/Elastic sometimes output logs in not correct order.
>Example: Thats order of logs is wrong.
Logtrail output: 
     log - doc with text sequence number 78 
     log - doc with text sequence number 76
     log - doc with text sequence number 77
     
How i can configure fluentd plugin to avoid the problem?
Does out_elasticsearch support not buffered or not bulk write operation?

Found :
I suppose that the problem appears because fluentd send bulk write request to elastic and it writes documents to different shards with the same timestamp and the same assigned sort key. Sort key consists timestamp(unixtime) + subseconds

#### Expected Behavior or What you need to ask
Documents with not the same timestamp in elasticsearch.

#### Using Fluentd and ES plugin versions
* OS Coreos/Ubuntu 19.04
* Kubernetes/minikube 
* Fluentd docker images  v1.7-debian-elasticsearch6-1
* ES plugin 3.5.5
# fluent-gem list
*** LOCAL GEMS ***
addressable (2.6.0)
bigdecimal (default: 1.4.1)
bundler (default: 1.17.2, 1.16.2)
cmath (default: 1.0.0)
concurrent-ruby (1.1.5)
cool.io (1.5.4)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
dig_rb (1.0.1)
domain_name (0.5.20190701)
e2mmap (default: 0.1.0)
elasticsearch (6.8.0)
elasticsearch-api (6.8.0)
elasticsearch-transport (6.8.0)
etc (default: 1.0.1)
excon (0.66.0)
faraday (0.15.4)
fcntl (default: 1.0.0)
ffi (1.11.1)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
fluent-config-regexp-type (1.0.0)
fluent-plugin-concat (2.3.0)
fluent-plugin-elasticsearch (3.5.5)
fluent-plugin-grok-parser (2.5.1)
fluent-plugin-json-in-json-2 (1.0.2)
fluent-plugin-kubernetes_metadata_filter (2.3.0)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-prometheus (1.5.0)
fluent-plugin-record-modifier (2.0.1)
fluent-plugin-rewrite-tag-filter (2.2.0)
fluent-plugin-systemd (1.0.2)
fluentd (1.7.0)
forwardable (default: 1.2.0)
gdbm (default: 2.0.0)
http (3.3.0)
http-accept (1.7.0)
http-cookie (1.0.3)
http-form_data (2.1.1)
http_parser.rb (0.6.0)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
json (default: 2.1.0)
kubeclient (4.4.0)
logger (default: 1.3.0)
lru_redux (1.1.0)
matrix (default: 0.1.0)
mime-types (3.2.2)
mime-types-data (3.2019.0331)
msgpack (1.3.1)
multi_json (1.13.1)
multipart-post (2.1.1)
mutex_m (default: 0.1.0)
netrc (0.11.0)
oj (3.8.1)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
prime (default: 0.1.0)
prometheus-client (0.9.0)
psych (default: 3.1.0)
public_suffix (3.1.1)
quantile (0.2.1)
rdoc (default: 6.1.0)
recursive-open-struct (1.1.0)
rest-client (2.1.0)
rexml (default: 3.1.9)
rss (default: 0.2.7)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
serverengine (2.1.1)
shell (default: 0.7)
sigdump (0.2.4)
stringio (default: 0.0.2)
strptime (0.2.3)
strscan (default: 1.0.0)
sync (default: 0.5.0)
systemd-journal (1.3.3)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
tzinfo (2.0.0)
tzinfo-data (1.2019.2)
unf (0.1.4)
unf_ext (0.0.7.6)
webrick (default: 1.4.2)
yajl-ruby (1.4.1)
zlib (default: 1.0.0)* ES version (optional)

**Comment by cosmo0920** [comment]
Did you specify `date_nanos` type with mapping template?
https://www.elastic.co/guide/en/elasticsearch/reference/7.x/date_nanos.html

**Comment by igortin** [comment]
HI, thank you for your response.
Installed elasticsearch version 6.8.

**Comment by cosmo0920** [comment]
Without nanosecond precision timestamp, this is known issue and expected behavior.
Your wrong ordered documents has same Unix epoch timestamp, right?

**Comment by igortin** [comment]
yes, you a right. Вшв i understand correctly that i can solve the issue if migrate to elastisearch version 7.0?

**Comment by cosmo0920** [comment]
I guess that you should upgrade to ES 7 and specify date_nanos type with mapping template?
https://www.elastic.co/guide/en/elasticsearch/reference/7.x/date_nanos.html

**Comment by igortin** [comment]
Could you please provide how i can change mapping in fluent, because in repo there is no template.json for creating index in el.

**Comment by igortin** [comment]
fixed, Thanks.
