### ISSUE TITLE
Flatten hashes not working in elasticsearch_dynamic mode

### ISSUE THREAD

**Issue by SergeyD** [uken/fluent-plugin-elasticsearch#650]
#### Problem
When using plugin in `elasticsearch_dynamic` mode flatten_hashes functionality is not working.

#### Steps to replicate

Elasticsearch output config:

```
 <match logstash-**>
    @type elasticsearch_dynamic
    @log_level "debug"
    with_transporter_log true
    user "xxxxx"
    password xxxxxx
    host "xxxxx"
    port 9243
    scheme https
    resurrect_after 5s
    reconnect_on_error true
    reload_on_failure true
    reload_connections false
    logstash_format true
    logstash_prefix "logstash-test-logstash-testurl"
    include_tag_key true
    flatten_hashes true
    flatten_hashes_separator "_"
    logstash_dateformat "%Y.%m.%d"
    <buffer>
      flush_at_shutdown true
      flush_mode immediate
      overflow_action block
      retry_forever true
    </buffer>
  </match>
```

Changing `@type elasticsearch_dynamic` to `@type elasticsearch` makes flatten hashes work.

#### Using Fluentd and ES plugin versions

* OS version: macOS 10.15 AND Alpine 3.9.4
* Both Bare Metal and within Docker/Kubernetes
* fluentd-1.0.2 on macOS; fluentd 1.5.2 in Kube
* 'fluent-plugin-elasticsearch' version '3.5.5'
* ES version 7.3

**Comment by cosmo0920** [comment]
Currently, `elasticsearch_dynamic` will be planned deprecated and should be maintenance phase.
Our work is concentrated to `elasticsearch`.
