### ISSUE TITLE
TD agent plugin install failed (td-agent-gem install fluent-plugin-elasticsearch)

### ISSUE THREAD

**Issue by nikhilraj474** [uken/fluent-plugin-elasticsearch#661]
#### Problem
we were installing the plugin td-agent-gem install fluent-plugin-elasticsearch we are getting the below error.

 ERROR:  While executing gem ... (SocketError)
    getaddrinfo: Name or service not known

```
root@TEST03:~# systemctl stop td-agent.service
root@TEST03:~# td-agent-gem install fluent-plugin-elasticsearch
ERROR:  While executing gem ... (SocketError)
    getaddrinfo: Name or service not known
```

I have even checked the DNS entry was able to ping the DNS servers.

#### Using Fluentd and ES plugin versions

* OS version-- Ubuntu18.04
*  td-agent_3.4.1-0

**Comment by cosmo0920** [comment]
This issue should be DNS issue on td-agent-gem command.
Could you check `host rubygems.org` result?

**Comment by nikhilraj474** [comment]
Here is the output when i check 
root@TEST03:~# host rubygems.org
rubygems.org has address 151.101.0.70
rubygems.org has address 151.101.128.70
rubygems.org has address 151.101.64.70
rubygems.org has address 151.101.192.70
rubygems.org has IPv6 address 2a04:4e42::70
rubygems.org mail is handled by 10 mxa.mailgun.org.
rubygems.org mail is handled by 10 mxb.mailgun.org.
