### ISSUE TITLE
Is ILM possible without index_date_pattern?

### ISSUE THREAD

**Issue by adyekjaer** [uken/fluent-plugin-elasticsearch#673]
#### Problem
I've setup ILM without major problems but I would like to prevent fluentd from creating index on the form: 

prefix-name-yyyy.mm.dd-000001
and instead just
prefix-name-000001.

Is this possible to configure it this way ? I've tried quite a few different options.

## Example config:
enable_ilm true
ilm_policy_id docker-policy
ilm_policy { "policy": { "phases": { "hot": { "min_age": "0ms", "actions": { "rollover": { "max_age": "7d", "max_size": "50gb" }, "set_priority": { "priority": 100 } } }, "delete": { "min_age": "30d", "actions": { "delete": {} } } } } }
template_name docker_index_template
template_file /fluentd/etc/docker_index_template.json
index_name docker-${container_name}
index_prefix docker
application_name ${container_name}
index_date_pattern now/d
rollover_index true
deflector_alias docker-${container_name}
customize_template {"<<index_prefix>>": "docker"}

The "index_date_pattern" key seem to be required ?

Thank you.

**Comment by cosmo0920** [comment]
> I've setup ILM without major problems but I would like to prevent fluentd from creating index on the form:
> 
> prefix-name-yyyy.mm.dd-000001
> and instead just
> prefix-name-000001.
> 
> Is this possible to configure it this way ? I've tried quite a few different options.

Currently, now way.

> The "index_date_pattern" key seem to be required ?

No, this is optional parameter. The default values is `now/d`.

**Comment by cosmo0920** [comment]
I've created a PR to fix this issue.

With #674, your feature request can handle:

```aconf
enable_ilm true
ilm_policy_id docker-policy
ilm_policy { "policy": { "phases": { "hot": { "min_age": "0ms", "actions": { "rollover": { "max_age": "7d", "max_size": "50gb" }, "set_priority": { "priority": 100 } } }, "delete": { "min_age": "30d", "actions": { "delete": {} } } } } }
template_name docker_index_template
template_file /fluentd/etc/docker_index_template.json
index_name docker-${container_name}
index_prefix docker
application_name ${container_name}
# empty index_date_pattern should handle to omit date pattern from rollover index
index_date_pattern "" 
rollover_index true
deflector_alias docker-${container_name}
customize_template {"<<index_prefix>>": "docker"}
```
