### ISSUE TITLE
[question] how to ignore the exceptions?

### ISSUE THREAD

**Issue by ted222** [uken/fluent-plugin-elasticsearch#680]
hello , I meet a problem that I set 

ignore_exceptions ["Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure"]

in my conf, but it didn't have any effect, I still saw the Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure errors in the td-agent.log. 

how to ignore the exceptions?

**Comment by cosmo0920** [comment]
This parameter aims to handle transport errors such as:

* `Faraday::ClientError`
*  `Elasticsearch::Transport::Transport::ServerError`

Basically, `Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure` should not be ignored.

**Comment by cosmo0920** [comment]
`Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure` is used for retrying mechanism on ES plguin.
So, it mustn't be ignored.
This behavior is intended. Closing.
