### ISSUE TITLE
Data too large, circuit_breaking_exception

### ISSUE THREAD

**Issue by Raboo** [uken/fluent-plugin-elasticsearch#682]
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

td-agent/fluentd fails to send data to elasticsearch sometimes.
It seems to try to send to much data. Don't know if it's a bulk request, but I believe this is when there is buffered messages.
My `chunk_limit_size` is set to 16m. And I haven't specified a `bulk_message`, so it should default to 20m.

This is the error I get
```
2019-12-10 11:55:35 +0100 [warn]: #0 failed to flush the buffer. retry_time=11 next_retry_seconds=2019-12-10 12:00:26 +0100 chunk="5995753ed4dc3235b02cf3726e434698" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"localhost\", :port=>9200, :scheme=>\"http\"}): [429] {\"error\":{\"root_cause\":[{\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be [12294116678/11.4gb], which is larger than the limit of [12240656793/11.3gb], real usage: [12293554880/11.4gb], new bytes reserved: [561798/548.6kb], usages [request=493200/481.6kb, fielddata=1775/1.7kb, in_flight_requests=10395102144/9.6gb, accounting=142117727/135.5mb]\",\"bytes_wanted\":12294116678,\"bytes_limit\":12240656793,\"durability\":\"TRANSIENT\"}],\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be [12294116678/11.4gb], which is larger than the limit of [12240656793/11.3gb], real usage: [12293554880/11.4gb], new bytes reserved: [561798/548.6kb], usages [request=493200/481.6kb, fielddata=1775/1.7kb, in_flight_requests=10395102144/9.6gb, accounting=142117727/135.5mb]\",\"bytes_wanted\":12294116678,\"bytes_limit\":12240656793,\"durability\":\"TRANSIENT\"},\"status\":429}"
```

I don't really know what all those numbers mean, but I interpret it fluentd is trying to send a 11.4gb http request?
Why would it do that?
And to be add more weirdness, it actually succeeded after a while (have `retry_forever true`) and  cleared the buffers.

#### Steps to replicate

Unknown, this seems to happen when there are buffered messages.
ES config.

I've snipped out the relevant part of the config.
```
<source>
  ...
  @label @ELASTIC
</source>

<label @ELASTIC>
  <match **>
    @type elasticsearch
    logstash_format true
    type_name fluentd

    # By default, the error logger won't record the reason for a 400 error from the Elasticsearch
    log_es_400_reason true

    time_key @timestamp
    time_key_format %Y-%m-%dT%H:%M:%S.%N%:z

    include_tag_key true

    logstash_prefix fluentd
    # 2019.12.06 temporary disable this.
    # template_name fluentd
    # template_file /etc/td-agent/fluentd.template.json

    reload_connections false
    reload_on_failure true

    request_timeout 15s # default is 5s, setting larger to accomodate big buffers

    # use file buffer to buffer events on disks so we can reduce/control message loss.
    <buffer>
      @type file # file or memory, defaults to memory
      path /var/log/td-agent/buffer/es.*.buf # only valid for file

      # 16m*256 = 4GB file buffer.
      chunk_limit_size 16m
      queue_limit_length 512
      overflow_action drop_oldest_chunk # if we haven't cleared buffer, drop oldest data.

      flush_interval 5s
      flush_thread_count 4
      retry_wait 1s # default 1s
      retry_forever true # we want to always retry, default is false
      retry_max_interval 5m
    </buffer>
  </match>
</label>

<label @ERROR>
  <match **>
    @type stdout
  </match>
</label>
```

I have no tuning options configured in elasticsearch. So everything is at default except for GC and heap settings. 

#### Expected Behavior or What you need to ask

fluentd should send data in smaller chunks that accommodate limits in elasticsearch.
What do I need to do in order to achieve that?

#### Using Fluentd and ES plugin versions

* Ubuntu 18.04 + 16.04
* Bare Metal
* td-agent 1.7.4
* ES plugin 3.5.5

```
$ td-agent-gem list

*** LOCAL GEMS ***

addressable (2.7.0)
aws-eventstream (1.0.3)
aws-partitions (1.230.0)
aws-sdk-core (3.72.0)
aws-sdk-kms (1.25.0)
aws-sdk-s3 (1.52.0)
aws-sdk-sqs (1.23.0)
aws-sigv4 (1.1.0)
bigdecimal (default: 1.3.2)
bundler (1.16.6)
concurrent-ruby (1.1.5)
cool.io (1.5.4)
did_you_mean (1.1.0)
dig_rb (1.0.1)
digest-crc (0.4.1)
elasticsearch (6.8.0)
elasticsearch-api (6.8.0)
elasticsearch-transport (6.8.0)
excon (0.68.0)
faraday (0.17.0)
ffi (1.11.1)
fluent-config-regexp-type (1.0.0)
fluent-logger (0.8.2)
fluent-plugin-beats (1.1.0, 1.0.1)
fluent-plugin-elasticsearch (3.5.5, 3.4.3, 1.10.2)
fluent-plugin-input-gelf (0.3.1)
fluent-plugin-kafka (0.12.1)
fluent-plugin-prometheus (1.7.0)
fluent-plugin-record-modifier (2.0.1, 1.1.0, 0.6.0)
fluent-plugin-rewrite-tag-filter (2.2.0)
fluent-plugin-s3 (1.2.0)
fluent-plugin-td (1.0.0)
fluent-plugin-td-monitoring (0.2.4)
fluent-plugin-webhdfs (1.2.4)
fluentd (1.7.4)
gelfd2 (0.4.1)
hirb (0.7.3)
http_parser.rb (0.6.0)
httpclient (2.8.2.4)
io-console (default: 0.4.6)
ipaddress (0.8.3)
jmespath (1.4.0)
json (default: 2.0.4)
ltsv (0.1.2)
mini_portile2 (2.4.0)
minitest (5.10.1)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7)
msgpack (1.2.9)
multi_json (1.14.1)
multipart-post (2.1.1)
net-telnet (0.1.1)
nokogiri (1.10.4)
ohai (6.20.0)
oj (3.7.12)
openssl (default: 2.0.9)
parallel (1.18.0)
power_assert (0.4.1)
prometheus-client (0.9.0)
psych (default: 2.2.2)
public_suffix (4.0.1)
quantile (0.2.1)
rake (12.3.3, 12.0.0)
rdkafka (0.7.0)
rdoc (default: 5.0.1)
ruby-kafka (0.7.10)
ruby-progressbar (1.10.1)
rubyzip (2.0.0)
serverengine (2.1.1)
sigdump (0.2.4)
strptime (0.2.3)
systemu (2.5.2)
td (0.16.5)
td-client (1.0.7)
td-logger (0.3.27)
test-unit (3.2.3)
tzinfo (2.0.0)
tzinfo-data (1.2019.3)
webhdfs (0.8.0)
xmlrpc (0.2.1)
yajl-ruby (1.4.1)
zip-zip (0.3)
```

* ES version v7.5.0

**Comment by cosmo0920** [comment]
This issue is Elasticsearch cluster side issue not Fluentd.
ref: https://github.com/elastic/elasticsearch/issues/31197#issuecomment-417053166

Could you consider to increase memory in running  Elasticsearch cluster nodes?

**Comment by cosmo0920** [comment]
And could you consider to specify [bulk_message_request_threshold](https://github.com/uken/fluent-plugin-elasticsearch#bulk_message_request_threshold) as 10MB or lower?

**Comment by Raboo** [comment]
Hi @cosmo0920,

I switched back to CMS from G1GC, it appears that the choice GC might affect the circuit breaker limits differently (https://discuss.elastic.co/t/7-0-1-new-circuitbreaker-segment-bigger-than-heap-should-this-break/195455)

And I guess I won't run into this unless we have a elasticsearch failure that caues fluentd to buffer messages or we have some applications producing a lot of logs in a higher pace than elastic can handle.

So is it only the `bulk_message` that controls how big requests the elasticsearch plugin sends?

**Comment by cosmo0920** [comment]
How about increase heap?

Default heap size is just 1G.

Example which increases heap size to 4G.

```
ES_JAVA_OPTS="-Xms4g -Xmx4g" ./bin/elasticsearch
```

see: https://github.com/elastic/elasticsearch/issues/31197#issuecomment-502914451

**Comment by Raboo** [comment]
At the time of the writing, we had a heap of around 12GB or 16GB(can't remember).
Switching from G1GC to CMS resolved the problem back then.. So I believe that elasticsearch misbehaves when using G1GC on calculating how large requests it can accept. 

However I am still curious if the `bulk_message` config controls how large requests this plugin sends?

As you can see in the original issue, it appears that the request sent to elasticsearch was 11.4GB, which for me sounds crazy big. But it could be that I am just not interpreting the logs correctly.

However I don't have this problem anymore and can close the issue if you want, I was just waiting to see if someone knew about `bulk_message`.

**Comment by cosmo0920** [comment]
Well, thanks for the detail answer.

> At the time of the writing, we had a heap of around 12GB or 16GB(can't remember).
> Switching from G1GC to CMS resolved the problem back then.. So I believe that elasticsearch misbehaves when using G1GC on calculating how large requests it can accept.

Hmm, it's curious.

> However I don't have this problem anymore and can close the issue if you want, I was just waiting to see if someone knew about `bulk_message`.

Thanks for providing solution. 😍 
Then, this should be Elasticsearch side issue.
We should close this issue.

**Comment by Brian-McM** [comment]
I know this is closed by the question of whether fluentd was trying to send 1.2GBs was never answered, and I was curious about this as well. @cosmo0920 is that what that log implies?

**Comment by Raboo** [comment]
It's insane to send such a big amounts of data (if in fact it does, never got an answer to that question). It should try to break it down to smaller requests IMO.
