### ISSUE TITLE
Using multiple record in 'logstash_prefix'

### ISSUE THREAD

**Issue by dcvtruong** [uken/fluent-plugin-elasticsearch#691]
#### Problem

I'm having trouble using multiple k8s record in the logstash_prefix.  

#### Steps to replicate
So far I tried the following scenario and it all return error,

```
logstash_prefix "${record['kubernetes']['host']}-${record['kubernetes']['namespace_name']}"
```
and 

```
logstash_prefix "${record['kubernetes']['host']-['namespace_name']}"
```

#### Expected Behavior or What you need to ask

index name would have the hostname follow by '-' then namespace,
```
devops_host-default
```
#### Using Fluentd and ES plugin versions

* OS version - RH 7.6
* Bare Metal or within Docker or Kubernetes or others? - Kubernetes 1.13.10
* Fluentd v1.6.1
* ES plugin 3.x.y/2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
* ES version (optional)
* ES template(s) (optional)

**Comment by cosmo0920** [comment]
You should specify the metadata which is used in buffer directive into built-in placeholders:

```aconf
logstash_prefix "${record['kubernetes']['host']}-${record['kubernetes']['namespace_name']}"
<buffer tag, $.kubernetes.host, $.kubernetes.namespace_name>
   @type memory # or file
</buffer>
```

```aconf
logstash_prefix "${record['kubernetes']['host']-['namespace_name']}"
<buffer tag, $.kubernetes.host, namespace_name>
   @type memory # or file
</buffer>
```

ref: https://docs.fluentd.org/configuration/buffer-section#nested-field-support

**Comment by cosmo0920** [comment]
No response. Closing.

**Comment by murilopacsonov** [comment]
When i use that, fluentd create this index in es:
green  open ${record['kubernetes']['namespace_name']}-2021.03.16
