### ISSUE TITLE
Logs not being written to ILM enabled index

### ISSUE THREAD

**Issue by ggoinden-rms** [uken/fluent-plugin-elasticsearch#693]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
The plugin is creating an index with rollover capability `(logstash-default-2020.01.11-000001)` but logs or not being written to it. Another index is being created `(logstash-2020.01.11)` and logs are going there instead.
...

#### Steps to replicate
my config:

```<match **>
      @type elasticsearch
      #@id out_es
      #@log_level info
      index_name fluentd
      type_name fluentd
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      path "#{ENV['FLUENT_ELASTICSEARCH_PATH']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
      ssl_version "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERSION'] || 'TLSv1'}"
      user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
      password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
      reload_connections "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS'] || 'false'}"
      reconnect_on_error "#{ENV['FLUENT_ELASTICSEARCH_RECONNECT_ON_ERROR'] || 'true'}"
      reload_on_failure "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_ON_FAILURE'] || 'true'}"
      log_es_400_reason "#{ENV['FLUENT_ELASTICSEARCH_LOG_ES_400_REASON'] || 'false'}"
      logstash_format true
      # Rollover index configuration
      #logstash_prefix app-logs
      template_name logstash-default
      template_file /fluentd/etc/app_index.template
      rollover_index true
      deflector_alias logstash-default
      ilm_policy_id AppLogsAuto
      enable_ilm true
      <buffer>
        flush_thread_count "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT'] || '8'}"
        flush_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL'] || '5s'}"
        chunk_limit_size "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE'] || '2M'}"
        queue_limit_length "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH'] || '32'}"
        retry_max_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL'] || '30'}"
        retry_forever true
      </buffer>
    </match>
```

#### Expected Behavior or What you need to ask
Logs should be written to the `logstash-default-2020.01.11-000001` index not `logstash-2020.01.11`
...

#### Using Fluentd and ES plugin versions

* OS version
* Kubernetes using the fluentd deamonset https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch.yaml. I've created my own docker image using `fluent/fluentd-kubernetes-daemonset:v1.7.4-debian-elasticsearch7-2.2` as the base image adding the `elasticsearch-xpack` gem https://rubygems.org/gems/elasticsearch-xpack/versions/7.4.0
* Fluentd v0.12 or v0.14/v1.0
  * `fluentd 1.7.4`
* Gem list
addressable (2.7.0)
bigdecimal (default: 1.4.1)
bundler (default: 1.17.2, 1.16.2)
cmath (default: 1.0.0)
concurrent-ruby (1.1.5)
cool.io (1.5.4)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
dig_rb (1.0.1)
domain_name (0.5.20190701)
e2mmap (default: 0.1.0)
elasticsearch (7.4.0)
elasticsearch-api (7.4.0)
elasticsearch-transport (7.4.0)
elasticsearch-xpack (7.4.0)
etc (default: 1.0.1)
excon (0.71.1)
faraday (0.17.1)
fcntl (default: 1.0.0)
ffi (1.11.3)
ffi-compiler (1.0.1)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
fluent-config-regexp-type (1.0.0)
fluent-plugin-concat (2.4.0)
fluent-plugin-detect-exceptions (0.0.13)
fluent-plugin-elasticsearch (3.8.0)
fluent-plugin-grok-parser (2.6.1)
fluent-plugin-json-in-json-2 (1.0.2)
fluent-plugin-kubernetes_metadata_filter (2.3.0)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-prometheus (1.6.1)
fluent-plugin-record-modifier (2.0.1)
fluent-plugin-rewrite-tag-filter (2.2.0)
fluent-plugin-systemd (1.0.2)
fluentd (1.7.4)
forwardable (default: 1.2.0)
gdbm (default: 2.0.0)
http (4.2.0)
http-accept (1.7.0)
http-cookie (1.0.3)
http-form_data (2.1.1)
http-parser (1.2.1)
http_parser.rb (0.6.0)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
json (default: 2.1.0)
kubeclient (4.5.0)
logger (default: 1.3.0)
lru_redux (1.1.0)
matrix (default: 0.1.0)
mime-types (3.3)
mime-types-data (3.2019.1009)
msgpack (1.3.1)
multi_json (1.14.1)
multipart-post (2.1.1)
mutex_m (default: 0.1.0)
netrc (0.11.0)
oj (3.8.1)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
prime (default: 0.1.0)
prometheus-client (0.9.0)
psych (default: 3.1.0)
public_suffix (4.0.1)
quantile (0.2.1)
rake (13.0.1)
rdoc (default: 6.1.2)
recursive-open-struct (1.1.0)
rest-client (2.1.0)
rexml (default: 3.1.9)
rss (default: 0.2.7)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
serverengine (2.2.0)
shell (default: 0.7)
sigdump (0.2.4)
stringio (default: 0.0.2)
strptime (0.2.3)
strscan (default: 1.0.0)
sync (default: 0.5.0)
systemd-journal (1.3.3)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
tzinfo (2.0.0)
tzinfo-data (1.2019.3)
unf (0.1.4)
unf_ext (0.0.7.6)
webrick (default: 1.4.2)
yajl-ruby (1.4.1)
zlib (default: 1.0.0)

Index template:
```
  {
      "index_patterns": [
        "logstash-default*"
      ],
      "settings": {
        "index": {
          "number_of_replicas": "2"
        }
      },
      "aliases": {
        "logstash-default": {}
      }
    }
```

**Comment by JoshDaone** [comment]
Seems like [customize_template](https://github.com/uken/fluent-plugin-elasticsearch#customize_template) is missing from your .conf

**Comment by ggoinden-rms** [comment]
thanks, @JoshDaone. I tried your suggestion but no luck. Could be that I'm not using the correct format for `customize_template`. Do you have a working example? My config now:

```
<match **>
  @type elasticsearch
  @log_level info
  type_name _doc
  include_tag_key true
  host elasticsearch-logging-test.test
  port 9200
  enable_ilm true
  template_name apps
  template_file /fluentd/etc/apps_index.json
  ilm_policy_id AppLogs
  rollover_index true
  deflector_alias logstash-default
  logstash_format true
  logstash_prefix logstash-default
  customize_template {"index.number_of_replicas": "4"} # have also tried {"number_of_replicas": "4"}
  <buffer>
    flush_thread_count "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT'] || '8'}"
    flush_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL'] || '5s'}"
    chunk_limit_size "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE'] || '2M'}"
    queue_limit_length "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH'] || '32'}"
    retry_max_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL'] || '30'}"
    retry_forever true
  </buffer>
</match>
```
My index template file:
```
{
     "settings": {
     "number_of_replicas": 3
  }
}
```
As well as the logs not going to the ILM-enabled index, the `number_of_replicas` value in the index file is not being substituted by the value in `customize_template`, assuming I'm understand how `customize_template` works.

**Comment by cosmo0920** [comment]
Current ES plugin implementation doesn't work well with logstash format style index.
Could you try to use #701 patch for your use case?

**Comment by ggoinden-rms** [comment]
@cosmo0920 The patch did the job! Thank you!
