### ISSUE TITLE
Cannot install fluent-plugin-elasticsearch gem on old td-agent due to dependency update

### ISSUE THREAD

**Issue by AlejoAsd** [uken/fluent-plugin-elasticsearch#696]
- [X] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
Cannot install the `fluent-plugin-elasticsearch` gem on old `td-agent` v2 installations because of an unconstrained dependency version. 

I'm running an Amazon Linux instance that requires me to use `td-agent` v2 due to a known `GLIBC` version incompatibility. I'm using the [2017.09 version](https://td-agent-package-browser.herokuapp.com/2/redhat/2017.09/x86_64) of `td-agent` v2, which is the last supported version for Amazon Linux 1 according to [this post](https://support.treasuredata.com/hc/en-us/articles/360010821214-Installing-td-agent-on-Amazon-Linux-).

#### Steps to replicate

I'm using the following script to install `td-agent`.

<details><summary><code>td-agent</code> Installation Script</summary>

```bash
## The following is based on script install-redhat-td-agent2.sh with
## some tweaks for our use (eg. also install elasticsearch plugin).
## We had to update the $baseurl because it was incorrect.
## See: https://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh
set -x
echo "=============================="
echo " td-agent Installation Script "
echo "=============================="
echo "This script requires superuser access to install rpm packages."
echo "You will be prompted for your password by sudo."

# clear any previous sudo permission
sudo -k

# run inside sudo
sudo sh <<SCRIPT

# add GPG key
rpm --import https://packages.treasuredata.com/GPG-KEY-td-agent

# add treasure data repository to yum
cat >/etc/yum.repos.d/td.repo <<'EOF';
[treasuredata]
name=TreasureData
baseurl=http://packages.treasuredata.com/2/redhat/2017.09/\$basearch
gpgcheck=1
gpgkey=https://packages.treasuredata.com/GPG-KEY-td-agent
EOF

# update your sources
yum check-update

# install the toolbelt and dev tools to later install elasticsearch plugin
yes | yum install -y td-agent make gcc g++ libc-dev libffi-dev

# now install the elasticsearch plugin
/usr/sbin/td-agent-gem install fluent-plugin-elasticsearch

SCRIPT

# message
echo ""
echo "Installation completed. Happy Logging!"
echo ""
```

</details>

This script installs the `td-agent 2.3.6` rpm package and `fluentd/td-agent 1.8.1`.

```bash
# td-agent version
[root@<redacted> ~]# yum info td-agent
Loaded plugins: priorities, update-motd, upgrade-helper
Installed Packages
Name        : td-agent
Arch        : x86_64
Version     : 2.3.6
Release     : 0.el2017
Size        : 176 M
Repo        : installed
From repo   : treasuredata
Summary     : Treasure Agent: A data collector for Treasure Data
URL         : http://treasuredata.com
License     : Apache-2.0
Description : Treasure Agent: A data collector for Treasure Data

# fluentd version
[root@<redacted> ~]# /usr/sbin/td-agent --version
td-agent 1.8.1
```

But then fails when attempting to install `fluent-plugin-elasticsearch`

<details><summary><code>fluent-plugin-elasticsearch</code> gem installation</summary>

```bash
# now install the elasticsearch plugin
[root@<redacted> ~]# /usr/sbin/td-agent-gem install fluent-plugin-elasticsearch
Fetching: msgpack-1.3.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed msgpack-1.3.1
Fetching: serverengine-2.2.0.gem (100%)
Successfully installed serverengine-2.2.0
Fetching: strptime-0.2.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed strptime-0.2.3
Fetching: dig_rb-1.0.1.gem (100%)
Successfully installed dig_rb-1.0.1
Fetching: fluentd-1.8.1.gem (100%)
Successfully installed fluentd-1.8.1
Fetching: excon-0.71.1.gem (100%)
Successfully installed excon-0.71.1
Fetching: multipart-post-2.1.1.gem (100%)
Successfully installed multipart-post-2.1.1
Fetching: faraday-1.0.0.gem (100%)
ERROR:  Error installing fluent-plugin-elasticsearch:
	faraday requires Ruby version >= 2.3.
```
</details>

`faraday 1.0.0` was released on Jan 1st, after which my `fluent-plugin-elasticsearch` installations started to break. Installations of `fluent-plugin-elasticsearch` on the same exact Amazon Linux 1 environments worked before. 

This is the [release history](https://rubygems.org/gems/faraday)

```
1.0.0 - January 01, 2020 (76 KB)
1.0.0.pre.rc1 - July 08, 2019 (42.5 KB)
0.17.3 - December 31, 2019 (70.5 KB)
0.17.1 - November 27, 2019 (69.5 KB)
0.17.0 - October 06, 2019 (39.5 KB)
```

The problem is that the `faraday` dependency gem requires Ruby >= 2.3 since version `1.0.0`, but older `td-agent` v2 versions bundle Ruby 2.1. The dependency graph for `faraday` looks like this

```
fluent-plugin-elasticsearch 3.8.0
└── elasticsearch (>= 0)
    └── elasticsearch-transport (>= 0, development)
        └── faraday (>= 0)
```

Notice the `faraday` version is unconstrained and is attempting to use the latest version. Using an older version of `faraday` fixes things: manually installing `faraday` to version `~> 0` will allow `fluent-plugin-elasticsearch` to install, as the dependency will be preemptively met and then `fluent-plugin-elasticsearch` will not need to attempt to install the latest version.

#### Expected Behavior or What you need to ask

I expect the `fluent-plugin-elasticsearch` gem to install in `td-agent v2.x.x` rpm package versions. 

This can be done by adding a `faraday ~> 0` dependency to `fluent-plugin-elasticsearch`. It may make more sense to make this change in the `elasticsearch` gem spec instead of to this one. Let me know and I'll gladly move the issue.

I can fix my specific issue by running
```bash
td-agent-gem install faraday:"~>0" fluent-plugin-elasticsearch
```

I have created this issue to raise awareness.

#### Using Fluentd and ES plugin versions

* OS version Amazon
Linux AMI 2018.03.
* Bare Metal or within Docker or Kubernetes or others?
Bare metal VM.
* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
```bash
[root@<redacted> ~]# /usr/sbin/td-agent --version
td-agent 1.8.1
```
* ES plugin 3.x.y/2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
Skipped.

  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
<details><summary>Gem list</summary>

```bash
*** LOCAL GEMS ***

actionmailer (4.2.8)
actionpack (4.2.8)
actionview (4.2.8)
activejob (4.2.8)
activemodel (4.2.8)
activerecord (4.2.8)
activesupport (4.2.8)
addressable (2.5.2, 2.5.1)
arel (6.0.4)
aws-sdk (2.10.45)
aws-sdk-core (2.10.45)
aws-sdk-resources (2.10.45)
aws-sigv4 (1.0.2)
bigdecimal (default: 1.2.4)
bson (4.1.1)
builder (3.2.3)
bundler (1.14.5)
celluloid (0.15.2)
cool.io (1.5.1)
crass (1.0.2)
diff-lcs (1.3)
dig_rb (1.0.1)
draper (1.4.0)
erubis (2.7.0)
excon (0.71.1)
fluent-logger (0.7.1)
fluent-mixin-plaintextformatter (0.2.6)
fluent-plugin-kafka (0.6.1)
fluent-plugin-mongo (0.8.1)
fluent-plugin-rewrite-tag-filter (1.5.6)
fluent-plugin-s3 (0.8.5)
fluent-plugin-scribe (0.10.14)
fluent-plugin-td (0.10.29)
fluent-plugin-td-monitoring (0.2.3)
fluent-plugin-webhdfs (0.7.1)
fluentd (1.8.1, 0.12.40)
fluentd-ui (0.4.4)
font-awesome-rails (4.7.0.1)
globalid (0.4.0)
haml (4.0.7)
haml-rails (0.5.3)
hike (1.2.3)
hirb (0.7.3)
http_parser.rb (0.6.0)
httpclient (2.8.2.4)
i18n (0.8.1)
io-console (default: 0.4.3)
ipaddress (0.8.3)
jbuilder (2.6.3)
jmespath (1.3.1)
jquery-rails (3.1.4)
json (default: 1.8.1)
kramdown (1.13.2)
kramdown-haml (0.0.3)
loofah (2.1.1, 2.0.3)
ltsv (0.1.0)
mail (2.6.4)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.3.0, 2.1.0)
minitest (5.10.1, default: 4.7.5)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7)
mongo (2.2.7)
msgpack (1.3.1, 1.1.0)
multi_json (1.12.1)
multipart-post (2.1.1)
nokogiri (1.8.1)
ohai (6.20.0)
oj (2.18.1)
parallel (1.8.0)
psych (default: 2.0.5)
public_suffix (3.0.0, 2.0.5)
puma (3.8.2)
rack (1.6.5)
rack-test (0.6.3)
rails (4.2.8)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.8)
rails-html-sanitizer (1.0.3)
railties (4.2.8)
rake (default: 10.1.0)
rdoc (default: 4.1.0)
request_store (1.3.2)
ruby-kafka (0.4.2)
ruby-progressbar (1.9.0)
rubyzip (1.2.1, 1.1.7)
sass (3.2.19)
sass-rails (4.0.5)
serverengine (2.2.0)
settingslogic (2.0.9)
sigdump (0.2.4)
sprockets (2.12.4)
sprockets-rails (2.3.3)
string-scrub (0.0.5)
strptime (0.2.3)
sucker_punch (1.0.5)
systemu (2.5.2)
td (0.15.2)
td-client (0.8.85)
td-logger (0.3.27)
test-unit (default: 2.1.10.0)
thor (0.19.4)
thread_safe (0.3.6)
thrift (0.8.0)
tilt (1.4.1)
timers (1.1.0)
tzinfo (1.2.3)
tzinfo-data (1.2017.2)
uuidtools (2.1.5)
webhdfs (0.8.0)
yajl-ruby (1.3.0)
zip-zip (0.3)
```
</summary>

* ES version (optional)
* ES template(s) (optional)

**Comment by cosmo0920** [comment]
Fluentd v0.12 series is already EOL.

> Notice the faraday version is unconstrained and is attempting to use the latest version. Using an older version of faraday fixes things: manually installing faraday to version ~> 0 will allow fluent-plugin-elasticsearch to install, as the dependency will be preemptively met and then fluent-plugin-elasticsearch will not need to attempt to install the latest version.

This should be [elasticsearch-ruby](https://github.com/elastic/elasticsearch-ruby)'s issue.
Could you report this issue in [elasticsearch-ruby's issue tracker](https://github.com/elastic/elasticsearch-ruby/issues/new)?

**Comment by AlejoAsd** [comment]
> Fluentd v0.12 series is already EOL. And also, td-agent 2 had been reached EOL.

Fair enough. I wanted to point this out in case it was relevant in some way.

> Could you report this issue in elasticsearch-ruby's issue tracker?

Absolutely.

Thank you for taking the time to answer.
