### ISSUE TITLE
Support placeholders in template_name and customize_template

### ISSUE THREAD

**Issue by splushii** [uken/fluent-plugin-elasticsearch#703]
As the title says I would like to be able to use placeholders in `template_name` and `customize_template` values.

The reason for doing this is to support sending logs to Open Distro Elasticsearch (which does not have ILM, but its own version of index lifecycle management called ISM which is not currently supported by this plugin). I want to send logs to different indices depending on placeholders, and these indices should use rollover aliases and specify an ISM policy.

I have implemented placeholders for `template_name` and `customize_template` in a fork and tested it with a configuration similar to:
```yaml
index_name               fluentd-${tag}

# Rollover index config
rollover_index     true
index_prefix       fluentd
application_name   ${tag}
index_date_pattern ""
deflector_alias    fluentd-${tag}

# Index template
template_name      fluentd-${tag}
template_file      /fluentd/etc/es_index_template.json
customize_template {"<<TAG>>":"${tag}"}
template_overwrite true
```
where `/fluentd/etc/es_index_template.json` looks like:
```json
{
  "index_patterns" : ["fluentd-<<TAG>>-*"],
  "settings" : {
    "number_of_shards": 3,
    "number_of_replicas": 2,
    "opendistro.index_state_management.policy_id": "fluentd-default-policy",
    "opendistro.index_state_management.rollover_alias": "fluentd-<<TAG>>"
  }
}
```
where the ISM policy `fluentd-default-policy` already exists in the ES cluster.

This works well. Does this sound like a good solution (to you the maintainers)? I will probably open a PR next week.

Saw that there had been some work with how templating works in the master branch so I thought it was wise to create an issue for this in case you have any plans that goes in line with or conflicts with this issue.

Thanks for a great plugin!

**Comment by cosmo0920** [comment]
Thanks for the feature request.
This plugin has been released some refactoring and breaking changes on v4.0.0.
Could you rebase off master, if you have a patch?

**Comment by splushii** [comment]
Sure! Rebased in the above PR. There are some issues that arose when rebasing though. Added info about it in the PR.

**Comment by cosmo0920** [comment]
#708 is merged. Closing.

**Comment by dgaffuri** [comment]
If you use this feature on AWS ElasticSearch managed service be aware that from Service software release R20210426 the `opendistro.index_state_management.policy_id` is no more allowed in template, and REST calls including it will get a 401. You'll have to match index names in the policy instead, as documented in [ISM templates](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/ism.html#ism-template)

**Comment by cosmo0920** [comment]
This plugin doesn't assume AWS services.
Please post your issue in the right place. Thanks.

**Comment by dgaffuri** [comment]
It was not meant as an issue, but as a help for people using AWS (or more generally Open Distro for Elasticsearch) with the configuration reported in this issue. Aside from AWS specific release the policy_id is deprecated from [Open Distro 1.13.0](https://opendistro.github.io/for-elasticsearch-docs/docs/im/ism/).

Sorry for the noise.
