### ISSUE TITLE
target_index_key not working

### ISSUE THREAD

**Issue by erms77** [uken/fluent-plugin-elasticsearch#714]
The data is indexed in the topic referenced by `index_name` but not in the index designated by the value of the field defined by the `target_index_key` configuration.

## Configuration of the output
```
<match log-**>
  target_index_key es_index
  verify_es_version_at_startup false
  index_name dead_letter_index
  @type elasticsearch
  hosts foo,bar,toto
  port 59200
  default_elasticsearch_version 7
  <buffer >
    @type memory
  </buffer>
</match>
```

## Data in input
```
{
  "schema": "com.foo.bar.logback.encoder.model.LogEntry_v1",
  "timestamp8601": "2020-02-10T15:02:01.870673+00:00",
  "level": "INFO",
  "es_index:": "log-mob-csm"
}
```

#### Using Fluentd and ES plugin versions

* OS version : Debian 10.2
* Fluentd run in docker environment
* Fluentd v1.9.1
* ES plugin v4.0.3
* ES version 7.5.0
* ES template(s) none

**Comment by erms77** [comment]
I close the issue, my bad... I found a typo in a filter that I applied on the target field.

**Comment by cosmo0920** [comment]
No worries.
Feel free to report an issue whenever you may found a bug or question. :punch:
