### ISSUE TITLE
Index templates not recreated after recreating elasticsearch 

### ISSUE THREAD

**Issue by simonklb** [uken/fluent-plugin-elasticsearch#715]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

Since the index templates are cached and not installed for each send_bulk an elasticsearch cluster that has been recreated will not get the index templates back.

#### Steps to replicate

Start fluentd
Recreate elasticsearch cluster

#### Expected Behavior or What you need to ask

Index templates being recreated.

#### Using Fluentd and ES plugin versions

* RancherOS
* Kubernetes 1.15
* fluentd 1.6.3
* ES plugin 4.0.3
* ES version 7.5.2

**Comment by cosmo0920** [comment]
ES plugin will cache templates and alias_index to prevent redundant requests to create them.

Just restart Fluentd instance(s) should fix this issue but your expected behavior is different for ours?

Which is better to fix your issue?

* Nothing caching for template and alias_indexes with added a new parameter
* Adding timer or something to clear caches.

Or else?

**Comment by simonklb** [comment]
@cosmo0920 Yes, restarting Fluentd would cause the index templates to be created. But I guess it would be nice if this wasn't required.

Clearing the caches might be a viable solution. The problem we end up with is that the index is not able to rollover since the ILM policy has not been recreated. This is what you see in Kibana when viewing an index:
```
Index lifecycle error
illegal_state_exception: unable to parse steps for policy [....] as it doesn't exist
```

It's also important that the index template is created before the rollover happens. So as long as the index template is first recreated and then the ILM policy things should be fine.

**Comment by cosmo0920** [comment]
> But I guess it would be nice if this wasn't required.

*Fluentd is not psychic.* It requires to send GET request to confirm template and index_alias.

**Comment by cosmo0920** [comment]
Again, what should we do fix this issue?
Currently, clearing template and index_alias way is not provided.
We should provide some method or API which clears template and index_alias caches?

**Comment by simonklb** [comment]
Yes, clearing the cache (within a reasonable time) to recreate the index templates should be enough in our case.

**Comment by cosmo0920** [comment]
I've created a PR (#719) to provide clearing caches timer.

e.g.) With this patch and `truncate_caches_interval 5m`, we can truncate caches for `alias_indexes` and `template_names` every 5 minutes.

Also, `truncate_caches_interval` parameter can handle an arbitrary value where you want to specify.

**Comment by cosmo0920** [comment]
I've released #719 as v4.0.4.
Could you check it?

**Comment by cosmo0920** [comment]
v4.0.4 had been released and no response.
If you got the similar behavior, please feel free to comment this issue.
Closing.

**Comment by simonklb** [comment]
Sorry for the delayed response. We had to run with a workaround where we created the index templates manually instead of letting fluentd take care of it.

We've tested the patch now and unfortunately it still does not re-create index templates. This time it's because we are not using any placeholders due to this commit https://github.com/uken/fluent-plugin-elasticsearch/pull/701/commits/8e93e640950ce7af75116f819558411865603051.

Would it be possible to always allow for template installation even without placeholders? Or is there some good reason why that is a bad idea?

**Comment by cosmo0920** [comment]
The reason why we don't like to support recreation indices is reducing request to Elasticsearch as much as possible.
Users Elasticsearch clusters sometimes exhausted, heavily loaded environmental.
Thus, we don't want to add increasing request feature.

**Comment by simonklb** [comment]
Is that not solved by the index_template and alias caching? As long as you don't clear the caches the number of requests should stay the same, no?
