### ISSUE TITLE
ILM policies not recreated after recreating elasticsearch and restoring elasticsearch snapshot

### ISSUE THREAD

**Issue by simonklb** [uken/fluent-plugin-elasticsearch#716]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

ILM policies are not recreated after recreating an elasticsearch cluster and restoring the indexes from a snapshot.

This is similar to https://github.com/uken/fluent-plugin-elasticsearch/issues/715 but with the addition of restoring the snapshot it's not just the caching that is preventing the policy creation but also that the alias already exists.

#### Steps to replicate

Start fluentd
Stop ingress flow from fluentd -> elasticsearch
Recreate elasticsearch cluster
Restore elasticsearch snapshot
Start ingress flow

#### Expected Behavior or What you need to ask

ILM policies being recreated after a restored elasticsearch cluster.

#### Using Fluentd and ES plugin versions

* RancherOS
* Kubernetes 1.15
* fluentd 1.6.3
* ES plugin 4.0.3
* ES version 7.5.2

**Comment by cosmo0920** [comment]
This can be fixed with similar approach for https://github.com/uken/fluent-plugin-elasticsearch/issues/715#issuecomment-586822819.

**Comment by simonklb** [comment]
@cosmo0920 The solution might not be completely similar since in the snapshot restore case you will actually get indices and aliases restored but not ILM policies.

Currently, ILM policies are only created at the same time as aliases, here (inside the create_rollover_alias method): https://github.com/uken/fluent-plugin-elasticsearch/blob/6732da787c412feb671bfe64e5afd901d4eb9ba7/lib/fluent/plugin/elasticsearch_index_template.rb#L144-L150

That means that the ILM policies will not be recreated if the indices with the deflector aliases are already restored and exists.

**Comment by cosmo0920** [comment]
> The solution might not be completely similar since in the snapshot restore case you will actually get indices and aliases restored but not ILM policies.

Oh, I didn't notice this restoring behavior. Thanks for the information.

**Comment by cosmo0920** [comment]
I've released https://github.com/uken/fluent-plugin-elasticsearch/pull/719/commits/f80efada8f659ba2797abb3a2881e979cd0d40e8 as v4.0.4.
Could you check it?

**Comment by cosmo0920** [comment]
v4.0.4 had been released and no response.
If you got the similar behavior, please feel free to comment this issue.
Closing.
