### ISSUE TITLE
ILM in v4 - incorrect index naming?

### ISSUE THREAD

**Issue by SergeyD** [uken/fluent-plugin-elasticsearch#720]
#### Problem

It is not clear from documentation what `application_name` param is intended for and why it affects index name.

All examples from "Enable Index Lifecycle Management" section of documentation (v 4.0.4) include `application_name`, but it seems like it is `fluentd` term not related to native `Elasticsearch ILM`. It definitely affects the index naming but I'm not sure how it affects ILM itself.

When using following config:

```
index_name "security-${target_index}"
application_name "${target_index}"
index_date_pattern ""
enable_ilm true
ilm_policy_id "security-policy"
ilm_policy "xxxxxx"
template_name "fluentd-template"
template_file "/fluentd/etc/fluentd-template.json"
```
and `${target_index}` = `linux.auth`,  i've got index created with name `security-linux.auth-linux.auth-000001` (while `security-linux.auth-000001` is expected).

If I remove `application_name` from config above I'm getting index created with name `security-linux.auth-default-000001`

Quote from documentation:
```ILM target index alias is created with index_name or an index which is calculated from logstash_prefix.```

This works OK - correct alias (`security-linux.auth`) is really being created based on `index_name` - so there is no need in "application_name" for alias creation I assume.

Another quote:

```From Elasticsearch plugin v4.0.0, ILM target index will be calculated from index_name (normal mode) or logstash_prefix (using with logstash_formatas true).```

This is not correct - as I'm getting an `application_name` appended to index name.

#### Using Fluentd and ES plugin versions

Kubernetes 1.13
fluentd 1.5.1
ES plugin 4.0.4
ES version 7.5.0

**Comment by cosmo0920** [comment]
Could you write a patch for the *wrong* documentation?
