### ISSUE TITLE
ILM configuration effect not as expected

### ISSUE THREAD

**Issue by ZMMWMY** [uken/fluent-plugin-elasticsearch#725]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
There are two problems
1. create index template named fluentd-current
2. create two indices ,One is called fluentd and the other is called fluentd-000001

#### Steps to replicate

```
# ILM configuration
  template_name fluentd-template
  template_file /fluentd/template/test_template.json
  customize_template {"<<index_prefix>>": "docker"}
  rollover_index true
  index_name fluentd
  deflector_alias fluentd-current
  enable_ilm true
  application_name ""
  ilm_policy_id fluentd-policy
  ilm_policy {}
  index_separator ""
  index_date_pattern ""
```
```
{
    "template": "fluentd*",
    "order": 0,
    "settings": {
        "index.lifecycle.name": "fluentd-policy",
        "index.lifecycle.rollover_alias": "fluentd-current",
        "index.refresh_interval": "5s",
        "number_of_shards": "1",
        "number_of_replicas": "0"
    }
 }
```

**Comment by cosmo0920** [comment]
`ilm_policy` should not  be `{}`.

**Comment by cosmo0920** [comment]
And using `deflector_alias` when you use ILM feature is deprecated usage.
You shouldn't specify it.

**Comment by cosmo0920** [comment]
>     2\. create two indices ,One is called fluentd and the other is called fluentd-000001

This should be valid. fluentd-000001 index is ephemeral index. This will be marked:

* hot -> warn -> cold

**Comment by ZMMWMY** [comment]
> And using `deflector_alias` when you use ILM feature is deprecated usage.
> You shouldn't specify it.

that's right. i remove it . it's work

**Comment by ZMMWMY** [comment]
> > ```
> > 2\. create two indices ,One is called fluentd and the other is called fluentd-000001
> > ```
> 
> This should be valid. fluentd-000001 index is ephemeral index. This will be marked:
> 
> * hot -> warn -> cold

Although fluentd-000001 is temporary, fluentd should not exist
When I remove ``deflector_alias``, only one index is generated
thank you

**Comment by ZMMWMY** [comment]
I found another strange thing.the generated template is different from my configuration
```
```

**Comment by cosmo0920** [comment]
> > > ```
> > > 2\. create two indices ,One is called fluentd and the other is called fluentd-000001
> > > ```
> > 
> > 
> > This should be valid. fluentd-000001 index is ephemeral index. This will be marked:
> > 
> > * hot -> warn -> cold
> 
> Although fluentd-000001 is temporary, fluentd should not exist
> When I remove `deflector_alias`, only one index is generated
> thank you

But your feature request is impossible to fix.
ILM feature should use two indices when using `test` index for ILM:

* test
* test-000001 (rollover index which is the alias for test index)

ES plugin writes test, then the actual data are written in test-000001.

**Comment by cosmo0920** [comment]
> I found another strange thing.the generated template is different from my configuration

Hm, this behavior should be a bug.

**Comment by cosmo0920** [comment]
Why this issue is closed?
This issue should be solved in your environment, @ZMMWMY?

**Comment by ZMMWMY** [comment]
> Why this issue is closed?
> This issue should be solved in your environment, @ZMMWMY?

Despite some minor issues with the template, ILM works
i can change the template configuration to match it

**Comment by cosmo0920** [comment]
> Despite some minor issues with the template, ILM works
> i can change the template configuration to match it

OK. Thanks.
If changing template configuration can handle ILM index glitch, we can close issue.
Anyway, thank you for your reporting!
If another issue is found, feel free to open an new issue. :smile:
