### ISSUE TITLE
Improved behavior when ES is unavailable during configure step

### ISSUE THREAD

**Issue by AlexHockey** [uken/fluent-plugin-elasticsearch#729]
(check apply)
- [ x ] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

I am trying to use fluentd to send logs to elasticsearch and to another receiver (in this case it happens to be another fluentd instance in another system using the out_forward plugin, but I don't think it matters). 

I am currently using `verify_es_version_at_startup` to detect the ES version. If ES is unavailable when fluentd starts, the plugin "hangs" in the configure phase, as noted in #596. The workaround in #596 suggests the following settings:

```
verify_es_version_at_startup false
default_elasticsearch_version 6 # Or another version
```

The problem with this workaround is I now can't easily upgrade ES. If I upgrade ES, fluentd will be stuck using the wrong version until I get round to updating all of my clients. 

#### Steps to replicate

* Make elasticsearch unavailable. 
* Start fluentd with vanilla elasticsearch config. 

#### Expected Behavior or What you need to ask

I am wondering if there is any interest in improving the behavior of version detection, rather than just turning it off completely. Here are some options I've been considering. I'd be open to implementing these, but want to check if they are likely to be accepted before I invest any time in it:

* Have the plugin "fall back" to using `default_elasticsearch_version` if it can't determine the actual version on startup. 
* Determine the ES version lazily - i.e. only when trying to send data to elasticsearch. 

#### Using Fluentd and ES plugin versions

* OS version: 
  * debian stretch.
* Bare Metal or within Docker or Kubernetes or others? 
  * Kubernetes
* Fluentd v0.12 or v0.14/v1.0: 
  * fluentd 1.7.3
* ES plugin 3.x.y/2.x.y or 1.x.y
  * 4.0.5

**Comment by cosmo0920** [comment]
Do you have an idea to improve this behavior?



> I am currently using `verify_es_version_at_startup` to detect the ES version. If ES is unavailable when fluentd starts, the plugin "hangs" in the configure phase, as noted in #596. The workaround in #596 suggests the following settings:

This behavior had been introduced for Elasticsearch and elasticsearch-ruby client glitch detection.
Before introduced this behavior, many many many issue reported "Why my elasticsearch can't receive ES plugin?".

> Have the plugin "fall back" to using default_elasticsearch_version if it can't determine the actual version on startup.

Fall back behavior is just delaying between Elasticsearch and its ruby client version glitch.

>     * Determine the ES version lazily - i.e. only when trying to send data to elasticsearch.

This is not good way to handle this. This behavior should cause the same behavior before detecting version.

**Comment by AlexHockey** [comment]
> This behavior had been introduced for Elasticsearch and elasticsearch-ruby client glitch detection.
Before introduced this behavior, many many many issue reported "Why my elasticsearch can't receive ES plugin?".

This behavior is fine if you are only sending data to Elasticsearch, or your Elastic search is highly available. My problem is that I have an Elasticsearch that is not highly available, and I need to send data to second destination. This behavior means that if Elasticsearch is unavailable when fluent starts, it doesn't send data to *any* destinations. I'm not saying that we should change this behavior for all users of the plugin, but I'm wondering if I could add a feature (probably with a configuration option) to improve my use case. 

> Fall back behavior is just delaying between Elasticsearch and its ruby client version glitch detection. I don't think that it is not improving this issue.

The current behavior is that if Elasticsearch is not available when fluentd tries to start, fluentd cannot start and handle any data. The improvement is that:

* If elasticsearch is available when fluentd starts you detect the version perfectly. 
* If elasticsearch is not available when fluent starts, the plugin could read the version number from `default_elasticsearch_version`. 
  * If this matches the elasticsearch version then everything will work when elasticsearch eventually becomes available. 
  * If the versions don't match, then the plugin will be using the wrong version. But this is a situation that the plugin faces already. For example the plugin starts, detects ES version X, but then ES is upgraded to version Y while fluentd is running. Does the plugin already handle version mismatches somehow?

>> Determine the ES version lazily - i.e. only when trying to send data to elasticsearch

>It is not good way to handle this. This behavior should cause the same behavior before detecting version.

I don't understand why this is not a good option. All it does is defer version detection until you actually need to send to Elasticsearch. I don't think you need to know the version before that point. If Elasticsearch is not available when you need to send data to it, then you can't detect the version, but that doesn't matter because Elasticsearch is not running at that point. 

> Do you have an idea to improve this behavior?

My suggestions were in my original comment. But I'm open to other suggestions. 🙂

**Comment by cosmo0920** [comment]
> The current behavior is that if Elasticsearch is not available when fluentd tries to start, fluentd cannot start and handle any data. The improvement is that:
> 
>     * If elasticsearch is available when fluentd starts you detect the version perfectly.
> 
>     * If elasticsearch is not available when fluent starts, the plugin could read the version number from `default_elasticsearch_version`.
>       
>       * If this matches the elasticsearch version then everything will work when elasticsearch eventually becomes available.
>       * If the versions don't match, then the plugin will be using the wrong version. But this is a situation that the plugin faces already. For example the plugin starts, detects ES version X, but then ES is upgraded to version Y while fluentd is running. Does the plugin already handle version mismatches somehow?

Hmm, that's reasonable.
I've added a fallbacking feature for es version detection.
Could you check #730?

**Comment by AlexHockey** [comment]
That all looks good to me - thank you very much!

Do you know when this would be available in a published gem?

**Comment by cosmo0920** [comment]
Well, it well be in the end of this week.
Thank you for the confirmation. :smile:
