### ISSUE TITLE
SSL connect error: ssl_min_version / ssl_max_version defaults

### ISSUE THREAD

**Issue by tonobo** [uken/fluent-plugin-elasticsearch#736]
I've started testing with latest **ubuntu 20.04** and discovered ssl connection issues. ( openssl 1.1.1d-2ubuntu6). The cause is the tls enforcement for `TLSv1` specified here https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/elasticsearch_tls.rb (included in out_elasticsearch.rb)

~~I suggest to not setting the ssl version by default (if possible), as the openssl should decide on it's own if nothing was given.~~

This behavior seems to be introduced with this PR. https://github.com/uken/fluent-plugin-elasticsearch/pull/710

/cc  @cosmo0920 

Edit:

I've scrolled through the merge request and discovered a major change, which might cause the issue ~~(i'll verify this tomorrow)~~. (This behave the same like setting max and min version identical)
@cosmo0920 you've changed the default from passing `ssl_version` to passing `ssl_min_version` and `ssl_max_version`.

A further question: Why do you enforce setting `min` and `max` version always together. `openssl s_client -connect` could handle this as expected. 

```
openssl s_client -connect google.de:443 -min_protocol TLSv1
> New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
...
openssl s_client -connect google.de:443 -max_protocol TLSv1.2
> New, TLSv1.2, Cipher is ECDHE-RSA-CHACHA20-POLY1305
```

**Comment by cosmo0920** [comment]
> A further question: Why do you enforce setting `min` and `max` version always together. `openssl s_client -connect` could handle this as expected.

This is because for older Elasticsearch.
But now, Elasticsearch mainline should be 6.x and 7.x.
I'll set TLSv1.2 for min/max ssl versions.

**Comment by cosmo0920** [comment]
Could you tell me why specifyng `min_ssl_version` and `max_ssl_version` in configuration is not enough for you?

**Comment by tonobo** [comment]
Why do you set ssl versions at all? I did not expect that you're setting custom default, basically everything is using the OS default. I understand that it's useful to provide the ability of applying custom ssl setting at all but overriding the os default isn't what i've expected.

> Could you tell me why specifyng min_ssl_version and max_ssl_version in configuration is not enough for you?

I didn't get the reason why you actively prevent users from using min_version only

**Comment by cosmo0920** [comment]
fluent-plugin-elasticsearch does not handle outside Fluentd environment such as openssl default protocol version.

**Comment by cosmo0920** [comment]
And this issue **does not follow issue template**.
So, I close this.

**Comment by tonobo** [comment]
As requested i've updated the issue description according to your guidlines.

**Comment by tonobo** [comment]
> fluent-plugin-elasticsearch does not handle outside Fluentd environment such as openssl default protocol version.

I guess there is a misunderstanding. Could you tell my why `fluent-plugin-elasticsearch` is specifying an default `ssl_version` at all? That's what I couldn't understand at the moment.

**Comment by cosmo0920** [comment]
This is because elasticsearch-ruby requests it. That's all.

**Comment by tonobo** [comment]
That's not true. I've noticed no issues by using elasticsearch-ruby only. The elasticsearch-transport is passing the ssl connection settings via faraday to the underlaying driver. At the moment we're using [excon](https://github.com/excon/excon)

**Comment by tonobo** [comment]
You've introduced the ssl_version default by merging https://github.com/uken/fluent-plugin-elasticsearch/pull/299

The reason for setting a default here doesn't makes sense in my mind and also does not apply to:
> This is because elasticsearch-ruby requests it. That's all.

Please **unset the default value**, and fallback to OS/openssl defaults.

**Comment by Kjarrigan** [comment]
And please allow to set `min_version` and `max_version` on it's own (currently I have to set both). But it makes sense to just e.g. say:
* don't use Version older than 1.2 (min_version) because I they are unsecure, but otherwise use whatever the server can handle _or_
* don't use versions bigger then 1.3 because my client can't hand newer versions

openssl allow to set them independently.

**Comment by cosmo0920** [comment]
I don't want to allow nil ssl_version/ssl_(min|max)_version for the following reasons:

1. Fluentd does not know external library version such as openssl.
   1. Only Ruby 2.5 or later case, we can remove completely openssl related configuration parameter. But Fluentd still support Ruby 2.4. We should consider such environment.
   2. I don't like entrust openssl default settings.
1. For debugging purpose. We want to make state explicitly by parameters.

**Comment by cosmo0920** [comment]
>     * don't use versions bigger then 1.3 because my client can't hand newer versions

If TLS v1.3 is not workable in your environment, `ssl_min_version` and `ssl_max_version` are not available. Just using `ssl_version`.
