### ISSUE TITLE
rollover_index true doe not work

### ISSUE THREAD

**Issue by atg22896** [uken/fluent-plugin-elasticsearch#737]
#### Problem
When trying to enable rollover_index and the deflector_alias they do not seem to do anything.
...

#### Steps to replicate

```
<match docker.**>
  @type elasticsearch
  host es01
  port 9200
  rollover_index true
  deflector_alias test-current
  logstash_format true
  logstash_prefix fluent

  tag_key @log_name
  use_gzip_command

  buffer_type memory
  buffer_chunk_limit 256m
  buffer_queue_limit 128
  flush_interval 10s
  disable_retry_limit false
  retry_limit 5
  retry_wait 1s
  max_retry_wait 10s # default is infinite
  num_threads 8
</match>
```
These are the indices:
```
health status index                 uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   fluenttest-2020.04.01 iTtoQvvDQqyJ5UEd8ZHPrg   1   1       4426            0      7.1mb          3.5mb
green  open   .kibana_task_manager  Wp0cO6BaSdWrdIcs9Uobdw   1   1          2            0       91kb         45.5kb
green  open   .kibana_1             xvwFZbKtS_yI7b98aNMUQA   1   1          4            1     69.1kb         34.5kb
green  open   fluent-2020.04.01     brEJEf09TGaQ9BhSZdzrgg   1   1      15390            0       29mb         13.6mb
```

As you can see, only fluent-2020.04.01 is created. The rollover index is not taking effect, and there are not aliases created.

#### Expected Behavior or What you need to ask

I expect the rollover numbers to be appended to the index name, and for an alias to be created.

#### Using Fluentd and ES plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others? Docker container
* Fluentd v0.12 or v0.14/v1.0
  * fluentd 1.1.0

* ES plugin 3.x.y/2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
  
[output.log](https://github.com/uken/fluent-plugin-elasticsearch/files/4416884/output.log)

  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
```
*** LOCAL GEMS ***

cool.io (1.4.6)
did_you_mean (1.0.0)
dig_rb (1.0.1)
elasticsearch (6.0.1)
elasticsearch-api (6.0.1)
elasticsearch-transport (6.0.1)
excon (0.60.0)
faraday (0.14.0)
fluent-plugin-concat (2.0.1)
fluent-plugin-elasticsearch (4.0.7, 2.6.0)
fluent-plugin-elasticsearch-timestamp-check (0.2.7)
fluent-plugin-grok-parser (2.1.2)
fluent-plugin-prometheus (1.0.1)
fluentd (1.1.0, 0.14.13)
http_parser.rb (0.6.0)
json (2.0.3)
msgpack (1.1.0)
multi_json (1.13.1)
multipart-post (2.0.0)
net-telnet (0.1.1)
oj (2.18.3)
power_assert (0.2.6)
prometheus-client (0.7.1)
psych (2.1.0.1)
quantile (0.2.0)
serverengine (2.0.5)
sigdump (0.2.4)
strptime (0.2.3, 0.1.9)
test-unit (3.1.5)
thread_safe (0.3.6)
tzinfo (1.2.2)
tzinfo-data (1.2017.1)
yajl-ruby (1.3.0)
```
I originally only had fluent-plugin-elasticsearch 2.6.0 and I got warnings in the logs for the rollover_index param and deflector_alias param.

**Comment by atg22896** [comment]
Anyone have any idea about why this is happening?

**Comment by atg22896** [comment]
@cosmo0920 Hello, any input?

**Comment by kumaravel29** [comment]
@atg22896 the rollover_index can be used along with customize_template parameter otherwise ignored.

**Comment by atg22896** [comment]
> @atg22896 the rollover_index can be used along with customize_template parameter otherwise ignored.
> https://github.com/uken/fluent-plugin-elasticsearch/blob/master/README.md#rollover_index

If customize_template is set, then this parameter will be in effect otherwise ignored.

What that says is that the rollover_index parameter is ignored only if the customize_template parameter is also used. I am not using customize_template, therefore it should work.

**Comment by kumaravel29** [comment]
@atg22896 it's the other way. The rollover_index is ignored if the custimize_template is **not** set.

**Comment by atg22896** [comment]
@kumaravel29 Ok, I will give that a try - But that is not what the current documentation is saying. I would say it should be re-worded to be more clear.

**Comment by atg22896** [comment]
For example: If customize_template is set, then this parameter will be in effect. Otherwise it will be ignored.

**Comment by kumaravel29** [comment]
You can raise a PR for updating the documentation but the current document is quite clear.

**Comment by cosmo0920** [comment]
Hmm..., @kumaravel29 should answer for this issue.
I think that making rollover_index w/o customize_template to be workable is acceptable for us.

Is there any problem to change behavior for rollover_index, @kumaravel29 ?

**Comment by kumaravel29** [comment]
@cosmo0920 considering the ILM feature, the rollover_index feature should be decoupled from the customize_template.
I will try to create a PR for this.

**Comment by cosmo0920** [comment]
> @cosmo0920 considering the ILM feature, the rollover_index feature may be decoupled from the template creation modules.

Oh, sure thing.

**Comment by cosmo0920** [comment]
When using ILM feature, `rollover_index` is not needed anymore and banned to use `deflector_alias` with `enabled_ilm` as `true` on #786.
This should make more decoupled for rollover_index feature.
But I'm not sure what is needed for more decoupling work....

**Comment by cosmo0920** [comment]
Decoupling work should be in another issue.
I'm closing this issue now.
