### ISSUE TITLE
High cpu usage with unexpected errors

### ISSUE THREAD

**Issue by RageYL** [uken/fluent-plugin-elasticsearch#744]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

Fluentd seems to use a lot of CPU when the plugin cannot connect to elasticsearch (e.g. wrong credentials) or when indices are read only (both 4xx errors).

#### Steps to replicate

You can use any configuration with elasticsearch plugin enabled (e.g. the one you give as example https://gist.github.com/pitr/9a518e840db58f435911). You just need a bad password.

#### Expected Behavior or What you need to ask

I did some digging and it seems an 'unexpected error' is raised and the worker gets killed. Supervisor then restart the worker, which get killed again. On my system this 'loop' consume ~40% CPU. I had the problem happening in production with a much higher load and the result was the same. 
It would be nice if we could handle those errors using a retry_wait/retry_interval instead of crashing and restarting all the time.

#### Using Fluentd and ES plugin versions

* Alpine
* Docker
* v1.9, v1.10
* fluent-plugin-elasticsearch (4.0.7)

**Comment by cosmo0920** [comment]
> It would be nice if we could handle those errors using a retry_wait/retry_interval instead of crashing and restarting all the time.

When workers get some kill signal, they are immediately died. This requests should be impossible to handle/implement in ES plugin.

And no reproducible step doesn't help us.

**Comment by williamzhao87** [comment]
@cosmo0920 
We have the same issue.  I think this issue should be re-opened.  Will the problem need to be handled on FluentD side?
