### ISSUE TITLE
New indexes created without template file settings

### ISSUE THREAD

**Issue by waynetaylor** [uken/fluent-plugin-elasticsearch#755]
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
If a user specifies a template and template values and template is not applied to the cluster already - a new index is created without the index template values e.g. shard/replica counts. 

#### Steps to replicate

1. Install fluentd and elasticsearch plugin
2. Ingest data without having existing template

#### Expected Behavior
Template is injected, installed and new indexes created with template values

#### Using Fluentd and ES plugin versions

- OS version: Ubuntu 18.04 Bionic
- EC2 Deployment
- Fluentd td-agent 1.10.2
- ES plugin 4.0.7

**Comment by cosmo0920** [comment]
> If a user specifies a template and template values and template is not applied to the cluster already - a new index is created without the index template values e.g. shard/replica counts.

What does it mean?
Ingesting data before set up template?

**Comment by waynetaylor** [comment]
@cosmo0920  - sorry if not clear. Imagine this scenario.

Brand new elasticsearch cluster, no templates, no indexes. 

You apply fluentd configuration which outlines a template_name and template_file path with the JSON. You then push messages e.g. fluentbit / debug or whatever method to match your configuration. Then load up Kibana, go to index management -> You will see any data ingested was apply with elasticsearch defaults vs your template.

If I was then to delete the index and ingest new data, the new index has the correct settings.

This may be expected behavior? E.g. is it expected users apply the template on cluster first?

**Comment by cosmo0920** [comment]
>  is it expected users apply the template on cluster first?

This is the expected scenario.

**Comment by waynetaylor** [comment]
Based upon response from @cosmo0920  closing
