### ISSUE TITLE
Setting elasticsearch index dynamically 

### ISSUE THREAD

**Issue by shaloba** [uken/fluent-plugin-elasticsearch#758]
#### Using Fluentd and ES plugin versions

* OS version OSX
* Fluentd 1.10.4/
* ES pluginelasticsearch (7.7.0) elasticsearch-api (7.7.0) elasticsearch-transport (7.7.0)
* ES version 7.4
* ES template json

#### Problem
I'm trying to forward logs to elastic-search and got stuck with setting the index dynamically (by field in the input data) my input data format is json and always have the key "es_idx". i wish to forward to elasticsearch by that key and add it timestamp, i use logstash_format true to achieve the timestamp feature and logstash_prefix to set the index name other than "fluentd"

this is how my fluentd config looks like:

```
# fluentd/conf/fluent.conf
<source>
  type stdin
  # Input pattern. It depends on Parser plugin
  format json

  # Optional. default is stdin.events
</source>

<match *.**>
  @type copy
  <store>
    @type stdout
  </store>
  <store>
    @type elasticsearch
    host <es-host>
    port<es-port>
    logstash_format true
    logstash_prefix ${$record["es_idx"]}
    type_name fluentd
    flush_interval 5s
  </store>

</match>

```

when using the following input {"tenant_id":"test","es_idx":"blabla"} I'm getting the following error:

```
2020-05-27 10:38:06 +0300 [warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch" location=nil tag="stdin.events" time=2020-05-27 10:37:59.498450000 +0300 record={"tenant_id"=>"test", "es_idx"=>"blabla"}

```

if i'm setting the logstash_pattern to other string like this : "logstash_pattern blabla" it works fine.
 I don't know if its a bad use or a bug but i tried almost every thing

**Comment by cosmo0920** [comment]
Your placeholder usage is wrong.
${tag} or %Y%m%d like strftime format string or ${custom_field} should be usable as built-in placeholders:

```aconf
  <store>
    @type elasticsearch
    host <es-host>
    port<es-port>
    logstash_format true
    logstash_prefix ${es_idx}
    type_name fluentd
    flush_interval 5s
    <buffer tag, es_idx>
      @type memory
    </buffer>
  </store>
```

see: https://github.com/uken/fluent-plugin-elasticsearch#custom-key

**Comment by shaloba** [comment]
thanks you @cosmo0920 works great, my bad
