### ISSUE TITLE
Index template does not work with logstash_format

### ISSUE THREAD

**Issue by TheodorAtBud** [uken/fluent-plugin-elasticsearch#761]
#### Problem

Using the following configuration the plugin creates an index of the format 'audit-log-{date}-0001', but it creates an index template with name 'audit-{date}' and index pattern 'audit-{date}-*'. 
Hence the index template never gets applied to my index. 

```
        logstash_format true
        logstash_prefix audit
        application_name log
        index_separator '-'
        index_date_pattern "now/d"
        enable_ilm true
        ilm_policy_id retention-policy
        ilm_policy { "policy": { "phases": { "hot": { "min_age": "0ms", "actions": { "rollover": { "max_age": "1d", "max_size": "5gb" } } }, "delete": { "min_age": "2d", "actions": { "delete": {}}}}}}
        ilm_policy_overwrite true
        # Template name is not used if ilm is in effect but it's mandatory parameter
        template_name audit_template
        template_overwrite true
        template_file /fluentd/etc/fluentd-template.json
```

#### Expected Behavior

I would expect the correct template_name i.e. 'audit-log' and index-pattern 'audit-log-*' to be created.

#### Using Fluentd and ES plugin versions

* Kubernetes
* Fluentd v1.10.2
* ES plugin 4.0.3

**Comment by cosmo0920** [comment]
Could you provide using template? 
Using only reported configuration is not reproducible your issue.

**Comment by Steve-Louie-Bose** [comment]
I'm seeing the same behavior.

It looks like the indices are made with `<logstash_prefix><index_separator><application_name><index_separator><date><index_separator><rollover-counter>`. 

But the index template generated does not include the `<application_name>` when it generates the regex for `index_patterns`, so it ends up with `<logstash_prefix><index_separator><date><index_separator>*` and does not match the index created by the plugin here. I tried plugin version `v4.0.9`, `v4.0.0` and `v4.0.10` 

My template index_patterns get overwritten by this plugin.

**Comment by Steve-Louie-Bose** [comment]
I wouldn't call myself a ruby person, but I suspect the issue is here. 

https://github.com/uken/fluent-plugin-elasticsearch/blob/49f1edeb654dcc0db0d10b1b87fd21ce0b8c0321/lib/fluent/plugin/out_elasticsearch.rb#L943

`deflector_alias` is unassigned when logstash_format is true. Maybe that should optionally be set to `application_name`? Not sure of other consequences of changing the values here.

**Comment by cosmo0920** [comment]
Thanks for the detailed break downing. I'll investigate this issue.

**Comment by cosmo0920** [comment]
I'd registered a PR to fix this: https://github.com/uken/fluent-plugin-elasticsearch/pull/779
Could you try this patch?

**Comment by Steve-Louie-Bose** [comment]
I just did an initial build / test and it looks good so far. I have a pretty simple index template and configuration just for my sanity check. I'll post back once I try something more complex.

**Comment by Steve-Louie-Bose** [comment]
It doesn't look like its working for a more advanced use case.

I'm trying something like this https://github.com/kubernetes/kubernetes/issues/23001#issuecomment-462538401

Which is dynamically naming indices based on values in the records. The ilm is doing a literal string copy of the value `${record['kubernetes']['namespace_name']}` instead of what that would evaluate to, which I get is happening on the fly as records come through. Is there a way to make a more dynamic ilm configuration work?

**Comment by Steve-Louie-Bose** [comment]
I was able to achieve the desired behavior by pre-processing the records

**Comment by cosmo0920** [comment]
> I was able to achieve the desired behavior by pre-processing the records

Yep, with record-transformer or record-modifier to manipulate is safer in this case.

The commented configuration seems to be wrong.
Including record['kubernetes']['namespace_name'] values should be needed to replace with built-in placeholder.

Correct one is:

```aconf
<match **>
  @type elasticsearch
  #user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
  #password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
  @log_level info
  include_tag_key true
  host "#{ENV['OUTPUT_HOST']}"
  port "#{ENV['OUTPUT_PORT']}"
  logstash_format true
  logstash_prefix logstash-${$.kubernetes.namespace_name}
  <buffer tag, $.kubernetes.namespace_name>
    @type file
    path /var/log/fluentd-buffers/kubernetes.system.buffer
    flush_mode interval
    retry_type exponential_backoff
    flush_thread_count 2
    flush_interval 5s
    retry_forever
    retry_max_interval 30
    chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
    queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
    overflow_action block
  </buffer>
</match>
```

ref: https://docs.fluentd.org/configuration/buffer-section#nested-field-support
