### ISSUE TITLE
How does the Input plug-in set incremental reads

### ISSUE THREAD

**Issue by xidiandb** [uken/fluent-plugin-elasticsearch#765]
#### Problem
Can the Input plug-in only be queried in full？How can I read data incrementally

#### Steps to replicate
The configuration looks like this:
 ```
<source>
  @type elasticsearch
  host elasticsearch
  port 9200
  index_name test
  tag my.logs
</match>
```
Each time I get the full amount of data in the index

#### Expected Behavior or What you need to ask

How do I configure to get incremental data without duplicates

**Comment by cosmo0920** [comment]
There is no incremental reading support.
This plugin should be assumed for creating replication with metadata.
https://github.com/uken/fluent-plugin-elasticsearch/blob/master/README.ElasticsearchInput.md#advanced-usage

**Comment by cosmo0920** [comment]
Elasticsearch does not support incremental query searching.
Fluentd plugin won't support this.
