### ISSUE TITLE
elasticsearch_genid generates a different id for the exact same log

### ISSUE THREAD

**Issue by toyaser** [uken/fluent-plugin-elasticsearch#767]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

I am trying to figure out how the elasticsearch_genid generates its id.

If I have the exact same log entry, I delete the line from the pos file so that its the same file. The _id field in elastic is different for the exact same log.

I wanted to make sure that i am using the correct configuration.

This is needed since we are running into issues with fluentd going down and I would like to be able to just update the pos file and expect fluentd to reship the same file again but just update the documents instead of create duplicates.

At the moment, since the _id is different it creates duplicates.

I have included my configuration below.

#### Steps to replicate
```
<source>
    @type tail
    @id in_my_log
    path "C:/Source/my-log-*.log"
    pos_file "C:/opt/td-agent/etc/td-agent/pos_files/my-log.pos"
    tag "my-logs.*"
    enable_watch_timer false
    enable_stat_watcher true
    read_from_head true
    <parse>
      @type "json"
    </parse>
  </source>
  <filter my-logs.**>
    @type elasticsearch_genid
    hash_id_key somethingid
  </filter>
  <match my-logs.**>
    @type copy
    <store>
      id_key somethingid
      remove_keys somethingid
      @type "elasticsearch"
      @log_level debug
      host "10.1.1.1"
      port 9200
      scheme http
      logstash_format true
      logstash_prefix "myindex"
      logstash_dateformat "%Y.%m"
      include_tag_key true
      user "elastic"
      password "password"
      type_name "_doc"
      tag_key "@log_name"
      <buffer>
        flush_thread_count 8
        flush_interval 5s
      </buffer>
    </store>
  </match>
```

#### Expected Behavior or What you need to ask

Generate the same _id for a json blob that is on one line so that Elastic will update the document instead of create a duplicate

#### Using Fluentd and ES plugin versions

* OS version
* Windows Server 2012
* Td-agent 3.7.1

**Comment by cosmo0920** [comment]
This is because filter?elasticsearch_genid just uses SecureRandom.uuid for calculating base64 id.
https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/filter_elasticsearch_genid.rb#L20
Calculating base64 id causes serious performance impact.
Should we provide way to calculate base64 ids from record's md5 or sha1?

**Comment by toyaser** [comment]
Thank you very much @cosmo0920. I should have just looked at the code (my ruby isnt great :blush: )

Im surprised this hasnt come up before?

I think if we can generate the base64 if from the records md5 or sha1 that would be great.

I know the README talks about using fluent-plugin-genhashvalue (i am having problems adding this plugin in windows) but as you can see it kind of does this:
```
<filter logs.**>
  @type genhashvalue
  keys session_id,request_id
  hash_type md5    # md5/sha1/sha256/sha512
  base64_enc true
  base91_enc false
  set_key _hash
  separator _
  inc_time_as_key true
  inc_tag_as_key true
</filter>
```

And thats what i thought the elasticsearch_genid filter would do.

**Comment by cosmo0920** [comment]
I'd registered a PR to fix this issue. Could you try it out, @toyaser ?

**Comment by toyaser** [comment]
Thank you very much @cosmo0920 . To save you the time, i will be creating another PR based on this feature. I will be adding another flag e.g. use_all_record_keys which defaults to false. IF that flag is set to true, it will ignore the record_keys and use the entire record (this is our case where i know that the combination of all the fields will be unique).
Does that make sense?

**Comment by cosmo0920** [comment]
Yep, it makes sense.

**Comment by cosmo0920** [comment]
Hash generating from record feature which is also included entire record originated hash had been shipped in v4.0.10.
Thanks for the feature request!
User feedback and feature request would be helpful for us!!!

**Comment by g3kr** [comment]
Even this is not working for us @cosmo0920 @toyaser . Any thoughts on what I could be missing? https://github.com/uken/fluent-plugin-elasticsearch/issues/899

**Comment by toyaser** [comment]
@g3kr hopefully this is ok, but we have ended up writing our own updated has generator here https://github.com/Labou77Code/fluent-plugin-genhashvalue-alt
