### ISSUE TITLE
Fluentd stops randomly "0 suppressed same stacktrace"

### ISSUE THREAD

**Issue by tirelibirefe** [uken/fluent-plugin-elasticsearch#778]
(check apply)
- [ok ] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
Although I don't have a complex configuration, Fluentd stops randomly. If I do something cause pod's recreated, it runs for a while than couple of hours later stops again.

```
2020-07-06 07:58:43 +0000 [warn]: #0 [elasticsearch] failed to flush the buffer. retry_time=1643 next_retry_seconds=2020-07-06 07:59:17 +0000 chunk="5a9ba6e6a532f98d1337d7d81573ab70" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"escluster-es-http.elastic-system.svc.cluster.local\", :port=>9200, :scheme=>\"https\", :user=>\"elastic\", :password=>\"obfuscated\"}): end of file reached (EOFError)"
  2020-07-06 07:58:43 +0000 [warn]: #0 suppressed same stacktrace
2020-07-06 07:58:43 +0000 [warn]: #0 [elasticsearch] failed to flush the buffer. retry_time=1644 next_retry_seconds=2020-07-06 07:59:16 +0000 chunk="5a9ba6e5b3ce87008b1fc1692934c273" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"escluster-es-http.elastic-system.svc.cluster.local\", :port=>9200, :scheme=>\"https\", :user=>\"elastic\", :password=>\"obfuscated\"}): end of file reached (EOFError)"
  2020-07-06 07:58:43 +0000 [warn]: #0 suppressed same stacktrace
```
...

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

**OR**

Provide example config and message

I use stable/fluentd chart.

```
# Default values for fluentd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: gcr.io/google-containers/fluentd-elasticsearch
  tag: v2.4.0
  pullPolicy: IfNotPresent
  # pullSecrets:
  #   - secret1
  #   - secret2

output:
  host: escluster-es-http.elastic-system.svc.cluster.local
  port: 9200
  scheme: https
  sslVersion: TLSv1_2
  buffer_chunk_limit: 2M
  buffer_queue_limit: 8

env: {}

# Extra Environment Values - allows yaml definitions
extraEnvVars:
  - name: ELASTICSEARCH_HOST
    value: "escluster-es-http.elastic-system.svc.cluster.local"
  - name: ELASTICSEARCH_PORT
    value: "9200"
  - name: ELASTICSEARCH_USERNAME
    value: elastic
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: escluster-es-elastic-user
        key: elastic

# extraVolumes:
#   - name: es-certs
#     secret:
#       defaultMode: 420
#       secretName: es-certs
# extraVolumeMounts:
#   - name: es-certs
#     mountPath: /certs
#     readOnly: true

plugins:
  enabled: false
  pluginsList: []

service:
  annotations: {}
  type: ClusterIP
  # loadBalancerIP:
  # type: NodePort
  # nodePort:
  # Used to create Service records
  ports:
    - name: "monitor-agent"
      protocol: TCP
      containerPort: 24220

metrics:
  enabled: true
  service:
    port: 24231
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    namespace: monitoring
    interval: 30s
    scrapeTimeout: 10s

annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "24231"

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
#    kubernetes.io/tls-acme: "true"
#    # Depending on which version of ingress controller you may need to configure properly - https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target
#    nginx.ingress.kubernetes.io/rewrite-target: /
  labels: []
  # If doing TCP or UDP ingress rule don't forget to update your Ingress Controller to accept TCP connections - https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/
  hosts:
#     - name: "http-input.local"
#       protocol: TCP
#       servicePort: 9880
#       path: /
  tls: {}
  # Secrets must be manually created in the namespace.
#    - secretName: http-input-tls
#      hosts:
#        - http-input.local

configMaps:
  general.conf: |
    # Prevent fluentd from handling records containing its own logs. Otherwise
    # it can lead to an infinite loop, when error in sending one message generates
    # another message which also fails to be sent and so on.
    <match fluentd.**>
      @type null
    </match>

    # Used for health checking
    <source>
      @type http
      port 9880
      bind 0.0.0.0
    </source>

    # Emits internal metrics to every minute, and also exposes them on port
    # 24220. Useful for determining if an output plugin is retryring/erroring,
    # or determining the buffer queue length.
    <source>
      @type monitor_agent
      bind 0.0.0.0
      port 24220
      tag fluentd.monitor.metrics
    </source>
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>
  forward-input.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
  output.conf: |
    <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level info
      include_tag_key true
      # Replace with the host/port to your Elasticsearch cluster.
      host "#{ENV['OUTPUT_HOST']}"
      port "#{ENV['OUTPUT_PORT']}"
      scheme "#{ENV['OUTPUT_SCHEME']}"
      ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
      logstash_format true
      logstash_prefix fluentd
      include_tag_key     true
      ssl_verify false
      verify_es_version_at_startup false
      user elastic
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
        queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
        overflow_action block
      </buffer>
    </match>
...
```

#### Expected Behavior or What you need to ask

I increased, changed buffer and chunk values, nothing changed. It stops when the buffer is filled.

  buffer_chunk_limit: 2M
  buffer_queue_limit: 8

The following settings doesn't affect; I can remove or they can stay, not sure.

      logstash_format true
      logstash_prefix fluentd
      include_tag_key     true

How can I get rid of "0 suppressed same stacktrace" error?

#### Using Fluentd and ES plugin versions

* OS version Kubernetes 1.18
* Bare Metal or within Docker or Kubernetes or others? Baremetal Kubernetes on Vsphere Kubespray
* Fluentd v0.12 or v0.14/v1.0 v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version`` the latest one.
* ES plugin 3.x.y/2.x.y or 1.x.y the latest one. it must be 3.x
  * paste boot log of fluentd or td-agent, I don't know how to check.
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
* ES version (optional) 7.8
* ES template(s) (optional)

**Comment by cosmo0920** [comment]
You've hit this case?
**https://github.com/uken/fluent-plugin-elasticsearch#stopped-to-send-events-on-k8s-why**

**Comment by tirelibirefe** [comment]
Thanks @cosmo0920 
I'm trying, I'll let you know.

**Comment by tirelibirefe** [comment]
The problem wasn't disappeared completely but at least Fluentd tries to flush chunks, sometimes succeeds sometimes not.

[fluentd-logs.zip](https://github.com/uken/fluent-plugin-elasticsearch/files/4878182/fluentd-logs.zip)

**Comment by cosmo0920** [comment]
How about adding sniffer class settings like this?
https://github.com/fluent/fluentd-kubernetes-daemonset/pull/403/files

**Comment by tirelibirefe** [comment]
Where/how should I add ""#{ENV['FLUENT_SNIFFER_CLASS_NAME']" in helm chart?

**Comment by tirelibirefe** [comment]
I changed output config as below based on [https://github.com/fluent/fluentd-kubernetes-daemonset/pull/403/files](https://github.com/fluent/fluentd-kubernetes-daemonset/pull/403/files)
 ```
   <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level info
      include_tag_key true
      # Replace with the host/port to your Elasticsearch cluster.
      host "#{ENV['OUTPUT_HOST']}"
      port "#{ENV['OUTPUT_PORT']}"
      scheme "#{ENV['OUTPUT_SCHEME']}"
      ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
      logstash_format true
      include_tag_key true
      type_name fluentd
      time_key @timestamp
      include_timestamp true
      reconnect_on_error true
      reload_on_failure true
      reload_connections false
      request_timeout 120s
      ssl_verify false
      verify_es_version_at_startup false
      user elastic
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
        queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
        overflow_action block
      </buffer>
    </match>
```
Things look like working right now but not sure it will keep working or stop again...

**Comment by tirelibirefe** [comment]
I added @label as described in the link; still working.

```
    <label @ES>
      <match **>
        @id elasticsearch
        @type elasticsearch
        @log_level info
        include_tag_key true
        # Replace with the host/port to your Elasticsearch cluster.
        host "#{ENV['OUTPUT_HOST']}"
        port "#{ENV['OUTPUT_PORT']}"
        scheme "#{ENV['OUTPUT_SCHEME']}"
        ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
        logstash_format true
        include_tag_key true
        type_name fluentd
        time_key @timestamp
        include_timestamp true
        reconnect_on_error true
        reload_on_failure true
        reload_connections false
        request_timeout 120s
        ssl_verify false
        verify_es_version_at_startup false
        user elastic
        password "#{ENV['ELASTICSEARCH_PASSWORD']}"
        <buffer>
          @type file
          path /var/log/fluentd-buffers/kubernetes.system.buffer
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 2
          flush_interval 5s
          retry_forever
          retry_max_interval 30
          chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
          queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
          overflow_action block
        </buffer>
      </match>
    </label>
```

**Comment by cosmo0920** [comment]
> Where/how should I add ""#{ENV['FLUENT_SNIFFER_CLASS_NAME']" in helm chart?

I'm not sure 'cause I'm not ES helm chart maintainer.
You should raise issue in helmet chart repository for this question.

**Comment by tirelibirefe** [comment]
is "#{ENV['FLUENT_SNIFFER_CLASS_NAME']" a output conf? Will it help us identify find the root cause?

**Comment by tirelibirefe** [comment]
is this an error message?

`2020-07-06 11:21:25 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch" location=nil tag="kube.var.log.containers.monitoring-grafana-5d55c6d598-hn8qn_monitoring_grafana-sc-dashboard-8d25c4c792a0cf3bbcda6977768cb1e7bb49f0e0a6a7d5d9a8c8c414aafe491f.log" time=2020-07-06 11:20:12.093398236 +0000 record={"log"=>"[2020-07-06 11:20:12] File in configmap etcd.json ADDED\n", "stream"=>"stdout", "time"=>"2020-07-06T11:20:12.093398236Z", "kubernetes"=>{"pod_name"=>"monitoring-grafana-5d55c6d598-hn8qn", "namespace_name"=>"monitoring", "pod_id"=>"913b400f-2943-4c76-bfbf-ce1ec3226842", "labels"=>{"app.kubernetes.io/instance"=>"monitoring", "app.kubernetes.io/name"=>"grafana", "pod-template-hash"=>"5d55c6d598"}, "annotations"=>{"checksum/config"=>"40f750a25d58e429b8dcdb894e94bb4668f6bc087826e585274c8427c08897b3", "checksum/dashboards-json-config"=>"01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b", "checksum/sc-dashboard-provider-config"=>"b1345365bf24f5454070b86d81669b78714bcfa08bce824a4f97ee11e432f2e1", "checksum/secret"=>"7011ea8d5badc45b46369dfae0a5ff5344fade7f2a8e5ffcd6dc2cf15e840745"}, "host"=>"dev1-worker2", "container_name"=>"grafana-sc-dashboard", "docker_id"=>"01fdc92b002815e54b91664ae123bff49c85a7608978990f3a76b8c15475f380", "container_hash"=>"7b98eecdf6d117b053622e9f317c632a4b2b97636e8b2e96b311a5fd5c68d211"}}`

**Comment by cosmo0920** [comment]
I'm not sure for your ES error log.
It just says "400 - Rejected by Elasticsearch".
https://github.com/uken/fluent-plugin-elasticsearch#log_es_400_reason might help.

**Comment by tirelibirefe** [comment]
...
You can set this true to capture the 400 error reasons without all the other debug logs.
Default value is false.
...

Which settings is mentioned there? Is it meant "@log_level info"?

**Comment by tirelibirefe** [comment]
after the last config, there are no more "400 - Rejected by Elasticsearch", so I don't need to debug further.
thank you very much @cosmo0920 , you helped me a lot.
