### ISSUE TITLE
 [warn]: parameter 'compression_level' in <match **>is not used

### ISSUE THREAD

**Issue by liuhename** [uken/fluent-plugin-elasticsearch#780]
#### Problem

The Parameter 'compression Level' doesn't work

2020-07-08 08:21:09 +0000 [warn]: parameter 'compression_level' in <match **>

The config yaml as below:

   <match **>
      @id containter
      @type elasticsearch
      @log_level info
      include_tag_key true
      logstash_format true
      logstash_prefix fluentd
      request_timeout 120s
      host es-cluster
      port 9200
      scheme http
      type_name _doc
    compression_level best_compression
  </match>

#### Using Fluentd and ES plugin versions
 Kubernetes 

elasticsearch (7.7.0)
elasticsearch-api (7.7.0)
elasticsearch-transport (7.7.0)
fluent-plugin-elasticsearch (2.4.1)
fluentd (1.1.0)

**Comment by cosmo0920** [comment]
This is because your using ES plugin is too old.
`compression_level` had been introduced in v3.6.1:
https://github.com/uken/fluent-plugin-elasticsearch/commit/4d47f992f93facd830e7a912a1fac59ac56f9e46
This is not an issue on current ES plugin.
Closing.
