### ISSUE TITLE
data in ILM with logstash format writing to wrong index

### ISSUE THREAD

**Issue by dongsiji** [uken/fluent-plugin-elasticsearch#783]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

With logstash format enabled and ilm enabled, the data from my logs are being written to index "fluentd-2020.07.13" instead of the ilm index "fluentd-log-2020.07.13-000001".

![image](https://user-images.githubusercontent.com/35907419/87290029-0c149900-c530-11ea-9429-a5a1bfde2c4c.png)

#### Steps to replicate

Config file:

```
    <label @FLUENT_LOG>
      <match fluent.**>
        @type null
      </match>
    </label>

    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      refresh_interval 1
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
        time_type string
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <match kubernetes.**>
      @type elasticsearch
      @log_level info
      logstash_format true
      logstash_prefix fluentd
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
      type_name _doc
      template_name fluentd
      template_file /fluentd/etc/fluentd-template.json
      template_overwrite true
      reload_connections true
      reconnect_on_error true
      reload_on_failure true
      index_date_pattern "now/d"
      enable_ilm true
      ilm_policy_id fluentd
      application_name log
      <buffer>
        flush_thread_count 8
        flush_interval 1s
        chunk_limit_size 2M
        queue_limit_length 32
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>
```

#### Expected Behavior or What you need to ask

Expected behavior is for the logs to be written to my ilm index "fluentd-log-2020.07.13-000001" for it to be under ilm policies.

#### Using Fluentd and ES plugin versions

Kubernetes
Fluentd v1.0
ES plugin v4.1.0
ES v7.8.0

**Comment by dongsiji** [comment]
Took a look at the source code, feels like the cause was this line here where it didn't take into account whether ilm support was enabled or not.
```target_index = "#{logstash_prefix}#{@logstash_prefix_separator}#{dt.strftime(logstash_dateformat)}"```

**Comment by cosmo0920** [comment]
I'd confirmed that this issue can be reproducible in my environment.
I'll take a look.

**Comment by cosmo0920** [comment]
I'd written a patch for fixing this: #786 
Could you try it out?
