### ISSUE TITLE
ES 7.x: [types removal] Specifying types in bulk requests is deprecated.

### ISSUE THREAD

**Issue by DandyDeveloper** [uken/fluent-plugin-elasticsearch#785]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
Deprecated types is present in documents managed by latest fluentd version (Possibly the fluentd_elasticsearch plugin):

Same issue described here in fluentbit: https://github.com/fluent/fluent-bit/issues/1359
```
warning: 299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "[types removal] Specifying types in bulk requests is deprecated."
warning: 299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "[types removal] Specifying types in bulk requests is deprecated."
warning: 299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "[types removal] Specifying types in bulk requests is deprecated."
```

#### Steps to replicate
Forward a document via the `elasticsearch` output plugin on any 7.X instance.

#### Expected Behavior or What you need to ask
Correct doc type used in bulk requests to ES API. 

#### Using Fluentd and ES plugin versions
- Fluentd 1.11-1 (Docker Image) / Latest ES Plugin
* Bare Metal 
* ES version (optional) 7.8

**Comment by cosmo0920** [comment]
https://github.com/uken/fluent-plugin-elasticsearch#suppress_type_name ?

**Comment by DandyDeveloper** [comment]
@cosmo0920 ... Yeah that has done the job... 

I'll RTFM next time. Thank you!

**Comment by cosmo0920** [comment]
Could you check unused parameter warning is raised from Fluentd on container? Thanks in advance.

**Comment by cdekok** [comment]
Does not work for me either, also the fix should probably not be to suppress the error as in ES v8 the functionality will be removed.
https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html#_why_are_mapping_types_being_removed

**Comment by moreinhardt** [comment]
@cdekok I was scared this only suppresses the warning too. But a look in the code (via related PRs) shows this is handled properly :wink: 

https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L909..L912

**Comment by cdekok** [comment]
yes i see that's good to know and setting the default es version to 7 seemed to help the error to go away. This was on a slightly older version though perhaps that was the issue.

**Comment by Whissi** [comment]
It's hardcoded https://github.com/rsyslog/rsyslog/blob/v8.2012.0/plugins/omelasticsearch/omelasticsearch.c#L2092-L2093 ... we will probably need a new option.
