### ISSUE TITLE
illegal_argument_exception: index [messages-32] is not the write index for alias [messages]

### ISSUE THREAD

**Issue by himanshigpta** [uken/fluent-plugin-elasticsearch#789]
(check apply)
- [ ] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
I'm facing issue while applying ILM on existing indexes. I've read a lot of issues, but nothing really helped yet. Somehow the index versions keep increasing automatically after 7 days, in this case messages-31,32 and so on, something that I haven't configured. In order to apply a policy, I've first created a Lifecycle policy(50gb_rollover), then a template with the following settings :
```
{
  "index": {
    "lifecycle": {
      "name": "50gb_rollover",
      "rollover_alias": "messages"
    },
    "number_of_shards": "3",
    "number_of_replicas": "1"
  }
}

```
For last week's index version(messages-31), applied the policy using below method and I could see the policy properly mapped:
```
POST /_aliases
{
  "actions" : [
    { "add" : { "index" : "messages-31", "alias" : "messages" } }
  ]
}

```
This week after rollover I can see messages-32 & messages-000032, where messages-32 has the following error:
`illegal_argument_exception: index.lifecycle.rollover_alias [messages] does not point to index [messages-32]`

If I try POST /_aliases on messages-32, I get below error:
`illegal_argument_exception: source alias [messages] does not point to a write index`

On the other hand, messages-000032 which seems to be the 'write' index has 0 docs, n I can see the doc count increasing for messages-32. Even if forcefully try to make is_write_index false for messages-32 via below:
```
POST /_aliases
{
    "actions" : [
        {
            "add" : {
                 "index" : "messages-000032",
                 "alias" : "messages",
                 "is_write_index" : true
            }
        },
        {
            "add" : {
                 "index" : "messages-32",
                 "alias" : "messages",
                 "is_write_index" : false
            }
        }
    ]
}

```
td-agent keeps writing on messages-32, if I close it it stops sending anything to ES at all with following error:

`[warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch [error type]: index_closed_exception [reason]: 'closed'" location=nil tag="stack2new.trace"`

I've tried this with td-agent of multiple versions of different servers including the latest td-agent 1.11.1(as it solved the previous issue https://github.com/uken/fluent-plugin-elasticsearch/issues/770) , issue remains the same.

My td-agent config looks like this:

```
<source>
  @type tail
  path /var/log/messages
  pos_file /path/to/var_log_msg_grok.log.pos
  time_format %b %dT%H:%M:%SZ
  tag var.msg
 # read_from_head true
  <parse>
    @type multiline_grok
#    multiline_start_regexp /[\w]+ \d{1,2} \d{1,2}:\d{1,2}:\d{1,2}/
    <grok>
     pattern %{SYSLOGTIMESTAMP:time}%{SPACE}%{HOSTNAME:hostname}%{SPACE}%{GREEDYDATA:service_name}:%{GREEDYDATA:log_meassage}
    </grok>
  </parse>
</source>

<filter var.msg>
    @type record_modifier
     <record>
     hostname "#{Socket.gethostname}"
     formatted_time ${Time.at(time).iso8601(3)}
     </record>
     char_encoding utf-8
     char_encoding utf-8:euc-jp
</filter>

<match var.msg>
  @type elasticsearch
  log_es_400_reason true
  user redacted
  password redacted
  type_name "_doc"
  ssl_version TLSv1_2
  ca_file "/path/to/abc.crt"
  hosts redacted
  scheme "https"
  logstash_format true
  logstash_dateformat %V
  logstash_prefix messages
  include_timestamp true
  reconnect_on_error true
  reload_on_failure true
  <buffer>
    @type file
    path /path/to/messages/buffers
    chunk_limit_size 1M
    flush_interval 5s
    retry_forever false
    retry_max_times 3
    retry_wait 10
    retry_max_interval 300
    flush_thread_count 8
  </buffer>
</match>
```
...

#### Expected Behavior or What you need to ask
I want td-agent to pick and write to the correct write index which in this case would be messages-000032
...

#### Using Fluentd and ES plugin versions

```
td-agent --version
td-agent 1.6.3

cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)

ES version 7.5.1

```

**Comment by cosmo0920** [comment]
Unfortunately, td-agent 1.6.3 and the latest version of 3.8.0 are not working correctly for ES ILM feature.
Could you update td-agent version to v3.8.0 and upgrade fluent-plugin-elasticsearch to v4.1.1?

**Comment by cosmo0920** [comment]
I'm using the following configuration during the two weeks, nothing illiegal error happens...

```aconf
  <match **>
    @type elasticsearch
    @id out_es
    @log_level "info"
    include_tag_key true
    host "elasticsearch-master.default.svc"
    port 9200
    path ""
    scheme http
    ssl_verify true
    ssl_version TLSv1_2
    user "elastic"
    password xxxxxx
    reload_connections false
    reconnect_on_error true
    reload_on_failure true
    log_es_400_reason false
    logstash_prefix "logstash"
    logstash_dateformat "%Y.%m.%d"
    logstash_format true
    index_name "logstash"
    type_name "fluentd"
    include_timestamp false
    template_name "logstash-default"
    template_file "/host/index_template.json"
    template_overwrite false
    sniffer_class_name "Fluent::Plugin::ElasticsearchSimpleSniffer"
    request_timeout 5s
    suppress_type_name true
    enable_ilm true
    ilm_policy_id logstash-policy
    ilm_policy { "policy": { "phases": { "hot": { "min_age": "0ms", "actions": { "rollover": { "max_age": "1d", "max_size": "5gb" } } }, "delete": { "min_age": "2d", "actions": { "delete": {}}}}}}
    ilm_policy_overwrite false
    <buffer>
      flush_thread_count 8
      flush_interval 5s
      chunk_limit_size 2M
      queue_limit_length 32
      retry_max_interval 30
      retry_forever true
    </buffer>
  </match>
```

Note that when passing `ilm_policy`, `enable_ilm` as `true` and template related parameters into Fluentd, Fluentd calculated automatically alias for indices and applying template for ILM managing.

**Comment by himanshigpta** [comment]
@cosmo0920 Thanks for the sample config, I'll try it! Can this be used with the below td-agent & gem versions:

```
# td-agent-gem list | grep elastic
elasticsearch (7.8.0)
elasticsearch-api (7.8.0)
elasticsearch-transport (7.8.0)
fluent-plugin-elasticsearch (4.0.9)

# td-agent --version
td-agent 1.11.1

# rpm -qa | grep td-agent
td-agent-4.0.0-1.el7.x86_64
```

I dont really wish to downgrade the version since this combination prevented the EOF errors reported earlier(https://github.com/uken/fluent-plugin-elasticsearch/issues/770)

**Comment by himanshigpta** [comment]
@cosmo0920 Thanks for the sample config! Would this work fine with the below td-agent and gem version? : 

```
# td-agent-gem list | grep elastic
elasticsearch (7.8.0)
elasticsearch-api (7.8.0)
elasticsearch-transport (7.8.0)
fluent-plugin-elasticsearch (4.0.9)

# td-agent --version
td-agent 1.11.1

# rpm -qa | grep td-agent
td-agent-4.0.0-1.el7.x86_64
```

**Comment by cosmo0920** [comment]
> @cosmo0920 Thanks for the sample config! Would this work fine with the below td-agent and gem version? :
> 
> ```
> # td-agent-gem list | grep elastic
> elasticsearch (7.8.0)
> elasticsearch-api (7.8.0)
> elasticsearch-transport (7.8.0)
> fluent-plugin-elasticsearch (4.0.9)
> ```

No. fluent-plugin-elasticsearch should be upgraded to 4.1.1 with:

```
$ td-agent-gem update fluent-plugin-elasticsearch
```

**Comment by cosmo0920** [comment]
> 2020-08-23 21:30:49 +0530 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `ilm' for #<Elasticsearch::Transport::Client:0x00007fa99e85cd08>"
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/elasticsearch_index_lifecycle_management.rb:60:in `ilm_policy_put'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/elasticsearch_index_lifecycle_management.rb:31:in `create_ilm_policy'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/elasticsearch_index_lifecycle_management.rb:7:in `setup_ilm'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/elasticsearch_index_template.rb:160:in `create_rollover_alias'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/out_elasticsearch.rb:959:in `block in template_installation_actual'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/elasticsearch_index_template.rb:35:in `retry_operate'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/out_elasticsearch.rb:952:in `template_installation_actual'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/out_elasticsearch.rb:974:in `send_bulk'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/out_elasticsearch.rb:804:in `block in write'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/out_elasticsearch.rb:803:in `each'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/out_elasticsearch.rb:803:in `write'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.1/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.1/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.1/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-08-23 21:30:49 +0530 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

This indicates that elasticsearch-xpack not to be installed.
Occurring `undefined method `ilm' for #<Elasticsearch::Transport::Client:0x00007fa99e85cd08>`  exception is strange.

> NOTE: This parameter requests to install elasticsearch-xpack gem.

ref: https://github.com/uken/fluent-plugin-elasticsearch#enable_ilm

**Comment by himanshigpta** [comment]
@cosmo0920 I just checked, its installed :
```
]# td-agent-gem list | grep xpack
elasticsearch-xpack (5.0.0)
```
Guess I have to upgrade this too

**Comment by cosmo0920** [comment]
> ]# td-agent-gem list | grep xpack
> elasticsearch-xpack (5.0.0)

It's not correct version installed.
elasticsearch-xpack 7.8.0 or later should be installed:
https://rubygems.org/gems/elasticsearch-xpack/versions

**Comment by himanshigpta** [comment]
@cosmo0920 Thanks for the quick response! I upgraded the version & it helped:

![image](https://user-images.githubusercontent.com/64949255/91006344-b9ca9b80-e5f6-11ea-954a-08b025102094.png)

I'll monitor this till tomorrow(kept the timing for deletion phase as 1 day from rollover), also I'll try this approach on one of the existing indexes now(which was the original issue), which might take some time, since there are multiple servers from where logs are getting ingested in any index, will share the results.

**Comment by himanshigpta** [comment]
@cosmo0920  I tried the configuration on 2 other indexes, & seems like it worked! :) One thing I'm not sure about is the naming convention, since it was throwing error when I tried using the existing index name(rmj), I used rmj_logss instead & could see rmj_logss-default-35-000001 on Kibana, after rollover can I see 2 indexes where 35 & 000001 suffix got incremented : 



![Uploading Screenshot 2020-09-02 at 9.34.42 AM.png…]()


Also I can see multiple templates getting created:

![Uploading image.png…]()

I can see similar multiple rollovers & multiple templates getting created for another index where I tried the suggested config, is this the expected behaviour?

**Comment by cosmo0920** [comment]
> One thing I'm not sure about is the naming convention, since it was throwing error when I tried using the existing index name(rmj), I used rmj_logss instead & could see rmj_logss-default-35-000001 on Kibana, after rollover can I see 2 indexes where 35 & 000001 suffix got incremented :

After rollover, 000001 suffix should be incremented.

 
> I can see similar multiple rollovers & multiple templates getting created for another index where I tried the suggested config, is this the expected behaviour?

This is because rollover_alias should put in template and handle index alias should be handled properly per index.
This multiple template registration issue is originated from logstash_format implementation.
`logstash_format` implementation emulates logstash's logstash index format but it does not use Elasticsearch date query format (e.g. now/d).
Thus, this multiple template registration shouldn't be avoidable. This is plugin limitation.

**Comment by himanshigpta** [comment]
@cosmo0920 Thanks for pointing this out, just to confirm, does that mean that template versions will keep on getting created whenever index rollover happens? If yes, would the older template be deleted when the corresponding index version gets deleted? If no, would this pose any issue in future you might've observed...?

**Comment by cosmo0920** [comment]
> @cosmo0920 Thanks for pointing this out, just to confirm, does that mean that template versions will keep on getting created whenever index rollover happens? 

I think installed template version should be kept without `template_overwrite true`.

> If yes, would the older template be deleted when the corresponding index version gets deleted? If no, would this pose any issue in future you might've observed...?

Yes, but there is a bit of misunderstanding ES plugin's behavior.
Index rollover should happen per defined lifecycles and rollover indices should be created on per defined periods.
No template deletion wasn't occurred due to just re-creation for ILM managed indices which are associated to aliased indices.

**Comment by himanshigpta** [comment]
Thanks again for quick response @cosmo0920 ! I'll update overwrite value to true. Hopefully that'll make everything work as expected :)

**Comment by himanshigpta** [comment]
@cosmo0920 I updated template_overwrite to true, n I can still see further template versions getting created :( 
![image](https://user-images.githubusercontent.com/64949255/93181979-c5713400-f756-11ea-9ea5-8b988fba10e6.png)

**Comment by cosmo0920** [comment]
@himanshigpta What is the issue which you mentioned?
This issue seems to be already resolved but you are still mentioning for the different issue. 
Please open a new issue what you mentioned.

**Comment by himanshigpta** [comment]
Thanks for your help & yes the original issue is resolved, this was another issue that popped up from the solution :)
