### ISSUE TITLE
Placeholders not working ?

### ISSUE THREAD

**Issue by eddycharly** [uken/fluent-plugin-elasticsearch#792]
#### Problem

From the docs:

> ## Placeholders
> v0.14 placeholders can handle ${tag} for tag, %Y%m%d like strftime format, and custom record keys like as record["mykey"].
>
> Note that custom chunk key is different notations for record_reformer and record_modifier. They uses record["some_key"] > to specify placeholders, but this feature uses ${key1}, ${key2} notation. And tag, time, and some arbitrary keys must be included in buffer directive attributes.

I tried to use placeholders but it doesn't seem to work. Here is my config:

```
      @type elasticsearch
      @id es-k8s
      exception_backup true
      fail_on_putting_template_retry_exceed true
      host elasticsearch-master.logging
      include_tag_key true
      logstash_format true
      logstash_prefix test-pods-${tag_parts[2]}-${tag_parts[3]}
      port 9200
      reconnect_on_error true
      reload_connections true
      scheme http
      ssl_verify true
      utc_index true
      verify_es_version_at_startup true
      <buffer tag,time>
        @type file
        chunk_limit_size 2M
        flush_interval 5s
        flush_mode interval
        flush_thread_count 2
        overflow_action block
        path /buffers/es-k8s
        queue_limit_length 8
        retry_forever true
        retry_max_interval 30
        retry_type exponential_backoff
        timekey 1m
        timekey_wait 30s
      </buffer>
```

I get only one index created named `test-pods-${tag_parts[2]}-${tag_parts[3]}-2020.08.17`.

Is there something wrong with my config ? Am i right to think that i should have one index per pod/container given the config above ?

#### Using Fluentd and ES plugin versions

* OS version linux
* Kubernetes
* Fluentd v1.11.1
* ES plugin 4.1.1
* ES version 7.8.1

**Comment by cosmo0920** [comment]
>  `logstash_prefix test-pods-${tag_parts[2]}-${tag_parts[3]}`
>  `<snip>`
> I get only one index created named test-pods-${tag_parts[2]}-${tag_parts[3]}-2020.08.17.

This is old syntax for `elasticsearch_dynamic`.
This should be:

`logstash_prefix test-pods-${tag[2]}-${tag[3]}` (`tag[N]` where N is 0-origin index.)

ref: https://docs.fluentd.org/configuration/buffer-section#placeholders

**Comment by eddycharly** [comment]
Thanks @cosmo0920, it's working for the `tag`.

Any chance that something like this could work too ?

```
    @type elasticsearch
    exception_backup true
    fail_on_putting_template_retry_exceed true
    host elasticsearch-master.logging
    include_tag_key true
    logstash_format true
    logstash_prefix tests-pods-${$.kubernetes.pod_name}-${$.kubernetes.container_name}
    port 9200
    reconnect_on_error true
    reload_connections true
    scheme http
    utc_index true
    verify_es_version_at_startup true
    <buffer time,$.kubernetes.pod_name,$.kubernetes.container_name>
      @type file
      path /buffers/es-k8s
      retry_forever true
      timekey 1m
      timekey_wait 30s
```

From what i understand, as long as the placeholder is part of the buffer chunk keys it should be looked up correctly when extracting placeholders ?

**Comment by eddycharly** [comment]
It looks like the syntax is working now... `¯\_(ツ)_/¯`

**Comment by eddycharly** [comment]
seems like it's all good now, i will reopen the issue if necessary.
