### ISSUE TITLE
Document `flush_at_shutdown` config default behavior for this plugin

### ISSUE THREAD

**Issue by patrick-webs** [uken/fluent-plugin-elasticsearch#794]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

Fluentd documentation states https://docs.fluentd.org/configuration/buffer-section

> flush_at_shutdown [bool]
> Default: false for persistent buffers (e.g. buf_file), true for
> non-persistent buffers (e.g. buf_memory)

It isn't clear to me from the README whether fluent-plugin-elasticsearch is considered to have a default of `false` or `true` for this parameter, and reading the code I can't tell either. I can see a number of other issues were opened where people included "flush_at_shutdown true" in their configs, so I suspect it's false by default?

Could a sentence be added to the README stating whether it's true or false by default?

I tried to see if I could write a test to determine the current state, but I got test failures locally on my machine from the master branch so I'm not sure what it is. https://github.com/patrick-webs/fluent-plugin-elasticsearch/commit/6f01a15013158545b5a1e24c4ce94073d71c3fb0

#### Steps to replicate

N/A

#### Expected Behavior or What you need to ask

Improved documentation in README

#### Using Fluentd and ES plugin versions

N/A

**Comment by cosmo0920** [comment]
This is not fluent-plugin-elasticsearch territory to write down documentation.
fluent-plugin-elasticsearch just uses built-in or some user-introduced buffer plugins.
This parameter depends on buf_file or buf_memory.
It shouldn't add descriptions for buffer parameter into this plugin documentation.
