### ISSUE TITLE
Cannot use "templates" to load multiple templates and also use ILM

### ISSUE THREAD

**Issue by dobesv** [uken/fluent-plugin-elasticsearch#798]
## Problem

Currently the use of ILM means you must use `template_name` and `template_file`.  In this case you cannot use `templates` to load multiple templates.

It would be nice if I could load multiple templates while using ILM.

I think the simplest way would be to allow `templates` to be specified along with `template_name` and `template_file`.  In this case it would load all the templates in `templates` but use `template_name` and `template_path` for the ILM stuff.

**Comment by cosmo0920** [comment]
Oh! I didn't notice about it.
I'll take a look on your PR.
