### ISSUE TITLE
"retry_count" is not zero cleared after a successful retry

### ISSUE THREAD

**Issue by jurim76** [uken/fluent-plugin-elasticsearch#800]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

Our monitoring system (zabbix) uses "retry_count" metric to monitor td-agent connection to elasticsearch cluster (trigger alert if retry_count > 0).
If connection to elasticsearch cluster fails, "retry_count" is not reseting to zero after a successfull retry and monitoring system always throws an alert. Manual td-agent restart after every alert is not best "production" solution in this case.
Or would you recommend the other way to monitor connections health?

#### Steps to replicate

Provide example config and message

```aconf
@type elasticsearch
hosts elk01,elk02,elk03,elk04,...
port 9200
include_timestamp true
logstash_format true
logstash_prefix fluentd
reload_connections false
reload_on_failure false
reconnect_on_error false
request_timeout 60s
resurrect_after 60s
slow_flush_log_threshold 35.0
scheme http
```

#### Expected Behavior or What you need to ask

"retry_count" resets to zero after a successful retry

#### Using Fluentd and ES plugin versions

* OS version - Debian 9
* Bare Metal or within Docker or Kubernetes or others? - Proxmox VM
* Fluentd v0.12 or v0.14/v1.0 - td-agent 1.10.2
* ES plugin 3.x.y/2.x.y or 1.x.y - fluent-plugin-elasticsearch (4.1.1)
* ES version (optional) - 7.9.1

**Comment by cosmo0920** [comment]
> If connection to elasticsearch cluster fails, "retry_count" is not reseting to zero after a successfull retry and monitoring system always throws an alert. Manual td-agent restart after every alert is not best "production" solution in this case.
> Or would you recommend the other way to monitor connections health?

This feature is originated from `Fluent::Plugin::Output` which is base class for `Fluent::Plugin::ElasticsearchOutput`(out_elasticsearch).
AFAIK, there is no resetting way without restart.
I don't want to modify these internal statics in ES plugin.
