### ISSUE TITLE
Got Operation timed out - connect(2) error in fluent-plugin-elasticsearch

### ISSUE THREAD

**Issue by chikinchoi** [uken/fluent-plugin-elasticsearch#804]
(check apply)
- [ ] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

Hi Team,

I got a lot of "Operation timed out - connect (2)" error but I cannot found any document about this error. This error occurs after I increased the worker count from 0 (default worker value) to 4. I am not sure if this is related. 
Also, it always retries succeeded after retry, but I don't understand why the operation timed out.
Please advise. Thank you very much!!

Error log:
```
2020-09-09 06:53:19 +0000 [warn]: #1 [firelens_es] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-09-09 06:53:20 +0000 chunk="5aedbe013a0667aff359f5e032e4f2bb" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"*******-uat.***.org.hk\", :port=>9200, :scheme=>\"https\", :user=>\"fluentd-user\", :password=>\"obfuscated\"}): Operation timed out - connect(2) for 10.50.19.17:9200 (Errno::ETIMEDOUT)"
2020-09-09 06:53:19 +0000 [warn]: #1 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-4.1.0/lib/fluent/plugin/out_elasticsearch.rb:1015:in `rescue in send_bulk'
2020-09-09 06:53:19 +0000 [warn]: #1 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-4.1.0/lib/fluent/plugin/out_elasticsearch.rb:977:in `send_bulk'
2020-09-09 06:53:19 +0000 [warn]: #1 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-4.1.0/lib/fluent/plugin/out_elasticsearch.rb:804:in `block in write'
2020-09-09 06:53:19 +0000 [warn]: #1 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-4.1.0/lib/fluent/plugin/out_elasticsearch.rb:803:in `each'
2020-09-09 06:53:19 +0000 [warn]: #1 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-4.1.0/lib/fluent/plugin/out_elasticsearch.rb:803:in `write'
2020-09-09 06:53:19 +0000 [warn]: #1 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.1/lib/fluent/plugin/output.rb:1133:in `try_flush'
2020-09-09 06:53:19 +0000 [warn]: #1 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.1/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
2020-09-09 06:53:19 +0000 [warn]: #1 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.1/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
2020-09-09 06:53:19 +0000 [warn]: #1 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-09-09 06:53:20 +0000 [warn]: #1 [firelens_es] retry succeeded. chunk_id="5aedbe013a0667aff359f5e032e4f2bb"
```

#### Steps to replicate

cannot reproduce because I don't know the reason of this error.
Below is my fluentd config:

```
<system>
  @log_level debug
  workers 4
  root_dir /var/log/fluent/
</system>

<source>
  @type  forward
  @id    input1
  @log_level debug
  port  24224
  bind 0.0.0.0
</source>

# Used for docker health check
<source>
  @type http
  port 8888
  bind 0.0.0.0
</source>

# records sent for health checking won't be forwarded anywhere
<match health**>
  @type null
</match>

# Prometheus Configuration
# count number of incoming records per tag
<filter **>
  @type prometheus
  <metric>
    name fluentd_input_status_num_records_total
    type counter
    desc The total number of incoming records
    <labels>
      tag ${tag}
      hostname ${hostname}
    </labels>
  </metric>
</filter>

<filter **firelens**>
  @type concat
  key log
  multiline_start_regexp '^\{\\"@timestamp'
  multiline_end_regexp '/\}/'
  separator ""
  flush_interval 1
  timeout_label @NORMAL
</filter>

<filter **firelens**>
  @type parser
  key_name log
  reserve_data true
  emit_invalid_record_to_error false
  <parse>
  @type json
  </parse>
</filter>

<filter **firelens**>
  @type record_transformer
  enable_ruby
  <record>
    taskDef ${record["ecs_task_definition"].gsub(/:.*/, '')}
  </record>
</filter>

<filter lambdaNode**>
  @type parser
  key_name data
  reserve_data true
  emit_invalid_record_to_error false
  <parse>
  @type json
  </parse>
</filter>

<filter lambdaPython**>
  @type record_transformer
  enable_ruby
  <record>
    function_name ${record["function_name"].gsub(/:.*/, '')}
  </record>
</filter>

<filter lambdaPython**>
  @type parser
  key_name message
  reserve_data true
  emit_invalid_record_to_error false
  <parse>
  @type json
  </parse>
</filter>

# count number of outgoing records per tag
<match **firelens**>
  @type copy
  @id firelens
  <store>
    @type elasticsearch
    @id firelens_es
    scheme https
    ssl_version TLSv1_2
    host  "#{ENV['ELASTIC_HOST']}"
    port  "#{ENV['ELASTIC_POST']}"
    user  "#{ENV['ELASTIC_USER']}"
    password "#{ENV['ELASTIC_PWD']}"
    ssl_verify false
    log_es_400_reason true
    index_name ${taskDef}-%Y.%m
    reconnect_on_error true
    reload_on_failure true
    reload_connections false
    suppress_type_name true
    sniffer_class_name Fluent::Plugin::ElasticsearchSimpleSniffer
    request_timeout 2147483648
    <buffer tag, time, ecs_task_definition, taskDef>
      @type file
      flush_mode lazy
      flush_thread_count 8
      # path /var/log/fluent/firelens.*.buffer
      total_limit_size 8GB
      chunk_limit_size 80MB
      timekey 5s
      timekey_wait 1s
      overflow_action drop_oldest_chunk
      retry_max_interval 16s
      disable_chunk_backup true
      retry_forever false
    </buffer>
  </store>
  <store>
    @type prometheus
    @id firelens_pro
    <metric>
      name fluentd_output_status_num_records_total
      type counter
      desc The total number of outgoing records
      <labels>
        tag ${tag}
        hostname ${hostname}
      </labels>
    </metric>
  </store>
</match>

<match lambdaNode**>
  @type copy
  @id lambdaNode
  <store>
    @type elasticsearch
    @id lambdaNode_es
    scheme https
    ssl_version TLSv1_2
    host  "#{ENV['ELASTIC_HOST']}"
    port  "#{ENV['ELASTIC_POST']}"
    user  "#{ENV['ELASTIC_USER']}"
    password "#{ENV['ELASTIC_PWD']}"
    include_timestamp true
    ssl_verify false
    log_es_400_reason true
    index_name ${$.context.functionName}-%Y.%m
    reconnect_on_error true
    reload_on_failure true
    reload_connections false
    suppress_type_name true
    sniffer_class_name Fluent::Plugin::ElasticsearchSimpleSniffer
    reload_after 100
    <buffer tag, time, $.context.functionName>
      flush_mode lazy
      chunk_limit_size 5MB
      flush_thread_count 8
      total_limit_size 512MB
      timekey 5s
      timekey_wait 1s
      retry_max_interval 16s
      disable_chunk_backup true
    </buffer>
  </store>
  <store>
    @type prometheus
    @id lambdaNode_pro
    <metric>
      name fluentd_output_status_num_records_total
      type counter
      desc The total number of outgoing records
      <labels>
        tag ${tag}
        hostname ${hostname}
      </labels>
    </metric>
  </store>
</match>

<match lambdaPython**>
  @type copy
  @id lambdaPython
  <store>
    @type elasticsearch
    @id lambdaPython_es
    scheme https
    ssl_version TLSv1_2
    host  "#{ENV['ELASTIC_HOST']}"
    port  "#{ENV['ELASTIC_POST']}"
    user  "#{ENV['ELASTIC_USER']}"
    password "#{ENV['ELASTIC_PWD']}"
    include_timestamp true
    ssl_verify false
    log_es_400_reason true
    index_name ${function_name}-%Y.%m
    reconnect_on_error true
    reload_on_failure true
    reload_connections false
    suppress_type_name true
    sniffer_class_name Fluent::Plugin::ElasticsearchSimpleSniffer
    reload_after 100
    <buffer tag, time, function_name>
      flush_mode lazy
      chunk_limit_size 5MB
      flush_thread_count 8
      total_limit_size 512MB
      timekey 5s
      timekey_wait 1s
      retry_max_interval 16s
      disable_chunk_backup true
    </buffer>
  </store>
  <store>
    @type prometheus
    @id lambdaPython_pro
    <metric>
      name fluentd_output_status_num_records_total
      type counter
      desc The total number of outgoing records
      <labels>
        tag ${tag}
        hostname ${hostname}
      </labels>
    </metric>
  </store>
</match>

<label @FLUENT_LOG>
  <match fluent.*>
    @type null
  </match>
</label>

<label @NORMAL>
  <match **>
    @type null
  </match>
</label>

# expose metrics in prometheus format
<source>
  @type prometheus
  bind 0.0.0.0
  port 24231
  metrics_path /metrics
</source>

<source>
  @type prometheus_output_monitor
  interval 10
  <labels>
    hostname ${hostname}
  </labels>
</source>
```

#### Expected Behavior or What you need to ask

No this error

#### Using Fluentd and ES plugin versions
fluentd running in AWS ECS Fargate service
fluentd version: v1.11.1
fluent-plugin-elasticsearch verrsion 4.1.0

**Comment by cosmo0920** [comment]
> I got a lot of "Operation timed out - connect (2)" error but I cannot found any document about this error. This error occurs after I increased the worker count from 0 (default worker value) to 4. I am not sure if this is related.
Also, it always retries succeeded after retry, but I don't understand why the operation timed out.
Please advise. Thank you very much!!

HTTP requests are not 100% surely sending contents.
We can't create a network which ensures 100% service-level agreement. 
And ES plugin cannot ensure network operation. 
ES plugin just relies on Elasticsearch Ruby client library and its dependent gems such as Faraday, excon, net/http, and other network related code.

The latter line says `[firelens_es] retry succeeded. chunk_id="5aedbe013a0667aff359f5e032e4f2bb"` and the first line says `[firelens_es] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-09-09 06:53:20 +0000 chunk="5aedbe013a0667aff359f5e032e4f2bb" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"*******-uat.***.org.hk\", :port=>9200, :scheme=>\"https\", :user=>\"fluentd-user\", :password=>\"obfuscated\"}): Operation timed out - connect(2) for 10.50.19.17:9200 (Errno::ETIMEDOUT)`.

The chunk whose chunk_id is "5aedbe013a0667aff359f5e032e4f2bb" should be succeeded to send to Elasticsearch.
So, this log is not error but retrying mechanism run and backed to be normal.

**Comment by chikinchoi** [comment]
> 
> 
> > I got a lot of "Operation timed out - connect (2)" error but I cannot found any document about this error. This error occurs after I increased the worker count from 0 (default worker value) to 4. I am not sure if this is related.
> > Also, it always retries succeeded after retry, but I don't understand why the operation timed out.
> > Please advise. Thank you very much!!
> 
> HTTP requests are not 100% surely sending contents.
> We can't create a network which ensures 100% service-level agreement.
> And ES plugin cannot ensure network operation.
> ES plugin just relies on Elasticsearch Ruby client library and its dependent gems such as Faraday, excon, net/http, and other network related code.
> 
> The latter line says `[firelens_es] retry succeeded. chunk_id="5aedbe013a0667aff359f5e032e4f2bb"` and the first line says `[firelens_es] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-09-09 06:53:20 +0000 chunk="5aedbe013a0667aff359f5e032e4f2bb" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"*******-uat.***.org.hk\", :port=>9200, :scheme=>\"https\", :user=>\"fluentd-user\", :password=>\"obfuscated\"}): Operation timed out - connect(2) for 10.50.19.17:9200 (Errno::ETIMEDOUT)`.
> 
> The chunk whose chunk_id is "5aedbe013a0667aff359f5e032e4f2bb" should be succeeded to send to Elasticsearch.
> So, this log is not error but retrying mechanism run and backed to be normal.

Hi, @cosmo0920 ,

Thank you for your reply!
I understand that it is just a warning and the retry mechanism is success. However, this warning appears almost every 5 minutes in our production environment.
As there is an A10 load balancer between the Fluentd and Elasticsearch (Fluentd > A10 Load balancer > Elasticsearch), Is it mean there is some networking problem between the Fluentd and the A10 Load balancer?

**Comment by cosmo0920** [comment]
> As there is an A10 load balancer between the Fluentd and Elasticsearch (Fluentd > A10 Load balancer > Elasticsearch), Is it mean there is some networking problem between the Fluentd and the A10 Load balancer?

A10 load balancer requests to use keepalive for persistent and stable HTTP connection?
If so, you should use typhoeus as a backend HTTP library. Currently, using excon as HTTP backend does not handle keepalive:
https://github.com/uken/fluent-plugin-elasticsearch#http_backend

**Comment by chikinchoi** [comment]
Hi @cosmo0920 ,

Thank you for your suggestion. 
I have added "http_backend typhoeus" to Fluentd config and the warning is gone.
Thank you!

**Comment by cosmo0920** [comment]
Oh! The first culprit is load balancer but excon does not handle keepalive in HTTP.
So, using typhoeus and keepalive can keep connection through A10 load balancer.
Thanks, it helps me alot. :+1:

**Comment by chikinchoi** [comment]
Hi @cosmo0920 ,

just found that the "Operation timed out" warning is gone but it triggered a lot of `buffer flush took longer time than slow_flush_log_threshold: elapsed_time=932.9871006549802 slow_flush_log_threshold=20.0` warning. The elapsed_time is always ~93x second which means about 15 minutes.
Do you have any idea of the reason for slow_flush 93x seconds?
Thank you.
