### ISSUE TITLE
Embedded Ruby Code in custom_headers

### ISSUE THREAD

**Issue by orjan** [uken/fluent-plugin-elasticsearch#806]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
I've tried to add an Authorization for ApiKey as a custom_header.
It works fine if it's in plain text e.g:
```
  custom_headers {
    "Authorization":"ApiKey BASE64ENCODEDAPIKEY=="
  }
```
But when it try to use an environment variable via the [embedded ruby code](https://docs.fluentd.org/configuration/config-file#embedded-ruby-code) it's not substituted.
```
  custom_headers {
    "Authorization":"ApiKey #{ENV['ELASTIC_API_KEY']}"
  }
```
My first idea for a reproducing test case was to add the header here:
https://github.com/uken/fluent-plugin-elasticsearch/blob/master/test/plugin/test_out_elasticsearch.rb#L213
But I'll guess this bypasses the actual parsing since, so it might not be an option?

I've also tried to create a failing test case in fluentd e.g. by patching this test, without no luck.
https://github.com/fluent/fluentd/blob/master/test/config/test_config_parser.rb#L486

Another thing is that the `custom_headers` is not marked as secret, an option could be to a secret parameter `api_key` or `authorization_header`? That could be both an improvement from a security point of view and a workaround for the not working hash substitution? 

It's possible that this issue is related to fluentd or that I've missed something in the config?

#### Steps to replicate
https://github.com/orjan/fluentd-elastic-custom-headers/blob/master/config/fluent.conf#L8
`docker-compose up`

#### Expected Behavior or What you need to ask
That the custom header `Authorization` will be substituted in transit.
In the logs below you can see the un-substituted ruby code. 
```
fake_1     | Listening on [0.0.0.0] (family 0, port 9200)
fluentd_1  | 2020-09-10 21:18:55 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
fluentd_1  | 2020-09-10 21:18:55 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.1.3'
fluentd_1  | 2020-09-10 21:18:55 +0000 [info]: gem 'fluentd' version '1.11.2'
fluentd_1  | 2020-09-10 21:18:56 +0000 [info]: using configuration file: <ROOT>
fluentd_1  |   <match my.logs>
fluentd_1  |     @type elasticsearch
fluentd_1  |     host "fake"
fluentd_1  |     port 9200
fluentd_1  |     logstash_format true
fluentd_1  |     custom_headers {"X-PlainHeader":"A plain header","Authorization":"ApiKey #{ENV['ELASTIC_API_KEY']}"}
fluentd_1  |   </match>
fluentd_1  | </ROOT>
fluentd_1  | 2020-09-10 21:18:56 +0000 [info]: starting fluentd-1.11.2 pid=7 ruby="2.7.1"
fluentd_1  | 2020-09-10 21:18:56 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/flue
  5 Troubleshoot env variable and custom headers¬
ntd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
fluentd_1  | 2020-09-10 21:18:56 +0000 [info]: adding match pattern="my.logs" type="elasticsearch"
fake_1     | Connection from fluentd_fluentd_1.fluentd_default 44728 received!
fake_1     | GET / HTTP/1.1
fake_1     | User-Agent: elasticsearch-ruby/7.9.0 (RUBY_VERSION: 2.7.1; linux x86_64; Faraday v1.0.1)
fake_1     | Accept: */*
fake_1     | Content-Type: application/json
fake_1     | X-PlainHeader: A plain header
fake_1     | Authorization: ApiKey #{ENV['ELASTIC_API_KEY']}
fake_1     | Host: fake:9200
fake_1     |
fluentd_fake_1 exited with code 0
```
#### Using Fluentd and ES plugin versions
Docker desktop, both OSX and Windows 10
```
Step 1/4 : FROM fluent/fluentd:v1.11-2
...
Successfully installed excon-0.76.0
Successfully installed multi_json-1.15.0
Successfully installed multipart-post-2.1.1
Successfully installed faraday-1.0.1
Successfully installed elasticsearch-transport-7.9.0
Successfully installed elasticsearch-api-7.9.0
Successfully installed elasticsearch-7.9.0
Successfully installed fluent-plugin-elasticsearch-4.1.3
```

**Comment by cosmo0920** [comment]
> But when it try to use an environment variable via the embedded ruby code it's not substituted.

Embedded Ruby code should be _entire string_.
So, it should be the following:

```aconf
custom_headers "#{ENV['ELASTIC_API_KEY_HEADER']}"
```

```console
$ export ELASTIC_API_KEY_HEADER='{"Authorization":"ApiKey BASE64ENCODEDAPIKEY=="}' 
```

Then, Fluentd can interpret for `ELASTIC_API_KEY_HEADER` environment variable:

```aconf
2020-09-11 14:22:47 +0900 [info]: using configuration file: <ROOT>
# ...
  <match **>
    @type elasticsearch
    # ...
    custom_headers {"Authorization":"ApiKey BASE64ENCODEDAPIKEY=="}
    # ...
  </match>
```

Fluentd implements configuration parser as follows:

ref: https://github.com/fluent/fluentd/blob/master/lib/fluent/config/v1_parser.rb#L107
ref: https://github.com/fluent/fluentd/blob/master/lib/fluent/config/literal_parser.rb#L80
ref: https://github.com/fluent/fluentd/blob/master/lib/fluent/config/literal_parser.rb#L90

**Comment by orjan** [comment]
@cosmo0920 thanks a lot for your help!

This is working as expected
```
  custom_headers "Authorization:ApiKey #{ENV['ELASTIC_API_KEY']}"
```

If you don't think there's a need for a secret `authorization_header` or `api_key` in the config feel, free to close the issue!
