### ISSUE TITLE
sniffer_class_name with load balancer issue

### ISSUE THREAD

**Issue by chikinchoi** [uken/fluent-plugin-elasticsearch#816]
Hi Team,

I have a Fluentd cluster that will connect to the A10 load balancer, then to the Elasticsearch. 
I found that there is an issue "Stopped to send events" [1] and I solved it by adding below configs:
```
reload_connections false
reconnect_on_error true
reload_on_failure true
```
I also found that I need to add "`sniffer_class_name Fluent::Plugin::ElasticsearchSimpleSniffer`" because I am connecting to a A10 load balancer. However, according to the document [2], I need to set the `reload_connections true` for the sniffer class name which is exclusive to the solution of the above issue.
May I know should I set the sniffer_class_name as the fluentd is connecting to the load balancer?
Please advise. Thank you.

[1] https://github.com/uken/fluent-plugin-elasticsearch#stopped-to-send-events-on-k8s-why
[2] https://github.com/uken/fluent-plugin-elasticsearch#sniffer-class-name

**Comment by cosmo0920** [comment]
> May I know should I set the sniffer_class_name as the fluentd is connecting to the load balancer?
> Please advise. Thank you.

We do not have any knowledge of A10 load balancer.
Document [2] just displays an example configuration.
Please use document [1] configuration and *Fluent::Plugin::ElasticsearchSimpleSniffer* class at your own risk.

**Comment by cosmo0920** [comment]
No response.
Closing.
