### ISSUE TITLE
Suppress Info log "disable filter chain optimization because..."

### ISSUE THREAD

**Issue by chikinchoi** [uken/fluent-plugin-elasticsearch#817]
#### Problem

I found that there are a lot of `[info]: disable filter chain optimization because [Fluent::Plugin::StringScrubFilter, Fluent::Plugin::ConcatFilter] uses ``#filter_stream`` method.` and I would like to suppress this log.
I know that I can update log_level to warn or error to suppress the info log. However, I would like to keep other fluentd info log.
Is there any config we can suppress the disable filter chain optimization only? if not, could you please add this for feature request?
Thank you!

**Comment by cosmo0920** [comment]
You should report this warnings into fluent-plugin-concat but I already answered this warnings cannot remove from Fluentd log.
Wrong repository. Closing.
