### ISSUE TITLE
Broken link to Fluentd's builtin Output plugin in Buffer options section

### ISSUE THREAD

**Issue by mfvanek** [uken/fluent-plugin-elasticsearch#819]
- [X] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
**Buffer options** section says "fluentd-plugin-elasticsearch extends Fluentd's builtin Output plugin and use compat_parameters plugin helper."  
but link to **Fluentd's builtin Output plugin** doesn't work.

#### Steps to replicate

Go to https://github.com/uken/fluent-plugin-elasticsearch#buffer-options and click on "Fluentd's builtin Output plugin".
You'll get "Page not found"

#### Expected Behavior or What you need to ask
redirecting to the Fluentd documentation

#### Using Fluentd and ES plugin versions
n/a

**Comment by cosmo0920** [comment]
Could you send a PR which uses `https://docs.fluentd.org/output#overview` on "Fluentd's builtin Output plugin" link?
