### ISSUE TITLE
question about the behaviour of Fluentd worker buffer

### ISSUE THREAD

**Issue by chikinchoi** [uken/fluent-plugin-elasticsearch#824]
#### Problem
Hi Teams,

I have a simple question about the behaviour of fluentd worker buffer, I know that eeach worker consumes disk space sperately according to [1]. Therefore, if I have 4 workers in fluentd and there is 16GB disk size for buffering. I should set 4GB total_limit_size for each worker. Is it right?
If I set the overflow_action to drop_oldest_chunk, when will the fluentd drop the log? when the worker hit the limit? or wait for all workers hit the limit?

Thank you!

[1] https://docs.fluentd.org/deployment/multi-process-workers#operation

**Comment by cosmo0920** [comment]
>  Therefore, if I have 4 workers in fluentd and there is 16GB disk size for buffering. I should set 4GB total_limit_size for each worker. Is it right?

Right.

> If I set the overflow_action to drop_oldest_chunk, when will the fluentd drop the log? when the worker hit the limit? or wait for all workers hit the limit?

Fluentd drops the log per worker.

**Comment by chikinchoi** [comment]
Hi @cosmo0920 ,

I have 4 workers and I found that one worker available buffer is about 10% but other workers are remain 80%. Do you have any idea why the worker is holding some log in buffer? or the incoming records didn't send to fluentd worker evenly?

**Comment by cosmo0920** [comment]
> Do you have any idea why the worker is holding some log in buffer? or the incoming records didn't send to fluentd worker evenly?

It depends on sending target capacity or sending flow rate....
I dunno why Fluentd workers send events evenly.

**Comment by cosmo0920** [comment]
No response. Closing.
