### ISSUE TITLE
json message field is shown nested in Kibana with fluentd

### ISSUE THREAD

**Issue by redefinitionof** [uken/fluent-plugin-elasticsearch#828]
#### Problem

In Kibana, all my log entries in my stream are: "failed to find message". When I inspect an entry, I see that my original log-output from my application is nested inside the log-field of the log-entry. I see that the original message is in JSON format and does contain the message-field. How can I get this message to be included as fields in the log-entry itself? I am new to ElasticSearch/FluentD/Kibana. Am I doing something wrong?

See screenshot: 
![Kibana Screenshot Nested message field 2020-10-21 18-36-15](https://user-images.githubusercontent.com/8598904/96752484-cf79f880-13ce-11eb-94c8-4c6efe024b20.png)

#### Steps to replicate

This is my fluentd config:

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<match pm.**>
  @type elasticsearch
  host elasticsearch
  port 9200
  index_name fluentd.${tag}
  logstash_format true
  logstash_prefix fluentd # defaults to "logstash"
  <buffer>
    flush_interval 5s
  </buffer>
</match>
```

#### Using Fluentd and ES plugin versions

* OS Version: CentOS7 on Hyper-V
* Run in Docker
* Fluentd fluentd 1.3.2
* ES
  * 2020-10-21 15:20:04 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.2.2'
  * 2020-10-21 15:20:04 +0000 [info]: gem 'fluentd' version '1.3.2'
  * #0 Detected ES 7.x: `_doc` will be used as the document `_type`.
  * elasticsearch:7.9.2

**Comment by cosmo0920** [comment]
Hi, thanks for using ES plugin!
It seems that your log doesn't follow default ECS schema structure:
https://www.elastic.co/guide/en/ecs/current/ecs-getting-started.html

Kibana Logs the "Log Columns" to add "log"  should be handled correctly.

ref: https://discuss.elastic.co/t/message-failed-to-find-message-in-kibana-logs/210522

**Comment by redefinitionof** [comment]
Thanks for the reply.
So to be compliant to ECS-structure my json should contain a field "@timestamp" and "message". I did not have "@" in my field, so I changed the appender of logback so that it adds it. See screenshot:

![Kibana Screenshot at-timestamp field  2020-10-22 12-32-11](https://user-images.githubusercontent.com/8598904/96861330-3ac1da00-1464-11eb-8ff7-858158770841.png)

old configuration in src/main/resources/logback.xml:
```
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
      <layout class="ch.qos.logback.contrib.json.classic.JsonLayout">
         <jsonFormatter class="ch.qos.logback.contrib.jackson.JacksonJsonFormatter"/>
         <appendLineSeparator>true</appendLineSeparator>
      </layout>
   </encoder>
</appender>
```
New configuration:
```
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
   <encoder class="net.logstash.logback.encoder.LogstashEncoder">
      <fieldNames>
        <timestamp>@timestamp</timestamp>
        <message>message</message>
        <thread>thread</thread>
        <levelValue>level</levelValue>
        <logger>logger</logger>
        <version>[ignore]</version>
      </fieldNames>
   </encoder>
</appender>
```
old build.gradle (dependencies {}):
```
    // dependencies for "ch.qos.logback.core.encoder.LayoutWrappingEncoder" json appender encoder for logback.
    compile 'ch.qos.logback.contrib:logback-json-classic:0.1.5'
    compile 'ch.qos.logback.contrib:logback-jackson:0.1.5'
    compile 'com.fasterxml.jackson.core:jackson-databind:[2.11.3,]' // <-- This dependency is already included via another dependency? - explicit defining version 2.9.5 gave crash, so we use formatting: version 2.11.3 or later.
    testCompile 'ch.qos.logback.contrib:logback-json-classic:0.1.5'
    testCompile 'ch.qos.logback.contrib:logback-jackson:0.1.5'
    testCompile 'com.fasterxml.jackson.core:jackson-databind:[2.11.3,]' // <-- This dependency is already included via another dependency? - explicit defining version 2.9.5 gave crash,, so we use formatting: version 2.11.3 or later.

```
new build.gradle (dependencies {}):
```
    // for: <encoder class="net.logstash.logback.encoder.LogstashEncoder"> in src/main/resources/logback.xml
    runtime 'net.logstash.logback:logstash-logback-encoder:6.4'
```
So if this does not solve having an ECS data structure, where exactly does this structure need to be defined? I would assume that the elastic-search-plugin should format this message into ECS. My current stack/configuration is:

docker compose configuration:
```
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: pm.api
```

java-spring-application->slf4j->logback->docker-compose-logging-definition->fluentd->fluentd-elasticsearchplugin->elasticsearch->kibana

It gets pretty complicated. Thanks for looking into it.

**Comment by redefinitionof** [comment]
I solved it by adding to my: fluent.conf:

```
<filter pm.**>
  @type parser # record_transformer
  # @log_level debug
  <parse>
    @type json
  </parse>
  key_name log
</filter>
```

As suggested here:
https://github.com/uken/fluent-plugin-elasticsearch/issues/521#issuecomment-461344826
(I see that comment was also posted by you)

It works, but can you maybe explain what it does and why it is needed, because it is not really clear to me what it does.

See screenshot of my Kibana now with fix:
![Kibana Screenshot 03 Log fields parsed 2020-10-22 15-21-29](https://user-images.githubusercontent.com/8598904/96883167-5f2baf80-1480-11eb-86ef-2a1f84ebf963.png)

**Comment by cosmo0920** [comment]
> It works, but can you maybe explain what it does and why it is needed, because it is not really clear to me what it does.

I guess Kibana Log app requests messages key to render correctly:
https://github.com/elastic/kibana/blob/master/x-pack/plugins/infra/server/lib/domains/log_entries_domain/log_entries_domain.ts#L133-L135
https://github.com/elastic/kibana/blob/master/x-pack/plugins/infra/server/lib/domains/log_entries_domain/log_entries_domain.ts#L137
https://github.com/elastic/kibana/blob/master/x-pack/plugins/infra/server/lib/domains/log_entries_domain/log_entries_domain.ts#L150-L171

**Comment by cosmo0920** [comment]
No response. Closing.
