### ISSUE TITLE
Generating hash from field values

### ISSUE THREAD

**Issue by hatharom** [uken/fluent-plugin-elasticsearch#831]
#### Problem
I would like to create an ES id from hashed values of certain fields

Something like:
```
<match **>
  @type elasticsearch
  id_key _hash(field1+field2) 
</match>
```
Is that possible?

**Comment by cosmo0920** [comment]
No. Currently impossible to specify two or more fields.

**Comment by cosmo0920** [comment]
Instead, we can use filter_elastic_genid plugin can handle hash calculation from multiple fields:

```aconf
<filter **>
  @type elasticsearch_genid
  hash_id_key _hash
  record_keys []
  separator _
  hash_type sha1
</filter>
<match **>
  @type elasticsearch
  id_key _hash
  # ...
</match>
```

ref: https://github.com/uken/fluent-plugin-elasticsearch/blob/master/README.ElasticsearchGenID.md#use_record_as_seed

**Comment by cosmo0920** [comment]
I did answer in https://github.com/uken/fluent-plugin-elasticsearch/issues/831#issuecomment-720263245.
But no response. Closing.
