### ISSUE TITLE
 error no valid placeholder(s). error: Parameter 'host_placeholder'

### ISSUE THREAD

**Issue by waok2** [uken/fluent-plugin-elasticsearch#834]
#### Problem
Getting this error when i use a basic ingress auth from K8s on my elasticsearch set up (ES has three nodes, on the K8s cluster )
[debug]: #0 'host_placeholder "example.com" ' is tested built-in placeholder(s) but there is no valid placeholder(s). error: Parameter 'host_placeholder: example.com' doesn't have tag placeholder
fluentd    | 2020-11-09 07:39:12 +0000 [warn]: #0 Could not communicate to Elasticsearch, resetting connection and trying again. connect_write timeout reached
...

**config file**

my config file 

```aconf
<match syslog.log>
  @type elasticsearch
  @log_level debug
  host example.com
  scheme https
  ssl_verify false
  ssl_version TLSv1_2
  user %{fluentd}
  password %{example}
  logstash_format true
  time_key time
  time_format %b %d %H:%M:%S
  logstash_prefix example_t_
  <buffer>
      @type "file"
      path "/var/log/fluentd-es.buffer"
      flush_at_shutdown true
      flush_mode interval
      flush_interval 60s
      flush_thread_count 2
      chunk_limit_size 10MB
      chunk_limit_records 10000
    </buffer>
</match>
```

#### Expected Behavior or What you need to ask

...

#### Using Fluentd and ES plugin versions

* docker container (FROM fluent/fluentd:v1.11-debian)

* ES plugin (fluent-plugin-elasticsearch)

**Comment by cosmo0920** [comment]
This is debug message. There is no error for `host_placeholder`.
This message is shown for debugging purpose.
