### ISSUE TITLE
Data stream support

### ISSUE THREAD

**Issue by metalrex100** [uken/fluent-plugin-elasticsearch#843]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

**Is your feature request related to a problem? Please describe.**

--

**Describe the solution you'd like**

--

**Describe alternatives you've considered**

--

**Additional context**

Elasticsearch has data streams for time series data and could be used for storing logs.
Currently as far as I saw source code of the current plugin - it does not support data streams. Would be nice to have such functionality.

https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html

**Comment by metalrex100** [comment]
@cosmo0920 Any ideas about data streams support?

**Comment by cosmo0920** [comment]
Don't break

**Comment by cosmo0920** [comment]
I'd appreciate if you send a PR to support this. Thanks for the requesting to the new feature.

**Comment by cosmo0920** [comment]
I suppose that this feature can be implemented for the analogy of ILM feature.

The indices styles are:

`.ds-<data-stream>-<generation>`

`.ds-` prefix is not handled in ES plugin, but `<data-stream>` or `<generation>` mechanism is already implemented in template handling on ES plugin.

**Comment by metalrex100** [comment]
@cosmo0920 thanks for the reply!
Are you familiar with data streams feature of the elasticsearch?
As far as I understood from the docs there is no need to manually create indexes for the data streams, because data stream create them by itself. They  called “backing indexes” and they are private.

So probably data streams are alternative for the indexes. ILM policy apply strategy is also different. There is no need to create rollover alias by yourself. You need just to assign ILM policy to index_template.

I could try to implement it, but I think you also need to research data streams stuff to help me with the design.
Probably data streams support should be implemented as separate out-plugin (as elasticsearch_dynamic), otherwise logic will be a mess with many if-else because of data streams approach differences. Example name: elasticsearch_ds.

Tell me please what do you think.
If you are ready to dive into data streams stuff and cooperate on this feature implementation - I will try.

**Comment by cosmo0920** [comment]
> elasticsearch_ds

I don't think using abbreviation name is appropriate for users.
Instead, I want to use non-abbrev name such as `elasticsearch_data_stream`.
I don't against to use abbreviated name if you strongly wanted to use short name.


> Probably data streams support should be implemented as separate out-plugin (as elasticsearch_dynamic), otherwise logic will be a mess with many if-else because of data streams approach differences.

Yeah, we should create separated plugin but it also inherits `Fluent::Plugin::ElasticsearchOutput` class like `elasticsearch_dynamic` does.



> So probably data streams are alternative for the indexes. ILM policy apply strategy is also different. There is no need to create rollover alias by yourself. You need just to assign ILM policy to index_template.

>> The stream automatically routes the request to backing indices that store the stream’s data. You can use index lifecycle management (ILM) to automate the management of these backing indices. 

ref: https://www.elastic.co/guide/en/elasticsearch/reference/7.9/data-streams.html#data-streams

DataStream is not alternative for indices. 
Backing indices are just following indices conventions (`.ds-<data-stream>-<generation>`). 
ILM can handle to prevent growing DataStream's backing indices.

`elasticsearch_data_streams` can perform `create` operation for backing indices:
https://www.elastic.co/guide/en/elasticsearch/reference/7.9/data-streams.html#data-stream-write-index

**Comment by metalrex100** [comment]
> DataStream is not alternative for indices.
> Backing indices are just following indices conventions (`.ds-<data-stream>-<generation>`).
> ILM can handle to prevent growing DataStream's backing indices.

Current approach (non data-stream) assumes manual index creation.
But data streams approach generates backing indexes automatically. So there is no need to think about indexes anymore, because data streams is some kind of abstraction under indexes.
And the `index templates` applied to data streams (ofc under the hood it applied to backing indexes, but you writing template for data streams).

Also there is no need to separately create data-stream since it will be automatically created on first record addition (if was not existed previously).
https://www.elastic.co/guide/en/elasticsearch/reference/7.9/set-up-a-data-stream.html#create-a-data-stream

> To automatically create the data stream, submit an indexing request to the stream. The stream’s name must match one of your template’s index patterns.

**Comment by cosmo0920** [comment]
> By this words I want to say that `elasticsearch_data_stream` module does not need `index_name` param, but need `data_stream_name` param.

Oh, that's reasonable.
Yeah, we want to use elasticasearch-ruby client for this feature but I've found that elasticsearch-ruby does not handle POST API for elasticsearch data streams.
I'd sent a question about this:
https://github.com/elastic/elasticsearch-ruby/issues/1119

**Comment by metalrex100** [comment]
@cosmo0920 I actually checked if ruby-client has data streams API implementation. From some moment they moved it to X-PACK.

https://github.com/elastic/elasticsearch-ruby/pull/990

**Comment by cosmo0920** [comment]
We use elasticsearch-ruby client to send bulk requests.
I assume that the following request sequences is needed:

1. Create Data Stream with Data streams API
    1. https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/indices/create_data_stream.rb
        1. https://www.elastic.co/guide/en/elasticsearch/reference/7.9/indices-create-data-stream.html#indices-create-data-stream

1. Use BULK API to create data for data streams
    1. https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-api/lib/elasticsearch/api/actions/bulk.rb   
        1. https://www.elastic.co/guide/en/elasticsearch/reference/7.9/use-a-data-stream.html#add-documents-to-a-data-stream

**Comment by cosmo0920** [comment]
ES plugin also depends on xpack for ILM feature.
It is reasonable to use elasticsearch-xpack gem. But ILM and Data streams is not main feature for Elasticsearch.
So, we should keep elasticsearch-xpack as optional dependency.

**Comment by metalrex100** [comment]
@cosmo0920 Ok, data streams module feature any way will be optional. The docs just should contain info about x-pack requirement.

**Comment by metalrex100** [comment]
I'm actually not familiar with ruby, so implementation process will be not so fast since I need to learn syntax and other stuff. So any tips will be useful. (I have good experience with PHP and GO)

**Comment by cosmo0920** [comment]
Ruby's tutorial looks attractive to learn Ruby language:
https://ruby-doc.org/docs/Tutorial/

We use test-unit for unit tests:
https://test-unit.github.io/test-unit/en/

And some tests use mock/stub libraries:
flexmock: https://flexmock.readthedocs.io/en/latest/ 
rr(double r):https://github.com/rr/rr

**Comment by cosmo0920** [comment]
I also asked @kenhys to take a look on this issue.

**Comment by cosmo0920** [comment]
We can setup Elasticsearch 7.10 data streams developement environment with:

```console
$ docker run --name elasticsearch-7.10 -p 9200:9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.10.0
```

This command makes ES 7.10 with data streams environment:
```console
% curl localhost:9200/_xpack | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1347  100  1347    0     0  29282      0 --:--:-- --:--:-- --:--:-- 29933
```
```json
{
  "build": {
    "hash": "51e9d6f22758d0374a0f3f5c6e8f3a7997850f96",
    "date": "2020-11-09T21:30:33.964949Z"
  },
  "license": {
    "uid": "266e0f72-5675-49b3-bf39-fa1b0725b179",
    "type": "basic",
    "mode": "basic",
    "status": "active"
  },
  "features": {
    "analytics": {
      "available": true,
      "enabled": true
    },
    "ccr": {
      "available": false,
      "enabled": true
    },
    "data_streams": {
      "available": true,
      "enabled": true
    },
    "data_tiers": {
      "available": true,
      "enabled": true
    },
    "enrich": {
      "available": true,
      "enabled": true
    },
    "eql": {
      "available": true,
      "enabled": true
    },
    "flattened": {
      "available": true,
      "enabled": true
    },
    "frozen_indices": {
      "available": true,
      "enabled": true
    },
    "graph": {
      "available": false,
      "enabled": true
    },
    "ilm": {
      "available": true,
      "enabled": true
    },
    "logstash": {
      "available": false,
      "enabled": true
    },
    "ml": {
      "available": false,
      "enabled": true,
      "native_code_info": {
        "version": "7.10.0",
        "build_hash": "ac991e2e31f99d"
      }
    },
    "monitoring": {
      "available": true,
      "enabled": true
    },
    "rollup": {
      "available": true,
      "enabled": true
    },
    "searchable_snapshots": {
      "available": false,
      "enabled": true
    },
    "security": {
      "available": true,
      "enabled": false
    },
    "slm": {
      "available": true,
      "enabled": true
    },
    "spatial": {
      "available": true,
      "enabled": true
    },
    "sql": {
      "available": true,
      "enabled": true
    },
    "transform": {
      "available": true,
      "enabled": true
    },
    "vectors": {
      "available": true,
      "enabled": true
    },
    "voting_only": {
      "available": true,
      "enabled": true
    },
    "watcher": {
      "available": false,
      "enabled": true
    }
  },
  "tagline": "You know, for X"
}
```

**Comment by kenhys** [comment]
> Create Data Stream with Data streams API / Get Data Stream existence with Data streams API

It seems that before creating data stream, index template must be created.

**Comment by metalrex100** [comment]
@kenhys yes, index template must be created before Data Stream. And only new (non legacy) templates support data streams.

**Comment by kenhys** [comment]
Here is the basic example to put into  `foo` data stream.

```ruby
client = Elasticsearch::Client.new log: true

body = <<-EOS
{
  "policy": {
    "phases": {
      "hot": {                      
        "actions": {
          "rollover": {
            "max_size": "50GB",     
            "max_age": "30d"
          }
        }
      }
    }
  }
}
EOS

params = {
  policy_id: "foo_policy",
  body: body
}

client.xpack.ilm.put_policy(params)

body = <<-EOS
{
  "index_patterns": ["foo*"],
  "data_stream": {},
  "template": {
    "settings" : {
      "index.lifecycle.name": "foo_policy"
    }
  }
}
EOS

params = {
  name: "foo",
  body: body
}
client.indices.put_index_template(params)

params = {
  name: "foo",
}
client.indices.create_data_stream(params)

body = <<-EOS
{"index": { "_index": "foo", "_id": "1"} },
{"key": "value"}
EOS

params = {
  index: "foo",
  body: body
}

client.bulk(params)
```

**Comment by nargmarg** [comment]
Dear all, thanks for your work. Do you know when this feature will be available? Thanks

**Comment by metalrex100** [comment]
Hello there! Sorry for not responding to this working on this issue, did not have time at all. Glad that it is in progress!
Will this data-streams feature also support dynamic indexes names?

**Comment by cosmo0920** [comment]
> Will this data-streams feature also support dynamic indexes names?

Yep. We can support dynamic data stream names.

**Comment by metalrex100** [comment]
@cosmo0920 do you know when https://github.com/fluent/fluentd-kubernetes-daemonset will be updated to use version 5.0.0 of this plugin?

**Comment by doge95** [comment]
> > Will this data-streams feature also support dynamic indexes names?
> 
> Yep. We can support dynamic data stream names.

 May I check when this will be available for use? thanks :)
