### ISSUE TITLE
error_class=Fluent::ConfigError error="Could not load sniffer class Fluent::Plugin::ElasticsearchSimpleSniffer: uninitialized constant Fluent::Plugin::ElasticsearchSimpleSniffer\nDid you mean?  Fluent::ElasticsearchIndexTemplate"

### ISSUE THREAD

**Issue by prashantcsutar** [uken/fluent-plugin-elasticsearch#845]
#### Problem
I have created a custom image for fluentd elasticsearch deamonset with alpine base image. The debian base image has one security issue. This security issue is observed during Azure Container Registry image scanning. So we tried to create a alpine image. But we are getting below error:

error_class=Fluent::ConfigError error="Could not load sniffer class Fluent::Plugin::ElasticsearchSimpleSniffer: uninitialized constant Fluent::Plugin::ElasticsearchSimpleSniffer\nDid you mean?  Fluent::ElasticsearchIndexTemplate"
 
#### Using Fluentd and ES plugin versions
* Elasticsearch Fluentd plugin: 4.2.2
* OS: alpine
* Fluentd: 1.11.5
* Elasticsearch version: 6.8

Please let me know if you will need Dockerfile and other details.

**Comment by prashantcsutar** [comment]
Dockerfile and other details are present at: 

https://github.com/prashantcsutar/alpine-elasticsearch6

**Comment by cosmo0920** [comment]
Please read the doc: https://github.com/uken/fluent-plugin-elasticsearch#tips

**Comment by ferenc-crey** [comment]
Do you have an example about how to set this up on a Windows container?

**Comment by ferenc-crey** [comment]
@cosmo0920
