### ISSUE TITLE
_type field is deprecated for bulk operation

### ISSUE THREAD

**Issue by ChrsMark** [uken/fluent-plugin-elasticsearch#847]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Problem
`_type` field is deprecated for `bulk` operations

#### Steps to replicate
Start Elasticsearch using version 7.11:
`docker run --name elasticsearch -p 9200:9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.11.0-SNAPSHOT`

Start flunentd pointing to this ES instance.

You will get a warning:

```
warning: 299 Elasticsearch-7.11.0-SNAPSHOT-6bf45f5a7c69ed84e3c4cfa209012dbf921071bf "[types removal] Specifying types in bulk requests is deprecated."
```

Start Elasticsearch using version 8.0:
`docker run --name elasticsearch -p 9200:9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT`

Start flunentd pointing to this ES instance.

You will get a warning (actually error):

```
2020-12-02 13:21:19 +0200 [warn]: #0 fluent/log.rb:350:warn: failed to flush the buffer. retry_time=4 next_retry_seconds=2020-12-02 13:21:27 +0200 chunk="5b57970add07a0e90b3f8167a5eff5ca" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"localhost\", :port=>9200, :scheme=>\"http\"}): [400] {\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Action/metadata line [1] contains an unknown parameter [_type]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"Action/metadata line [1] contains an unknown parameter [_type]\"},\"status\":400}"
```

#### Expected Behavior or What you need to ask
`_type` field should not be added in these versions 

#### Using Fluentd and ES plugin versions

* Fluentd `fluentd 1.12.0.rc1`
* ES plugin `4.2.2`
* ES version `7.11.x` and `8.x.x`

**Comment by ChrsMark** [comment]
@cosmo0920 you can ignore it. The error with version 8 occurred when I had `verify_es_version_at_startup` set to `false` and the warning for version 7.11 looks normal to me.

In this, feel free to close it and sorry for the noise!

**Comment by cosmo0920** [comment]
Oh, that's nice!
Could you share your configuration?

As you know, fluent-plugin-elasticsearch uses `#configure` phase result for `GET /` to obtain version.

**Comment by ChrsMark** [comment]
Here is the configuration that fails:

```
# ~/fluentd/pipelines/simple.conf
<source>
  @type forward
</source>

<filter my.logs>
  @type elasticsearch_genid
  hash_id_key event.hash
</filter>

<match my.logs>
  @type elasticsearch
  include_timestamp true
  include_tag_key true
  tag_key tags
  user elastic
  password changeme
  logstash_format true
  verify_es_version_at_startup false
  <buffer tag, time>
    timekey 10s 
  </buffer>
  
</match>
```

Removing `verify_es_version_at_startup false` makes it work and I also get `2020-12-03 12:55:54 +0200 [warn]: #0 fluent/log.rb:350:warn: Detected ES 8.x or above: document type will not be used.` which proves that plugin handle it properly.

**Comment by cosmo0920** [comment]
I've merged a patch which is related to this issue.
Yeah, we can close this issue.
This is because combination of `verify_es_version_at_startup false` and default value of [`default_elasticsearch_version`](https://github.com/uken/fluent-plugin-elasticsearch#default_elasticsearch_version) should be specified at the user's own risk.
