### ISSUE TITLE
Reroute the log to backup storage when ES is down

### ISSUE THREAD

**Issue by naviat** [uken/fluent-plugin-elasticsearch#856]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

**Is your feature request related to a problem? Please describe.**

When I create a pipeline for logging sends from fluentd to elasticsearch, I tried to reroute the log to another storage when fluentd cannot connect to elasticsearch ( after `request_timeout`, `reload_connections`, `reload_on_failure`).

**Describe the solution you'd like**

An option to config the other storage when the maximum of retry or reload is over.

**Describe alternatives you've considered**

Another way to config the reroute with the built-in options we have

**Additional context**

**Comment by cosmo0920** [comment]
You can use built-in secondary_file plugin.
ref: https://docs.fluentd.org/output/secondary_file

Fluentd world loves to composable and minimized plugins not monolithic plugin.
