### ISSUE TITLE
json_parse_exception","reason":"Invalid UTF-8 start byte 0xa9

### ISSUE THREAD

**Issue by ajayanaj** [uken/fluent-plugin-elasticsearch#858]
(check apply)
- [ ] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Problem
We are getting the below error while writing to elasticsearch
---
Elasticsearch::Transport::Transport::Errors::BadRequest [400] {"error":{"root_cause":[{"type":"json_parse_exception","reason":"Invalid UTF-8 start byte 0xa9\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@1c4892f3; line: 1, column: 114]"}],"type":"json_parse_exception","reason":"Invalid UTF-8 start byte 0xa9\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@1c4892f3; line: 1, column: 114]"},"status":400
---
I tried the solution mentioned here https://github.com/uken/fluent-plugin-elasticsearch/issues/77 but it's not working. Not sure why it's still throwing the error.

...

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

**OR**

Provide example config and message

#### Expected Behavior or What you need to ask
UTF-8 should be resolved.
...

#### Using Fluentd and ES plugin versions
fluent-plugin-elasticsearch:4.2.2

* OS version
* Bare Metal or within Docker or Kubernetes or others? kubernetes
* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version`` fluentd 1.11.5
* ES plugin 3.x.y/2.x.y or 1.x.y. fluent-plugin-elasticsearch:4.2.2

  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
async (1.27.0)
async-http (0.46.3)
async-io (1.30.1)
aws-eventstream (1.1.0)
aws-partitions (1.396.0)
aws-sdk-cloudwatchlogs (1.38.0)
aws-sdk-core (3.109.3)
aws-sdk-kms (1.39.0)
aws-sdk-s3 (1.84.1)
aws-sdk-sqs (1.34.0)
aws-sigv4 (1.2.2)
base91 (0.0.1)
bigdecimal (default: 1.4.1)
bundler (default: 1.17.2)
cmath (default: 1.0.0)
console (1.10.1)
cool.io (1.7.0)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0)
dig_rb (1.0.1)
digest-crc (0.6.1)
e2mmap (default: 0.1.0)
elasticsearch (7.10.0)
elasticsearch-api (7.10.0)
elasticsearch-transport (7.10.0)
etc (default: 1.0.1)
ethon (0.12.0)
excon (0.78.0)
faraday (1.1.0)
fcntl (default: 1.0.0)
ffi (1.13.1)
fiber-local (1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
fluent-config-regexp-type (1.0.0)
fluent-plugin-cloudwatch-logs (0.11.2)
fluent-plugin-elasticsearch (4.2.2)
fluent-plugin-genhashvalue (1.1)
fluent-plugin-grok-parser (2.1.6)
fluent-plugin-kafka (0.15.2)
fluent-plugin-prometheus (1.7.3)
fluent-plugin-record-modifier (2.1.0)
fluent-plugin-remote_syslog (1.0.0)
fluent-plugin-rewrite-tag-filter (2.3.0)
fluent-plugin-s3 (1.1.3)
fluent-plugin-zookeeper (0.1.0)
fluentd (1.11.5, 1.6.2)
forwardable (default: 1.2.0)
gdbm (default: 2.0.0)
http_parser.rb (0.6.0)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
jmespath (1.4.0)
json (2.2.0, default: 2.1.0)
logger (default: 1.3.0)
ltsv (0.1.2)
matrix (default: 0.1.0)
mini_portile2 (2.5.0)
minitest (5.11.3)
msgpack (1.3.3)
multi_json (1.15.0)
multipart-post (2.1.1)
murmurhash3 (0.1.6)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
nio4r (2.5.4)
oj (3.3.10)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
power_assert (1.1.3)
prime (default: 0.1.0)
prometheus-client (0.9.0)
protocol-hpack (1.4.2)
protocol-http (0.8.1)
protocol-http1 (0.8.3)
protocol-http2 (0.9.7)
psych (default: 3.1.0)
quantile (0.2.1)
rake (13.0.1, 12.3.3)
rdkafka (0.8.0)
rdoc (default: 6.1.2)
remote_syslog_sender (1.2.1)
rexml (default: 3.1.9)
rss (default: 0.2.7)
ruby-kafka (1.3.0)
ruby2_keywords (0.0.2)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
serverengine (2.2.2)
shell (default: 0.7)
sigdump (0.2.4)
stringio (default: 0.0.2)
strptime (0.2.5)
strscan (default: 1.0.0)
sync (default: 0.5.0)
syslog_protocol (0.9.2)
test-unit (3.2.9)
thread_safe (0.3.6)
thwait (default: 0.1.0)
timers (4.3.2)
tracer (default: 0.1.0)
typhoeus (1.4.0)
tzinfo (1.2.8)
tzinfo-data (1.2020.4)
uuidtools (2.2.0)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
yajl-ruby (1.4.1)
zlib (default: 1.0.0)
* ES version (optional) 6.8
* ES template(s) (optional)

**Comment by cosmo0920** [comment]
ES plugin just pass-throughs and send into Elasticsearch received data.
This is not ES plugin issues just for encoding issues on your data.
Could you provide reproducible steps or sample data which causes encoding error?

**Comment by ajayanaj** [comment]
@cosmo0920  Thank you for the reply, we found the issue with our data. I'm closing this now.

**Comment by ajayanaj** [comment]
@petergvizd  Yes, we fixed the issue by modifying the incoming data. But I don't remember what I did, I left the company a year back.
