### ISSUE TITLE
Adding a new mantainer

### ISSUE THREAD

**Issue by cosmo0920** [uken/fluent-plugin-elasticsearch#868]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

**Is your feature request related to a problem? Please describe.**

I'm proposing to add a new maintainer.

**Describe the solution you'd like**
My colleague @kenhys is also workable on this repository.

**Describe alternatives you've considered**

**Additional context**
Sometimes I'm struggled to maintain this repository alone.

Could you handle to add @kenhys as a new maintainer, @gihad?

**Comment by cosmo0920** [comment]
@gihad Bump.

@kenhys is the main creator for out_elasticsearch_data_stream plugin. His work is exceptional great due for writing plugin, testing, and documentations. Do you have a chance to add @kenhys as new maintainer?

**Comment by cosmo0920** [comment]
I'd sent a email into Gibad for adding a new maintainer.

**Comment by kenhys** [comment]
I've received an invitation, thanks!

**Comment by cosmo0920** [comment]
Done!
