### ISSUE TITLE
Cannot specify Elasticsearch cluster name in fluentd.conf

### ISSUE THREAD

**Issue by vedaprasad** [uken/fluent-plugin-elasticsearch#87]
Is there a way to specify elasticsearch cluster name instead of hostname/IP 

<match **>
  type elasticsearch
 logstash_format true
  host XXXX
  port 9200
  index_name fluentd
  type_name fluentd
</match>

**Comment by dterror** [comment]
You mean as in using auto-discovery? if so, that's not supported as of now.

**Comment by pitr** [comment]
@vedaprasad Feel free to open a PR or reopen the discussion if you think this feature should be implemented.
