### ISSUE TITLE
Dynamic Datastream Naming

### ISSUE THREAD

**Issue by iahmad94** [uken/fluent-plugin-elasticsearch#891]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

**Is your feature request related to a problem? Please describe.**

**Feature Request**

Currently fluentd is unable to create datastream names dynamically using the `@type elasticsearch_data_stream` output.  I have been able to successfully create dynamic indexes using `@type elasticsearch_dynamic` but not datastreams.

**Describe the solution you'd like**

**Example config that currently DOES NOT work:**

```txt
<match **>
        @type elasticsearch_data_stream
        data_stream_name logs-${record['event']['dataset']} 
        ....
        ....
        ....
</match>
```

**Describe alternatives you've considered**

  I have been able to successfully create dynamic indexes using `@type elasticsearch_dynamic` but not datastreams.

**Additional context**

* I did see some conversation around this feature in a closed issue, conversation found [here](https://github.com/uken/fluent-plugin-elasticsearch/issues/843#issuecomment-833465295)

**Comment by cosmo0920** [comment]
> I have been able to successfully create dynamic indexes using `@type elasticsearch_dynamic` but not datastreams.

out_elasticsearch_datastream uses built-in placeholders not using eval directly. So, placeholder syntax is different:
https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch_data_stream.rb#L164

This section would be helpful for you:
https://github.com/uken/fluent-plugin-elasticsearch#placeholders

**Comment by iahmad94** [comment]
> This section would be helpful for you:
> https://github.com/uken/fluent-plugin-elasticsearch#placeholders

Thanks so much for that @cosmo0920! 

Main take away's I had were: 
1. use placeholder syntax not direct eval, so: 
* `${some_key}`  instead of `${record['some_key']}`
2. make sure to  add these in the buffer directive attributes!! So your buffer should have:
* `<buffer tag, some_key>`

**Comment by iahmad94** [comment]
I still had some trouble with accessing a nested key, but ended up using a `record_transformer` to pull up the value. 

So if my record looked like this: 
```txt
records = { some_key: { nested_key: "value1"}}
```
And my end goal was to create a datastream with the name `value1`, the below config is what I ended up using:

```
    <filter **>
      @type record_transformer
      enable_ruby
      <record>
        my_new_key ${record["some_key"]["nested_key"]}
      </record>
    </filter>
    <match **>
      @type elasticsearch_data_stream
      data_stream_name ${my_new_key}
      ... 
      ... 
      ... 
      <buffer tag, my_new_key>
        .... 
      </buffer>
    </match>
```

I'm not sure if this is the "cleanest" implementation, totally open to suggestions on how to improve it, but hopefully this helps some in a pinch.

**Comment by cosmo0920** [comment]
> I still had some trouble with accessing a nested key, but ended up using a record_transformer to pull up the value.

Only using built-in holders, we can use `$.the.nested.keys.accessor` syntax.
But with this way, you should use stable nested key.

ref: https://docs.fluentd.org/configuration/buffer-section#nested-field-support-1

**Comment by iahmad94** [comment]
Ty so much @cosmo0920! Feel free to close this issue, i'm good on my end!

**Comment by madanrishi** [comment]
@iahmad94 were you able to do dynamic data streams with this?

```
data_stream_name ${my_new_key}
```
for me it just creates a data stream with the name $(my_new_key)

**Comment by Ga13Ou** [comment]
> @iahmad94 were you able to do dynamic data streams with this?
> 
> ```
> data_stream_name ${my_new_key}
> ```
> 
> for me it just creates a data stream with the name $(my_new_key) it doesn't evaluate the data_stream_name

I have the same issue, did you solve it?

**Comment by SumoSumir** [comment]
@Ga13Ou @madanrishi - super late response - I was facing the same issue.
but fixed it by using @iahmad94 's suggestion of creating a buffer in the output block with <buffer tag, my_new_key>
Else it just creates a data stream with the name $(my_new_key) as you've faced.

Can you confirm if you had done the same?
Also please share your fluentd versions
