### ISSUE TITLE
"enable_ilm = false" when @type elasticsearch_data_stream is used

### ISSUE THREAD

**Issue by JPIFR** [uken/fluent-plugin-elasticsearch#904]
It's written in the doc: "**Configuration - Elasticsearch Output Data Stream**": 

**When @type elasticsearch_data_stream is used, ILM default policy is set to the specified data stream. Then, the matching index template is also created automatically.**

We would like to disable all automatic creation of Fluentd elastcisearch plugin because we use an index template which creates and manage already everything.  

Are you planning to develop such a feature?

Thanks for your help!

**Comment by cosmo0920** [comment]
No. We don't plan to support such feature.

**Comment by expteam-interactiv** [comment]
I have the same need using a custom index template/ILM with data streams
