### ISSUE TITLE
fluentd does not work with ssl_version TLSv1_3 

### ISSUE THREAD

**Issue by aggarwalShivani** [uken/fluent-plugin-elasticsearch#908]
(check apply)
- [ ] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Problem
Fluentd fails to contact elasticsearch that has only "TLSv1.3" protocol enabled on REST layer. 
When the ssl_version parameter in fluentd-elasticsearch match section is configured as TLSv1_3:
```
 <match **>
  @type elasticsearch
  host elasticsearch
  scheme https
  ssl_version TLSv1_3
```
 **fluentd fails with the following error** :
` [error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="valid options are SSLv23,TLSv1,TLSv1_1,TLSv1_2 but got TLSv1_3 `

As per suggestions in [the documentation](https://github.com/uken/fluent-plugin-elasticsearch#clienthost-certificate-options), fluentd-elasticsearch plugin 4.0.8 onwards support ssl_max_version be TLSv1_3, but even with the following configuration, fluentd fails to come up - 
```
 <match **>
  @type elasticsearch
  host elasticsearch
  scheme https
  ssl_max_version TLSv1_3
  ssl_min_version TLSv1_2
```
Error:
`2021-07-22 18:01:37 +0000 [error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="valid optio   ns are SSLv23,TLSv1,TLSv1_1,TLSv1_2 but got TLSv1_3"`
...

#### Steps to replicate: Provide example config and message

1. Enable tls v1.3 on elasticsearch. For ex. if using elasticsearch with opendistro_security, set in elasticsearch.yml
```
opendistro_security.ssl.http.enabled_protocols:
 - "TLSv1.3"
```
2. Fluentd config
  Enable ssl_version as TLSv1_3 in elasticsearch match section as shared above.

#### Expected Behavior or What you need to ask
Fluentd should be able to come up successfully and contact elasticsearch with TLS v1.3 protocol on REST layer.

Is tls1.3 supported by the fluend-elasticsearch plugin? If yes, from which version onwards and what is the right way to configure it?

#### Using Fluentd and ES plugin versions
* OS version: centos7.9
* Bare Metal or within Docker or Kubernetes or others? Kubernetes
* Fluentd version:  **td-agent 4.1.0**, **fluentd 1.12.1**
* ES plugin :  fluent-plugin-elasticsearch' version **'4.3.3'**
* ES version: 7.8.0

**Comment by cosmo0920** [comment]
> Is tls1.3 supported by the fluend-elasticsearch plugin? If yes, from which version onwards and what is the right way to configure it?

It depends on your using openssl library version and Ruby's openssl version. This issue is not for ES plugin.

**Comment by cosmo0920** [comment]
CentOS 7 does not have OpenSSL 1.1.1 package.
This could be CentOS 7 issue.
If you want to use TLS v1.3 on CentOS 7, you must build openssl 1.1.1k (the latest openssl 1.1.1 series) and Ruby 2.5 or later by yourself.
We don't recommend to use td-agent 4.1.0 for this case.

**Comment by aggarwalShivani** [comment]
Thanks for the response @cosmo0920 , **what version of td-agent** do you recommend for this case i.e. to build centos7-based image with openssl 1.1.1?

**Comment by cosmo0920** [comment]
> **what version of td-agent** do you recommend for this case i.e. to build centos7-based image with openssl 1.1.1?

No recommended version. If you want to use OpenSSL 1.1.1, you must upgrade CentOS to 8.

**Comment by cosmo0920** [comment]
In CentOS 8, td-agent will use OpenSSL 1.1.1:

```console
$ dnf info openssl
Failed to set locale, defaulting to C.UTF-8
CentOS Linux 8 - AppStream                                                                  3.6 MB/s | 8.3 MB     00:02    
CentOS Linux 8 - BaseOS                                                                     2.9 MB/s | 4.5 MB     00:01    
CentOS Linux 8 - Extras                                                                      15 kB/s | 9.8 kB     00:00    
Available Packages
Name         : openssl
Epoch        : 1
Version      : 1.1.1g
Release      : 15.el8_3
Architecture : x86_64
Size         : 707 k
Source       : openssl-1.1.1g-15.el8_3.src.rpm
Repository   : baseos
Summary      : Utilities from the general purpose cryptography library with TLS implementation
URL          : http://www.openssl.org/
License      : OpenSSL and ASL 2.0
Description  : The OpenSSL toolkit provides support for secure communications between
             : machines. OpenSSL includes a certificate management tool and shared
             : libraries which provide various cryptographic algorithms and
             : protocols.


```
