### ISSUE TITLE
 unexpected error error_class=NoMethodError error="undefined method host_unreachable_exceptions' for #<Elasticsearch::Transport::Client:0x00007fe5231b5e08>"

### ISSUE THREAD

**Issue by tarkik-infostretch** [uken/fluent-plugin-elasticsearch#912]
#### Problem
We are using AWS Elasticsearch Service and fleuntd to push the logs of microservice. We have installed fluentd on EC2 instance using docker based configuration. We have followed the steps mentioned in the https://docs.fluentd.org/container-deployment/docker-compose and also it was working pretty fine till last week. There is no change in the configuration of both elastcicsearch service and ec2 instance we are provisioning. Below is the error logs we are getting.

``2021-08-05 20:35:57 +0000 [error]: #0 unexpected error error_class=NoMethodError error="undefined method host_unreachable_exceptions' for #<Elasticsearch::Transport::Client:0x00007fe5231b5e08>"   2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.5/lib/fluent/plugin/elasticsearch_index_template.rb:41:in rescue in retry_operate' 2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.5/lib/fluent/plugin/elasticsearch_index_template.rb:39:in retry_operate'   2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.5/lib/fluent/plugin/out_elasticsearch.rb:487:in handle_last_seen_es_major_version' 2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.5/lib/fluent/plugin/out_elasticsearch.rb:339:in configure'   2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin.rb:178:in configure' 2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/agent.rb:132:in add_match'   2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/agent.rb:74:in block in configure' 2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/agent.rb:64:in each'   2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/agent.rb:64:in configure' 2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/root_agent.rb:146:in configure'   2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/engine.rb:105:in configure' 2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/engine.rb:80:in run_configure'   2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/supervisor.rb:714:in block in run_worker' 2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/supervisor.rb:966:in main_process'   2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/supervisor.rb:706:in run_worker' 2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/command/fluentd.rb:364:in <top (required)>'   2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in require' 2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in require'   2021-08-05 20:35:57 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/bin/fluentd:15:in <top (required)>' 2021-08-05 20:35:57 +0000 [error]: #0 /usr/bin/fluentd:23:in load'   2021-08-05 20:35:57 +0000 [error]: #0 /usr/bin/fluentd:23:in ``
Below is the configuration used.

**docker-compose.yml**

```
version: '3'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "8880:8880"
      - "8880:8880/udp"
```
**Dockerfile**
```
FROM fluent/fluentd:v1.13.3
USER root
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "5.0.5"]
USER fluent
```
**fluentd.conf**

```
<source>
  @type forward
  port 8880
  bind 0.0.0.0
</source>

<match **>
    host ES_HOT
    port 443
    scheme https
    logstash_format true
    logstash_prefix "fluentd-logs"
    logstash_dateformat "%Y%m%d"
    user "elastic"
    password xxxxxx
    flush_interval 10s
    fail_on_detecting_es_version_retry_exceed false
    verify_es_version_at_startup false
    max_retry_get_es_version 2
    default_elasticsearch_version 7.10
    request_timeout 60s
    reload_on_failure true
</match>
```

Our configuration with AWS Elasticsearch Service 7.10, Fluentd v1.12.0-debian-1.0 and fluent-plugin-elasticsearch 4.3.3, was working perfectly fine till last week. One of the ec2 instance which was provisioned 10 days back, was able to connect and push the logs as well. But when we restarted that instance its also stopped working with the same error. We have Terraform scripts that provision all infrastructure. Later, we have tried different versions combinations as well. But nothing worked out.

Thanks in advance
...

...

#### Using Fluentd and ES plugin versions

* OS version :: AWS LInux AMI 
* Fluentd v1.0
* ES version 7.10

**Comment by antonio-robles-1** [comment]
Same issue here, we have solved it installing the following gem 

`sudo gem install elasticsearch -v 7.13.3`

**Comment by anoopkrsonkar** [comment]
We are getting same error.

**Comment by kevinlul** [comment]
This could be due to the release of 7.14.0 of the elasticsearch Ruby dependency if downgrading solves the problem. https://github.com/elastic/elasticsearch-ruby/releases/tag/v7.14.0 this was released three days ago, and the version in this plugin does not seem to be pinned. Maybe this client breaks compatibility with 7.10, the last Open Distro release?

**Comment by tarkik-infostretch** [comment]
> Same issue here, we have solved it installing the following gem
> 
> `sudo gem install elasticsearch -v 7.13.3`

You are the saviour Captain :) The workaround did the trick and it's working now.

**Comment by stockholmux** [comment]
Most likely related to this to the 7.14 client library putting in distribution/version/product checking logic. 

This blog post has more info:
https://aws.amazon.com/blogs/opensource/keeping-clients-of-opensearch-and-elasticsearch-compatible-with-open-source/

**Comment by tarkik-infostretch** [comment]
> Most likely related to this to the 7.14 client library putting in distribution/version/product checking logic.
> 
> This blog post has more info:
> https://aws.amazon.com/blogs/opensource/keeping-clients-of-opensearch-and-elasticsearch-compatible-with-open-source/

Able to solve the issue by downgrading the version.

**Comment by cosmo0920** [comment]
@kenhys Any thoughts?

**Comment by liuchintao** [comment]
I met similar issue on arm64 platform, but plugin works well on amd64 platform.
My plugin version is 4.1.0.

> sudo gem install elasticsearch -v 7.13.3

This version is not work for me, I install elasticsearch -v 6.8.3 (my es version is 7.2.0)

**Comment by mstenta** [comment]
> `sudo gem install elasticsearch -v 7.13.3`

This resolved the issue for me as well.

In case it is helpful to anyone else, here is roughly what my `Dockerfile` looks like, which extends from the official `fluentd/fluentd:v1.13-1` image, applies this fix, and then installs the `fluent-plugin-elasticsearch` plugin:

```
# Inherit from the official fluentd image.
FROM fluent/fluentd:v1.13-1

# Install elasticsearch library and fluent plugin.
USER root
RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 # Pin the elasticsearch-ruby library < 7.14.
 # See https://github.com/uken/fluent-plugin-elasticsearch/issues/912
 && sudo gem install elasticsearch -v 7.13.3 \
 && sudo gem install fluent-plugin-elasticsearch \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem
USER fluent
```

Thanks @antonio-robles-1 for finding the fix!

**Comment by arash-bizcover** [comment]
This is a real issue. why is this closed. someone open it up
