### ISSUE TITLE
Unable to download data from https://rubygems.org/

### ISSUE THREAD

**Issue by richarwu** [uken/fluent-plugin-elasticsearch#97]
Hi, I'm a new fish about ruby, and don't know how to install fluent-plugin-elasticsearch manually. And when I run the install-command:/opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-elasticsearch, it displays error info as: 
Unable to download data from https://rubygems.org/ - Errno::ETIMEDOUT: Connection timed out - connect(2) for "s3.amazonaws.com" port 443 (https://api.rubygems.org/latest_specs.4.8.gz)
As the network situation in china, Can anybody know how to install this plugin in some other method? Thanks.

**Comment by repeatedly** [comment]
This is a rubygems and your environment issue.
I think ruby mailing list or stackoverflow like site is better.
